### PR TITLE
fix bounded retry logging for shuffle coalesce

### LINKED ISSUE #14536: [BUG] CloseableTableSeqWithTargetSize.toString causes Java heap OOM during shuffle coalesce retry
### Description

`CloseableTableSeqWithTargetSize` (introduced in #14010 / commit 391635f06) extends
`Seq[T]` but does not override `toString()`. When the retry/split path in
`RmmRapidsRetryIterator.AutoCloseableAttemptSpliterator.split()` builds error context
via `curAttempt.toString()`, Scala's default `SeqLike.toString` calls `mkString` which
iterates and stringifies every element in the sequence. With thousands of shuffle
partitions coalesced in a single batch, this constructs a massive `StringBuilder` that
triggers `java.lang.OutOfMemoryError: Java heap space`.

### Symptoms

Run a shuffle-heavy query with a large initial shuffle partition count:
```
spark.sql.shuffle.partitions=20000
spark.rapids.shuffle.kudo.serializer.read.mode=CPU
```
Ensure JVM heap is not oversized (default executor memory settings).

Observe java.lang.OutOfMemoryError: Java heap space with this stack:
java.util.Arrays.copyOf(Arrays.java:3332)
java.lang.AbstractStringBuilder.ensureCapacityInternal(...)
java.lang.StringBuilder.append(...)
...
com.nvidia.spark.rapids.CloseableTableSeqWithTargetSize.mkString(GpuShuffleCoalesceExec.scala:472)
com.nvidia.spark.rapids.CloseableTableSeqWithTargetSize.toString(GpuShuffleCoalesceExec.scala:472)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.$anonfun$split$1(...)
com.nvidia.spark.rapids.CoalesceIteratorBase.$anonfun$concatenateTables$1(GpuShuffleCoalesceExec.scala:568)
Execution time scales with partition count, not data volume:
5,000 partitions → ~2 min
20,000 partitions → ~10 min
20,000 partitions + spark.shuffle.io.preferDirectBufs=true → ~20 sec
The dominant cost is GC time, confirming JVM heap pressure from the unbounded toString().

### Affected Versions
v26.02.0 and later (any version containing #14010).

### Expected Behavior
The retry/split error path should not allocate memory proportional to the number of
input partitions. A bounded summary (element count, target size, min size) is sufficient
for diagnostics.

### PR DESCRIPTION
**Pull request by winningsix**
Fixes #14536.

### Description

`CloseableTableSeqWithTargetSize` (introduced in #14010) extends `Seq[T]` but does not
override `toString()`. When the retry/split path in
`RmmRapidsRetryIterator.AutoCloseableAttemptSpliterator.split()` calls
`curAttempt.toString()` to capture diagnostic context, Scala's default `SeqLike.toString`
iterates over every element and builds an unbounded string via `mkString`. With thousands
of shuffle partitions coalesced in a single batch, this secondary allocation triggers
`java.lang.OutOfMemoryError: Java heap space`.

**User-visible impact:**

- Execution time scales with partition count rather than data volume (5k partitions ~2min,
  20k partitions ~10min). The dominant cost is GC time from the unbounded string
  construction on the retry error path.
- `java.lang.OutOfMemoryError: Java heap space` with stack trace through
  `CloseableTableSeqWithTargetSize.toString -> mkString -> StringBuilder.append`.

**Fix:**
Override `toString()` in `CloseableTableSeqWithTargetSize` with a constant-cost summary
that only reports `numTables`, `targetSize`, and `minSize`. This keeps the diagnostic
information useful while avoiding memory allocation proportional to the number of input
partitions.

No new configurations introduced.

Existing tests in `GpuShuffleCoalesceSuite` cover the affected code path. The fix is a
trivial `toString` override with no behavioral change to the split/retry logic itself.

### Checklists

- [x] This PR has added documentation for new or modified features or behaviors.
- [x] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [x] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by winningsix** [comment]
build

**Comment by GaryShen2008** [comment]
Let's target release/26.04 first.

**Comment by winningsix** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala [hunk 1]
```diff
@@ -481,6 +481,12 @@ case class CloseableTableSeqWithTargetSize[T <: AutoCloseable](
   override def length: Int = tables.length
   override def iterator: Iterator[T] = tables.iterator
   override def apply(idx: Int): T = tables.apply(idx)
+
+  // Keep retry-OOM reporting bounded. SeqLike.toString would stringify every table.
+  override def toString: String = {
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala:486]: This tells me we should, instead of subclassing `Seq[T]` directly or `AutoCloseable`, have specific traits for Retry that do just that then require one to implement a well documented stringify method.

Comment (abellina) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala:486]: @winningsix can you please help me understand what `T` is and why this an unbounded Seq?

Comment (winningsix) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala:486]: T is KudoSerializedTableColumn. 
```
CloseableTableSeqWithTargetSize.toString()     ← Scala SeqLike default
  → mkString("; ")                              ← iterates ALL elements
    → KudoSerializedTableColumn.toString()      ← no override, falls to Object.toString
      → includes: spillableKudoTable field
        → SpillableKudoTable.toString()
          → "SpillableKudoTable{header=<KudoTableHeader>, shb=<SpillableHostBuffer>}"
            → SpillableHostBuffer.toString()
              → "SpillableHostBuffer length:N, handle:<SpillableHostBufferHandle>"
```

**Comment by abellina** [comment]
@winningsix if we can stop constructing the string for every split here: https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala#L491C11-L491C26 that would be a win. It's ok if that's a follow on.

**Comment by abellina** [comment]
> @winningsix if we can stop constructing the string for every split here: https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala#L491C11-L491C26 that would be a win. It's ok if that's a follow on.

oh you already did that,nice

**Comment by winningsix** [comment]
build

**Comment by GaryShen2008** [comment]
Hi @winningsix，can you cherry-pick this PR to branch release/26.02？
