### PR TITLE
Fix `collection_ops_tests` for Spark 4.0 [databricks]

### LINKED ISSUE #11011: Fix tests failures in collection_ops_test.py
```
FAILED ../../../../integration_tests/src/main/python/collection_ops_test.py::test_sequence_too_long_sequence
```

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #11011.

This commit fixes the failures in `collection_ops_tests` on Spark 4.0.

On all versions of Spark, when a Sequence is collected with rows that exceed MAX_INT,
an exception is thrown indicating that the collected Sequence/array is
larger than permissible. The different versions of Spark vary in the
contents of the exception message.

On Spark 4, one sees that the error message now contains more
information than all prior versions, including:
1. The name of the op causing the error.
2. The errant sequence size.

This commit introduces a shim to make this new information available in
the exception.

Note that this shim does not fit cleanly in RapidsErrorUtils, because
there are differences within major Spark versions. For instance, Spark
3.4.0-1 have a different message as compared to 3.4.2 and 3.4.3.
Likewise, the differences in 3.5.0, 3.5.1, 3.5.2.

### CODE REVIEW

**Comment by mythrocks** [comment]
Build

File: sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/SequenceSizeError.scala [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+/*** spark-rapids-shim-json-lines
+{"spark": "400"}
+spark-rapids-shim-json-lines ***/
+package org.apache.spark.sql.rapids.shims
+
+import org.apache.spark.sql.errors.QueryExecutionErrors
+
+object SequenceSizeError {
+  def getTooLongSequenceErrorString(sequenceSize: Int, functionName: String): String = {
+    QueryExecutionErrors.createArrayWithElementsExceedLimitError(functionName, sequenceSize)
```
Comment (razajafri) [inline sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/SequenceSizeError.scala:26]: We should move this to RapidsErrorUtils 

The way I would do it is remove the `TOO_LONG_SEQUENCE` from the `GetSequenceSize.scala` altogether 

Then introduce another trait `RapidsErrorUtilsForSequence` with a method `tooLongSequenceError`. The versions of 320 will have it's own implementation returning the hardcoded message "Too long..."  334-352 will have it's own implementation returning "Unsuccessful try..." and 400 will have it's own where it returns the QueryExecution.createArrayWithElementsExceedLimitErrors

Comment (mythrocks) [reply sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/SequenceSizeError.scala:26]: I think we're talking at cross purposes.  Or maybe I'm simply unable to grok the suggestion yet.

>  The versions of 320 will have it's own implementation returning the hardcoded message "Too long..." 334-352 will have it's own implementation

This largely describes what my patch currently does, save for moving it into `RapidsErrorUtils`.

The reason (I think) I can't move this into `RapidsErrorUtils` is that the error messages differ within the same major Spark version.  

The error messages are split as follows:
1. `Too long sequence found`:
    1. 3.2.*
    1. 3.3.[x<4]
    1. 3.4.[x<2]
    1. 3.5.0
2. `Unsuccessful try to create array`:
    1. 3.3.4
    1. 3.4.[2-3]
    1. 3.5.[1-2]
3. `Can't create array with...`:
    1. Only 4.0.  

The `RapidsErrorUtils` shims are grouped by version, as follows:
1. All 3.2.* together.
2. All 3.3.* except 3.3.*db
3. All 3.3.[0,2]db
4. 3.4.[0-3] + 3.5.[0-2] + 4.0.0.

Now if I'm trying to accommodate the correct error message for, say, `Spark 3.4.2`, I can't because there's only one `RapidsErrorUtils` for all of Spark 3.4.x (and that class happens to affect all 3.5.x as well as 4.0).  

Is the suggestion to further slice up `3.4.*`'s `RapidsErrorUtils`?  We will then have to also slice up the same for `3.3.x` and `3.5.x` as well, with code duplicated everywhere.  This doesn't sound productive to me.  

Maybe I've missed something.  Perhaps we should discuss this offline, and update the result on this bug.

Comment (mythrocks) [reply sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/SequenceSizeError.scala:26]: This refactor is turning into a rats' nest.  When the next shim needs to be added, and things need to be split further, I think it's going to be unreadable.

`RapidsErrorUtilsBase`, used in `33xdb` is a very misleading name for the errors shim.  It seems to apply only in `33x`, while its name suggests that it's the base-class for all the `RapidsErrorUtils`.  This is painful.

I'm going to try to add this with as little collateral damage as I can.

**Comment by mythrocks** [comment]
Apologies for the noise.  I had to rebase this to target `branch-24.12`, which then caused a lot of new reviewers to be added. 

@razajafri is already examining this change.  The others can ignore this.

**Comment by mythrocks** [comment]
Build

File: integration_tests/src/main/python/collection_ops_test.py [hunk 2]
```diff
@@ -17,6 +17,8 @@
 from asserts import assert_gpu_and_cpu_are_equal_collect, assert_gpu_and_cpu_error
 from data_gen import *
 from pyspark.sql.types import *
+
+from src.main.python.spark_session import is_before_spark_400
```
[the remark this answers is not in the document]
Comment (mythrocks) [reply integration_tests/src/main/python/collection_ops_test.py]: Agreed.  I think the qualification was added by the IDE.  I've fixed this.  Thank you for pointing this out.

File: sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GetSequenceSize.scala [hunk 3]
```diff
@@ -42,7 +42,12 @@ import com.nvidia.spark.rapids.Arm._
 import org.apache.spark.unsafe.array.ByteArrayMethods.MAX_ROUNDED_ARRAY_LENGTH
 
 object GetSequenceSize {
-  val TOO_LONG_SEQUENCE = s"Too long sequence found. Should be <= $MAX_ROUNDED_ARRAY_LENGTH"
+  def TOO_LONG_SEQUENCE(sequenceLength: Int, functionName: String) = {
```
[the remark this answers is not in the document]
Comment (mythrocks) [reply sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GetSequenceSize.scala]: True.  This was an attempt at reducing code change.  This constant has been removed, in the new version of this change.

File: sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/SequenceSizeError.scala (hunk 1 above)
Comment (mythrocks) [reply sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/SequenceSizeError.scala]: I have fixed this.  As discussed, I have refactored the `RapidsErrorUtils` into more concrete versions, and used mix-ins for the new behaviours.

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 4]
```diff
@@ -21,64 +21,9 @@
...
 spark-rapids-shim-json-lines ***/
 package org.apache.spark.sql.rapids.shims
 
-import org.apache.spark.SparkDateTimeException
-import org.apache.spark.sql.catalyst.trees.Origin
-import org.apache.spark.sql.errors.QueryExecutionErrors
-import org.apache.spark.sql.internal.SQLConf
-import org.apache.spark.sql.types.{DataType, Decimal, DecimalType}
+object RapidsErrorUtils extends RapidsErrorUtils330To334Base
+                        with    SequenceSizeTooLongErrorBuilder
```
Comment (razajafri) [inline sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:28]: check format

File: sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 5]
```diff
@@ -22,7 +22,9 @@ package org.apache.spark.sql.rapids.shims
 
 import org.apache.spark.sql.errors.QueryExecutionErrors
 
-object RapidsErrorUtils extends RapidsErrorUtilsBase with RapidsQueryErrorUtils {
+object RapidsErrorUtils extends RapidsErrorUtilsBase
+                        with    RapidsQueryErrorUtils
+                        with    SequenceSizeTooLongErrorBuilder {
```
Comment (razajafri) [inline sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:27]: check format

File: sql-plugin/src/main/spark334/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+ * limitations under the License.
+ */
+
+/*** spark-rapids-shim-json-lines
+{"spark": "334"}
+spark-rapids-shim-json-lines ***/
+package org.apache.spark.sql.rapids.shims
+
+object RapidsErrorUtils extends RapidsErrorUtils330To334Base
+                        with    SequenceSizeTooLongUnsuccessfulErrorBuilder
```
Comment (razajafri) [inline sql-plugin/src/main/spark334/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:23]: check format

File: sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 7]
```diff
@@ -17,80 +17,9 @@
...
-  def sqlArrayIndexNotStartAtOneError(): RuntimeException = {
-    QueryExecutionErrors.invalidIndexOfZeroError(context = null)
-  }
-  
-  override def intervalDivByZeroError(origin: Origin): ArithmeticException = {
-    QueryExecutionErrors.intervalDividedByZeroError(origin.context)
-  }
-}
+object RapidsErrorUtils extends RapidsErrorUtils340PlusBase
+                        with    SequenceSizeTooLongErrorBuilder
```
Comment (razajafri) [inline sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:25]: check format

File: sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 8]
```diff
@@ -21,7 +21,9 @@ package org.apache.spark.sql.rapids.shims
 
 import org.apache.spark.sql.errors.QueryExecutionErrors
 
-object RapidsErrorUtils extends RapidsErrorUtilsBase with RapidsQueryErrorUtils {
+object RapidsErrorUtils extends RapidsErrorUtilsBase
+                        with    RapidsQueryErrorUtils
+                        with    SequenceSizeTooLongErrorBuilder {
```
Comment (razajafri) [inline sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:26]: check format

File: sql-plugin/src/main/spark342/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 9]
```diff
@@ -0,0 +1,26 @@
...
+/*** spark-rapids-shim-json-lines
+{"spark": "342"}
+{"spark": "343"}
+{"spark": "351"}
+{"spark": "352"}
+spark-rapids-shim-json-lines ***/
+package org.apache.spark.sql.rapids.shims
+
+object RapidsErrorUtils extends RapidsErrorUtils340PlusBase
+                        with    SequenceSizeTooLongUnsuccessfulErrorBuilder
```
Comment (razajafri) [inline sql-plugin/src/main/spark342/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:26]: check format

File: sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 10]
```diff
@@ -0,0 +1,23 @@
...
+ * limitations under the License.
+ */
+
+/*** spark-rapids-shim-json-lines
+{"spark": "400"}
+spark-rapids-shim-json-lines ***/
+package org.apache.spark.sql.rapids.shims
+
+object RapidsErrorUtils extends RapidsErrorUtils340PlusBase
+                        with    SequenceSizeExceededLimitErrorBuilder
```
Comment (razajafri) [inline sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:23]: check format

**Comment by mythrocks** [comment]
I've addressed the code formatting suggestions.

**Comment by mythrocks** [comment]
Build

File: sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GetSequenceSize.scala [hunk 11]
```diff
@@ -39,10 +39,7 @@ package com.nvidia.spark.rapids.shims
 import ai.rapids.cudf._
 import com.nvidia.spark.rapids.Arm._
 
-import org.apache.spark.unsafe.array.ByteArrayMethods.MAX_ROUNDED_ARRAY_LENGTH
```
Comment (mythrocks) [inline sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GetSequenceSize.scala:42]: We'll need to add `{"spark": "350db"}` to support Databricks 14.3.

File: sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 12]
```diff
@@ -21,7 +21,8 @@ package org.apache.spark.sql.rapids.shims
 
 import org.apache.spark.sql.errors.QueryExecutionErrors
 
-object RapidsErrorUtils extends RapidsErrorUtilsBase with RapidsQueryErrorUtils {
+object RapidsErrorUtils extends RapidsErrorUtilsBase
```
Comment (mythrocks) [inline sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:24]: Likewise here, this shim should include `350db` to support Databricks 14.3.

File: sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/SequenceSizeTooLongErrorBuilder.scala [hunk 13]
```diff
@@ -0,0 +1,48 @@
...
+{"spark": "331"}
+{"spark": "332"}
+{"spark": "332cdh"}
+{"spark": "332db"}
+{"spark": "333"}
+{"spark": "340"}
+{"spark": "341"}
+{"spark": "341db"}
+{"spark": "350"}
+spark-rapids-shim-json-lines ***/
```
Comment (mythrocks) [inline sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/SequenceSizeTooLongErrorBuilder.scala:36]: This probably needs `350db` to support Databricks 14.3.  I'm checking this now.

File: sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GetSequenceSize.scala (hunk 11 above)
Comment (mythrocks) [reply sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GetSequenceSize.scala:42]: I'm closing this out.  As discussed, we'll chase down Databricks 14.3's changes in a follow-up.

File: sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/SequenceSizeTooLongErrorBuilder.scala (hunk 13 above)
Comment (mythrocks) [reply sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/SequenceSizeTooLongErrorBuilder.scala:36]: I'm closing this out.  As discussed, we'll chase down Databricks 14.3's changes in a follow-up.

File: sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala (hunk 12 above)
Comment (mythrocks) [reply sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:24]: I'm closing this out.  As discussed, we'll chase down Databricks 14.3's changes in a follow-up.

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
@razajafri:  After addressing your whitespace concerns, I had started evaluating support for the 14.3 failure.  I had a couple of markers to indicate changes, but I've closed them now.

The behaviour with `14.x` differs from `13.x`, and will require a shim split to address.  I'll do this in a follow-up.    

If this current state looks good to you for shipping, I'll merge this change, and address `14.3` separately.

**Review by razajafri — APPROVED** [review]

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
Thanks for the review, @razajafri.  I have merged this change.
