### PR TITLE
Fix databricks for 3.1.1

### LINKED ISSUE #2628: [BUG] failed to build plugin in databricks runtime 8.2
**Describe the bug**
failed to compile plugin in databricks 8.2 runtime (3.1.1)

GpuBroadcastExchangeExecBase conflict w/ db311 BroadcastExchangeLike
GpuShuffleExchangeExecBase conflict w/ db311 ShuffleExchangeLike
```
[2021-06-08T03:16:51.292Z] [INFO] --- scala-maven-plugin:4.3.0:compile (scala-compile-first) @ rapids-4-spark-shims-spark311-databricks_2.12 ---
[2021-06-08T03:16:51.292Z] [INFO] Using incremental compilation using Mixed compile order
[2021-06-08T03:16:51.292Z] [INFO] Compiler bridge file: /home/ubuntu/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.12-1.3.1-bin_2.12.8__52.0-1.3.1_20191012T045515.jar
[2021-06-08T03:16:51.547Z] [INFO] Compiling 16 Scala sources to /home/ubuntu/spark-rapids/shims/spark311db/target/classes ...
[2021-06-08T03:16:58.069Z] [ERROR] [Error] /home/ubuntu/spark-rapids/shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuBroadcastExchangeExec.scala:26: class GpuBroadcastExchangeExec inherits conflicting members:
[2021-06-08T03:16:58.069Z]   lazy value completionFuture in class GpuBroadcastExchangeExecBase of type scala.concurrent.Future[org.apache.spark.broadcast.Broadcast[Any]]  and
[2021-06-08T03:16:58.069Z]   method completionFuture in trait BroadcastExchangeLike of type => scala.concurrent.Future[org.apache.spark.broadcast.Broadcast[Any]]
[2021-06-08T03:16:58.069Z] (Note: this can be resolved by declaring an override in class GpuBroadcastExchangeExec.)
[2021-06-08T03:16:58.069Z] [ERROR] [Error] /home/ubuntu/spark-rapids/shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuShuffleExchangeExec.scala:25: class GpuShuffleExchangeExec inherits conflicting members:
[2021-06-08T03:16:58.069Z]   lazy value mapOutputStatisticsFuture in class GpuShuffleExchangeExecBase of type scala.concurrent.Future[org.apache.spark.MapOutputStatistics]  and
[2021-06-08T03:16:58.069Z]   method mapOutputStatisticsFuture in trait ShuffleExchangeLike of type => scala.concurrent.Future[org.apache.spark.MapOutputStatistics]
[2021-06-08T03:16:58.069Z] (Note: this can be resolved by declaring an override in class GpuShuffleExchangeExec.)
[2021-06-08T03:16:58.069Z] [ERROR] two errors found
```

### PR DESCRIPTION
**Pull request by revans2**
This fixes #2628

I got through about 90% of the python tests before databricks timed out, so I am going to rerun them in parallel with this PR.

### CODE REVIEW

**Comment by revans2** [comment]
build

File: shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuShuffleExchangeExec.scala [hunk 1]
```diff
@@ -13,7 +13,11 @@
  * See the License for the specific language governing permissions and
  * limitations under the License.
  */
-package com.nvidia.spark.rapids.shims.spark311db
+package org.apache.spark.sql.rapids.shims.spark311db
```
Comment (tgravescs) [inline shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuShuffleExchangeExec.scala:16]: we should change the file directory location to match new package

**Comment by revans2** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by revans2** [comment]
build

File: shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuShuffleExchangeExec.scala [hunk 2]
```diff
@@ -20,13 +20,14 @@ import org.apache.spark.sql.catalyst.plans.logical.Statistics
 import org.apache.spark.sql.catalyst.plans.physical.Partitioning
 import org.apache.spark.sql.execution.{ShufflePartitionSpec, SparkPlan}
 import org.apache.spark.sql.execution.exchange.ShuffleExchangeLike
-import org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase
+import org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBaseWithMetrics
```
Comment (mythrocks) [inline shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuShuffleExchangeExec.scala:23]: This might be a stupid question: If the build is failing on Databricks 8.2 (i.e. the `3.1.1` shim), why must we change the `3.0.1` shim?

Comment (revans2) [reply shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuShuffleExchangeExec.scala:23]: I changed the class hierarchy to allow databricks 8.2 to diverge from the others. I did this by inserting a new class in between `GpuShuffleExchangeExecBase` and all of the other implementations. This let Databrciks modify how metrics are accessed and still have a common implementation for the others.  A similar thing also happened with broadcast for the future there too.

I thought it was better than copying hundreds of lines of code just to change a handful of them.

**Comment by revans2** [comment]
The python tests all passed on databricks 8.2 when I ran them just now.

**Review by tgravescs — APPROVED** [review]

**Review by mythrocks — APPROVED** [review]
