### PR TITLE
[BUG] Fix unregister/remove path for wrapped shuffle resolver

### LINKED ISSUE #14683: [BUG] NDS-H SF1K single-node benchmark fails with java.io.IOException: No space left on device
**Describe the bug**
With the 26.04 jar, an NDS-H single-node SF1K (1TB) run fails eventually with this error:
```
26/04/24 14:05:44 WARN TaskSetManager: Lost task 7.0 in stage 485.0 (TID 9184) (hostname executor driver): TaskKilled (Stage cancelled: Job aborted due to stage failure: Task 3 in stag
e 485.0 failed 1 times, most recent failure: Lost task 3.0 in stage 485.0 (TID 9180) (hostname executor driver): java.io.IOException: No space left on device                           
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)                                            
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)                                
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)                                        
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)                                                                                                                                                                  
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)                                     
        at com.nvidia.spark.rapids.spill.SpillablePartialFileHandle.$anonfun$spill$1(SpillablePartialFileHandle.scala:610)                                                                                          
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)                                                                                                                                   
        at org.apache.spark.sql.rapids.GpuTaskMetrics.$anonfun$timeIt$1(GpuTaskMetrics.scala:376)         
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)                                        
        at org.apache.spark.sql.rapids.GpuTaskMetrics.timeIt(GpuTaskMetrics.scala:374)                                                                                                                              
        at org.apache.spark.sql.rapids.GpuTaskMetrics.spillToDiskTime(GpuTaskMetrics.scala:409)           
        at com.nvidia.spark.rapids.spill.SpillablePartialFileHandle.spill(SpillablePartialFileHandle.scala:603)                                                                                                     
        at org.apache.spark.shuffle.sort.io.RapidsLocalDiskShuffleMapOutputWriter.$anonfun$commitAllPartitions$1(RapidsLocalDiskShuffleMapOutputWriter.scala:201)                                                   
        at scala.Option.foreach(Option.scala:407)    
        at org.apache.spark.shuffle.sort.io.RapidsLocalDiskShuffleMapOutputWriter.commitAllPartitions(RapidsLocalDiskShuffleMapOutputWriter.scala:195)                                                              
        at org.apache.spark.sql.rapids.shims.RapidsShuffleThreadedWriter.doCommitAllPartitions(RapidsShuffleThreadedWriter.scala:96)                                                                                
        at org.apache.spark.sql.rapids.RapidsShuffleWriterShimHelper.commitAllPartitions(RapidsShuffleInternalManagerBase.scala:291)                                                                                
        at org.apache.spark.sql.rapids.RapidsShuffleWriterShimHelper.commitAllPartitions$(RapidsShuffleInternalManagerBase.scala:290)                                                                               
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.commitAllPartitions(RapidsShuffleInternalManagerBase.scala:298)                                                                              
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$writePartitionedGpuBatches$7(RapidsShuffleInternalManagerBase.scala:829)                                                            
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)                                                                                                                                 
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)                      
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)                                                                                                                                       
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.writePartitionedGpuBatches(RapidsShuffleInternalManagerBase.scala:810)                                                                       
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.write(RapidsShuffleInternalManagerBase.scala:592)                                                                                            
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)           
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)                    
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)                     
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)                       
        at org.apache.spark.scheduler.Task.run(Task.scala:141)                                            
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:621)               
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)             
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)            
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)                            
```

**Steps/Code to reproduce bug**
Run NDS-H SF1K on a single node.  I've reproduced with a single node with an L4.

**Expected behavior**
NDS-H should complete with no errors.  

**Additional context**
Issue was not observed with 26.02 release jar.

### PR DESCRIPTION
**Pull request by abellina**
Contributes https://github.com/NVIDIA/spark-rapids/issues/14683

### Description

With this change in 26.04 https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala#L1819 we started to use `GpuShuffleBlockResolver` as our shuffle resolver, instead of using the default `IndexShuffleBlockResolver`. 

The problem is then seen in `unregisterShuffle` where a special case https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala#L2102 prevents shuffles to be cleaned anymore, since now we use a different resolver.

The issue then is that we keep old shuffle files around even though they have been GC'ed. The fix, is to extract the `IndexShuffleBlockResolver` out of our `GpuShuffleBlockResolver` and ask it to remove shuffle files for map outputs we wrote, as we did prior to 26.04. This PR implements that path.

I verified this with nds-h, where without this patch, we would leave 50% more shuffle space used for the sf1k data scale. This could leave us open to "disk full" exceptions.

I could write tests for this as a follow on: something that verifies unregistered shuffle clears files. But I would like to do that as a follow on if that is OK.

### Checklists

Documentation
- [ ] Updated for new or modified user-facing features or behaviors
- [x] No user-facing change

Testing
- [ ] Added or modified tests to cover new code paths
- [ ] Covered by existing tests
      (Please provide the names of the existing tests in the PR description.)
- [x] Not required

Performance
- [ ] Tests ran and results are added in the PR description
- [ ] Issue filed with a link in the PR description
- [x] Not required

### CODE REVIEW

**Comment by abellina** [comment]
build

File: sql-plugin/src/main/spark321/scala/org/apache/spark/rapids/shims/GpuShuffleBlockResolver.scala [hunk 1]
```diff
@@ -56,7 +56,7 @@ import org.apache.spark.sql.rapids.GpuShuffleBlockResolverBase
 import org.apache.spark.storage.ShuffleMergedBlockId
 
 class GpuShuffleBlockResolver(
-    resolver: IndexShuffleBlockResolver,
+    val resolver: IndexShuffleBlockResolver,
```
Comment (zpuller) [inline sql-plugin/src/main/spark321/scala/org/apache/spark/rapids/shims/GpuShuffleBlockResolver.scala:59]: nit: why do we need to add this?

**Review by zpuller — DISMISSED** [review]

File: sql-plugin/src/main/spark321/scala/org/apache/spark/rapids/shims/GpuShuffleBlockResolver.scala (hunk 1 above)
Comment (abellina) [reply sql-plugin/src/main/spark321/scala/org/apache/spark/rapids/shims/GpuShuffleBlockResolver.scala:59]: this allows us access to the field, since the resolver isn't a `case class`. It makes the field `resolver` public.

**Comment by pxLi** [comment]
NOTE: there is no automerge since we have already released 26.04.0, so the change should be filed for both `main` and `release/26.04`, thanks

**Comment by abellina** [comment]
@zpuller I had to retarget to 26.04, mind taking another look?

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
once this one merges, we'll want to merge https://github.com/NVIDIA/spark-rapids/pull/14687 to main.

**Review by binmahone — APPROVED** [review]
nice catch @abellina

**Review by zpuller — APPROVED** [review]
