### PR TITLE
[AutoSparkUT] Fix LIKE with invalid escape pattern to match CPU behavior

### LINKED ISSUE #14117: [AutoSparkUT]"SPARK-33677: LikeSimplification should be skipped if pattern contains any escapeChar" in SQLQuerySuite failed
**Describe the bug**
"SPARK-33677: LikeSimplification should be skipped if pattern contains any escapeChar" in SQLQuerySuite failed.
Below query doesn't throw exception as CPU does.
sql("SELECT s LIKE 'm%@ca' ESCAPE '%' FROM df").collect()

**Steps/Code to reproduce bug**
Spark-shell:
```
/data/spark-3.3.0-bin-hadoop3/bin/spark-shell   --master local[2]   --conf spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation,org.apache.spark.sql.catalyst.optimizer.ConstantFolding   --conf spark.rapids.sql.enabled=true   --conf spark.plugins=com.nvidia.spark.SQLPlugin   --conf spark.sql.queryExecutionListeners=org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback   --conf spark.rapids.sql.explain=ALL   --conf spark.rapids.sql.test.isFoldableNonLitAllowed=true   --conf spark.rapids.sql.csv.read.decimal.enabled=true   --conf spark.rapids.sql.format.avro.enabled=true   --conf spark.rapids.sql.format.avro.read.enabled=true   --conf spark.rapids.sql.format.json.enabled=true   --conf spark.rapids.sql.format.json.read.enabled=true   --conf spark.rapids.sql.incompatibleDateFormats.enabled=true   --conf spark.rapids.sql.python.gpu.enabled=true   --conf spark.rapids.sql.rowBasedUDF.enabled=true   --conf spark.rapids.sql.window.collectList.enabled=true   --conf spark.rapids.sql.window.collectSet.enabled=true   --conf spark.rapids.sql.window.range.byte.enabled=true   --conf spark.rapids.sql.window.range.short.enabled=true   --conf spark.rapids.sql.expression.Ascii=true   --conf spark.rapids.sql.expression.Conv=true   --conf spark.rapids.sql.expression.GetJsonObject=true   --conf spark.rapids.sql.expression.JsonToStructs=true   --conf spark.rapids.sql.expression.StructsToJson=true   --conf spark.rapids.sql.exec.CollectLimitExec=true   --conf spark.rapids.sql.exec.FlatMapCoGroupsInPandasExec=true   --conf spark.rapids.sql.exec.WindowInPandasExec=true   --conf spark.rapids.sql.hasExtendedYearValues=false   --conf spark.unsafe.exceptionOnMemoryLeak=true   --conf spark.sql.session.timeZone=UTC
```

Scala code:
```
Seq("m@ca").toDF("s").createOrReplaceTempView("df")
sql("SELECT s LIKE 'm%@ca' ESCAPE '%' FROM df").collect()
```

Expect AnalysisException
```
 assert(e.message.contains("the pattern 'm%@ca' is invalid, " +
        "the escape character is not allowed to precede '@'"))
```

But GPU just ran successfully with result "true".

**Expected behavior**
GPU should behave as same as CPU does.

**Environment details (please complete the following information)**
 - Environment location: [Spark 330, local mode]

### PR DESCRIPTION
**Pull request by wjxiz1992**
Closes #14117

## Summary

- Validate LIKE escape patterns on GPU to match CPU semantics. Previously `GpuLike` passed patterns directly to cuDF, which silently accepted invalid escape sequences (e.g. `LIKE 'm%@ca' ESCAPE '%'`), returning wrong results instead of throwing `AnalysisException` like CPU does.
- Add `tagExprForGpu` in `BinaryExprMeta[Like]` with a focused O(n) escape-char validation that detects invalid patterns and falls back to CPU, which throws the correct `AnalysisException`.
- Remove SPARK-33677 exclusion from `RapidsTestSettings`.

## UT Traceability

| Item | Detail |
|------|--------|
| RAPIDS suite | `RapidsSQLQuerySuite` |
| Spark original test | `"SPARK-33677: LikeSimplification should be skipped if pattern contains any escapeChar"` |
| Spark source file | `sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala` |
| Line range | L3758–L3773 |
| Source (master) | [SQLQuerySuite.scala#L3758-L3773](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala#L3758-L3773) |
| Source (pinned) | [SQLQuerySuite.scala@f66c336#L3758-L3773](https://github.com/apache/spark/blob/f66c3361852214d2adc35ed1dc4a1980057dba6f/sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala#L3758-L3773) |

### Performance

**No runtime path changes.** `GpuLike.doColumnar` is unchanged — the GPU execution path is identical before and after this PR. The only addition is a planning-time O(n) character scan in `tagExprForGpu` that runs once per `Like` expression during query planning.

**Before/after benchmark** (RTX 5880 48 GB, Spark 3.3.0, `local[8]`, 8 GB driver, `allocFraction=0.3`, `pinnedPool=2g`, AQE off):

- BEFORE JAR: built from `origin/main` at `9685a7b4e` (no escape validation)
- AFTER JAR: built from this PR branch at `bd7f8eb17` (with `tagExprForGpu` validation)
- Same query: `LIKE '%1!_%' ESCAPE '!'` on `spark.range(0, 4294967296L, 1, 32).selectExpr("CAST(id AS STRING) AS sid")`

| Test | BEFORE (`main`) | AFTER (this PR) | Delta |
|------|-----------------|-----------------|-------|
| Large query (4B rows, 32 partitions) | 772 ms | 736 ms | -36 ms (-4.7%, noise) |
| 500 small queries (10 rows each, planning overhead) | 44.32 ms/q | 44.59 ms/q | +0.27 ms (+0.6%, noise) |
| Small-batch stress (10 MiB batch, 4B rows) | 753 ms | 756 ms | +3 ms (+0.4%, noise) |

All deltas are within run-to-run variance (< 5%). No measurable performance regression.

## Test Plan

- `mvn package -pl tests -am -Dbuildver=330 -DwildcardSuites=...RapidsSQLQuerySuite` — 215 passed, 0 failed, 18 ignored
- Pre-merge CI (defaults unchanged, expected no regression)

### Checklists

- [ ] This PR has added documentation for new or modified features or
behaviors.
- [x] This PR has added new tests or modified existing tests to cover
new code paths.
(The SPARK-33677 exclusion is removed, re-enabling the existing Spark test
`"SPARK-33677: LikeSimplification should be skipped if pattern contains any escapeChar"`
in `RapidsSQLQuerySuite`, which covers the new `tagExprForGpu` validation path.)
- [x] Performance testing has been performed and its results are added
in the PR description. Or, an issue has been filed with a link in the PR
description.

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by wjxiz1992** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala [hunk 1]
```diff
@@ -3501,6 +3501,24 @@ object GpuOverrides extends Logging {
...
+                StringUtils.escapeLikeRegex(
+                  l.value.asInstanceOf[UTF8String].toString,
+                  a.escapeChar)
+              case _ =>
+            }
+          } catch {
+            case _: Exception =>
+              willNotWorkOnGpu(
+                "invalid LIKE escape pattern")
+          }
```
[the remark this answers is not in the document]
Comment (wjxiz1992) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala]: Good catch. Fixed in d4191a37f — now using `NonFatal(e)` (already imported at line 23) and including `e.getMessage` in the `willNotWorkOnGpu` reason:

```scala
case NonFatal(e) =>
  willNotWorkOnGpu(
    s"invalid LIKE escape pattern: " +
      s"${e.getMessage}")
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala [hunk 2]
```diff
@@ -976,12 +977,19 @@ case class GpuLike(left: Expression, right: Expression, escapeChar: Char)
...
   override def toString: String = escapeChar match {
     case '\\' => s"$left gpulike $right"
     case c => s"$left gpulike $right ESCAPE '$c'"
   }
 
   override def doColumnar(lhs: GpuColumnVector, rhs: GpuScalar): ColumnVector = {
+    if (!escapeValidated && rhs.isValid) {
+      StringUtils.escapeLikeRegex(
+        rhs.getValue.asInstanceOf[UTF8String].toString, escapeChar)
+      escapeValidated = true
```
[the remark this answers is not in the document]
Comment (wjxiz1992) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala]: Agreed. Fixed in d4191a37f — replaced `rhs.getValue.asInstanceOf[UTF8String].toString` with `rhs.getValue.toString`, which safely handles both `UTF8String` and `String` backed scalars.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala [hunk 3]
```diff
@@ -3501,6 +3501,24 @@ object GpuOverrides extends Logging {
...
+        override def tagExprForGpu(): Unit = {
+          import org.apache.spark.sql.catalyst.util.StringUtils
+          try {
+            a.right match {
+              case l: Literal
+                  if l.value != null &&
+                    l.dataType == StringType =>
+                StringUtils.escapeLikeRegex(
+                  l.value.asInstanceOf[UTF8String].toString,
+                  a.escapeChar)
```
[the remark this answers is not in the document]
Comment (wjxiz1992) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala]: Good point. Fixed in d4191a37f — replaced the `l.dataType == StringType` guard with `l.value.isInstanceOf[UTF8String]`, which validates the runtime type directly. This correctly covers `CharType`/`VarcharType` (whose values are still `UTF8String` at runtime) without needing to enumerate all string-like data types. Also switched to `l.value.toString` accordingly.

**Comment by wjxiz1992** [comment]
build

**Comment by wjxiz1992** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala [hunk 4]
```diff
@@ -3501,6 +3501,23 @@ object GpuOverrides extends Logging {
...
       (a, conf, p, r) => new BinaryExprMeta[Like](a, conf, p, r) {
+        override def tagExprForGpu(): Unit = {
+          import org.apache.spark.sql.catalyst.util.StringUtils
+          try {
+            a.right match {
+              case l: Literal
+                  if l.value.isInstanceOf[UTF8String] =>
+                StringUtils.escapeLikeRegex(
+                  l.value.toString, a.escapeChar)
+              case _ =>
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala]: So it is okay if we get a literal that is not a string? or is this more that constant folding was disabled?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala [hunk 5]
```diff
@@ -3501,6 +3501,23 @@ object GpuOverrides extends Logging {
         ("src", TypeSig.STRING, TypeSig.STRING),
         ("search", TypeSig.lit(TypeEnum.STRING), TypeSig.STRING)),
       (a, conf, p, r) => new BinaryExprMeta[Like](a, conf, p, r) {
+        override def tagExprForGpu(): Unit = {
+          import org.apache.spark.sql.catalyst.util.StringUtils
+          try {
+            a.right match {
+              case l: Literal
+                  if l.value.isInstanceOf[UTF8String] =>
+                StringUtils.escapeLikeRegex(
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala]: This does a lot of work.

https://github.com/apache/spark/blob/104e43b75f4f106b03c63f0f0e5fd18d69b1cdf9/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala#L36-L70

Can we please look at what it would take to validate this in a faster way. The main reason I ask is because we want to be able to support cudf's like with a columnar pattern and if we don't understand it validating the pattern on the GPU with the full column is going to be a pain.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala [hunk 6]
```diff
@@ -976,12 +977,19 @@ case class GpuLike(left: Expression, right: Expression, escapeChar: Char)
...
+  @transient private var escapeValidated = false
+
   override def toString: String = escapeChar match {
     case '\\' => s"$left gpulike $right"
     case c => s"$left gpulike $right ESCAPE '$c'"
   }
 
   override def doColumnar(lhs: GpuColumnVector, rhs: GpuScalar): ColumnVector = {
+    if (!escapeValidated && rhs.isValid) {
+      StringUtils.escapeLikeRegex(
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala]: Why do we have to validate this here too? Should we cache if we did this in planning so we don't have to do it multiple times?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala (hunk 4 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala]: We can remove this path: `case _ =>` because "search" only accept literal, it can not be other type.
```scala
("search", TypeSig.lit(TypeEnum.STRING), TypeSig.STRING))
```

**Comment by res-life** [comment]
> Add defensive validation in GpuLike.doColumnar as a safety net.

Not needed. Because there will be no GpuLike if validation is failed.

**Comment by res-life** [comment]
Add the checklist in the desc of this PR:
    ### Checklists
    
    - [ ] This PR has added documentation for new or modified features or
    behaviors.
    - [ ] This PR has added new tests or modified existing tests to cover
    new code paths.
    (Please explain in the PR description how the new code paths are tested,
    such as names of the new/existing tests that cover them.)
    - [ ] Performance testing has been performed and its results are added
    in the PR description. Or, an issue has been filed with a link in the PR
    description.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala (hunk 4 above)
Comment (wjxiz1992) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala]: Nice catch, updated to use a pattern match for it.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala (hunk 6 above)
Comment (wjxiz1992) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala]: right, no need to check at runtime, removed.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala (hunk 5 above)
Comment (wjxiz1992) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala]: Agree. Now replace it with a light-weight logic to checks the two invalid cases defined in Spark's [`Like` expression doc](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/regexpExpressions.scala#L143-L145) ("It is invalid to escape any other character") and implemented by [`StringUtils.escapeLikeRegex`](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala#L36-L70):
1. Escape char at end of pattern (no char to escape)
2. Escape char followed by a char that is not `_`, `%`, or the escape char itself

I'm not sure if this should also be put in a specific function?

**Comment by wjxiz1992** [comment]
> What is the performance impact of this change? All PRs are supposed to have a performance impact unless it is something like a doc or comment only change.

Update the PR description for performance impact with latest change according to review comments. Now only checks at planning stage once with a O(n) logic, where Like strings are usually not that super long.

**Comment by wjxiz1992** [comment]
@revans2 I'm trying to add rules to LLM that we should conduct performance regression check after touching any core functional codes. My question is, what kind of performance check are proper for these changes. 

I can think of 2 types in general: 
- NDS
- micro benchmarks

For NDS, I saw some colleagues do it when it comes to like shuffle optimization, join optimization, rules optimizations etc. 

For micro benchmarks, I saw cuDF has a lot for it, also I recall some micro-benchmarks designed for like long string operations in spark-rapids.

Use this regex change for example, I prefer micro benchmark for it instead of NDS if it really needs a performance regression check. What's your suggestion on this top? A general rule to choose what type of performance checks to apply?

**Comment by revans2** [comment]
@wjxiz1992 we need to use different benchmarks for different reasons and situations. If the change targets a specific set of functionality ( an expression for example, or columnar to row modification), then a targeted micro benchmark can isolate the impact of the change. If the change is general, or the micro benchmark showed a significant regression then a more real world benchmark is helpful to either put the regression in context of real world processing or to exercise the broad change. But we have to be sure that that "real world" benchmark exercises the code we care about. NDS does not fall back to the CPU for any processing. That is good to show shuffle, but not columnar to row changes. NDS does not use maps, or arrays, or structs. So it is not good to test them. It hardly uses strings like real world queries do, so it is bad at that too. We often come up with other more realistic queries or use inspiration from customer queries we know of to help build some of these types of tests.

In general I want to think about how this change could impact the performance of the system and then build tests that would cover that case.  Here we have escape checks that happen at planning time and escape checks that are happening at run time.  The run time checks happen on a per-batch basis. So I probably want a few different tests. Some that are more malicious and some more realistic.

The "real world" test would be something like. `spark.time(spark.range(0, 4294967296L, 1, 32).selectExpr("CAST(id as STRING) as sid").filter("SID LIKE '%B1_B1%' ESCAPE 'B'").count)` I didn't check the syntax, but it should give about a 1 GiB batch to each task and give us 32 tasks to work with (assuming that we have a 1 GiB target batch size and we have 8 or 16 CPU cores to work with for spark running in local mode). This way we get parallelism on the GPU and multiple waves. I typically will capture a history file with this too and compare the optime for the operator that includes the change (probably filter in this case). For this case you have to have some knowledge of how Spark deal with the like operator. If the pattern is static then it may optimize some patterns into other operators. So we cannot do simple things, for example '%1%' is converted into a contains.

If I want to be malicious, then I start to change things around. We can set the target batch size much smaller (10 MiB for example so we get about 100x the number of batches) and see if the runtime check at the beginning of each batch has a measurable impact for before and after.

We could also do a lot of 2 or three row queries in a loop to see if the planning change has a measurable impact.

If we test what we think is the worst case situations and there is no measurable impact then we know it is not a big deal. 

For this case I would not likely use NDS at all. There are few LIKE operations in it. There are few strings too, and the size of the string data isn't large, also most of the patterns that NDS uses are ones that Spark will rewrite to not use LIKE directly at all.

**Comment by wjxiz1992** [comment]
> @wjxiz1992 we need to use different benchmarks for different reasons and situations. If the change targets a specific set of functionality ( an expression for example, or columnar to row modification), then a targeted micro benchmark can isolate the impact of the change. If the change is general, or the micro benchmark showed a significant regression then a more real world benchmark is helpful to either put the regression in context of real world processing or to exercise the broad change. But we have to be sure that that "real world" benchmark exercises the code we care about. NDS does not fall back to the CPU for any processing. That is good to show shuffle, but not columnar to row changes. NDS does not use maps, or arrays, or structs. So it is not good to test them. It hardly uses strings like real world queries do, so it is bad at that too. We often come up with other more realistic queries or use inspiration from customer queries we know of to help build some of these types of tests.
> 
> In general I want to think about how this change could impact the performance of the system and then build tests that would cover that case. Here we have escape checks that happen at planning time and escape checks that are happening at run time. The run time checks happen on a per-batch basis. So I probably want a few different tests. Some that are more malicious and some more realistic.
> 
> The "real world" test would be something like. `spark.time(spark.range(0, 4294967296L, 1, 32).selectExpr("CAST(id as STRING) as sid").filter("SID LIKE '%B1_B1%' ESCAPE 'B'").count)` I didn't check the syntax, but it should give about a 1 GiB batch to each task and give us 32 tasks to work with (assuming that we have a 1 GiB target batch size and we have 8 or 16 CPU cores to work with for spark running in local mode). This way we get parallelism on the GPU and multiple waves. I typically will capture a history file with this too and compare the optime for the operator that includes the change (probably filter in this case). For this case you have to have some knowledge of how Spark deal with the like operator. If the pattern is static then it may optimize some patterns into other operators. So we cannot do simple things, for example '%1%' is converted into a contains.
> 
> If I want to be malicious, then I start to change things around. We can set the target batch size much smaller (10 MiB for example so we get about 100x the number of batches) and see if the runtime check at the beginning of each batch has a measurable impact for before and after.
> 
> We could also do a lot of 2 or three row queries in a loop to see if the planning change has a measurable impact.
> 
> If we test what we think is the worst case situations and there is no measurable impact then we know it is not a big deal.
> 
> For this case I would not likely use NDS at all. There are few LIKE operations in it. There are few strings too, and the size of the string data isn't large, also most of the patterns that NDS uses are ones that Spark will rewrite to not use LIKE directly at all.

Super clear and down to the last detail! Appreciate, will do.

**Comment by wjxiz1992** [comment]
Thanks for the detailed benchmark guidance — very helpful for calibrating future changes.

Clarification on current state: the third commit removed the runtime validation from `GpuLike.doColumnar` per your and res-life's feedback. The only change now is a planning-time O(n) scan in `tagExprForGpu` — `doColumnar` is byte-for-byte identical to `main`.

I ran a proper before/after benchmark (BEFORE = `origin/main` at `9685a7b4e`, AFTER = this PR at `bd7f8eb17`; RTX 5880, Spark 3.3.0, `local[8]`, `allocFraction=0.3`):

| Test | BEFORE | AFTER | Delta |
|---|---|---|---|
| 4B rows, 32 partitions | 772 ms | 736 ms | −36 ms (noise) |
| 500 small queries (planning) | 44.32 ms/q | 44.59 ms/q | +0.27 ms (noise) |
| Small-batch stress (10 MiB) | 753 ms | 756 ms | +3 ms (noise) |

All within run-to-run variance. Updated PR description with results.

**Comment by wjxiz1992** [comment]
build

**Comment by wjxiz1992** [comment]
build

**Comment by wjxiz1992** [comment]
build
