### PR TITLE
[BUG] Fix IT discrepancy which depending on TEST_PARALLEL

### LINKED ISSUE #5714: [BUG] discrepancy in the plugin jar deployment in run_pyspark_from_build.sh depending on TEST_PARALLEL
**Describe the bug**
Classloading bugs detected by CI may be unnecessarily hard to repro locally. We deploy jars differently based on TEST_PARALLEL call path. When xdist call path is triggered we add `--jars` https://github.com/NVIDIA/spark-rapids/blob/4b13b04950235da38cbc9d85ba5230861835e7d6/integration_tests/run_pyspark_from_build.sh#L238

which may change plugin's classloader

**Steps/Code to reproduce bug**
Compare the repro fixed in #5708. The only reason that TEST_PARALLEL=2 mentioned in #5703 is important can be highlighted with pyspark REPL

***was hidden with --jars:***
```
pyspark --jars $PWD/dist/target/rapids-4-spark_2.12-22.06.0-SNAPSHOT-cuda11.jar \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.rapids.force.caller.classloader=false \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin
>>> df=spark.createDataFrame([ ['2022-06-01 07:45'] ], 'a string').selectExpr('hour(a)')
>>> sc._jvm.com.nvidia.spark.rapids.ExplainPlan.explainPotentialGpuPlan(df._jdf, "ALL")
'!Exec <ProjectExec> cannot run on GPU because not all expressions can be replaced\n  @Expression <Alias> hour(cast(a#0 as timestamp), Some(America/Los_Angeles)) AS hour(a)#2 could run on GPU\n    !Expression <Hour> hour(cast(a#0 as timestamp), Some(America/Los_Angeles)) cannot run on GPU because input expression Cast cast(a#0 as timestamp) (TimestampType is not supported when the JVM system timezone is set to America/Los_Angeles. Set the timezone to UTC to enable TimestampType support); Only UTC zone id is supported. Actual zone id: America/Los_Angeles\n      !Expression <Cast> cast(a#0 as timestamp) cannot run on GPU because the GPU only supports a subset of formats when casting strings to timestamps. Refer to the CAST documentation for more details. To enable this operation on the GPU, set spark.rapids.sql.castStringToTimestamp.enabled to true.; Cast from StringType to TimestampType is not supported; Parsing the full rage of supported years is not supported. If your years are limited to 4 positive digits set spark.rapids.sql.hasExtendedYearValues to false.\n        @Expression <AttributeReference> a#0 could run on GPU\n  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec\n    @Expression <AttributeReference> a#0 could run on GPU\n
```

***was broken with extraClassPath***
```
pyspark --driver-class-path $PWD/dist/target/rapids-4-spark_2.12-22.06.0-SNAPSHOT-cuda11.jar \
   --conf spark.executor.extraClassPath=$PWD/dist/target/rapids-4-spark_2.12-22.06.0-SNAPSHOT-cuda11.jar \
   --conf spark.rapids.sql.enabled=true \
   --conf spark.rapids.force.caller.classloader=false \
   --conf spark.plugins=com.nvidia.spark.SQLPlugin
>>> df=spark.createDataFrame([ ['2022-06-01 07:45'] ], 'a string').selectExpr('hour(a)')
>>> sc._jvm.com.nvidia.spark.rapids.ExplainPlan.explainPotentialGpuPlan(df._jdf, "ALL")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/gshegalov/dist/spark-3.2.1-bin-hadoop3.2/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1321, in __call__
  File "/mnt/c/Users/gshegalov/dist/spark-3.2.1-bin-hadoop3.2/python/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/mnt/c/Users/gshegalov/dist/spark-3.2.1-bin-hadoop3.2/python/lib/py4j-0.10.9.3-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.nvidia.spark.rapids.ExplainPlan.explainPotentialGpuPlan.
: java.lang.NoClassDefFoundError: com/nvidia/spark/rapids/GpuOverrides$
        at com.nvidia.spark.rapids.ExplainPlanImpl.explainPotentialGpuPlan(GpuOverrides.scala:4196)
        at com.nvidia.spark.rapids.ExplainPlan$.explainPotentialGpuPlan(ExplainPlan.scala:65)
        at com.nvidia.spark.rapids.ExplainPlan.explainPotentialGpuPlan(ExplainPlan.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.nvidia.spark.rapids.GpuOverrides$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 15 more
```

**Expected behavior**
TEST_PARALLEL should not affect whether integration tests reveal Plugin bugs, just the throughput of integration tests 

**Environment details (please complete the following information)**
- any

**Additional context**
#5703

### PR DESCRIPTION
**Pull request by res-life**
Fixes #5714

### Changes:

- Use `spark.jars` configuration instead of `spark.executor.extraClassPath` and `spark.driver.extraClassPath`.
  There're 2 paths depending on `TEST_PARALLEL`.
```
    if ((${#TEST_PARALLEL_OPTS[@]} > 0));
    then
        exec python "${RUN_TESTS_COMMAND[@]}" "${TEST_PARALLEL_OPTS[@]}" "${TEST_COMMON_OPTS[@]}"
    else
        # We set the GPU memory size to be a constant value even if only running with a parallelism of 1
        # because it helps us have consistent test runs.
        exec "$SPARK_HOME"/bin/spark-submit --jars "${ALL_JARS// /,}" \
            --driver-java-options "$PYSP_TEST_spark_driver_extraJavaOptions" \
            $SPARK_SUBMIT_FLAGS \
            --conf 'spark.rapids.memory.gpu.allocSize='"$PYSP_TEST_spark_rapids_memory_gpu_allocSize" \
            "${RUN_TESTS_COMMAND[@]}" "${TEST_COMMON_OPTS[@]}"
    fi
```

Update the first path, also use `spark.jars` which is same as `--jars`

  `spark.executor.extraClassPath` is deprecated see: 
  https://spark.apache.org/docs/latest/configuration.html

```
spark.executor.extraClassPath: 
Extra classpath entries to prepend to the classpath of executors. 
This exists primarily for backwards-compatibility with older versions of Spark. 
Users typically should not need to set this option.	
```

We can also find the `spark.jars` configure from the above link.

- Update `bash` script to test jar file existence before set JAR_PATH

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
Note: should re-target 22.10

**Comment by tgravescs** [comment]
put in draft since seems for 22.10

File: integration_tests/run_pyspark_from_build.sh [hunk 1]
```diff
@@ -46,27 +46,48 @@ else
 
     # support alternate local jars NOT building from the source code
     if [ -d "$LOCAL_JAR_PATH" ]; then
-        AVRO_JARS=$(echo "$LOCAL_JAR_PATH"/spark-avro*.jar)
-        PLUGIN_JARS=$(echo "$LOCAL_JAR_PATH"/rapids-4-spark_*.jar)
-        if [ -f $(echo $LOCAL_JAR_PATH/parquet-hadoop*.jar) ]; then
+        if [ -f "$LOCAL_JAR_PATH"/spark-avro*.jar ]; then
```
Comment (gerashegalov) [inline integration_tests/run_pyspark_from_build.sh:49]: on the one hand it's good to check for file existence, but on the other hand we don't take any action if it does not exist. There is no error message. And the ALL_JARS assignment on L106 does not  seem to care about it either. Do we need this change?

File: integration_tests/run_pyspark_from_build.sh [hunk 2]
```diff
@@ -46,27 +46,48 @@ else
...
+            AVRO_JARS=$(echo "$LOCAL_JAR_PATH"/spark-avro*.jar)
```
Comment (gerashegalov) [inline integration_tests/run_pyspark_from_build.sh:50]: nit: these echos can be `$(readlink -f  path)` which would get of `..` for some of the paths we use.

File: integration_tests/run_pyspark_from_build.sh [hunk 3]
```diff
@@ -189,8 +210,8 @@ else
     SPARK_TASK_MAXFAILURES=1
     [[ "$VERSION_STRING" < "3.1.1" ]] && SPARK_TASK_MAXFAILURES=4
 
-    export PYSP_TEST_spark_driver_extraClassPath="${ALL_JARS// /:}"
-    export PYSP_TEST_spark_executor_extraClassPath="${ALL_JARS// /:}"
+    export PYSP_TEST_spark_jars="${ALL_JARS// /,}"
```
Comment (gerashegalov) [inline integration_tests/run_pyspark_from_build.sh:213]: for the sake of DRY and consistency let us change L271 for spark-submit in non-xdist callpath
```diff
diff --git a/integration_tests/run_pyspark_from_build.sh b/integration_tests/run_pyspark_from_build.sh
index 5f33bbf12..a6142aaa6 100755
--- a/integration_tests/run_pyspark_from_build.sh
+++ b/integration_tests/run_pyspark_from_build.sh
@@ -268,7 +268,7 @@ else
     else
         # We set the GPU memory size to be a constant value even if only running with a parallelism of 1
         # because it helps us have consistent test runs.
-        exec "$SPARK_HOME"/bin/spark-submit --jars "${ALL_JARS// /,}" \
+        exec "$SPARK_HOME"/bin/spark-submit --conf spark.jars=${PYSP_TEST_spark_jars} \
             --driver-java-options "$PYSP_TEST_spark_driver_extraJavaOptions" \
             $SPARK_SUBMIT_FLAGS \
             --conf 'spark.rapids.memory.gpu.allocSize='"$PYSP_TEST_spark_rapids_memory_gpu_allocSize" \
```

**Review by gerashegalov — CHANGES_REQUESTED** [review]
looks good, just minor comments

File: integration_tests/run_pyspark_from_build.sh (hunk 3 above)
Comment (res-life) [reply integration_tests/run_pyspark_from_build.sh]: Done.

**Comment by res-life** [comment]
The following command gets an invalid path if do not have `spark-avro` jars:  xxx/spark-avro*.jar,
it should return an empty string.

```
AVRO_JARS=$(echo "$LOCAL_JAR_PATH"/spark-avro*.jar)
```

This will cause the following error if put `non-exist jar` into `spark.jars`
```
22/07/22 04:03:12 ERROR SparkContext: Failed to add /home/non-exist.jar to Spark environment
java.io.FileNotFoundException: Jar /home/non-exist.jar not found
	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gerashegalov** [comment]
> The following command gets an invalid path if do not have `spark-avro` jars: xxx/spark-avro*.jar, it should return an empty string.
> 
> ```
> AVRO_JARS=$(echo "$LOCAL_JAR_PATH"/spark-avro*.jar)
> ```

Note that I suggested to replace `echo` by `readlink` https://github.com/NVIDIA/spark-rapids/pull/6044#discussion_r926971343
```bash
$ AVRO_JARS=$(readlink -f /non/existing/path/spark-avro*.jar)
$ echo -n "$AVRO_JARS" | wc -c
0
```

File: integration_tests/run_pyspark_from_build.sh (hunk 2 above)
Comment (res-life) [reply integration_tests/run_pyspark_from_build.sh]: Done

**Comment by res-life** [comment]
A single `readlink -f path` can't get the right answer, see below:
See the final version of the code, currently, it works, and already added the `readlink` to canonicalize the path.

```
$ ls /home/chongg/local-disk/code/spark-rapids/integration_tests/target
run_dir
// not have `integration-tests jar`

$ ls /home/chongg/local-disk/code/spark-rapids/integration_tests/target/rapids-4-spark-integration-tests*-spark330.jar
ls: cannot access '/home/chongg/local-disk/code/spark-rapids/integration_tests/target/rapids-4-spark-integration-tests*-spark330.jar': No such file or directory
// not have `integration-tests jar`

$ readlink -f /home/chongg/local-disk/code/spark-rapids/integration_tests/target/rapids-4-spark-integration-tests*-spark330.jar
/home/chongg/local-disk/code/spark-rapids/integration_tests/target/rapids-4-spark-integration-tests*-spark330.jar
// But readlink gets this non-existing path,  this command can't get the right answer


```

**Comment by gerashegalov** [comment]
re https://github.com/NVIDIA/spark-rapids/pull/6044#issuecomment-1192213024
I inadvertently gave you a switch `-f` that I often use with readlink allowing the leaf path component to be absent. But there is also `-e` requiring all path components to exist. 
 
https://linuxcommand.org/lc3_man_pages/readlink1.html

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
> re [#6044 (comment)](https://github.com/NVIDIA/spark-rapids/pull/6044#issuecomment-1192213024) I inadvertently gave you a switch `-f` that I often use with readlink allowing the leaf path component to be absent. But there is also `-e` requiring all path components to exist.
> 
> https://linuxcommand.org/lc3_man_pages/readlink1.html

Good idea, done.

File: integration_tests/run_pyspark_from_build.sh [hunk 4]
```diff
@@ -87,8 +87,12 @@ else
         AVRO_JARS=""
     fi
 
-    # Only 3 jars: dist.jar integration-test.jar avro.jar
-    ALL_JARS="$PLUGIN_JARS $TEST_JARS $AVRO_JARS $PARQUET_HADOOP_TESTS"
+    # ALL_JARS includes dist.jar integration-test.jar avro.jar parquet.jar if they exist
+    # Remove non-existing paths and canonicalize the paths including get rid of links and `..`
+    ALL_JARS=$(readlink -e $PLUGIN_JARS $TEST_JARS $AVRO_JARS $PARQUET_HADOOP_TESTS || true)
+    # comma separated jars
+    ALL_JARS=$(echo "$ALL_JARS" | tr '\n' ',')
```
Comment (gerashegalov) [inline integration_tests/run_pyspark_from_build.sh:94]: nit: could use the original syntax as well:
```Bash
ALL_JARS="${ALL_JARS//$'\n'/\:}"
```

**Review by gerashegalov — COMMENTED** [review]
LGTM

**Review by gerashegalov — APPROVED** [review]
LGTM, 

please verify that the script works with Iceberg.  Talking to @jlowe I recall it was sensitive to exrtaClassPath vs --jars classloader https://github.com/NVIDIA/spark-rapids/blob/e0a7cd28b724aa7641b8d2828a762fd72c531cf3/jenkins/spark-tests.sh#L181-L192

**Comment by res-life** [comment]
build

**Review by gerashegalov — APPROVED** [review]

**Comment by res-life** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
Investigating the ` class not found` issue:
```
22/08/01 05:25:08 INFO SecurityManager: Changing view acls groups to: 
22/08/01 05:25:08 INFO SecurityManager: Changing modify acls groups to: 
22/08/01 05:25:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
22/08/01 05:25:08 INFO TransportClientFactory: Successfully created connection to premerge-ci-1-jenkins-rapids-premerge-github-5274-b5jn1-05nrp/10.233.110.96:39717 after 3 ms (0 ms spent in bootstraps)
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1748)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:393)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:382)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: java.lang.ClassNotFoundException: com.nvidia.spark.rapids.spark311.RapidsShuffleManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:207)
	at org.apache.spark.SparkEnv$.instantiateClass$1(SparkEnv.scala:275)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:338)
	at org.apache.spark.SparkEnv$.createExecutorEnv(SparkEnv.scala:205)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:442)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	... 4 more
```

**Comment by gerashegalov** [comment]
> Investigating the ` class not found` issue when running `rapids_shuffle_smoke_test` https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/jenkins/spark-premerge-build.sh#L91

This confirms my previous finding #5796 that extraClassPath has been there to begin with to deal with the bug in Spark Standalone. We can work it around and still remain consistent by inspecting whether `spark.shuffle.manager` is part of the config
https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/integration_tests/run_pyspark_from_build.sh#L236 
to decide whether to use --jars or extraClassPath. Then it's clearly documentable when to use which option

**Comment by res-life** [comment]
build

**Comment by gerashegalov** [comment]
> build

@res-life blossom-ci is disabled on draft PR's 

@pxLi  maybe we could move the check to yml because there seems to be Boolean "draft" field on pull_request object https://stackoverflow.com/questions/68349031/only-run-actions-on-non-draft-pull-request

File: integration_tests/run_pyspark_from_build.sh [hunk 5]
```diff
@@ -253,7 +260,8 @@ else
     else
         # We set the GPU memory size to be a constant value even if only running with a parallelism of 1
         # because it helps us have consistent test runs.
-        exec "$SPARK_HOME"/bin/spark-submit --jars "${ALL_JARS// /,}" \
+        # `spark.jars` is the same as `--jars`, e.g.: --jars a.jar,b.jar...
+        exec "$SPARK_HOME"/bin/spark-submit --conf spark.jars=${PYSP_TEST_spark_jars} \
```
Comment (gerashegalov) [inline integration_tests/run_pyspark_from_build.sh:264]: if the above is acceptable here we can do
```suggestion
        if [[ -n "$PYSP_TEST_spark_jars" ]]; then
           jarOpts=(--conf spark.jars="$PYSP_TEST_spark_jars")
        elif [[ -n "$PYSP_TEST_spark_driver_extraClassPath" ]]; then
            jarOpts=(--driver-class-path "$PYSP_TEST_spark_driver_extraClassPath")
        fi
        # `spark.jars` is the same as `--jars`, e.g.: --jars a.jar,b.jar...
        exec "$SPARK_HOME"/bin/spark-submit "${jarOpts[@]}" \
```

File: integration_tests/run_pyspark_from_build.sh [hunk 6]
```diff
@@ -195,8 +199,7 @@ else
     SPARK_TASK_MAXFAILURES=1
     [[ "$VERSION_STRING" < "3.1.1" ]] && SPARK_TASK_MAXFAILURES=4
 
-    export PYSP_TEST_spark_driver_extraClassPath="${ALL_JARS// /:}"
-    export PYSP_TEST_spark_executor_extraClassPath="${ALL_JARS// /:}"
+    export PYSP_TEST_spark_jars="${ALL_JARS}"
```
Comment (gerashegalov) [inline integration_tests/run_pyspark_from_build.sh:202]: here we can have something to the tune of
```bash
    if [[ "${PYSP_TEST_spark_shuffle_manager}" =~ "RapidsShuffleManager" ]]; then
        export PYSP_TEST_spark_driver_extraClassPath="${ALL_JARS// /:}"
        export PYSP_TEST_spark_executor_extraClassPath="${ALL_JARS// /:}"
    else
        export PYSP_TEST_spark_jars="${ALL_JARS}"
    fi
```

**Review by gerashegalov — CHANGES_REQUESTED** [review]

**Comment by pxLi** [comment]
> > build
> 
> @res-life blossom-ci is disabled on draft PR's

> @pxLi maybe we could move the check to yml because there seems to be Boolean "draft" field on pull_request object https://stackoverflow.com/questions/68349031/only-run-actions-on-non-draft-pull-request

blossom-ci should work on draft PR. This one was actually timeout due to above issues

**Comment by gerashegalov** [comment]
> blossom-ci should work on draft PR. This one was actually timeout due to above issues

Thanks @pxLi , good to know

**Comment by res-life** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM
