### PR TITLE
[SparkUT]Add try-catch on dataframe.collect in UT framework

### LINKED ISSUE #13760: [AutoSparkUT]DATE_FROM_UNIX_DATE test case in RapidsDateExpressionsSuite threw java.lang.ArithmeticException: integer overflow
**Describe the bug**
The DATE_FROM_UNIX_DATE in RapidsDateExpressionsSuite threw below exception when running on GPU.
It seems a bug in our UT framework when trying to collect the result from one of the cases.
Need to fix it later. For now, exclude the test case.
It's not a plugin bug because CPU also threw the same exception. 
Our UT framework might change a way to checkResult.

And the TIMESTAMP_MICROS also failed by similar exception.
`java.lang.ArithmeticException: long overflow`

```
- DATE_FROM_UNIX_DATE *** FAILED ***
  java.lang.RuntimeException: Error while decoding: java.lang.ArithmeticException: integer overflow
createexternalrow(staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, ObjectType(class java.sql.Date), toJavaDate, input[0, date, false], true, false, true), StructField(date_from_unix_date(-2147483648),DateType,false))
  at org.apache.spark.sql.errors.QueryExecutionErrors$.expressionDecodingError(QueryExecutionErrors.scala:1214)
  at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:184)
  at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:172)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
  at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
  ...
  Cause: java.lang.ArithmeticException: integer overflow
  at java.lang.Math.toIntExact(Math.java:1011)
  at org.apache.spark.sql.catalyst.util.RebaseDateTime$.localRebaseGregorianToJulianDays(RebaseDateTime.scala:199)
  at org.apache.spark.sql.catalyst.util.RebaseDateTime$.rebaseGregorianToJulianDays(RebaseDateTime.scala:212)
  at org.apache.spark.sql.catalyst.util.DateTimeUtils$.toJavaDate(DateTimeUtils.scala:136)
  at org.apache.spark.sql.catalyst.util.DateTimeUtils.toJavaDate(DateTimeUtils.scala)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
  at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:181)
  at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:172)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
  ...
```

**Steps/Code to reproduce bug**
Comment out the line of .exclude("DATE_FROM_UNIX_DATE", ... in RapidsTestSettings.scala.
mvn -nsu -Dbuildver=330 -pl tests -Dsuites="org.apache.spark.sql.rapids.suites.RapidsDateExpressionsSuite" test

**Expected behavior**
Even we don't support date_from_unix_date, the test case should pass.

**Environment details (please complete the following information)**
Spark Version: 3.3.0
RAPIDS Plugin Version: 25.12.0-SNAPSHOT
Local mode

### PR DESCRIPTION
**Pull request by GaryShen2008**
Some cases the dataframe failed to collect like the case in #13760 
Cast the column to string and compare with the expectation as String type when collect() call throws exception.

Close #13760

### CODE REVIEW

File: tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala [hunk 1]
```diff
@@ -317,7 +318,13 @@ trait RapidsTestsTrait extends RapidsTestsCommonTrait {
           Literal(inputRow.asInstanceOf[GenericInternalRow].get(ordinal, dataType), dataType)
       }
       resultDF = _spark.range(0, 1).select(Column(expression))
-      result = resultDF.collect()
+      try {
+        result = resultDF.collect()
+      } catch {
+        case _ : Exception =>
```
[the remark this answers is not in the document]
Comment (GaryShen2008) [reply tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala]: Already changed.

**Comment by GaryShen2008** [comment]
build

File: tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala [hunk 2]
```diff
@@ -317,7 +318,14 @@ trait RapidsTestsTrait extends RapidsTestsCommonTrait {
...
       }
       resultDF = _spark.range(0, 1).select(Column(expression))
-      result = resultDF.collect()
+      try {
+        result = resultDF.collect()
+      } catch {
+        case e : Exception =>
+          logWarning(s"Exception during resultDF.collect() for $expression: ${e.getMessage}", e)
+          isComparedByString = true
+          result = resultDF.select(Column(resultDF.columns(0)).cast("string")).collect()
```
Comment (wjxiz1992) [inline tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala:327]: Only one concern: any posibility that this string-cast hide some errors?

I consult with Cursor, and it gives the following case, I'm not quite sure if it's possible:


When GPU incorrectly returns a Decimal with wrong precision/scale: (the collect firstly throws exception and then)

```scala
// Expected: Decimal(123.450, precision=10, scale=3)
// GPU Bug: Returns Decimal(123.45, precision=5, scale=2)
```

### Problem with String Comparison

```scala
expected.toString        // "123.45"
actual.cast("string")    // "123.45"
// Both match! ✓ Test passes but there's a bug
```

The test **passes** even though:
- Precision: 10 vs 5 (wrong!)
- Scale: 3 vs 2 (wrong!)
- Value appears same as string: "123.45"

Comment (wjxiz1992) [reply tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala:327]: let me share the cursor conversion in a markdown file to you offline.

Comment (GaryShen2008) [reply tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala:327]: Not sure if the case will happen. It might be possible.
My change is another trying after the dataframe failed to run collect(). Without the change, the case will throw exception.

Any solution suggested by Cursor?

Comment (GaryShen2008) [reply tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala:327]: To be clear, most of the cases shouldn't enter the new added code of casting to String to compare. It's only when the dataframe.collect() throws exception, then I do a further trying to check if the text of the result looks as same as expectation value.
I can't 100% guarantee there's no cases entering the new code. But I think it should be rare.

The root cause of the issue is that in our UT framework, we use spark dataframe/sql to execute the expression on GPU then compare to the expected value. But some expression's result can't be ran on the collect(). The original Spark UT is just to run Expression.eval() to calculate the result so it won't meet the issue that collect() doesn't work.

Comment (wjxiz1992) [reply tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala:327]: I see, then it should be ok.
