### PR TITLE
Fix two-shim smoke test for DB-17.3 [databricks]

### LINKED ISSUE #14472: [BUG] Smoke test fails on Databricks-17.3
**Describe the bug**

The smoke test fails on Databricks 17.3 with this CLI, as shown below.
```
SPARK_HOME=$HOME/spark-3.3.0-bin-hadoop3 \
        SPARK_SHELL_SMOKE_TEST=1 \
        PYSP_TEST_spark_shuffle_manager=com.nvidia.spark.rapids.spark330.RapidsShuffleManager \
            bash integration_tests/run_pyspark_from_build.sh
```

Error Log

```
 Running spark-shell smoke test...
 + SPARK_SHELL_ARGS_ARR=(--master local-cluster[1,2,1024] --conf spark.plugins=com.nvidia.spark.SQLPlugin --conf spark.deploy.maxExecutorRetries=0)
 + [[ com.nvidia.spark.rapids.spark330.RapidsShuffleManager != '' ]]
 + SPARK_SHELL_ARGS_ARR+=(--conf spark.shuffle.manager="${PYSP_TEST_spark_shuffle_manager}" --driver-class-path "${PYSP_TEST_spark_driver_extraClassPath}" --conf spark.executor.extraClassPath="${PYSP_TEST_spark_driver_extraClassPath}")
```

### PR DESCRIPTION
**Pull request by nartal1**
Contributes to https://github.com/NVIDIA/spark-rapids/issues/14015 and fixes https://github.com/NVIDIA/spark-rapids/issues/14472

### Description

For DB-17.3 (Spark 4.0.0 / Scala 2.13), the two-shim dist jar contains
`spark350` + `spark400db173` shims, but the smoke test hardcoded Spark 3.3.0
and `spark330`, causing the test to fail.

In this PR we derive the upstream Spark version, shim, and Scala suffix dynamically
from `BASE_SPARK_VERSION`:
So smoke test is run based on BASE_SPARK_VERSION.
- Spark 4.x → `spark-3.5.0-bin-hadoop3-scala2.13.tgz`, shim `spark350`
- Spark 3.x → `spark-3.3.0-bin-hadoop3.tgz`, shim `spark330`

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [ ] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by nartal1** [comment]
build

File: jenkins/databricks/test.sh
Comment (NvTimLiu) [inline jenkins/databricks/test.sh]: Please help update Copyright to 2026, thanks!

**Review by NvTimLiu — DISMISSED** [review]

File: jenkins/databricks/test.sh [hunk 1]
```diff
@@ -63,6 +63,21 @@ source jenkins/databricks/setup.sh
 source jenkins/databricks/common_vars.sh
 
 BASE_SPARK_VERSION=${BASE_SPARK_VERSION:-$(< /databricks/spark/VERSION)}
+
+# For Spark 4.x (Scala 2.13), the upstream base shim is 350 (Spark 3.5.0).
+# For Spark 3.x (Scala 2.12), the upstream base shim is 330 (Spark 3.3.0).
+if [[ "$BASE_SPARK_VERSION" == 4.* ]]; then
+    # TODO: Revisit UPSTREAM_SHIM_VER when new Spark 4.x Databricks runtimes are introduced
+    # that may pair with a different upstream shim (e.g., spark360).
+    UPSTREAM_SPARK_VERSION="3.5.0"
```
Comment (gerashegalov) [inline jenkins/databricks/test.sh:72]: Ideally the version of Scala is read using Python like in other places. And base version would come from help:evaluate.

**Review by gerashegalov — DISMISSED** [review]

**Comment by nartal1** [comment]
build

**Review by NvTimLiu — DISMISSED** [review]
LGTM, +1

Blocked by: https://github.com/NVIDIA/spark-rapids/issues/14474

**Comment by nartal1** [comment]
build

**Comment by nvauto** [comment]
**NOTE: release/26.04 has been created from main. Please retarget your PR to release/26.04 if it should be included in the release.**

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
re-target to the branch release/26.04

**Comment by NvTimLiu** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
