### PR TITLE
Replace Scala document with Scala comment for inner functions

### LINKED ISSUE #4341: [BUG] GpuCast.scala:nnn warning: discarding unmoored doc comment
**Describe the bug**
```
[INFO] --- scala-maven-plugin:4.3.0:doc-jar (attach-scaladocs) @ rapids-4-spark-sql_2.12 ---
/home/gshegalov/gits/NVIDIA/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:679: warning: discarding unmoored doc comment
      /**
      ^
/home/gshegalov/gits/NVIDIA/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:705: warning: discarding unmoored doc comment
      /**
      ^
/home/gshegalov/gits/NVIDIA/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:720: warning: discarding unmoored doc comment
      /**
      ^
model contains 1086 documentable templates
```

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>
close #4341 

When doing `mvn verify`, a warning "discarding unmoored doc comment" is thrown.
What causes the warning is that adding Scala document to an inner function is useless.
We fix this bug by replacing Scala document with Scala comment.

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 1]
```diff
@@ -676,7 +676,7 @@ object GpuCast extends Arm {
 
       /* -------------------------------- helper functions -----------------------*/
 
-      /**
+      /*
        * cast all not-null elements in a child column to string type <p>
        * add `' '` to all elements when `legacyCastToString = true`
        * @param child child column of an array column
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:682]: Nit: Odd to be using Scaladoc directives in a comment that is not marked for Scaladoc.  Someone may come along later and assume it was intended to be a Scaladoc comment and "fix" it to be so.

This comment applies to the other instances.

**Review by jlowe — APPROVED** [review]
Minor nit that is not mustfix, otherwise lgtm.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 1 above)
Comment (HaoYang670) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:682]: Thank you for your advice, I will fix it

**Comment by HaoYang670** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 2]
```diff
@@ -657,7 +657,7 @@ object GpuCast extends Arm {
    *
    * when `legacyCastToString = false`, step 2, 5 are skipped
    */
-  private  def castArrayToString(input:                    ColumnView,
+  private def castArrayToString(input:                    ColumnView,
                                  elementType:                DataType,
                                  ansiMode:                    Boolean,
                                  legacyCastToString:          Boolean,
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:663]: These lines are now mis-indented due to the whitespace fix above.

**Comment by HaoYang670** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 2 above)
Comment (HaoYang670) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: Thank you. Has been fixed.

**Review by jlowe — APPROVED** [review]
