### PR TITLE
Fix fastparquet installation for [databricks]

### LINKED ISSUE #9553: [BUG] `fastparquet` pip install fails on Databricks
**Description**
The pip install of `fastparquet` for CI integration tests seems to [fail on Databricks](https://prod.blsm.nvidia.com/sw-gpu-spark-jenkins/job/rapids-it-aws-databricks-12.2/17/):
```
[2023-10-26T18:53:49.357Z] + PYTHON_SITE_PACKAGES=/home/ubuntu/.local/lib/python3.8/site-packages
[2023-10-26T18:53:49.357Z] + /usr/bin/python -m pip install --target /home/ubuntu/.local/lib/python3.8/site-packages pytest sre_yield requests pandas pyarrow findspark pytest-xdist pytest-order fastparquet
...
[2023-10-26T18:54:05.489Z] ERROR: Could not build wheels for fastparquet, which is required to install pyproject.toml-based projects
```
This causes the Databricks CI runs to fail.

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #9553.

This commit fixes the installation of `fastparquet` on Databricks. The [`fastparquet` documentation](https://fastparquet.readthedocs.io/en/latest/install.html) mentions that `numpy` needs to be installed as a dependency of `fastparquet`, because pip sometimes fails to solve the environment.

### CODE REVIEW

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
Build

File: jenkins/databricks/setup.sh [hunk 1]
```diff
@@ -49,4 +49,8 @@ PYTHON_VERSION=$(${PYSPARK_PYTHON} -c 'import sys; print("python{}.{}".format(sy
 # Set the path of python site-packages, and install packages here.
 PYTHON_SITE_PACKAGES="$HOME/.local/lib/${PYTHON_VERSION}/site-packages"
 # Use "python -m pip install" to make sure pip matches with python.
-$PYSPARK_PYTHON -m pip install --target $PYTHON_SITE_PACKAGES pytest sre_yield requests pandas pyarrow findspark pytest-xdist pytest-order fastparquet
+$PYSPARK_PYTHON -m pip install --target $PYTHON_SITE_PACKAGES pytest sre_yield requests pandas pyarrow findspark pytest-xdist pytest-order
+
+# Install fastparquet (and numpy as its dependency).
+$PYSPARK_PYTHON -m pip install --target $PYTHON_SITE_PACKAGES numpy
+$PYSPARK_PYTHON -m pip install --target $PYTHON_SITE_PACKAGES fastparquet
```
Comment (winningsix) [inline jenkins/databricks/setup.sh:56]: nit: can we merge ```numpy``` and ```fastparquet``` into a single command? e.g., ```$PYSPARK_PYTHON -m pip install --target $PYTHON_SITE_PACKAGES numpy fastparquet```

Comment (mythrocks) [reply jenkins/databricks/setup.sh:56]: I can try that after this run. But the `fastparquet` documentation specifically states that `numpy` needs to be installed *before* `fastparquet`, or there might be a failure in solving the wheel. :shrug:

**Comment by pxLi** [comment]
build

**Review by tgravescs — APPROVED** [review]
