### PR TITLE
Remove unused generic types

### LINKED ISSUE #5264: [BUG] Delete unused generic type.
**Describe the bug**
```scala
  implicit class ReallyAGpuExpression[A <: Expression](exp: Expression) {
    def columnarEval(batch: ColumnarBatch): Any = {
      exp.asInstanceOf[GpuExpression].columnarEval(batch)
    }
  }

  implicit class AutoCloseableColumn[A <: AutoCloseable](autoCloseable: AutoCloseable) {

    /**
     * safeClose: Is an implicit on AutoCloseable class that tries to close the resource, if an
     * Exception was thrown prior to this close, it adds the new exception to the suppressed
     * exceptions, otherwise just throws
     *
     * @param e Exception which we don't want to suppress
     */
    def safeClose(e: Throwable = null): Unit = {
      if (autoCloseable != null) {
        if (e != null) {
          try {
            autoCloseable.close()
          } catch {
            case suppressed: Throwable => e.addSuppressed(suppressed)
          }
        } else {
          autoCloseable.close()
        }
      }
    }
  }
  ```
The generic type `A` is not used in the class body. We should remove them.

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>
Close #5264 

Just to remove some unused type annotations in the implicit classes.

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

**Review by jlowe — APPROVED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala [hunk 1]
```diff
@@ -29,13 +29,13 @@ import org.apache.spark.sql.vectorized.ColumnarBatch
  */
 object RapidsPluginImplicits {
 
-  implicit class ReallyAGpuExpression[A <: Expression](exp: Expression) {
+  implicit class ReallyAGpuExpression(exp: Expression) {
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala:32]: I think this was meant to be future-proof 
```
implicit class ReallyAGpuExpression[E <: Expression](exp: E) {
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala [hunk 2]
```diff
@@ -29,13 +29,13 @@ import org.apache.spark.sql.vectorized.ColumnarBatch
...
     def columnarEval(batch: ColumnarBatch): Any = {
       exp.asInstanceOf[GpuExpression].columnarEval(batch)
     }
   }
 
-  implicit class AutoCloseableColumn[A <: AutoCloseable](autoCloseable: AutoCloseable) {
+  implicit class AutoCloseableColumn(autoCloseable: AutoCloseable) {
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala:38]: similarly
```
implicit class AutoCloseableColumn[A <: AutoCloseable](autoCloseable: A) {
```
