### PR TITLE
Fix OOM when shuffle partition exceeds 2GB in threaded writer

### LINKED ISSUE #14174: OOM when a single shuffle partition exceeds 2GB in RapidsShuffleThreadedWriter
### Problem

When using Rapids Shuffle Manager with the threaded writer, an `OutOfMemoryError` occurs if a single shuffle partition's compressed data exceeds ~2GB:

```
java.lang.OutOfMemoryError: Required array length 2147483639 + 23463 is too large
    at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
    at net.jpountz.lz4.LZ4BlockOutputStream.flushBufferedData(LZ4BlockOutputStream.java:225)
```

### Root Cause

The current implementation uses a single `OpenByteArrayOutputStream` per partition to buffer all compressed records before writing to disk. When partition data is highly skewed, a single partition can accumulate more than 2GB of compressed data, hitting the Java array size limit (~2^31 bytes).

### Proposed Fix

Instead of accumulating all records into one buffer per partition, each compressed record should get its own `OpenByteArrayOutputStream`. The merger thread processes and releases these buffers individually, preventing large accumulations.

### Reproduction

This occurs with queries that produce skewed shuffle partitions (e.g., aggregations with few distinct keys and many rows) where the data for one partition exceeds 2GB after compression.

### PR DESCRIPTION
**Pull request by binmahone**
## Description

Fixes #14174

When using Rapids Shuffle Manager with the threaded writer, an `OutOfMemoryError` occurs if a single shuffle partition's compressed data exceeds ~2GB due to Java's array size limit.

### Root Cause

The previous implementation used a single `OpenByteArrayOutputStream` per partition to buffer all compressed records before writing to disk. When partition data is highly skewed, a single partition can accumulate more than 2GB of compressed data, hitting the Java array size limit (~2^31 bytes).

### Solution

Instead of accumulating all records into one buffer per partition, each compressed record now gets its own `OpenByteArrayOutputStream`. The merger thread processes and releases these buffers individually, preventing large accumulations.

Key changes:
- Introduced `CompressedRecord` case class to encapsulate individual record buffers
- Changed `partitionBuffers` (single buffer per partition) to `partitionRecords` (queue of record futures per partition)
- Merger thread now polls individual records from the queue and releases buffers immediately after writing

## Checklist
- [x] Signed-off-by
- [x] Unit tests pass

### CODE REVIEW

**Comment by binmahone** [comment]
Thanks for the reviews! Here's my response to each comment:

**Comment 1 (race condition in isLastForPartition check):**

The current logic is actually correct because the main thread adds records and updates `maxPartitionIdQueued` atomically in the same synchronized block (lines 716-725). If `maxPartitionIdQueued > currentPartitionToWrite`, it means the main thread has already moved on to process later partitions, so all records for the current partition are guaranteed to be in the queue.

However, I agree the suggestion makes the code clearer by checking partition completion only after the queue is confirmed empty. I'll consider this optimization in a follow-up if needed.

**Comment 2 (potential buffer leak on cancelled futures):**

Good catch on the analysis. However, the buffer (`OpenByteArrayOutputStream`) is created inside the task execution (line 700). If the task is cancelled before it starts, no buffer is allocated. If cancelled during execution, the window where a buffer exists but the future can't be retrieved is extremely small.

Adding a warning log could help debugging, but since this is a rare edge case during error cleanup, I'll leave it as-is for now.

**Comment 3 (currentBatch cleanup if not in batchStates):**

This is a valid bug! Fixed in the latest commit - now the finally block also cleans up `currentBatch` if it was never added to `batchStates`.

**Comment by binmahone** [comment]
build

**Comment by binmahone** [comment]
@abellina can you please take a look? the code logic becomes simpler after the bug fix

**Review by amahussein — COMMENTED** [review]
Thanks @binmahone for fixing the 2GB partition limit!

I have a question about the tradeoff in the implementation strategy. Moving from a single accumulated buffer per partition to allocating a separate `OpenByteArrayOutputStream` (and `CompressedRecord` wrapper) for every single record seems like it could introduce significant object allocation overhead.

- Object Overhead/GC: Is there a concern about increased GC pressure or memory fragmentation due to creating and discarding so many short-lived buffer objects, especially if the "records" being written are small and numerous?

- Performance: Was there any performance comparison/benchmarking done between the legacy single-buffer approach and this per-record approach to ensure the overhead is negligible for standard use cases that don't hit the 2GB limit?

**Comment by binmahone** [comment]
> Thanks @binmahone for fixing the 2GB partition limit!
> 
> I have a question about the tradeoff in the implementation strategy. Moving from a single accumulated buffer per partition to allocating a separate `OpenByteArrayOutputStream` (and `CompressedRecord` wrapper) for every single record seems like it could introduce significant object allocation overhead.
> 
> * Object Overhead/GC: Is there a concern about increased GC pressure or memory fragmentation due to creating and discarding so many short-lived buffer objects, especially if the "records" being written are small and numerous?
> * Performance: Was there any performance comparison/benchmarking done between the legacy single-buffer approach and this per-record approach to ensure the overhead is negligible for standard use cases that don't hit the 2GB limit?

Hi @amahussein ,  the record here is not row-wise, it's many rows. Typically for each partition we only have one record.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala [hunk 1]
```diff
@@ -425,121 +424,83 @@ abstract class RapidsShuffleThreadedWriterBase[K, V](
...
-            partitionWrittenBytes.remove(partitionId)
-          }
-        case None =>
-          throw new IllegalStateException(
-            s"No buffer found for partition $partitionId in batch $batchId")
-      }
-    }
-
     // Merger task for this batch
+    // Simplified design: each record has its own buffer, so we just:
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala]: nit: why add comments about what we change, instead of what it does. "simplified design" here is not needed

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala [hunk 2]
```diff
@@ -425,121 +424,83 @@ abstract class RapidsShuffleThreadedWriterBase[K, V](
...
+    // 1. Poll records from the queue
+    // 2. Write buffer content to output stream
+    // 3. Close buffer immediately (no accumulation!)
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala]: What happens if we have lots of batches that end up with small numbers of serialized buffers?  Do we end up with a lot of overhead for this?

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala [hunk 3]
```diff
@@ -425,121 +424,83 @@ abstract class RapidsShuffleThreadedWriterBase[K, V](
...
-
-                // Release the remaining quota after data is written to output stream.
-                // The limiter controls heap memory pressure from deserialization and
-                // OpenByteArrayOutputStream. Once data is written to output stream (which may
-                // buffer in SpillablePartialFileHandle or write to disk), the heap buffer
-                // becomes eligible for GC. Releasing quota here allows more compression
-                // tasks to proceed without causing heap OOM.
-                limiter.release(remainingQuota)
-              }
+                    // Close buffer immediately - this is the key to avoiding 2GB limit!
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala]: Again the comment here is like an AI is telling you what it did to avoid a problem. Not explaining what the code actually does.

**Comment by revans2** [comment]
I just ran this locally and got a hang on shutdown.

```
  // 268435456L rows * ~160 bytes (with payload) = ~40GB raw, but join reduces this
  val numRows = 268435456L
  
  // df1: simple side with just the join key
  val df1 = spark.range(0, numRows * 5, 1, 32).selectExpr("id + 1 as id_a")
  
  // df2: side with payload columns to make shuffle more realistic
  val df2 = spark.range(0, numRows * 5, 1, 32)
  .selectExpr(
      "id - 1 as id_b",
      "(id * 7) as payload_long1",           // Long column
      "(id * 13) as payload_long2",          // Long column
      "(id * 17) as payload_long3",          // Long column
      "cast((id % 1000000) as int) as payload_int1",  // Int column
      "cast((id % 100000) as int) as payload_int2",  // Int column
      "(id * 3.14159) as payload_double1",   // Double column
      "(id * 2.71828) as payload_double2",   // Double column
      "cast((id % 2) as boolean) as payload_bool1",  // Boolean column
      "concat('str_', cast((id % 10000) as string)) as payload_string1"  // String column
    )
  
  // Join and use all payload columns in aggregation to ensure they go through shuffle
  spark.time(
    df1.join(df2, col("id_a") === col("id_b"))
      .selectExpr(
        "COUNT(id_a) as cnt",
        "COUNT(payload_long1) as cnt_l1",
        "COUNT(payload_long2) as cnt_l2",
        "COUNT(payload_long3) as cnt_l3",
        "COUNT(payload_int1) as cnt_i1",
        "COUNT(payload_int2) as cnt_i2",
        "COUNT(payload_double1) as cnt_d1",
        "COUNT(payload_double2) as cnt_d2",
        "COUNT(payload_bool1) as cnt_b1",
        "COUNT(payload_string1) as cnt_str"
      )
      .show()
```

I did it 5 times with kudo set to run on the CPU for both reads and writes. This was on Spark 3.5.3 with 10 shuffle partitions. 
```
        --conf spark.rapids.sql.enabled=true \
        --conf spark.shuffle.manager=com.nvidia.spark.rapids.spark353.RapidsShuffleManager \
        --conf spark.rapids.shuffle.kudo.serializer.enabled=true \
        --conf spark.rapids.shuffle.kudo.serializer.write.mode=CPU \
        --conf spark.rapids.shuffle.kudo.serializer.read.mode=CPU
```
Note that this was in local mode, so it would have been killed in a production environment eventually after the heartbeats stopped, but that is not the point.

```
26/01/24 12:33:29 WARN ShutdownHookManager: ShutdownHook '' timeout, java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.util.ShutdownHookManager.executeShutdown(ShutdownHookManager.java:124)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:95)
26/01/24 12:33:59 WARN ShutdownHookManager: ShutdownHook 'ClientFinalizer' timeout, java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.util.ShutdownHookManager.executeShutdown(ShutdownHookManager.java:124)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:95)
26/01/24 12:34:29 ERROR ShutdownHookManager: ShutdownHookManager shutdown forcefully after 30 seconds.
26/01/24 12:35:07 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 129483 ms exceeds timeout 120000 ms
26/01/24 12:35:07 WARN SparkContext: Killing executors is not supported by current scheduler.
26/01/24 12:38:07 WARN ShuffleCleanupManager: Removing stale shuffle cleanup entry for shuffle 12 with NO executor cleanup reported (registered 308235ms ago). Shuffle resources may not have been cleaned up properly.
26/01/24 12:38:07 WARN ShuffleCleanupManager: Removing stale shuffle cleanup entry for shuffle 13 with NO executor cleanup reported (registered 308235ms ago). Shuffle resources may not have been cleaned up properly.
26/01/24 12:38:07 WARN ShuffleCleanupManager: Removing stale shuffle cleanup entry for shuffle 14 with NO executor cleanup reported (registered 308235ms ago). Shuffle resources may not have been cleaned up properly.
```

**Comment by revans2** [comment]
I did a bit more debugging and it looks like there is an AB-BA deadlock that can happen between SpillableHostStore and SpillablePartialFileHandle.  I think the right fix is to always ensure that we always grab the locks in the same order everywhere and document that.  From what I have seen Handle first then store is the simplest to do.  That said it looks like we are triggering the problem by having two shutdown hooks. The plugin shutdown will try and shut everything down, but we also have a JVM shutdown hook to also try and shut it all down. I am fine with both if we really want to be sure that it is shut down, but we should guard against two of them running at the same time.

**Comment by nvauto** [comment]
**NOTE: release/26.02 has been created from main. Please retarget your PR to release/26.02 if it should be included in the release.**

**Comment by binmahone** [comment]
> I did a bit more debugging and it looks like there is an AB-BA deadlock that can happen between SpillableHostStore and SpillablePartialFileHandle. I think the right fix is to always ensure that we always grab the locks in the same order everywhere and document that. From what I have seen Handle first then store is the simplest to do. That said it looks like we are triggering the problem by having two shutdown hooks. The plugin shutdown will try and shut everything down, but we also have a JVM shutdown hook to also try and shut it all down. I am fine with both if we really want to be sure that it is shut down, but we should guard against two of them running at the same time.

Hi @revans2 I tried your script on spark 332 and 356, but cannot reproduce. Based on your description I created another PR https://github.com/NVIDIA/spark-rapids/pull/14202, can you verify if that fixes your problem?

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala (hunk 2 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala]: The overhead of creating one buffer per record (vs. one buffer per partition) is minimal:
- The overhead is small - mainly OpenByteArrayOutputStream object allocation
- Buffers are closed immediately after the merger writes them to disk, so they don't accumulate in memory
- This trade-off is worthwhile compared to the OOM caused by hitting the 2GB array limit

And I ran NDS test on before/after change, there's no significant difference

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala (hunk 1 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala]: resolved

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala (hunk 3 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala]: resolved

**Comment by binmahone** [comment]
> Architecturally this is a large change. The issue and this PR show no performance testing and there is no repro case for the problem either. I really want to understand what is happening before we approve something like this. I am especially concerned about the performance impact for cases that are not running into this problem. Was this problem introduced by the recent shuffle manager changes? I thought we had code to at least mitigate issues with a single row being to large, but I have seen nothing about all of the data together being too large. We had run with things like that before all the time.
> 
> I don't see any large problems with the code, but I do want to understand what is happening here and the impact of the changes.

@revans2  I ran NDS test on before/after change, there's no significant difference

**Comment by binmahone** [comment]
build
