### PR TITLE
Ensure an executor broadcast is in a single batch [databricks]

### LINKED ISSUE #10645: [BUG] java.lang.IllegalStateException: Expected to only receive a single batch
Databricks Spark Cluster

Spark Rapids Configuration:
spark.task.resource.gpu.amount 0.02
spark.rapids.shuffle.multiThreaded.reader.threads 48
spark.executorEnv.PYTHONPATH /databricks/jars/rapids-4-spark_2.12-24.02.0.jar:/databricks/spark/python
spark.shuffle.manager com.nvidia.spark.rapids.spark330db.RapidsShuffleManager
spark.rapids.memory.host.spillStorageSize 16GB
spark.plugins com.nvidia.spark.SQLPlugin
spark.executor.resource.gpu.amount 1
spark.rapids.sql.explain ALL
spark.rapids.filecache.enabled TRUE
spark.rapids.sql.python.gpu.enabled true
spark.rapids.memory.pinnedPool.size 8G
spark.rapids.shuffle.multiThreaded.writer.threads 48
spark.python.daemon.module rapids.daemon_databricks
spark.sql.files.maxPartitionBytes 2GB
spark.rapids.sql.multiThreadedRead.numThreads 100
spark.rapids.sql.concurrentGpuTasks 3

Full Stacktrace:
java.lang.IllegalStateException: Expected to only receive a single batch
	at com.nvidia.spark.rapids.ConcatAndConsumeAll$.getSingleBatchWithVerification(GpuCoalesceBatches.scala:103)
	at org.apache.spark.sql.rapids.execution.GpuExecutorBroadcastHelper$.getExecutorBroadcastBatch(GpuExecutorBroadcastHelper.scala:100)
	at org.apache.spark.sql.rapids.execution.GpuBroadcastHashJoinExec.$anonfun$getExecutorBuiltBatchAndStreamIter$1(GpuBroadcastHashJoinExec.scala:151)
	at com.nvidia.spark.rapids.Arm$.closeOnExcept(Arm.scala:98)
	at org.apache.spark.sql.rapids.execution.GpuBroadcastHashJoinExec.getExecutorBuiltBatchAndStreamIter(GpuBroadcastHashJoinExec.scala:142)
	at org.apache.spark.sql.rapids.execution.GpuBroadcastHashJoinExec.$anonfun$doColumnarExecutorBroadcastJoin$1(GpuBroadcastHashJoinExec.scala:181)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:410)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:410)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:410)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:410)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:410)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:410)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:410)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$3(ShuffleMapTask.scala:81)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$1(ShuffleMapTask.scala:81)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:174)
	at org.apache.spark.scheduler.Task.$anonfun$run$4(Task.scala:137)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:41)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:100)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:105)
	at scala.util.Using$.resource(Using.scala:269)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:104)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:137)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:96)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:902)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1697)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:905)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:760)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #10645.

This wraps the GpuShuffleCoalesceIterator into a GpuCoalesceIterator with a coalesce goal of RequireSingleBatch. This ensures that we always get a single batch to use for the broadcast join. Also added an integration test that tweaks the batch size to test this codepath.

### CODE REVIEW

**Comment by NVnavkumar** [comment]
build

File: sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala [hunk 1]
```diff
@@ -65,11 +66,23 @@ object GpuExecutorBroadcastHelper {
...
+        dataTypes, metricsMap).asInstanceOf[Iterator[ColumnarBatch]],
+      dataTypes,
+      RequireSingleBatch,
+      metricsMap(NUM_INPUT_ROWS), // numInputRows
+      metricsMap(NUM_INPUT_BATCHES), // numInputBatches
+      metricsMap(NUM_OUTPUT_ROWS), // numOutputRows
+      metricsMap(NUM_OUTPUT_BATCHES), // numOutputBatches
+      metricsMap(COLLECT_TIME), // collectTime
+      metricsMap(CONCAT_TIME), // concatTime
+      metricsMap(OP_TIME), // opTime
```
Comment (jlowe) [inline sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala:84]: I think this is going to end up over counting many of these metrics, as we pass the metrics map to the HostShuffleCoalesceIterator as well as GpuShuffleCoalesceIterator.  If all of these things end up incrementing input rows, output rows, etc, then we're going to get numbers way off from what one would expect to be reported for a broadcast join.  I'm wondering if we were already over counting metrics from before since we're passing the metrics map to GpuShuffleCoalesceIterator and HostShuffleCoalesceIterator.  I suspect we only want to pass a map containing OP_TIME and CONCAT_TIME to these iterators and nothing else.  For GpuCoalesceIterator which takes individual metrics, we can pass NoopMetric for the ones we don't want to count.

File: sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala [hunk 2]
```diff
@@ -92,7 +92,8 @@ case class GpuBroadcastHashJoinExec(
     JOIN_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_JOIN_TIME),
     NUM_INPUT_ROWS -> createMetric(DEBUG_LEVEL, DESCRIPTION_NUM_INPUT_ROWS),
     NUM_INPUT_BATCHES -> createMetric(DEBUG_LEVEL, DESCRIPTION_NUM_INPUT_BATCHES),
-    CONCAT_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_CONCAT_TIME)
+    CONCAT_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_CONCAT_TIME),
+    COLLECT_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_COLLECT_TIME)
```
Comment (jlowe) [inline sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala:96]: I'm not sure we want to add this metric, as it usually isn't very useful in practice.

**Comment by NVnavkumar** [comment]
build

File: sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala [hunk 3]
```diff
@@ -65,11 +66,31 @@ object GpuExecutorBroadcastHelper {
...
+    // grab and release the semaphore while doing I/O. We wrap this with GpuCoalesceIterator
+    // to ensure this always a single batch for the following step.
+    val timeMetrics = Set(CONCAT_TIME, OP_TIME)
+    val shuffleMetrics = metricsMap.map { case (k, v) =>
+      if (timeMetrics.contains(k)) {
+        (k, v)
+      } else {
+        (k, NoopMetric)
+      }
+    }
```
Comment (jlowe) [inline sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala:78]: Nit: We're iterating the larger map rather than the smaller one, and we don't need to iterate at all.
```suggestion
    val shuffleMetrics = Map(
      CONCAT_TIME -> metricsMap(CONCAT_TIME),
      OP_TIME -> metricsMap(OP_TIME))
```

Comment (NVnavkumar) [reply sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala:78]: So we do it this way because GpuShuffleCoalesceIterator and HostShuffleCoalesceIterator expect many of those metrics to be in the metricsMap, so we're just replacing these effectively with a default value. I think I can do a cleaner version using withDefaultValue.

**Comment by NVnavkumar** [comment]
build

File: integration_tests/src/main/python/aqe_test.py [hunk 4]
```diff
@@ -298,3 +298,40 @@ def do_it(spark):
...
+        df_school = gen_df(spark, StructGen([('id', id_gen), ('school', school_gen)], nullable=False), length=250)
+        df.createOrReplaceTempView("df_school")
+
+    with_cpu_session(prep)
+
+    def do_it(spark):
+        res = spark.sql(
+            """
+                select /*+ BROADCAST(df_school) */ * from df, df_school where df.id == df_school.id
+            """
```
Comment (gerashegalov) [inline integration_tests/src/main/python/aqe_test.py:327]: nit: PySpark API looks nicer and would not require resorting to view registration along the lines

```Python
df.join(broadcast(df_school), df.id == df_school.id) 
```

File: jenkins/databricks/test.sh
Comment (gerashegalov) [inline jenkins/databricks/test.sh:1]: Please revert debugging changes. I am aware that Databricks test.sh does not really respect TEST environment to run a single test, we might want a bug for this.

File: integration_tests/src/main/python/aqe_test.py (hunk 4 above)
Comment (NVnavkumar) [reply integration_tests/src/main/python/aqe_test.py:327]: Understood, but this test requires a join hint to ensure a broadcast hash join is used in this test.

File: jenkins/databricks/test.sh
Comment (NVnavkumar) [reply jenkins/databricks/test.sh:1]: Good catch, I had thought I had reverted these changes before committing, but the git cli did something misleading

**Comment by NVnavkumar** [comment]
build

File: integration_tests/src/main/python/aqe_test.py (hunk 4 above)
Comment (gerashegalov) [reply integration_tests/src/main/python/aqe_test.py:327]: I think my suggestion does that: https://github.com/apache/spark/blob/de2079163270d371e0ead33f09d61d66ee496e88/python/pyspark/sql/connect/functions/builtin.py#L317-L325

File: sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala (hunk 3 above)
Comment (jlowe) [reply sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala]: Ah, good catch, I meant to put `withDefaultValue` in my example.
