### PR TITLE
Fix the unstable unit test case: ResourceBoundedExecutorSuite

### LINKED ISSUE #13788: [BUG] Scala test 'AsyncCpuTask task priority' failed in pre-merge
**Describe the bug**
A pre-merge CI reported following scala test failure:
```

[2025-11-14T05:40:21.459Z] ResourceBoundedExecutorSuite:

[2025-11-14T05:40:21.713Z] - AsyncCpuTask task priority *** FAILED ***

[2025-11-14T05:40:21.713Z]   java.lang.IllegalArgumentException: requirement failed: Unexpected order of wallTime: List(9616349641154202, 9616349656878335, 9616349651642964, 9616349646412823)

[2025-11-14T05:40:21.713Z]   at scala.Predef$.require(Predef.scala:281)

[2025-11-14T05:40:21.713Z]   at com.nvidia.spark.rapids.ResourceBoundedExecutorSuite.$anonfun$new$13(ResourceBoundedExecutorSuite.scala:94)

[2025-11-14T05:40:21.713Z]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)

[2025-11-14T05:40:21.713Z]   at com.nvidia.spark.rapids.ResourceBoundedExecutorSuite.$anonfun$new$1(ResourceBoundedExecutorSuite.scala:93)

[2025-11-14T05:40:21.713Z]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

[2025-11-14T05:40:21.713Z]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)

[2025-11-14T05:40:21.713Z]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)

[2025-11-14T05:40:21.713Z]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

[2025-11-14T05:40:21.713Z]   at org.scalatest.Transformer.apply(Transformer.scala:22)

[2025-11-14T05:40:21.713Z]   at org.scalatest.Transformer.apply(Transformer.scala:20)

[2025-11-14T05:40:21.713Z]   ...
```

**Steps/Code to reproduce bug**
It happened in the pre-merge CI and seems to be occurring at random.
I haven't been able to reproduce it locally yet.

**Expected behavior**
Test should pass.

### PR DESCRIPTION
**Pull request by sperlingxx**
Fixes #13788

Mirror PR of #13906, which enforces the fix on branch-25.12 as well.

This PR stabilizes a flaky unit test whose output was nondeterministic due to runtime fluctuations by introducing a startup lock to enforce a deterministic execution order.

### CODE REVIEW

File: tests/src/test/scala/com/nvidia/spark/rapids/ResourceBoundedExecutorSuite.scala [hunk 1]
```diff
@@ -39,83 +40,94 @@ class ResourceBoundedExecutorSuite extends AnyFunSuite with RmmSparkRetrySuiteBa
...
+    futures += executor.submit(AsyncRunner.newUnboundedTask(buildDummyFn(lck)))
     // (5) priority = 7 - 10KB = -3
-    futures += executor.submit(AsyncRunner.newCpuTask(buildDummyFn(),
+    futures += executor.submit(AsyncRunner.newCpuTask(buildDummyFn(lck),
       memoryBytes = 10 << 10, priority = 7L))
-    // (6) Unbounded task with the highest priority
-    futures += executor.submit(AsyncRunner.newUnboundedTask(buildDummyFn()))
-    results = Array(1, 4, 6, 2, 5, 3).zip(futures).sortBy(_._1).map {
+    lck.unlock() // Allow tasks to start executing.
+    results = Array(2, 3, 5, 1, 4).zip(futures).sortBy(_._1).map {
```
Comment (firestarman) [inline tests/src/test/scala/com/nvidia/spark/rapids/ResourceBoundedExecutorSuite.scala]: NIT: missing 6 here compared to the original array.

**Review by firestarman — DISMISSED** [review]

**Review by pxLi — DISMISSED** [review]

File: tests/src/test/scala/com/nvidia/spark/rapids/ResourceBoundedExecutorSuite.scala [hunk 2]
```diff
@@ -39,83 +40,94 @@ class ResourceBoundedExecutorSuite extends AnyFunSuite with RmmSparkRetrySuiteBa
...
+      executor.submit(AsyncRunner.newCpuTask(buildDummyFn(lck), memoryBytes = i << 20))
     }
+    lck.unlock() // Allow tasks to start executing.
+    results = sortedFut.map(_.get().data)
     (0 until results.length - 1).foreach { i =>
       require(results(i) > results(i + 1), s"Unexpected order of wallTime: ${results.toList}")
     }
 
     // Comprehensive test for task priority and memory usage (including unbounded tasks):
     // Execution order: 1, 4, 6, 2, 5, 3
```
[the remark this answers is not in the document]
Comment (sperlingxx) [reply tests/src/test/scala/com/nvidia/spark/rapids/ResourceBoundedExecutorSuite.scala]: Fixed

File: tests/src/test/scala/com/nvidia/spark/rapids/ResourceBoundedExecutorSuite.scala (hunk 1 above)
Comment (sperlingxx) [reply tests/src/test/scala/com/nvidia/spark/rapids/ResourceBoundedExecutorSuite.scala]: @firestarman , yes, since I changed the test sample as well. Currently, only 5 samples are included. Description was also updated.

**Comment by sperlingxx** [comment]
build

**Comment by res-life** [comment]
LGTM, but we may improve this PR in a follow-up PR.

I have the following concerns:

> Tasks with higher priority should be executed first even if they are submitted later.

But the `buildDummyFn` returns the complete time not the start time.

Maybe we can:
Create the priority single thread pool, then commit a long time(may be 1s) running task.
The long time running task will make sure the followng submitted tasks in the thread pool queue.
Then submit  some tasks and the priority thread pool will reorder the tasks in the task queue.
And we only need to record the task start time to verify the priority thread pool works fine.
In this way, we do not need to introduce a `lock`.
By short: do not verify the first task, only verify the following tasks.

**Comment by sperlingxx** [comment]
> LGTM, but we may improve this PR in a follow-up PR.
> 
> I have the following concerns:
> 
> > Tasks with higher priority should be executed first even if they are submitted later.
> 
> But the `buildDummyFn` returns the complete time not the start time.
> 
> Maybe we can: Create the priority single thread pool, then commit a long time(may be 1s) running task. The long time running task will make sure the followng submitted tasks in the thread pool queue. Then submit some tasks and the priority thread pool will reorder the tasks in the task queue. And we only need to record the task start time to verify the priority thread pool works fine. In this way, we do not need to introduce a `lock`. By short: do not verify the first task, only verify the following tasks.

Good idea! Thanks!
