### PR TITLE
 Fix bloop project generation on [databricks]

### LINKED ISSUE #12245: [BUG] Bloop project import for VSCode/Metals fails for Databricks Maven profiles
**Describe the bug**
```bash
dbrhost:~/spark-rapids$ WITH_BLOOP=1 ./jenkins/databricks/build.sh
[INFO] Compiling 20 Scala sources and 2 Java sources to /home/ubuntu/spark-rapids/sql-plugin-api/target/spark350db143/classes...                                                                                     
[ERROR] warning: [options] bootstrap class path not set in conjunction with -source 8                                                                                                                                
[ERROR] error: warnings found and -Werror specified                                                       
[ERROR] error: warnings found and -Werror specified                                                       
[ERROR] error: warnings found and -Werror specified                                                       
[ERROR] error: warnings found and -Werror specified                                                       
[ERROR] 4 errors                                     
[ERROR] 1 warning  
```

Looks like we inadvertently fallback to JDK8 profiles although we request zulu11+ 

https://github.com/NVIDIA/spark-rapids/blob/fe452cb1382a3e332b94be49cc32adaad95ecb7c/jenkins/databricks/build.sh#L166

### PR DESCRIPTION
**Pull request by gerashegalov**
Closes #12245 

- Drop special scala-maven-plugin on Databricks preventing picking up the right flags for scalac for JDK9+
- Upgrade scala-maven-plugin to the latest 4.9.2
- Upgrade bloop-maven-plugin to the latest 2.0.1
- For Bloop on Databricks use zulu17 if available to workaround another Incremental compile error
- Set downloadSources to true by default
- Disable two-shim build when used WITH_BLOOP because with different JDKs used for 320 and db shims each it will fail on binary-dedupe given differences in the constant pool in otherwise equivalent classfiles.
    
 Signed-off-by: Gera Shegalov <gshegalov@nvidia.com>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
CI failed on unrelated #12260

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by mythrocks — DISMISSED** [review]
To the extent that I understand this, I'm 👍.

File: jenkins/databricks/build.sh [hunk 1]
```diff
@@ -163,7 +163,8 @@ fi
 if [[ "$WITH_BLOOP" == "1" ]]; then
     MVN_OPT="-DbloopInstall $MVN_OPT"
     MVN_PHASES="clean install"
-    export JAVA_HOME="/usr/lib/jvm/zulu11"
+    export JAVA_HOME="/usr/lib/jvm/zulu17"
```
Comment (tgravescs) [inline jenkins/databricks/build.sh:166]: this is ok for all supported Databricks versions?

Comment (gerashegalov) [reply jenkins/databricks/build.sh:166]: good point it is not available on DBR 11.3

File: pom.xml [hunk 2]
```diff
@@ -606,8 +606,6 @@
                 </property>
             </activation>
             <properties>
-                <!-- Downgrade scala plugin version due to: https://github.com/sbt/sbt/issues/4305 -->
-                <scala.plugin.version>3.4.4</scala.plugin.version>
```
[the remark this answers is not in the document]
Comment (gerashegalov) [reply pom.xml:610]: Thanks for reviewing @revans2 

723 is a follow up PR in sbt 4305 for 1.3x. The main PR associated with this issue is https://github.com/sbt/zinc/pull/719.

Commit https://github.com/sbt/zinc/commit/6720d5fb8327b0a51df860f633f97c25c844b27a is included  in 1.10.0

which scala-maven-plugin upgraded to in https://github.com/davidB/scala-maven-plugin/commit/d6caa5f6d6e5792d80553dd0677b04f2a164ca3d 4.9.1

**Comment by gerashegalov** [comment]
build
