### PR TITLE
Fallback Delta Lake optimized writes if GPU cannot support partitioning

### LINKED ISSUE #7799: [BUG] Cannot lexicographic compare a table with a LIST of STRUCT column at ai.rapids.cudf.Table.sortOrder
**Describe the bug**
Customer job tried upgrading to a  23.04 snapshot build (job was  using 23.02.20221221 version) and got the following error:

`ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-346-cuda11/thirdparty/cudf/cpp/src/table/row_operators.cu:288: Cannot lexicographic compare a table with a LIST of STRUCT column
	at ai.rapids.cudf.Table.sortOrder(Native Method)
	at ai.rapids.cudf.Table.sortOrder(Table.java:1956)
	at com.nvidia.spark.rapids.GpuSorter.$anonfun$computeSortOrder$2(SortUtils.scala:327)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:65)
	at com.nvidia.spark.rapids.GpuSorter.$anonfun$computeSortOrder$1(SortUtils.scala:326)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:65)
	at com.nvidia.spark.rapids.GpuSorter.computeSortOrder(SortUtils.scala:325)
	at com.nvidia.spark.rapids.GpuSorter.$anonfun$fullySortBatch$1(SortUtils.scala:377)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:65)
	at com.nvidia.spark.rapids.GpuSorter.fullySortBatch(SortUtils.scala:372)
	at com.nvidia.spark.rapids.GpuSortEachBatchIterator.$anonfun$next$2(GpuSortExec.scala:173)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuSortEachBatchIterator.withResource(GpuSortExec.scala:159)
	at com.nvidia.spark.rapids.GpuSortEachBatchIterator.$anonfun$next$1(GpuSortExec.scala:172)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuSortEachBatchIterator.withResource(GpuSortExec.scala:159)
	at com.nvidia.spark.rapids.GpuSortEachBatchIterator.next(GpuSortExec.scala:171)
	at com.nvidia.spark.rapids.GpuSortEachBatchIterator.next(GpuSortExec.scala:159)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:318)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:340)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$2(RapidsShuffleInternalManagerBase.scala:281)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$2$adapted(RapidsShuffleInternalManagerBase.scala:274)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.withResource(RapidsShuffleInternalManagerBase.scala:234)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$1(RapidsShuffleInternalManagerBase.scala:274)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$1$adapted(RapidsShuffleInternalManagerBase.scala:273)`

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #7799.

Updates the tagging of Delta Lake write operations to fallback to the CPU for optimized writes that will need to use a round-robin partitioning when the GPU cannot order one or more types in the schema.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by tgravescs** [comment]
hyperlink  [✖] https://github.com/NVIDIA/spark-rapids/blob/main/build/shimplify.py → Status: 404

@gerashegalov

File: delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/RapidsDeltaUtils.scala [hunk 1]
```diff
@@ -53,6 +55,42 @@ object RapidsDeltaUtils {
       }
     }
 
+    // Optimized writes for non-partitioned tables involves a round-robin partitioning, and that
+    // can involve a sort on all columns. The GPU doesn't currently support sorting on all types,
+    // so we fallback if the GPU cannot support the round-robin partitioning.
+    if (sqlConf.sortBeforeRepartition) {
+      val orderableTypeSig = (GpuOverrides.pluginSupportedOrderableSig + TypeSig.DECIMAL_128
```
Comment (tgravescs) [inline delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/RapidsDeltaUtils.scala:62]: Do we want to make a val that combines all of these and is used here and in GpuOverides SortOrder so that if we change in GpuOverrides we make this picks it up?

**Review by tgravescs — APPROVED** [review]

File: delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/RapidsDeltaUtils.scala (hunk 1 above)
Comment (jlowe) [reply delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/RapidsDeltaUtils.scala:62]: Yes, very much so, but I think that's outside the scope of this PR.  I filed #7807 to fix that along with a bug in ShuffleExchangeExecBase related to the fact that there isn't a proper val for this.
