### PR TITLE
Put the GPU data back on host before processing cache on CPU

### LINKED ISSUE #2942: [BUG] Cache of Array using ParquetCachedBatchSerializer failed with "DATA ACCESS MUST BE ON A HOST VECTOR"
**Describe the bug**
Cache of Array using ParqudBatchSerializer failed with "DATA ACCESS MUST BE ON A HOST VECTOR".

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.
```
pyspark --conf spark.sql.cache.serializer=com.nvidia.spark.rapids.shims.spark311.ParquetCachedBatchSerializer
```

Then run:
```
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, split

data = [("aaa", "123 456 789"), ("bbb", "444 555 666"), ("ccc", "777 888 999")]
columns = ["a","b"]
df = spark.createDataFrame(data).toDF(*columns)
newdf = df.withColumn('newb', split(col('b'),' '))
newdf.persist()
newdf.count()
```
Full stacktrace:
```
  File "/xxx/xxx/spark/myspark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o177.count.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 17.0 failed 4 times, most recent failure: Lost task 5.3 in stage 17.0 (TID 60) (xxx.xxx.xxx.xxx executor 0): java.lang.IllegalStateException: DATA ACCESS MUST BE ON A HOST VECTOR
      at com.nvidia.spark.rapids.GpuColumnVectorBase.isNullAt(GpuColumnVectorBase.java:53)
      at org.apache.spark.sql.vectorized.ColumnarBatchRow.isNullAt(ColumnarBatch.java:190)
      at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.writeFields(ParquetWriteSupport.scala:156)
      at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.$anonfun$write$1(ParquetWriteSupport.scala:148)
      at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.consumeMessage(ParquetWriteSupport.scala:464)
      at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.write(ParquetWriteSupport.scala:148)
      at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.write(ParquetWriteSupport.scala:54)
      at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:128)
      at org.apache.parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:182)
      at org.apache.parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:44)
      at com.nvidia.spark.rapids.shims.spark311.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$InternalRowToCachedBatchIterator.next(ParquetCachedBatchSerializer.scala:1231)
      at com.nvidia.spark.rapids.shims.spark311.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$InternalRowToCachedBatchIterator.next(ParquetCachedBatchSerializer.scala:1074)
      at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
      at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
      at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
      at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
      at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
      at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
      at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
      at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
      at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
      at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
      at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
      at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
      at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
      at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
      at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
      at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
      at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
      at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
      at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
      at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
      at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
      at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
      at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
      at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
      at org.apache.spark.scheduler.Task.run(Task.scala:131)
      at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
      at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
      at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
      at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**
It should not fail. 

Note: If we unpersist the DF, it works fine:
```
newdf.unpersist()
newdf.count()
```

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue
Spark 3.1.1
CUDA 11.0
RAPIDS plugin 21.08 snapshot

**Additional context**

### PR DESCRIPTION
**Pull request by razajafri**
If DataType isn't supported by `ParquetCachedBatchSerializer` on the GPU but the data is already on the GPU, we should copy it back to the host before writing it to cache otherwise the plugin will throw an exception. 

Fixes #2942 

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

**Comment by razajafri** [comment]
build

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala [hunk 1]
```diff
@@ -1249,7 +1249,32 @@ class ParquetCachedBatchSerializer extends CachedBatchSerializer with Arm {
...
+          override def hasNext: Boolean = rowIterator.hasNext
+
+          // We have to check for null context because of the unit test
+          if (TaskContext.get() != null) {
+            TaskContext.get().addTaskCompletionListener[Unit]((_: TaskContext) => {
+              if (hostBatch != null) {
+                hostBatch.close()
+              }
+            })
+          }
```
Comment (jlowe) [inline shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala:1276]: Constructor-like code should appear towards the top of the class.

This can be simplified to something like this:
```suggestion
          Option(TaskContext.get).foreach(_.addTaskCompletionListener[Unit](_ => hostBatch.close())
```

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala [hunk 2]
```diff
@@ -1249,7 +1249,32 @@ class ParquetCachedBatchSerializer extends CachedBatchSerializer with Arm {
...
+          val rowIterator = hostBatch.rowIterator().asScala
+
+          override def next: InternalRow = rowIterator.next
+
+          override def hasNext: Boolean = rowIterator.hasNext
+
+          // We have to check for null context because of the unit test
+          if (TaskContext.get() != null) {
+            TaskContext.get().addTaskCompletionListener[Unit]((_: TaskContext) => {
+              if (hostBatch != null) {
```
Comment (jlowe) [inline shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala:1272]: How is `hostBatch` going to be null?

**Review by jlowe — COMMENTED** [review]
> If DataType isn't supported on the GPU and the data is already on the GPU

This sentence is confusing.  If the data type isn't supported by the GPU, how did it get on the GPU?  I assume this is a case where the cache serializer doesn't support the type on the GPU but other operators do.

Adding a test would help explain what's going on and also help avoid regressions.

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala (hunk 1 above)
Comment (razajafri) [reply shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala]: I have updated the PR description lmk if that is cleaner? I have also added a test which should've been added anyways, thanks for reminding.

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala (hunk 2 above)
Comment (razajafri) [reply shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala]: never. It was something I had before I decided to do it this way.

**Review by jlowe — APPROVED** [review]

**Comment by razajafri** [comment]
build
