### PR TITLE
Fallback GpuDeltaParquetFileFormat to CPU in presence of deletion vectors [databricks] 

### LINKED ISSUE #12460: [BUG] Fallback to the CPU when FileSourceScan is reading Deletion Vectors on Databricks 14.3
**Describe the bug**
https://github.com/NVIDIA/spark-rapids/pull/12397 is merged, but we could still read deletion vectors on the GPU  if the `PERFILE` reader is being used. However, because of performance regression, we should fallback to the CPU for now. 

**Steps/Code to reproduce bug**
```
@allow_non_gpu("SortExec, ColumnarToRowExec", *delta_meta_allow)
@delta_lake
@ignore_order
@pytest.mark.skipif(not supports_delta_lake_deletion_vectors(), \
                    reason="Deletion vectors new in Delta Lake 2.4 / Apache Spark 3.4")
def test_delta_deletion_vector_read_fallback(spark_tmp_path):
    data_path = spark_tmp_path + "/DELTA_DATA"
    def setup_tables(spark):
        setup_delta_dest_table(spark, data_path,
                               dest_table_func=lambda spark: unary_op_df(spark, int_gen),
                               use_cdf=False, enable_deletion_vectors=True)
    def write_func(path):
        delete_sql="DELETE FROM delta.`{}` where a = 0".format(path)
        def delete_func(spark):
            spark.sql(delete_sql)
        return delete_func

    def read_parquet_sql(data_path):
        return lambda spark : spark.sql('select * from delta.`{}`'.format(data_path))

    enable_conf = copy_and_update(delta_delete_enabled_conf,
                                   {"spark.databricks.delta.delete.deletionVectors.persistent": "true"})

    with_cpu_session(setup_tables, conf=enable_conf)
    with_cpu_session(write_func(data_path), conf=enable_conf)

    assert_gpu_fallback_collect(read_parquet_sql(data_path), "FileSourceScanExec")
```
The above test can be executed by 
```
PYSP_TEST_spark_rapids_sql_format_parquet_reader_type='PERFILE' TEST_MODE=DELTA_LAKE_ONLY WITH_DEFAULT_UPSTREAM_SHIM=0 TESTS=delta_lake_delete_test.py::test_delta_deletion_vector_read_fallback ./jenkins/databricks/test.sh
```
**Expected behavior**
The test should pass

**Environment details (please complete the following information)**
Databricks 14.3

### PR DESCRIPTION
**Pull request by razajafri**
This PR tags the plan to fallback to the CPU when deletion vectors are being read. 

fixes #12460

### CODE REVIEW

File: delta-lake/delta-spark350db143/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala [hunk 1]
```diff
@@ -247,8 +247,14 @@ case class GpuDeltaParquetFileFormat(
 
 object GpuDeltaParquetFileFormat {
   def tagSupportForGpuFileSourceScan(meta: SparkPlanMeta[FileSourceScanExec]): Unit = {
-    if (!meta.conf.isParquetPerFileReadEnabled) {
-      meta.willNotWorkOnGpu("Deletion vectors only supported for PERFILE reader")
+    val format = meta.wrapped.relation.fileFormat.asInstanceOf[DeltaParquetFileFormat]
```
Comment (gerashegalov) [inline delta-lake/delta-spark350db143/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala:250]: Let us grab protocol and metadata from fromat and call DeltectionVectorUtrils.is Supported

Comment (gerashegalov) [reply delta-lake/delta-spark350db143/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala:251]: why do we check for writable in the Scan acceleration? checking for readable would make sense https://github.com/delta-io/delta/blob/6118f3fd4bf4cb32abd5ebeff1e74d3d9656bd86/spark/src/main/scala/org/apache/spark/sql/delta/commands/DeletionVectorUtils.scala#L85

Comment (razajafri) [reply delta-lake/delta-spark350db143/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala:251]: That will only check if the protocol supports deletion vector and if the metadata format is parquet. Is that what we want? I thought we wanted to check the table properties?

Comment (gerashegalov) [reply delta-lake/delta-spark350db143/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala:250]: the table property only seems to tell us if we are allowed to add a new DV. But the existing DV data remains readable. So I guess we should just use what you had

**Comment by razajafri** [comment]
build
