### PR TITLE
Fix non-nullable under nullable struct write

### LINKED ISSUE #11762: [BUG] Non-nullable bools in a nullable struct fails
**Describe the bug**
While working on a test for issue https://github.com/NVIDIA/spark-rapids/issues/11736. I see failures with below stack trace when booleans that have `nullable=false` are passed into structs with `nullable=true` . 

```
Caused by: ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni-release-4-cuda12/thirdparty/cudf/cpp/src/io/orc/writer_impl.cu:586: Mismatch in metadata prescribed nullability and input column. Metadata for input column with nulls cannot prescribe nullability = false
E                   	at ai.rapids.cudf.Table.writeORCChunk(Native Method)
E                   	at ai.rapids.cudf.Table.access$1300(Table.java:41)
E                   	at ai.rapids.cudf.Table$ORCTableWriter.write(Table.java:2038)
E                   	at com.nvidia.spark.rapids.ColumnarOutputWriter.$anonfun$encodeAndBufferToHost$1(ColumnarOutputWriter.scala:205)
E                   	at com.nvidia.spark.rapids.ColumnarOutputWriter.$anonfun$encodeAndBufferToHost$1$adapted(ColumnarOutputWriter.scala:196)
E                   	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
E                   	at com.nvidia.spark.rapids.ColumnarOutputWriter.encodeAndBufferToHost(ColumnarOutputWriter.scala:196)
E                   	at com.nvidia.spark.rapids.ColumnarOutputWriter.$anonfun$bufferBatchAndClose$2(ColumnarOutputWriter.scala:180)
E                   	at com.nvidia.spark.rapids.ColumnarOutputWriter.$anonfun$bufferBatchAndClose$2$adapted(ColumnarOutputWriter.scala:179)
```

**Steps/Code to reproduce bug**
`orc_write_test.py` , pass `BooleanGen(nullable=False)` to `StructGen` and run the tests. 
```
orc_write_basic_gens = [byte_gen, short_gen, int_gen, long_gen, float_gen, double_gen,
        string_gen, BooleanGen(nullable=False), DateGen(start=date(1590, 1, 1)),
        TimestampGen(start=datetime(1970, 1, 1, tzinfo=timezone.utc)) ] + \
        decimal_gens
```
```
orc_write_basic_struct_gen = StructGen([['child'+str(ind), sub_gen] for ind, sub_gen in enumerate(orc_write_basic_gens)])
```
Run command : 
```
TEST_PARALLEL=10 ./run_pyspark_from_build.sh  -k "orc_write_test"
```

**Expected behavior**
Not error, fallback or  ideally allow for Spark parity with nullables being reflected thru the metadata field. 

**Environment details (please complete the following information)**
 - Any, onprem in this case

### PR DESCRIPTION
**Pull request by revans2**
This fixes #11762

But we need to be careful and coordinate this with #11763 because I think we are going to disable boolean writes for all of ORC.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by jihoonson — DISMISSED** [review]
LGTM

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala [hunk 1]
```diff
@@ -329,10 +331,13 @@ object SchemaUtils {
       builder: NestedBuilder[T, V],
       schema: StructType,
       writeInt96: Boolean = false,
-      parquetFieldIdEnabled: Boolean = false): T = {
+      parquetFieldIdEnabled: Boolean = false,
+      nullable: Boolean = true): T = {
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala:335]: Is true an appropriate default value?  I noticed that every occurrence of this had to either be updated to explicitly pass `false` or a computed value, which makes me wonder if `false` would be the better default.  `false` would also match the prior behavior, respecting each top-level field's nullable setting rather than smashing it.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@jlowe please take another look

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
Test failures in CI
```
[2024-12-11T22:26:54.226Z] FAILED ../../src/main/python/orc_write_test.py::test_write_round_trip_nullable_struct[native-Boolean(not_null)][DATAGEN_SEED=1733949546, TZ=UTC] - pyspark.sql.utils.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.command.DataWritingCommandExec
[2024-12-11T22:26:54.226Z] Execute InsertIntoHadoopFsRelationCommand file:/tmp/pyspark_tests/premerge-ci-2-jenkins-rapids-premerge-github-10369-qjm3n-vdg90-gw1-2497-46613182/ORC_DATA/GPU, false, ORC, [path=/tmp/pyspark_tests//premerge-ci-2-jenkins-rapids-premerge-github-10369-qjm3n-vdg90-gw1-2497-46613182//ORC_DATA/GPU], ErrorIfExists, [a]
[2024-12-11T22:26:54.226Z] +- Scan ExistingRDD[a#161900]
[2024-12-11T22:26:54.226Z] FAILED ../../src/main/python/orc_write_test.py::test_write_round_trip_nullable_struct[hive-Boolean(not_null)][DATAGEN_SEED=1733949546, TZ=UTC] - pyspark.sql.utils.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.command.DataWritingCommandExec
[2024-12-11T22:26:54.226Z] Execute InsertIntoHadoopFsRelationCommand file:/tmp/pyspark_tests/premerge-ci-2-jenkins-rapids-premerge-github-10369-qjm3n-vdg90-gw1-2497-86215200/ORC_DATA/GPU, false, ORC, [path=/tmp/pyspark_tests//premerge-ci-2-jenkins-rapids-premerge-github-10369-qjm3n-vdg90-gw1-2497-86215200//ORC_DATA/GPU], ErrorIfExists, [a]
[2024-12-11T22:26:54.226Z] +- Scan ExistingRDD[a#162002]
```

I suspect this is because booleans are in the datagen and we recently changed to fallback on ORC writes of booleans.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@jlowe please take another look

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
build
