### PR TITLE
Fix cast to date bug

### LINKED ISSUE #2868: [BUG] to_date produces wrong value on GPU for some corner cases
**Describe the bug**

`to_date` (without a format specified) produces incorrect results for some invalid inputs. For example, the input string `3330-7 39 49` produces `null` on the CPU but produces the date `3330-07-01` on the GPU.

```
CPU: [3330-7 39 49: 1,null]

GPU: [3330-7 39 49: 1,3330-07-01]
```

**Steps/Code to reproduce bug**

I was experimenting with some basic fuzzing in the unit test.

```scala
private def generateTimestampStrings(n: Int): Seq[String] = {
  val validChars = "0123456789:-. \t\n"
  val rand = new Random(0) // fixed seed
  val list = new ListBuffer[String]()
  for (_ <- 0 to n) {
    val len = rand.nextInt(32)
    val str = new StringBuilder(len)
    for (_ <- 0 to len) {
      str.append(validChars.charAt(rand.nextInt(validChars.length)))
    }
    list += str.toString
  }
  list
}
```

**Expected behavior**
Results should be consistent between CPU and GPU.

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by andygrove**
This PR builds on #2875 and closes #2868 

Commit # 4 adds the test and commit # 5 adds the fix.

There was a bug in the regex that sanitizes input for CAST string to date where it was removing trailing characters in some cases, converting invalid inputs into valid inputs.

### CODE REVIEW

**Comment by jlowe** [comment]
Marking this a draft so it isn't inadvertently committed while #2875 is under review.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 1]
```diff
@@ -158,6 +159,24 @@ object GpuCast {
...
+  /**
+   * Sanitization step for CAST string to date. Inserts a single zero before any
+   * single digit month or day.
+   */
+  def sanitizeStringToDate(input: ColumnVector): ColumnVector = {
+    val rules = Seq(
+      /// replace yyyy-m with yyyy-mm
+      RegexReplace("(\\A\\d{4})-(\\d{1})\\Z", "\\1-0\\2"),
+      /// replace yyyy-m- with yyyy-mm-
+      RegexReplace("(\\A\\d{4})-(\\d{1}-)", "\\1-0\\2"),
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:172]: Is it possible to combine these?  I'm thinking of something similar to what the regex just below does to handle the different endings, for example (also using `raw` strings for improved legibility):
```suggestion
      RegexReplace(raw"(\A\d{4})-(\d{1})([\-|\Z])", raw"\1-0\2\3"),
```

Comment (andygrove) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: Thanks, I was able to combine the first two. Also switched to raw strings.

**Review by jlowe — APPROVED** [review]

**Comment by andygrove** [comment]
This is now rebased.

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build
