### PR TITLE
Replace anonymous classes for SortOrder and FIlterExec overrides

### LINKED ISSUE #10838: Improve converToGpu diagnostics and unbloat GpuOverrides
As of branch-24.06, GpuOverrides.scala is a file of ~4800 Lines of Code (and growing) consisting of numerous replacement rules.

In the center of  the rule is an instance of the Function type 
```Scala
doWrap: (INPUT, RapidsConf, Option[RapidsMeta[_, _, _]], DataFromReplacementRule)
          => SparkPlanMeta[INPUT]
```

which is almost uniformly provided inline compiling down to an anonymous class. Hence, whenever there is an exception in convertToGpu akin to #881

we cannot determine which replacement rule is throwing the exception based on the stack trace alone
	
```
at com.nvidia.spark.rapids.GpuOverrides$$anon$95.$anonfun$convertToGpu$8(GpuOverrides.scala:1221)
```

without having to look at the source code from which the class was compiled

https://github.com/NVIDIA/spark-rapids/blob/d2abd359caaa37477f065911b20397db9dbdccbc/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala#L1216-L1222

Note that the original stack trace of #881 does not mention`SortOrder`

This issue proposes a convention to have the function instance be nested in a companion object reflecting in its name the Exec, Expression being replaced. This way we can determine the expression, exec causing the issue without matching the line numbers of the stack trace to the right git hash of GpuOverides.

When this function is implemented in a companion object where the corresponding GPU implementation lives, GpuOverrides will become smaller and the rules more compact and clear.

### PR DESCRIPTION
**Pull request by gerashegalov**
Demo PR contributing to #10838 

It showcases a coding convention to follow using SortOrder and FilterExec replacements as an example

```scala
scala>  spark.range(100).where($"id" <= 10).collect()

java.lang.RuntimeException: convertToGpu failed
  at scala.sys.package$.error(package.scala:30)
  at com.nvidia.spark.rapids.GpuFilterExecMeta.convertToGpu(basicPhysicalOperators.scala:790)
  at com.nvidia.spark.rapids.GpuFilterExecMeta.convertToGpu(basicPhysicalOperators.scala:783)
  at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:838)
  at com.nvidia.spark.rapids.GpuOverrides$.com$nvidia$spark$rapids$GpuOverrides$$doConvertPlan(GpuOverrides.scala:4383)
  at com.nvidia.spark.rapids.GpuOverrides.applyOverrides(GpuOverrides.scala:4728)
  at com.nvidia.spark.rapids.GpuOverrides.$anonfun$applyWithContext$3(GpuOverrides.scala:4588)
  at com.nvidia.spark.rapids.GpuOverrides$.logDuration(GpuOverrides.scala:455)
  at com.nvidia.spark.rapids.GpuOverrides.$anonfun$applyWithContext$1(GpuOverrides.scala:4585)
  at com.nvidia.spark.rapids.GpuOverrideUtil$.$anonfun$tryOverride$1(GpuOverrides.scala:4551)
  at com.nvidia.spark.rapids.GpuOverrides.applyWithContext(GpuOverrides.scala:4605)
  at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:4578)
  at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:4574)
  at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1(Columnar.scala:532)
```

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala [hunk 1]
```diff
@@ -407,3 +408,56 @@ class GpuSorter(
...
+  val pluginChecks: ExprChecks = ExprChecks.projectOnly(
+    pluginSupportedOrderableSig + TypeSig.ARRAY.nested(gpuCommonTypes)
+      .withPsNote(TypeEnum.ARRAY, "STRUCT is not supported as a child type for ARRAY"),
+    TypeSig.orderable,
+    Seq(ParamCheck(
+      "input",
+      pluginSupportedOrderableSig + TypeSig.ARRAY.nested(gpuCommonTypes)
+        .withPsNote(TypeEnum.ARRAY, "STRUCT is not supported as a child type for ARRAY"),
+      TypeSig.orderable)))
+}
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala:463]: I'm lukewarm on this kind of change.  We created yet another class just to hold the result of an ExprChecks call that otherwise wouldn't need a new class to hold it.  If we scale this out to all the exprs and execs we support, that's a lot of new classes that need to be loaded during startup.

**Review by jlowe — COMMENTED** [review]
I like the anonymous class changes, since we're trading class-for-class, making the stacktrace much more useful without adding to the classloading burden.  As for the pluginChecks change, that I'm less convinced is a net benefit change.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala (hunk 1 above)
Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala]: This makes sense too, updated

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]
