### PR TITLE
Remove the ORC encryption tests [databricks]

### LINKED ISSUE #5733: [BUG] Integration test test_orc_write_encryption_fallback fail
**Describe the bug**
```
21:14:38  FAILED ../../src/main/python/orc_write_test.py::test_orc_write_encryption_fallback[-pii:a--][ALLOW_NON_GPU(DataWritingCommandExec)]
21:14:38  FAILED ../../src/main/python/orc_write_test.py::test_orc_write_encryption_fallback[-pii:a--kms:/http@localhost:9600/kms][ALLOW_NON_GPU(DataWritingCommandExec)]
21:14:38  FAILED ../../src/main/python/orc_write_test.py::test_orc_write_encryption_fallback[-pii:a-hadoop-][ALLOW_NON_GPU(DataWritingCommandExec)]
21:14:38  FAILED ../../src/main/python/orc_write_test.py::test_orc_write_encryption_fallback[-pii:a-hadoop-kms:/http@localhost:9600/kms][ALLOW_NON_GPU(DataWritingCommandExec)]
21:14:38  FAILED ../../src/main/python/orc_write_test.py::test_orc_write_encryption_fallback[sha256:a-pii:a--][ALLOW_NON_GPU(DataWritingCommandExec)]
21:14:38  FAILED ../../src/main/python/orc_write_test.py::test_orc_write_encryption_fallback[sha256:a-pii:a--kms:/http@localhost:9600/kms][ALLOW_NON_GPU(DataWritingCommandExec)]
21:14:38  FAILED ../../src/main/python/orc_write_test.py::test_orc_write_encryption_fallback[sha256:a-pii:a-hadoop-][ALLOW_NON_GPU(DataWritingCommandExec)]
21:14:38  FAILED ../../src/main/python/orc_write_test.py::test_orc_write_encryption_fallback[sha256:a-pii:a-hadoop-kms:/http@localhost:9600/kms][ALLOW_NON_GPU(DataWritingCommandExec)]
```
```
21:14:38  [1m[31mE                   Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 35.0 failed 1 times, most recent failure: Lost task 0.0 in stage 35.0 (TID 35) (10.233.91.41 executor 0): java.io.IOException: Failed to connect to: [http://localhost:9600/kms/v1/key/pii/_metadata[0m](http://localhost:9600/kms/v1/key/pii/_metadata%1B[0m)
`21:14:38  [1m[31mE                   Caused by: java.net.ConnectException: Error while authenticating with endpoint: [http://localhost:9600/kms/v1/key/pii/_metadata[0m](http://localhost:9600/kms/v1/key/pii/_metadata%1B[0m)`
```

### PR DESCRIPTION
**Pull request by razajafri**
This PR removes the ORC encryption test

There will be a follow-on PR for adding tests

fixes #5733 

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

**Comment by tgravescs** [comment]
please put a description of changes made and why

**Comment by razajafri** [comment]
build

File: tests/src/test/320+/scala/com/nvidia/spark/rapids/OrcEncryptionSuite.scala [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+    "DataWritingCommandExec",
+    intsDf,
+    conf = new SparkConf().set("hadoop.security.key.provider.path", "test:///")
+        .set("orc.key.provider", "hadoop")
+        .set("orc.encrypt", "pii:ints,more_ints")
+        .set("orc.mask", "sha256:ints,more_ints")) {
+    frame =>
+      // ORC encryption is only allowed in 3.2+
+      val isValidTestForSparkVersion = SparkShimImpl.getSparkShimVersion match {
+        case SparkShimVersion(major, minor, _) => major == 3 && minor != 1
```
Comment (tgravescs) [inline tests/src/test/320+/scala/com/nvidia/spark/rapids/OrcEncryptionSuite.scala:39]: we don't need these checks if this is in a 320+ directory right?

Comment (razajafri) [reply tests/src/test/320+/scala/com/nvidia/spark/rapids/OrcEncryptionSuite.scala:39]: Yes, we don't. I am being defensive here in case someone moves things around. If this is an issue, I can remove them

**Comment by HaoYang670** [comment]
Build failure is due to #5744

**Comment by sameerz** [comment]
build

File: tests/src/test/320+/scala/com/nvidia/spark/rapids/OrcEncryptionSuite.scala [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+        case DatabricksShimVersion(major, minor, _, _) => major == 3 && minor != 1
+        case ClouderaShimVersion(major, minor, _, _) => major == 3 && minor != 1
+        case _ => true
+      }
+      assume(isValidTestForSparkVersion)
+
+      withCpuSparkSession(session => {
+        val conf = session.sessionState.newHadoopConf()
+        val provider = HadoopShimsFactory.get.getHadoopKeyProvider(conf, new Random)
+        assume(!provider.getKeyNames.isEmpty,
```
Comment (tgravescs) [inline tests/src/test/320+/scala/com/nvidia/spark/rapids/OrcEncryptionSuite.scala:49]: this isn't testing anything the way its written, we need a different way to test

**Review by tgravescs — CHANGES_REQUESTED** [review]

**Review by tgravescs — APPROVED** [review]
we need another issue filed to add a working test back

**Comment by razajafri** [comment]
> we need another issue filed to add a working test back

#5722

**Comment by razajafri** [comment]
build
