### PR TITLE
Add RapidsDeltaWrite node to fix undesired transitions with AQE

### LINKED ISSUE #7505: [BUG] Delta Lake writes with AQE can have unnecessary row transitions
**Describe the bug**
When the query plan to write to Delta Lake has AdaptiveSparkPlanExec as the root node of the plan, the GPU transition planning code does not have the context to know whether the result of the AQE plan should be GPU columnar or CPU row, since it cannot see the parent node.  Typical, non-Delta writes do not have this problem since the Delta Lake write appears in the plan as a node to execute, and it becomes the parent of the AQE node.  Delta Lake writes do not appear in the plan, so the AQE node becomes the root, and it injects columnar-to-row transitions in the AQE plan only to produce a row-to-columnar transition immediately afterwards to perform the GPU write.

**Steps/Code to reproduce bug**
Execute the following code in PySpark on a Spark version with AQE enabled:
```python
df = spark.range(10)
df.join(df, ["id"], "inner").write.format("delta").save("/tmp/deltajoin")
```
and examine the SQL plan for the query to be written to Delta Lake.  Note the GpuColumnarToRow transition just before the AdaptiveSparkPlanExec as the root node in the query plan.

**Expected behavior**
No columnar-to-row transition should occur.

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #7505.

This adds a new RapidsDeltaWrite logical node along with the Strategy to translate it into a RapidsDeltaWriteExec stub physical node.  That node in turn is translated into a GpuRapidsDeltaWriteExec node which derives from V2CommandExec to prevent AdaptiveSparkPlanExec from appearing before it in a plan.  This logical node is then used by the Delta Write code in GpuOptimisticTransaction.writeFiles to allow any AQE sub-plan in the query plan to write to be transformed properly by the GPU transition planning code (i.e.: without extraneous row transitions).

Unlike CPU plans, this new node does appear in the SQL plans for Delta Lake write operations.  However I think this is ultimately a good thing, as it makes it very clear the write was translated to the GPU and also provides a place to attach metrics specific to the write operation (i.e.: time spent writing files vs. other Delta Lake operations like merge join processing, etc.).

### CODE REVIEW

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuOptimisticTransaction.scala [hunk 1]
```diff
@@ -164,8 +158,20 @@ class GpuOptimisticTransaction
...
       normalizeData(deltaLog, data)
+
+    // Build a new plan with a stub GpuDeltaWrite node to work around undesired transitions between
+    // columns and rows when AQE is involved. Without this node in the plan, AdaptiveSparkPlanExec
+    // could be the root node of the plan. In that case we do not have enough context to know
+    // whether the AdaptiveSparkPlanExec should be columnar or not, since the GPU overrides do not
+    // see how the parent is using the AdaptiveSparkPlanExec outputs. By using this stub node, the
+    // parent node is present and it will be planned accordingly. We could force the AQE node to be
+    // columnar by explicitly replacing the node, but that breaks the connection between the
+    // queryExecution and the AdaptiveSparkPlanExec node that will actually execute.
```
Comment (revans2) [inline sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuOptimisticTransaction.scala:171]: Do we want to explain how it avoids the AQE transition so if that stops working in the future we can understand what is happening? I don't think it will stop, but who knows.

File: sql-plugin/src/main/321+-db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuOptimisticTransactionBase.scala [hunk 2]
```diff
@@ -174,9 +168,21 @@ abstract class GpuOptimisticTransactionBase
...
     val highWaterMarks = trackHighWaterMarks.getOrElse(dataHighWaterMarks)
+
+    // Build a new plan with a stub GpuDeltaWrite node to work around undesired transitions between
+    // columns and rows when AQE is involved. Without this node in the plan, AdaptiveSparkPlanExec
+    // could be the root node of the plan. In that case we do not have enough context to know
+    // whether the AdaptiveSparkPlanExec should be columnar or not, since the GPU overrides do not
+    // see how the parent is using the AdaptiveSparkPlanExec outputs. By using this stub node, the
+    // parent node is present and it will be planned accordingly. We could force the AQE node to be
+    // columnar by explicitly replacing the node, but that breaks the connection between the
+    // queryExecution and the AdaptiveSparkPlanExec node that will actually execute.
```
Comment (revans2) [inline sql-plugin/src/main/321+-db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuOptimisticTransactionBase.scala:182]: Same comment here about explaining how this fixes the issue.

File: sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+ * use this as a workaround for undesired row transitions in the plan when adaptive
+ * execution is enabled. Without it, AdaptiveSparkPlanExec can become the root node
+ * of the physical plan to write into Delta. Without a parent node above
+ * AdaptiveSparkPlanExec, the GPU transition planning does not know whether to make
+ * the result of the adaptive plan GPU columnar or CPU row, so it ends up assuming CPU
+ * row and injecting a columnar-to-row transition at the end of the plan. The Delta
+ * write code cannot directly replace the AdaptiveSparkPlanExec to force it to be
+ * columnar, because it's tied to the QueryExecution which can only be created with
+ * logical plans. Thus our workaround is to inject a node in the logical plan for
+ * the write and ensure the physical node appears to Spark as a write so the
```
Comment (revans2) [inline sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala:52]: Again it might be nice to explain how a "write" stops this from happening. But I think if we only want to explain it in one place, instead of three, then here is the better place to do it.

File: sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+ * root of the plan to write. See the description for RapidsDeltaWrite for details.
+ */
+case class GpuRapidsDeltaWriteExec(child: SparkPlan) extends V2CommandExec
+    with UnaryExecNode with GpuExec {
+  override def output: Seq[Attribute] = child.output
+
+  lazy val basicMetrics: Map[String, SQLMetric] = GpuWriteJobStatsTracker.basicMetrics
+  lazy val taskMetrics: Map[String, SQLMetric] = GpuWriteJobStatsTracker.taskMetrics
+
+  override lazy val allMetrics: Map[String, GpuMetric] =
```
Comment (revans2) [inline sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala:94]: Because we are exposing actual metrics do we want to explain somewhere in the user docs what this node is and that the metrics are not really all that relevant.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+    // DeltaLake, but if we add other custom plan nodes later
+    // their strategies can be appended here.
+    DeltaProvider().getStrategyRules
+  }
+
+  override def apply(plan: LogicalPlan): Seq[SparkPlan] = {
+    val rapidsConf = new RapidsConf(plan.conf)
+    if (rapidsConf.isSqlEnabled && rapidsConf.isSqlExecuteOnGPU) {
+      // Using view since the strategies are first fit.
+      strategies.view.map(_(plan)).find(_.nonEmpty).getOrElse(Nil)
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala:43]: So we apply the first rule to this that node not return Nil, and go with that, and if we cannot find one we return Nil. This feels a little odd. Is this the same thing that Spark does? If so then why is it a Sequence? If not, then why are we different?

**Review by revans2 — COMMENTED** [review]
Just a few nits about documentation and a question about how we are handling the transition strategy API.  It feels a little odd.

File: sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala (hunk 4 above)
Comment (jlowe) [reply sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala:94]: I'll add something to the Delta Lake docs, but why would the metrics be not relevant? These are the same metrics that a typical, non-Delta write shows, and they are updated via the actual write code (see the extra job tracker added in GpuOptimisticTransaction.writeFiles using the metrics from this node).

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala (hunk 5 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala:43]: This is close to what Spark is doing.  See the `GenericStrategy` interface in Spark and Catalyst's `QueryPlanner` has a sequence of strategies that are called in turn.  We have to "play nice" with that, so we have to either match on the plan or return Nil.  I just delegated that to an internal list of strategies since it was complicated to register them all directly with Spark due to classloader issues trying to register them directly with Spark so early in the startup.

The "early out" is something I added since unlike Spark I didn't expect we would have strategies that built on top of the work of our other strategies.  Regarding keeping it a sequence like Spark, I didn't make it a hash map since I wanted to allow for more complicated pattern matching than just a single logical node.  We're not just handing a single node to the strategy, we're handing it the sub-plan starting at that node. However if we don't think we'll ever need anything than one-to-one I could make it a hashmap lookup similar to that used by GpuOverrides.

File: sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala (hunk 4 above)
Comment (revans2) [reply sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala:94]: Where are the metrics getting set?  they are not set here. This is not doing any writes, it just passes the buck on to its child to execute.

`GpuWriteJobStatsTracker.basicMetrics` is a `def` that will eventually call down and produce a map of metrics that calls `create*` to produce the `GpuMetric` instances.  That `create*` is going to produce an ID for each of the metrics. The ID is the critical part to make sure everything lines up so the info from the task ends up tied back the proper node in the SQL graph. For `number of written files` to be updated for the `GpuRapidsDeltaWriteExec` node in SQL UI, the metrics or at least the IDs from `GpuRapidsDeltaWriteExec.allMetrics` must be passed into the operator that actually does the write. If you do manage to make this work, then we should try to make the other node in the tree NOT include the ID, or else some automated tools might get really confused seeing the same metric/ID in two places in the same graph.  Best case it end up double counting some things.

Comment (jlowe) [reply sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala:94]: > Where are the metrics getting set?

They are getting set by the job stats tracker being added to the GpuFileFormat.write call.  See https://github.com/NVIDIA/spark-rapids/pull/7506/files#diff-fa589a4afea438f0bc720a61e640480ccd9a38a3f40050978d3957e740572e6cR246-R250

> The ID is the critical part to make sure everything lines up so the info from the task ends up tied back the proper node in the SQL graph.

Yes, I'm relying on this to tie the metrics being tracked by the added job stats tracker in the GpuFileFormat.write call back to this node in the SQL UI.

> For number of written files to be updated for the GpuRapidsDeltaWriteExec node in SQL UI, the metrics or at least the IDs from GpuRapidsDeltaWriteExec.allMetrics must be passed into the operator that actually does the write.

That's what's happening in the code I linked to above.

> If you do manage to make this work, then we should try to make the other node in the tree NOT include the ID,

What other node?  Delta write normally does not appear at all in a SQL plan, it's hidden as part of some larger operation, like a SaveIntoDataSourceCommand or MergeIntoDelta, that appears in a completely different SQL plan that executes this plan as a sub-plan.  Those outer-plan nodes have their own separate metrics with their own separate IDs.  That's why I added a whole new stats tracker to the write instead of overwriting/reusing an existing one.

File: sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuOptimisticTransaction.scala (hunk 1 above)
Comment (jlowe) [reply sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuOptimisticTransaction.scala]: I updated this and the other places, along with updating the Delta Lake support docs to mention the new, custom node.  I didn't elaborate on the workaround nature of the node in the user docs since I thought that would be too much information, and IMO the node justifies itself with the ability to see stats just on the write rather than stats that include the write along with a bunch of other stuff (i.e.: the stats on the higher-level SQL operation that runs this plan as part of it).

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala (hunk 4 above)
Comment (revans2) [reply sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala:95]: Okay so long as you have tested this and are sure that it is working.

**Review by revans2 — APPROVED** [review]
