### PR TITLE
Persist the bufConverter of TypedImperativeAggregate into LogicalPlan instead of PhysicalPlan [databricks]

### LINKED ISSUE #13820: [BUG] NullPointerException - aggregate.TypedImperativeAggregate.merge when final agg on CPU
**Describe the bug**
Customer hit a bug where the partial agg was on the GPU and the final was on the CPU.

The code threw an exception:

```
Py4JJavaError: An error occurred while calling o248.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 56.0 failed 4 times, most recent failure: Lost task 0.3 in stage 56.0 (TID 635) (100.68.107.117 executor 4): java.lang.NullPointerException
	at org.apache.spark.sql.catalyst.expressions.aggregate.Collect.deserialize(collect.scala:81)
	at org.apache.spark.sql.catalyst.expressions.aggregate.Collect.deserialize(collect.scala:39)
	at org.apache.spark.sql.catalyst.expressions.aggregate.TypedImperativeAggregate.merge(interfaces.scala:589)
	at org.apache.spark.sql.execution.aggregate.AggregationIterator$$anonfun$1.$anonfun$applyOrElse$3(AggregationIterator.scala:200)
	at org.apache.spark.sql.execution.aggregate.AggregationIterator$$anonfun$1.$anonfun$applyOrElse$3$adapted(AggregationIterator.scala:200)
	at org.apache.spark.sql.execution.aggregate.AggregationIterator.$anonfun$generateProcessRow$7(AggregationIterator.scala:214)
	at org.apache.spark.sql.execution.aggregate.AggregationIterator.$anonfun$generateProcessRow$7$adapted(AggregationIterator.scala:208)
	at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.processInputs(ObjectAggregationIterator.scala:170)
	at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.<init>(ObjectAggregationIterator.scala:84)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$1(ObjectHashAggregateExec.scala:114)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$1$adapted(ObjectHashAggregateExec.scala:90)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:880)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:880)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
```

Plan:

GpuCustomShuffleReader -> GpuShuffleCoalesce->GpuColumnarToRow -> ObjectHashAggregate -> GpuRowToColumnar ->GpuBroadcastExchange

The issue looks like we aren't inserting the gputocpucollectbuffer transition 

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by sperlingxx**
Fixes #13820

This PR attempts to fix the subtle issue (#13820) of failing to convert aggregate buffers of `TypedImperativeAggregate` from CPU/GPU to the counterpart when AQE is enabled. Specifically, this bug is due to agg buffer converters, which are inserted into `SparkPlan` as `TreeNodeTag`, will be lost if the re-optimize of AQE takes effect (by then, the plan will be totally rebuilt on the top of the new logical plan).

This PR modifies insertion/extraction of aggregate buffer converters under AQE: bind them to the related logical plan instead of physical plan. Since single logical aggregate refers to AggregateExec of multiple stages, "stage mask" is also injected along with the buffer converters as the signature of the certain aggregate stage. The "stage mask" is computed from the distinct aggregate modes of all aggregate functions, which is light-weight and reliable:
```scala
    plan match {
      case aggExec: BaseAggregateExec =>
        aggExec.aggregateExpressions.foldLeft(0) { (mask, expr) =>
          val modeBit = expr.mode match {
            case Partial => 1
            case PartialMerge => 2
            case Final => 4
            case Complete => 8
          }
          mask | modeBit
        }
      case _ => 0
    }
```

This PR also adds a specific test case, which stimulates the scenario of #13820 through the unimplemented high-order function `forall`, regarding the function `map_from_entries` leaded to #13820 has been supported by #13806

### CODE REVIEW

**Comment by sperlingxx** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala [hunk 1]
```diff
@@ -1644,19 +1654,105 @@ object GpuTypedImperativeSupportedAggregateExecMeta {
...
+   */
+  private def insertBufferConverter(plan: SparkPlan,
+      expr: Seq[NamedExpression], isR2C: Boolean): Unit = {
+    val tag: TreeNodeTag[TypedAggBufConverter] = bufConverterTag(isR2C)
+    if (!plan.conf.adaptiveExecutionEnabled) {
+      plan.setTagValue(tag, (expr, 0))
+    } else {
+      plan.logicalLink match {
+        case Some(logicalPlan) =>
+          logicalPlan.setTagValue(tag, (expr, aggregateStageMask(plan)))
```
[the remark this answers is not in the document]
Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1692]: Physical aggregate plans from different stages cannot share the same mask. This is because masks are determined by the distinct aggregate mode, which by definition must be different across stages

**Comment by sperlingxx** [comment]
build

**Comment by sperlingxx** [comment]
build

File: integration_tests/src/main/python/hash_aggregate_test.py [hunk 2]
```diff
@@ -1120,6 +1120,72 @@ def test_hash_groupby_collect_partial_replace_fallback(data_gen,
...
+@allow_non_gpu('ObjectHashAggregateExec', 'SortAggregateExec',
+               'ShuffleExchangeExec', 'HashPartitioning', 'SortExec',
+               'SortArray', 'Alias', 'Literal', 'Count', 'CollectList', 'CollectSet',
+               'AggregateExpression', 'ProjectExec', *non_utc_allow)
+@pytest.mark.parametrize('data_gen', [[
+    ('k1', RepeatSeqGen(LongGen(), length=100)),
+    ('k2', RepeatSeqGen(LongGen(), length=20)),
+    ('v', StringGen(nullable=False))]], ids=idfn)
+@pytest.mark.parametrize('use_obj_hash_agg', ['false', 'true'], ids=idfn)
+@pytest.mark.parametrize("kudo_enabled", ["true", "false"], ids=idfn)
```
Comment (firestarman) [inline integration_tests/src/main/python/hash_aggregate_test.py]: Personally, only the default setting is good enough here for kudo.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala [hunk 3]
```diff
@@ -1644,19 +1654,105 @@ object GpuTypedImperativeSupportedAggregateExecMeta {
...
         }
       case _ =>
     }
   }
 
+  /**
+   * Insert buffer converters into the given plan as TreeNodeTags, so that these converters
+   * can be retrieved later during GpuTransitionOverrides to fill the gap between CPU and GPU
+   * aggregation buffers.
+   * For non-AQE mode, we can directly bind the converters to the given plan.
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1678]: Is it possible we always use the logical plan way, regardless of AQE mode ?

Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1678]: Why using logical plans work here? These tags will be copied to the physical plans ?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala [hunk 4]
```diff
@@ -1644,19 +1654,105 @@ object GpuTypedImperativeSupportedAggregateExecMeta {
...
+  private def insertBufferConverter(plan: SparkPlan,
+      expr: Seq[NamedExpression], isR2C: Boolean): Unit = {
+    val tag: TreeNodeTag[TypedAggBufConverter] = bufConverterTag(isR2C)
+    if (!plan.conf.adaptiveExecutionEnabled) {
+      plan.setTagValue(tag, (expr, 0))
+    } else {
+      plan.logicalLink match {
+        case Some(logicalPlan) =>
+          logicalPlan.setTagValue(tag, (expr, aggregateStageMask(plan)))
+        case None => // logicalLink is guaranteed to be present normally
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1693]: Why is this guaranteed ? A limit plan set the input plan can be ?

Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1693]: Since I saw line 1751 allows None when reading a tag back.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala [hunk 5]
```diff
@@ -50,21 +51,19 @@ class GpuTransitionOverrides extends Rule[SparkPlan] {
...
       GpuColumnarToRowExec(optimizeGpuPlanTransitions(bb.child))
-    // inserts postColumnarToRowTransition into newly-created GpuColumnarToRowExec
-    case p if p.getTagValue(GpuOverrides.postColToRowProjection).nonEmpty =>
-      val c2r = p.children.map(optimizeGpuPlanTransitions).head.asInstanceOf[GpuColumnarToRowExec]
-      val newChild = p.getTagValue(GpuOverrides.postColToRowProjection).map { exprs =>
-        ProjectExec(exprs, c2r)
-      }.getOrElse(c2r)
-      p.withNewChildren(Array(newChild))
-    case p =>
+    case p if p.children.size == 1 => // single child case
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala]: Will we miss any cases due to the condition change from tag-only to the child size ?

File: integration_tests/src/main/python/hash_aggregate_test.py (hunk 2 above)
Comment (sperlingxx) [reply integration_tests/src/main/python/hash_aggregate_test.py]: Removed the optional argument.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala (hunk 4 above)
Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1693]: It is supposed to mean that as for a normal `SparkPlan`, the `SparkPlan.logicalLink` should NOT be None since Spark SQL set the logicalLink explicitly.

**Comment by sperlingxx** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala (hunk 3 above)
Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1678]: I think it is possible to use logical plan for all cases, while it costs more efforts to compute and compare the stage mask to distinguish the AggregateExec of different stages. Therefore, tries to use Physical Plan if possible at here.

Why Logical Plan works? Because tags saved in logical plan will be preserved even if a re-optimize occurs: https://github.com/apache/spark/blob/branch-3.5/sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala#L351  New physical plan has no connection with the former one, but connecting with the former logical plan. In addition, the transformation of logical plan copies the Tag: https://github.com/apache/spark/blob/branch-3.5/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/trees/TreeNode.scala#L475

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala (hunk 4 above)
Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1693]: So the input plan should be processed by the planner ? what if a plan is not. e.g. We create one manually. For example, a [GpuFilteExec is created if the filterCondition is defined](https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala#L71). Then no logicalLink for this case i think.

Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala:1693]: @firestarman The injections is based on the `wrapped` plan of `SparkPlanMeta`, which means CPU plans.

**Comment by sperlingxx** [comment]
build

**Comment by sperlingxx** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala (hunk 5 above)
Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala]: How about this ?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala [hunk 6]
```diff
@@ -1644,19 +1654,105 @@ object GpuTypedImperativeSupportedAggregateExecMeta {
           // GpuRowToColumnarExec
           case List(parent, child) if parent.canThisBeReplaced =>
             val childPlan = child.wrapped.asInstanceOf[SparkPlan]
-            val expressions = createBufferConverter(stages(i), stages(i + 1), true)
-            childPlan.setTagValue(GpuOverrides.preRowToColProjection, expressions)
+            val expressions = createBufferConverter(stages(i), stages(i + 1),
+              fromCpuToGpu = true)
+            // Insert the converter into childPlan as a tag value
+            insertBufferConverter(childPlan, expressions, isR2C = true)
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala]: NIT: It would be nice to unify the argument name, i mean `isR2C` -> `fromCpuToGpu`.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala (hunk 5 above)
Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala]: Hi @firestarman, the `optimizeGpuPlanTransitions` applies on plans of each level recursively. And here we just need to check the plan whose child is `GpuColumnarToRowExec`.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala (hunk 6 above)
Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala]: Good idea. Done.

**Review by firestarman — APPROVED** [review]

**Comment by sperlingxx** [comment]
build
