### PR TITLE
Fix bug that can not switch Alluxio auto-mount option on the fly

### LINKED ISSUE #6856: [BUG] Can not switch Alluxio auto-mount option on the fly
**Describe the bug**

Some code paths did the initialization if the auto-mount is false.

**Steps/Code to reproduce bug**

set `spark.rapids.alluxio.automount.enabled` as false on start time.

First run
```
spark.conf.set("spark.rapids.sql.enabled", "true")
spark.conf.set("spark.rapids.alluxio.replacement.algo", "CONVERT_TIME")
spark.read.parquet("s3a://liangcail/chongg-test").count()
```

Second run
```
spark.conf.set("spark.rapids.sql.enabled", "true")
spark.conf.set("spark.rapids.alluxio.automount.enabled", "true")  //Note set auto-mount
spark.conf.set("spark.rapids.alluxio.replacement.algo", "CONVERT_TIME")

spark.read.parquet("s3a://liangcail/chongg-test").count()
```

Reports error:
AssertionError: assertion failed
code is: assert(alluxioMasterHost.isDefined)

**Additional context**
databricks 321 with alluxio support.

See [code](https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala#L157-L191)
```
      if (!isInit) {
        if (conf.getAlluxioAutoMountEnabled) {
            ......
        } else {
          alluxioPathsToReplaceMap = getReplacementMapOption(conf)
        }
        isInit = true
```

One `isInit` variable controls auto-mount and replace-map 2 types.

[Code](https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala#L143-L144)
```
              if (conf.isAlluxioReplacementAlgoConvertTime) {
                AlluxioUtils.replacePathIfNeeded(
```
The convert-time setting will invoke the `init` via  `replacePathIfNeeded`, and then set `isInit = true`

Should also update the doc.
      "This config should be enabled when initially starting the application but it " +
      "can be turned off and one programmatically after that.")

### PR DESCRIPTION
**Pull request by res-life**
Fixes #6856 

### Bug root cause
If set auto-mount as false and set CONVERT_TIME,  will invoke the `init` via replacePathIfNeeded, and then set `isInit = true`, then the `init` will never invoke again.
The second query with auto-mount as true will run into an `assert` error because `alluxioMasterHost` is None

[See Code](https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala#L143-L144)
```
              if (conf.isAlluxioReplacementAlgoConvertTime) {
                AlluxioUtils.replacePathIfNeeded(

```

See [code](https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala#L157-L191)
```
init method:
     if (!isInit) {
        if (conf.getAlluxioAutoMountEnabled) {
            ......
            alluxioMasterHost = some(...)
        } else {
          alluxioPathsToReplaceMap = getReplacementMapOption(conf)
        }
        isInit = true
```
We can see that one `isInit` variable controls auto-mount and replace-map 2 types.

### solution

- Use 2 init flags, one for auto-mount, one for replace-map
- Reverse the order of init replace-map and init auto-mount, because the doc says:
```
val ALLUXIO_PATHS_REPLACE = conf("spark.rapids.alluxio.pathsToReplace")
......
If you set this config, spark.rapids.alluxio.automount.enabled won't be valid
```
- Also check if auto-mount or replace-map is enabled in `isAlluxioReplacementAlgoConvertTime` and rename `isAlluxioReplacementAlgoConvertTime` to `enabledAlluxioReplacementAlgoConvertTime`
- Change alluxio bucket regexp to startup time config

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
To be tested, the test flow is somehow time-consuming:
Start databricks cluster to build -> upload jar to s3 -> download to local -> make docker -> upload docker -> start  databricks cluster to test.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala [hunk 1]
```diff
@@ -154,8 +156,15 @@ object AlluxioUtils extends Logging {
       alluxioCmd = conf.getAlluxioCmd
       checkAlluxioNotSupported(conf)
 
-      if (!isInit) {
-        if (conf.getAlluxioAutoMountEnabled) {
+      if (isConfiguredReplacementMap(conf)) {
+        // replace-map is enabled, if set this will invalid the auto-mount
+        if (!isInitReplaceMap) {
+          alluxioPathsToReplaceMap = getReplacementMapOption(conf)
```
Comment (tgravescs) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala:162]: so this also means that the replacement map can't be change during runtime, which is fine but might want to document.  It would be weird to change during runtime anyway since user has to mount them

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala [hunk 2]
```diff
@@ -154,8 +156,15 @@ object AlluxioUtils extends Logging {
...
+          isInitReplaceMap = true
+        }
+      } else if (conf.getAlluxioAutoMountEnabled) {
+        // auto-mound is enabled
```
Comment (tgravescs) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala:166]:
```suggestion
        // auto-mount is enabled
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala [hunk 3]
```diff
@@ -154,8 +156,15 @@ object AlluxioUtils extends Logging {
...
+        if (!isInitMountPointsForAutoMount) {
```
Comment (tgravescs) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala:167]: similar comment here, since we do initialization once we can't change the bucket regex at run time and have it work.  This is fine just might want to comment on it.   @GaryShen2008

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
2 commits:
more check on whether convert time algo is enabled, should also check if auto-mount or replace-map is enabled.
change alluxio bucket regexp to startup time config

**Comment by res-life** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala (hunk 2 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala]: Done

**Comment by res-life** [comment]
build failed because of https://github.com/NVIDIA/spark-rapids/issues/6869

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
build
