### PR TITLE
Fix crash when casting decimals to long

### LINKED ISSUE #6128: [BUG] Can not ansi cast decimal type to long type while fetching decimal column from data table
**Describe the bug**
Cudf Exception thrown when trying to cast decimal to long

**Steps/Code to reproduce bug**
```
spark.conf.set("spark.sql.ansi.enabled", true)
val df = Seq(222.22, 777.77).toDF("f")
val df2 = df.repartition(1).selectExpr("cast(f as decimal(5,2))")
val df3 = df2.repartition(1).selectExpr("cast(f as long)")
df3.show
```

```
Caused by: ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-pre_release-29-cuda11/thirdparty/cudf/cpp/src/binaryop/binaryop.cpp:205: Unsupported operator for these types
  at ai.rapids.cudf.ColumnView.binaryOpVS(Native Method)
  at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:1254)
  at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:1244)
  at ai.rapids.cudf.BinaryOperable.lessThan(BinaryOperable.java:277)
  at ai.rapids.cudf.BinaryOperable.lessThan(BinaryOperable.java:284)
  at com.nvidia.spark.rapids.GpuCast$.$anonfun$assertValuesInRange$3(GpuCast.scala:641)
```
**Expected behavior**
The script should not throw an exception

### PR DESCRIPTION
**Pull request by razajafri**
This PR avoids type mismatch that can occur if the min/max decimal values are a different precision than the column being casted in ANSI mode.

e.g. 
Casting 222.22 to long will result in a call to check to see the values are in range before converting them to long values. That check will cause a crash as the minimum value possible in decimal(5,2) will result in a Decimal 128 value and the `assertValuesInRange` method in `GpuCast` will result in a type mismatch error from cudf when it calls `lessThan`.

@ttnghia Suggested a way around this is to first find the minimum value in the input column and compare that value to the decimal 128 value using a Java `BigDecimal.compareTo` which can handle comparing Decimals of different precisions. 

fixes #6128

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 1]
```diff
@@ -378,11 +378,18 @@ object GpuCast extends Arm {
...
         // This is a work around for https://github.com/rapidsai/cudf/issues/9282
-        val min = BigDecimal(Long.MinValue)
+        val bigDecimalMin = BigDecimal(Long.MinValue)
             .setScale(dt.scale, BigDecimal.RoundingMode.DOWN).bigDecimal
-        val max = BigDecimal(Long.MaxValue)
+        val bigDecimalMax = BigDecimal(Long.MaxValue)
             .setScale(dt.scale, BigDecimal.RoundingMode.DOWN).bigDecimal
-        assertValuesInRange(input, Scalar.fromDecimal(min), Scalar.fromDecimal(max))
+        withResource(input.min()) { min =>
+          withResource(input.max()) { max =>
```
Comment (ttnghia) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:386]: `min` or `max` should be just a number, right? So we won't need to wrap them.

Comment (abellina) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:386]: This is not just a number, it is a `Scalar` object (https://github.com/rapidsai/cudf/blob/branch-22.08/java/src/main/java/ai/rapids/cudf/Scalar.java#L35), so it has to be closed.

**Comment by tgravescs** [comment]
it would be nice to have an issue associated with this that describes the problem and reproducing it

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 2]
```diff
@@ -378,11 +378,18 @@ object GpuCast extends Arm {
...
+            if (min.getBigDecimal().compareTo(bigDecimalMin) == -1 ||
+                max.getBigDecimal().compareTo(bigDecimalMax) == 1) {
+              throw new IllegalStateException(GpuCast.INVALID_INPUT_MESSAGE)
```
Comment (tgravescs) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:389]: this same thing throws in Spark on Cpu?

Comment (amahussein) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:389]: Maybe we need to add an integration test to compare?

File: tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala [hunk 3]
```diff
@@ -466,6 +466,11 @@ class AnsiCastOpSuite extends GpuExpressionTestSuite {
     }
   }
 
+  testSparkResultsAreEqual("ansi_cast decimals to long",
+    generateValidValuesDecimalDF(Short.MinValue, Short.MaxValue, 18, 3), sparkConf) {
+    frame => testCastTo(DataTypes.LongType)(frame)
+  }
+
```
Comment (amahussein) [inline tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala:473]: Is it possible to test that we actually throw the expected exception?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 2 above)
Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: > this same thing throws in Spark on Cpu?

CPU throws an ArithmeticException but I wanted to match the existing behavior. I have changed it to match the CPU. 

> Maybe we need to add an integration test to compare?

Just adding an integration test to for a handful of values or testing a wider range? I experimented with this and it will be a lot more involved test as there are many other types of exceptions that can be thrown in ANSI e.g. overflow

File: tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala (hunk 3 above)
Comment (razajafri) [reply tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala:473]: This test is only for the valid values. May be I need to add a test that tests just that an exception is thrown?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 4]
```diff
@@ -378,11 +378,18 @@ object GpuCast extends Arm {
...
       case (dt: DecimalType, LongType) if ansiMode =>
         // This is a work around for https://github.com/rapidsai/cudf/issues/9282
-        val min = BigDecimal(Long.MinValue)
+        val bigDecimalMin = BigDecimal(Long.MinValue)
             .setScale(dt.scale, BigDecimal.RoundingMode.DOWN).bigDecimal
-        val max = BigDecimal(Long.MaxValue)
+        val bigDecimalMax = BigDecimal(Long.MaxValue)
             .setScale(dt.scale, BigDecimal.RoundingMode.DOWN).bigDecimal
-        assertValuesInRange(input, Scalar.fromDecimal(min), Scalar.fromDecimal(max))
+        withResource(input.min()) { min =>
```
[the remark this answers is not in the document]
Comment (ttnghia) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:388]: In fact, the `assertValuesInRange` function is inefficient: It calls `less` operator then `any` then `greater` then `any`, and all these operations are `O(N)`. We can achieve the result by half of computation by using this new approach: `min` then `max` in `O(N)` then compare the min/max values with the boundary in `O(1)`.

[the remark this answers is not in the document]
Comment (ttnghia) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:388]: I've filed a corresponding issue: https://github.com/NVIDIA/spark-rapids/issues/6130

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 1 above)
Comment (ttnghia) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:389]: If it is scalar then we may want to call `isValid` to check the min and max values.

**Review by tgravescs — APPROVED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 5]
```diff
@@ -378,11 +378,21 @@ object GpuCast extends Arm {
       // ansi cast from larger-than-long integral-like types, to long
       case (dt: DecimalType, LongType) if ansiMode =>
         // This is a work around for https://github.com/rapidsai/cudf/issues/9282
-        val min = BigDecimal(Long.MinValue)
+        val bigDecimalMin = BigDecimal(Long.MinValue)
             .setScale(dt.scale, BigDecimal.RoundingMode.DOWN).bigDecimal
-        val max = BigDecimal(Long.MaxValue)
+        val bigDecimalMax = BigDecimal(Long.MaxValue)
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:383]: bigDecimalMax/Min are not minimums of BigDecimal,  the names are confusing. The conversion from long is probably non-trivial, might be worthwhile to make these class vals

**Review by gerashegalov — CHANGES_REQUESTED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 5 above)
Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:383]: The `BigDecimal` will have to be re-scaled and most of the calculation is done in that method. I am not sure what we will gain by just making a `BigDecimal(Long.MIN)` as a class val. I can still do it but I just wanted to make sure I was understanding you correctly.

**Comment by razajafri** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 5 above)
Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: Are we gaining anything by keeping recomputing the constants like `BigDecimal(Long.MaxValue)`?

If nothing else it's a bunch of unnecessary object allocations

https://github.com/scala/scala/blob/2.12.x/src/library/scala/math/BigDecimal.scala#L211
https://github.com/frohoff/jdk8u-dev-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/share/classes/java/math/BigDecimal.java#L1217-L1223
https://github.com/frohoff/jdk8u-dev-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/share/classes/java/math/BigDecimal.java#L1217-L1223

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 2 above)
Comment (amahussein) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: I can imagine that this will be the case for other cast operations.
If we do not have integration tests to cover the behavior of CPU vs GPU, then we can create a new followup issue to improve the tests including the "Decimal to Long".

File: tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala (hunk 3 above)
Comment (amahussein) [reply tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala:473]: We won't need to have a new case as you are throwing the same exception because this will be covered in `testCastFailsForBadInputs("ansi_cast overflow decimals to longs",..)`.
If we change the behavior to match the CPU, then we would need a new test.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 5 above)
Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: Note `BigDecimal` instances are just like `Integer` immutable. So `setScale` will produce another object

Comment (amahussein) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: It is a valid argument depending on how frequent casting Decimals to Longs is done in a workload. The other concern is using static/constants increases the footprint of the VM and slows down the initialization.
Anyway, if this is going to be addressed within the same PR, then I suggest to create constants in a `util` to be used in different classes.
The repo has two other locations that use constants BigDecimal.
in arithemtic.scala there are two local variables 
```
 val zero = BigDecimal(0).bigDecimal
```
Then we can create three constants `BigDecimal(0).bigDecimal`, BigDecimal(Long.MaxValue), and BigDecimal(Long.MinValue)

All other constant BigDecimals are in test classes which we can ignore.

Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: Can we please handle creating of the util class in a separate PR?

Comment (amahussein) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: I agree it is fair. Both `BigDecimal(Long.MaxValue)`, and `BigDecimal(Long.MinValue)` were not introduced in this PR.

File: tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala (hunk 3 above)
Comment (razajafri) [reply tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala:473]: OK, then that test is already testing the exception that is thrown.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 5 above)
Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: I think we don't have yet to worry about the constant pool because of the two constants being added. We can do a more sweeping refactoring in a separate PR.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 2 above)
Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala]: +1 for adding a test to make sure that we are not regressing on the exception.

**Review by gerashegalov — DISMISSED** [review]
LGTM but would be great to see this case be validated against  CPU
https://github.com/NVIDIA/spark-rapids/pull/6103/files#diff-e981882f5ee2f922528de849ae5397dd30e5bfe9dd5fdbe3421de4733a0eae1aR392

**Review by amahussein — APPROVED** [review]
LGTM.

A minor styling issue is to have constants in capital letters.
I am not sure that we have a clear formatting rule for this, but it looks like all the constants in GpuCast in capital letters.

**Comment by razajafri** [comment]
build

**Review by amahussein — APPROVED** [review]
Thanks Raza!

LGTM.

**Review by ttnghia — APPROVED** [review]

**Comment by sameerz** [comment]
build

**Review by revans2 — APPROVED** [review]
