### PR TITLE
Fix a special case in limit where it could return an empty batch with the wrong number of columns

### LINKED ISSUE #13914: [BUG] An empty table  `crossJoin`  another table brings errors on the GPU engines
**Describe the bug**
An error (requirement failed: Rows-only broadcast resolved had non-empty output c1#18) occurred when an empty table `crossJoin` another table reading from the csv file on the GPU engines.

**Steps/Code to reproduce bug**
```python
import os
os.environ['JAVA_HOME'] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ['SPARK_HOME'] = "./spark-4.0.1-bin-hadoop3"
os.environ['PYSPARK_SUBMIT_ARGS'] = "--jars ./rapids-4-spark_2.13-25.10.0.jar,./cudf-25.10.0-cuda12.jar --master local[*] pyspark-shell"

import findspark
findspark.init()
from pyspark.sql import SparkSession
from pyspark.conf import SparkConf
from pyspark.sql import functions as F

spark = SparkSession.builder.appName('SparkRAPIDS').config('spark.plugins','com.nvidia.spark.SQLPlugin').config("spark.executor.memory", "8g").config("spark.driver.memory", "8g").getOrCreate()
spark.sparkContext.addPyFile('./rapids-4-spark_2.13-25.10.0.jar')
spark.sparkContext.addPyFile('./cudf-25.10.0-cuda12.jar')
spark.conf.set('spark.rapids.sql.incompatibleOps.enabled', 'true')
spark.conf.set('spark.rapids.sql.format.csv.read.enabled', 'true')
spark.conf.set('spark.rapids.sql.format.csv.enabled', 'true')
spark.conf.set("spark.executor.resource.gpu.amount", "1")
spark.conf.set("spark.task.resource.gpu.amount", "1")
spark.conf.set("spark.rapids.sql.concurrentGpuTasks", "1")
spark.conf.set("spark.rapids.sql.exec.CollectLimitExec", "true")
spark.conf.set('spark.rapids.sql.enabled', 'false')

df = spark.read.csv("t0.csv", header=True, inferSchema=True)
df.createOrReplaceTempView("t0")
df = spark.read.csv("t1.csv", header=True, inferSchema=True)
df.createOrReplaceTempView("t1")

print("CPU:")
cpu_result = spark.table('t0').crossJoin(spark.table('t1')).select(F.col('c1'))
cpu_result.show(truncate=False)

spark.conf.set('spark.rapids.sql.enabled', 'true')
print("GPU:")
gpu_result = spark.table('t0').crossJoin(spark.table('t1')).select(F.col('c1'))
gpu_result.show(truncate=False)
```
t0.csv:
```bash
c0,c1

```
t1.csv:
```bash
c0
true

```
```bash
CPU:
+---+
|c1 |
+---+
+---+

GPU:
Traceback (most recent call last):
  File "/xxx/bug.py", line 41, in <module>
    gpu_result.show(truncate=False)
  File "/xxx/../library/spark-4.0.1-bin-hadoop3/python/pyspark/sql/classic/dataframe.py", line 285, in show
    print(self._show_string(n, truncate, vertical))
  File "/xxx/../library/spark-4.0.1-bin-hadoop3/python/pyspark/sql/classic/dataframe.py", line 316, in _show_string
    return self._jdf.showString(n, int_truncate, vertical)
  File "../library/spark-4.0.1-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1362, in __call__
  File "/xxx/../library/spark-4.0.1-bin-hadoop3/python/pyspark/errors/exceptions/captured.py", line 288, in deco
    raise converted from None
pyspark.errors.exceptions.captured.IllegalArgumentException: requirement failed: Rows-only broadcast resolved had non-empty output c1#18
```

**Expected behavior**
No error occurs when using the GPU engines.
The result is consistent when using the CPU and GPU engines.

**Environment details (please complete the following information)**
 - Environment location: Standalone
 - Spark configuration settings related to the issue:
       java-17-openjdk-amd64
      spark-4.0.1-bin-hadoop3
      rapids-4-spark_2.13-25.10.0
      cudf-25.10.0-cuda12

**Additional context**

### PR DESCRIPTION
**Pull request by revans2**
This Fixes #13914

### Description

The code was wrong, but not so wrong that unless we broadcast the empty batch it would probably just be filtered out and ignored.

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [X] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala [hunk 1]
```diff
@@ -71,7 +70,10 @@ class GpuBaseLimitIterator(
     // If the last batch is null, then we have offset >= numRows in this partition.
     // In such case, we should return an empty batch
     if (batch == null || batch.numRows() == 0) {
-      return new ColumnarBatch(new ArrayBuffer[GpuColumnVector](numCols).toArray, 0)
+      val fields = dataTypes.zipWithIndex.map {
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala:73]: nit, since we only use `dataTypes` in this corner case, should we move the creation of this array inside of this if statement?

**Comment by revans2** [comment]
@abellina please take another look

**Comment by revans2** [comment]
build
