### PR TITLE
Fix issues with AQE and DPP enabled on Spark 3.2 [databricks]

### LINKED ISSUE #3653: [BUG] Issue seen with AQE on in Q5 (possibly others) using Spark 3.2 rc3
I can get the full stack trace, will take me a while, but I know that with AQE off we get way further in the query:

sorry a bit long:

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.nvidia.spark.rapids.AvoidAdaptiveTransitionToRow.doExecuteColumnar(GpuTransitionOverrides.scala:621)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:211)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:207)
        at org.apache.spark.sql.rapids.GpuFileFormatWriter$.write(GpuFileFormatWriter.scala:199)
        at org.apache.spark.sql.rapids.GpuInsertIntoHadoopFsRelationCommand.runColumnar(GpuInsertIntoHadoopFsRelationCommand.scala:166)
        at com.nvidia.spark.rapids.GpuDataWritingCommandExec.sideEffectResult$lzycompute(GpuDataWritingCommandExec.scala:97)
        at com.nvidia.spark.rapids.GpuDataWritingCommandExec.sideEffectResult(GpuDataWritingCommandExec.scala:96)
        at com.nvidia.spark.rapids.GpuDataWritingCommandExec.doExecuteColumnar(GpuDataWritingCommandExec.scala:120)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:211)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:207)
        at com.nvidia.spark.rapids.GpuColumnarToRowExecParent.doExecute(GpuColumnarToRowExec.scala:301)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:184)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:180)
        at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:325)
        at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:391)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
        at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:128)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:848)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:382)
        at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:355)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239)
        at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:781)
        at com.nvidia.spark.rapids.tests.common.BenchUtils$.$anonfun$runBench$1(BenchUtils.scala:227)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at com.nvidia.spark.rapids.tests.common.BenchUtils$.runBench(BenchUtils.scala:189)
        at com.nvidia.spark.rapids.tests.common.BenchUtils$.writeParquet(BenchUtils.scala:143)
        at com.nvidia.spark.rapids.tests.BenchmarkRunner.writeParquet(BenchmarkRunner.scala:341)
        at com.nvidia.spark.rapids.tests.BenchmarkRunner$.$anonfun$main$3(BenchmarkRunner.scala:97)
        at scala.util.Try$.apply(Try.scala:213)
        at com.nvidia.spark.rapids.tests.BenchmarkRunner$.$anonfun$main$1(BenchmarkRunner.scala:86)
        at com.nvidia.spark.rapids.tests.BenchmarkRunner$.$anonfun$main$1$adapted(BenchmarkRunner.scala:81)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at com.nvidia.spark.rapids.tests.BenchmarkRunner$.main(BenchmarkRunner.scala:81)
        at com.nvidia.spark.rapids.tests.BenchmarkRunner.main(BenchmarkRunner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
        at org.apache.spark.sql.execution.SubqueryBroadcastExec.executeCollect(SubqueryBroadcastExec.scala:113)
        at org.apache.spark.sql.execution.InSubqueryExec.updateResult(subquery.scala:127)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$waitForSubqueries$1(SparkPlan.scala:252)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$waitForSubqueries$1$adapted(SparkPlan.scala:251)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.sql.execution.SparkPlan.waitForSubqueries(SparkPlan.scala:251)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:221)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:207)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.inputBatchRDD$lzycompute(GpuShuffleExchangeExecBase.scala:194)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.inputBatchRDD(GpuShuffleExchangeExecBase.scala:194)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBaseWithMetrics.mapOutputStatisticsFuture$lzycompute(GpuShuffleExchangeExecBase.scala:137)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBaseWithMetrics.mapOutputStatisticsFuture(GpuShuffleExchangeExecBase.scala:136)
        at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.$anonfun$submitShuffleJob$1(ShuffleExchangeExec.scala:68)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
        at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.submitShuffleJob(ShuffleExchangeExec.scala:68)
        at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.submitShuffleJob$(ShuffleExchangeExec.scala:67)
        at com.nvidia.spark.rapids.shims.v2.GpuShuffleExchangeExec.submitShuffleJob(GpuShuffleExchangeExec.scala:26)
        at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.shuffleFuture$lzycompute(QueryStageExec.scala:170)
        at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.shuffleFuture(QueryStageExec.scala:170)
        at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.doMaterialize(QueryStageExec.scala:172)
        at org.apache.spark.sql.execution.adaptive.QueryStageExec.materialize(QueryStageExec.scala:82)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$5(AdaptiveSparkPlanExec.scala:256)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$5$adapted(AdaptiveSparkPlanExec.scala:254)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$1(AdaptiveSparkPlanExec.scala:254)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.getFinalPhysicalPlan(AdaptiveSparkPlanExec.scala:226)
        ... 78 more
Caused by: java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:208)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$doExecuteBroadcast$1(AdaptiveSparkPlanExec.scala:359)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:366)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.doExecuteBroadcast(AdaptiveSparkPlanExec.scala:358)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:197)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
        at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:193)
        at org.apache.spark.sql.execution.SubqueryBroadcastExec.$anonfun$relationFuture$2(SubqueryBroadcastExec.scala:81)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:139)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:137)
        at org.apache.spark.sql.execution.SubqueryBroadcastExec.$anonfun$relationFuture$1(SubqueryBroadcastExec.scala:78)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        ... 5 more
```

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #3653.

This fixes a number of issues with `GpuBroadcastToCpuExec`.  In Spark 3.2+, there's an assert to verify that the child of an `AdaptiveSparkPlanExec` is a `BroadcastQueryStageExec` if it tries to compute the broadcast.  The transition plans would place `GpuBroadcastToCpuExec` immediately under `AdaptiveSparkPlanExec` which triggered the assert.

Unfortunately creating a new `BroadcastQueryStageExec` instance requires shimming, since the signature of `BroadcastQueryStageExec` has changed across Spark versions.  Newer versions require a canonicalized plan parameter, so I needed to add a shim method to create a new instance given an old one and a new child to place underneath.

Besides fixing that assert, there was also a mishandling of the broadcast data in `GpuBroadcastToCpuExec`.  The code assumed that `ColumnarBatch.rowIterator` would return a unique row per iteration, but it returns _the same row object instance_ for each iteration and mutates that object's internal state to produce the proper row when the row's data is requested.  The code was producing an array of `InternalRow` without manifesting the data from the row, which caused each entry to be the same `ColumnarBatchRow` instance, pointing at the last row of data.  In addition the `UnsafeRow` instances were being reused in a similar manner.  The fix is to not force the internal rows to manifest in an array until they are being converted to an unsafe row, and when converting we need to make a copy of each unsafe row.

One last issue, which ended up being the majority of the change in this PR, is that `BroadcastQueryStageExec` expects a `BroadcastExchangeLike` child, so to fix the original assert, `GpuBroadcastToCpuExec` needs to be a `BroadcastExchangeLike`.  Unfortunately `BroadcastExchangeLike` was forcing shims due to Databricks changing the signature of that class.  Rather than shim yet another class that needs `BroadcastExchangeLike`, I ended up creating a shim v2 version of `BroadcastExchangeLike` called `ShimBroadcastExchangeLike` that encapsulates the differences between Apache Spark and Databricks with this class.  This not only allows us to avoid shimming `GpuBroadcastToCpuExec` but also allows us to unshim `GpuBroadcastExchangeExec` which was only being shimmed due to this trait signature difference.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by abellina** [comment]
Looks like a databricks301 build issue: 
```

[2021-09-28T20:35:06.698Z] [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala:69: not enough arguments for method apply: (id: Int, plan: org.apache.spark.sql.execution.SparkPlan, _canonicalized: org.apache.spark.sql.execution.SparkPlan)org.apache.spark.sql.execution.adaptive.BroadcastQueryStageExec in object BroadcastQueryStageExec.

[2021-09-28T20:35:06.698Z] Unspecified value parameter _canonicalized.

[2021-09-28T20:35:06.698Z] [ERROR]       newPlan: SparkPlan): BroadcastQueryStageExec = BroadcastQueryStageExec(old.id, newPlan)

[2021-09-28T20:35:06.698Z] [ERROR]                           
```

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Review by tgravescs — DISMISSED** [review]
It might be nice to add an integration test with this combo, I think we may have issues filed for both DPP and AQE testing though too, not sure about together.

**Comment by jlowe** [comment]
There are some double-close issues in some cases, converting to draft while I investigate.

**Comment by jlowe** [comment]
Found the double-buffer issue, had to do with multiple columns appearing in the same batch all referencing the same buffer.

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala [hunk 1]
```diff
@@ -83,36 +83,36 @@ case class GpuBroadcastToCpuExec(override val mode: BroadcastMode, child: SparkP
...
+            val gpuBatches = withResource(serializedBatches) { _ =>
+              serializedBatches.safeMap { cb =>
+                val hostColumns = (0 until cb.header.getNumColumns).map { i =>
+                  val columnHeader = cb.header.getColumnHeader(i)
+                  val hcv = new HostColumnVector(
+                    columnHeader.getType,
+                    columnHeader.rowCount,
+                    Optional.of(columnHeader.nullCount),
+                    cb.buffer,
+                    null, null, List.empty.asJava)
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala:95]: I fixed the double-close issue, but this original code seems broken to me.  It's setting up all host columns in the batch to point to the _same data_ and no validity or offsets which seems very wrong.  this could never handle StringType which requires offsets or anything that could contain null values.

**Comment by jlowe** [comment]
I think I've fixed the problems with `HostColumnVector` deserialization.  Queries seem to be computing proper results, but I'm seeing the CPU and GPU execute queries with very different shapes (e.g.: CPU never runs a stage with more than 35 partitions, yet GPU will run many partitions with the full 200 partitions).  Investigating.

**Comment by jlowe** [comment]
The occasional lack of AQE shuffle coalescing on GPU queries is unrelated to this change.  Filed #3713 to track it separately.

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala [hunk 2]
```diff
@@ -83,36 +87,27 @@ case class GpuBroadcastToCpuExec(override val mode: BroadcastMode, child: SparkP
...
               checkRowLimit(numRows)
               numOutputRows += numRows
 
               val relation = withResource(new NvtxWithMetrics(
                 "broadcast build", NvtxColor.DARK_GREEN, buildTime)) { _ =>
                 val toUnsafe = UnsafeProjection.create(output, output)
-                val unsafeRows = rows.iterator.map(toUnsafe)
-                 val relation = ShimLoader.getSparkShims
+                val unsafeRows = gpuBatches.flatMap {
+                  _.rowIterator().asScala.map(r => toUnsafe(r).copy())
```
Comment (abellina) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala:108]: nit, it may be worth adding a comment above this explaining the reason for the copy. I think folks can backtrack to this github issue, and it can be done later too, not to block this PR from an expensive CI run today.

**Review by abellina — APPROVED** [review]
lgtm

**Comment by abellina** [comment]
Note I am running with this change in spark2a, and I haven't found the NPE I was seeing before.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala [hunk 3]
```diff
@@ -175,3 +170,138 @@ case class GpuBroadcastToCpuExec(mode: BroadcastMode, child: SparkPlan)
...
+        val columnHeader = header.getColumnHeader(i)
+        val hcv = buildHostColumn(columnHeader, columnOffsets, buffer)
+        hostColumns += new RapidsHostColumnVector(dataTypes(i), hcv)
+      }
+      assert(columnOffsets.isEmpty)
+      hostColumns.toArray
+    }
+  }
+
+  // TODO: The methods below either replicate private functionality in cudf
```
Comment (tgravescs) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala:194]: did we file an issue for this?

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala [hunk 4]
```diff
@@ -83,36 +87,27 @@ case class GpuBroadcastToCpuExec(override val mode: BroadcastMode, child: SparkP
...
-                val hcv = new HostColumnVector(
-                  columnHeader.getType,
-                  columnHeader.rowCount,
-                  Optional.of(columnHeader.nullCount),
-                  cb.buffer,
-                  null, null, List.empty.asJava)
-                new RapidsHostColumnVector(dataTypes(i), hcv)
+            val gpuBatches = withResource(serializedBatches) { _ =>
+              serializedBatches.safeMap { cb =>
+                val hostColumns = GpuBroadcastToCpuExec.buildHostColumns(cb.header, cb.buffer,
```
Comment (tgravescs) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala:92]: follow up for later: not sure if there is an easy way to unit test or specifically test this since we obviously building this wrong, or perhaps if we get some dpp/aqe testing with data validation it would cover it.

**Review by tgravescs — APPROVED** [review]

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala (hunk 3 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala:194]: Filed #3723

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala (hunk 4 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala:92]: I think DPP+AQE testing would cover it.  Filed #3724.
