### PR TITLE
Fix the failure in `map_test.py` on Spark 3.4 [databricks]

### LINKED ISSUE #6383: [SPARK-40066][SQL] ANSI mode: always return null on invalid access to map column
#### Context

- Spark 3.4: https://github.com/apache/spark/commit/95cbd61857
  - Followup: https://github.com/apache/spark/commit/fbc0edac58
- Other related error formatting auditing issues: https://github.com/NVIDIA/spark-rapids/issues/6293

#### What changes were proposed in SPARK pull request?

Change the syntax of map column access under ANSI mode: always return null results instead of
throwing `MAP_KEY_DOES_NOT_EXIST`  errors.
This PR also remove an internal `spark.sql.ansi.strictIndexOperator`.

#### Why are the changes needed in Spark?

PostgreSQL/Snowflake/Biguqery and all of them returns null return on map(json) key not exists.

#### Does this PR introduce _any_ user-facing change?

Yes.

Since Spark 3.4, when ANSI SQL mode(configuration `spark.sql.ansi.enabled`) is on, Spark SQL always
returns NULL result on getting a map value with a non-existing key.
In Spark 3.3 or earlier, there will be an error.

#### Why it might affect RAPIDS?

Yes, change of behavior in Ansi Mode.
- shims for 3.4+ need to be updated.

#### Impact on Testing?

Yes, need to update integration tests to match Spark Behavior

#### Requires Doc update?

No

https://github.com/NVIDIA/spark-rapids/issues/6383#tasklist-block-6d267eea-60b1-478b-bd81-4634ae979ff5

### LINKED ISSUE #7093: [BUG] Spark-3.4 - Integration test failures in map_test
**Describe the bug**
```
=========================== short test summary info ============================
FAILED ../../src/main/python/map_test.py::test_simple_get_map_value_with_strict_index[Map(String(not_null),String)-true]
FAILED ../../src/main/python/map_test.py::test_simple_get_map_value_with_strict_index[Map(String(not_null),String)-false]
FAILED ../../src/main/python/map_test.py::test_element_at_map_string_col_keys_ansi_fail[Map(String(not_null),String)]
FAILED ../../src/main/python/map_test.py::test_get_map_value_string_col_keys_ansi_fail[Map(String(not_null),String)]
FAILED ../../src/main/python/map_test.py::test_map_element_at_ansi_fail[Map(String(not_null),String)]
==== 5 failed, 481 passed, 1 skipped, 15294 deselected in 253.19s (0:04:13) ====
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.
```
./run_pyspark_from_build.sh -k map_test.py
```

**Expected behavior**
All tests should pass

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>
Closes #7093.
Closes #6383.

## Rationales of the changes
Since Spark3.4, `GetMapValue` and `ElementAt` always return null on invalid access to map column

## Changes in this PR
1. Add `ElementAt` to the shim expressions of Spark 3.4+
2. Update tests

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

**Comment by HaoYang670** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala [hunk 1]
```diff
@@ -2507,7 +2507,7 @@ object GpuOverrides extends Logging {
               TypeEnum.FLOAT, TypeEnum.DOUBLE, TypeEnum.DATE, TypeEnum.TIMESTAMP,
               TypeEnum.STRING, TypeEnum.DECIMAL), "Unsupported as array index."),
           TypeSig.all)),
-      (in, conf, p, r) => new BinaryExprMeta[ElementAt](in, conf, p, r) {
+      (in, conf, p, r) => new ElementAtMeta(in, conf, p, r) {
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:2510]: Nit: It's weird to have a dedicated meta class to an expression that needs to be heavily overridden to be used properly.  Suggest moving this anonymous class override code to something like a common ElementAtMetaBase class that the specific ElementAtMeta shim classes derive from.

**Comment by firestarman** [comment]
This will become simpler after #7167 is merged.

File: integration_tests/src/main/python/map_test.py [hunk 2]
```diff
@@ -322,9 +322,17 @@ def test_simple_get_map_value_ansi_fail(data_gen):
             conf=ansi_enabled_conf,
             error_message=message)
 
+@pytest.mark.skipif(is_before_spark_340(),
+                    reason="Only in Spark 3.4 + ANSI mode, map key returns null on no such element")
```
Comment (firestarman) [inline integration_tests/src/main/python/map_test.py:326]:
```suggestion
                    reason="Only in Spark 3.4+ with ANSI mode, map key returns null on no such element")
```

File: integration_tests/src/main/python/map_test.py [hunk 3]
```diff
@@ -322,9 +322,17 @@ def test_simple_get_map_value_ansi_fail(data_gen):
...
+@pytest.mark.parametrize('data_gen', [simple_string_to_string_map_gen], ids=idfn)
+def test_simple_get_map_value_ansi_null(data_gen):
+        assert_gpu_and_cpu_are_equal_collect(
+                lambda spark: unary_op_df(spark, data_gen).selectExpr(
+                        'a["NOT_FOUND"]'),
+                conf=ansi_enabled_conf)
 
-@pytest.mark.skipif(is_before_spark_330(),
-                    reason="Only in Spark 3.3.0 + ANSI mode + Strict Index, map key throws on no such element")
+@pytest.mark.skipif(is_before_spark_330() or is_spark_340_or_later(),
```
Comment (firestarman) [inline integration_tests/src/main/python/map_test.py:334]: We have a `is_spark_33X` now

File: integration_tests/src/main/python/map_test.py (hunk 2 above)
Comment (HaoYang670) [reply integration_tests/src/main/python/map_test.py]: Done

File: integration_tests/src/main/python/map_test.py (hunk 3 above)
Comment (HaoYang670) [reply integration_tests/src/main/python/map_test.py]: Updated

File: sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/Spark340PlusShims.scala [hunk 4]
```diff
@@ -76,7 +78,59 @@ trait Spark340PlusShims extends Spark331PlusShims {
...
+              .withPsNote(TypeEnum.MAP ,"If it's map, only primitive key types are supported."),
+            TypeSig.ARRAY.nested(TypeSig.all) + TypeSig.MAP.nested(TypeSig.all)),
+          ("index/key", (TypeSig.commonCudfTypes + TypeSig.DECIMAL_128)
+            .withPsNote(
+              Seq(TypeEnum.BOOLEAN, TypeEnum.BYTE, TypeEnum.SHORT, TypeEnum.LONG,
+                TypeEnum.FLOAT, TypeEnum.DOUBLE, TypeEnum.DATE, TypeEnum.TIMESTAMP,
+                TypeEnum.STRING, TypeEnum.DECIMAL), "Unsupported as array index."),
+            TypeSig.all)),
+        (in, conf, p, r) => new BinaryExprMeta[ElementAt](in, conf, p, r) {
+          override def tagExprForGpu(): Unit = {
```
Comment (firestarman) [inline sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/Spark340PlusShims.scala:101]: Better to create an abstract class as the base to cover the common code for this meta class, to avoid copying this long method `tagExprForGpu` here.

**Comment by firestarman** [comment]
Don't we have to update the `GetMapValue`  as well ?

**Comment by HaoYang670** [comment]
> Don't we have to update the GetMapValue as well ?

The `GetMapValue` has been updated in https://github.com/NVIDIA/spark-rapids/pull/6952

**Comment by HaoYang670** [comment]
build

File: integration_tests/src/main/python/map_test.py [hunk 5]
```diff
@@ -322,9 +322,17 @@ def test_simple_get_map_value_ansi_fail(data_gen):
             conf=ansi_enabled_conf,
             error_message=message)
 
+@pytest.mark.skipif(is_before_spark_340(),
```
Comment (firestarman) [inline integration_tests/src/main/python/map_test.py:325]: Is the `strict_index` missing in this tests ?

File: integration_tests/src/main/python/map_test.py [hunk 6]
```diff
@@ -408,19 +416,32 @@ def test_get_map_value_element_at_map_string_col_keys(data_gen):
...
+    # For 3.3.X strictIndexOperator should not affect element_at
     test_conf = copy_and_update(ansi_enabled_conf, {'spark.sql.ansi.strictIndexOperator': 'false'})
     assert_gpu_and_cpu_error(
         lambda spark: two_col_df(spark, data_gen, keys).selectExpr(
             'element_at(a, b)').collect(),
         conf=test_conf,
         error_message=message)
 
+@pytest.mark.skipif(is_before_spark_340(),
+                    reason="Only in Spark 3.4 + ANSI mode, map key returns null on no such element")
```
Comment (firestarman) [inline integration_tests/src/main/python/map_test.py:434]:
```suggestion
                    reason="Only in Spark 3.4+ with ANSI mode, map key returns null on no such element")
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 7]
```diff
@@ -103,6 +103,68 @@ case class GpuMapConcat(children: Seq[Expression]) extends GpuComplexTypeMerging
   }
 }
 
+object GpuElementAtMeta {
+  def elementAtRule(NullOnInvalidAccessToMap: Boolean): ExprRule[_ <: Expression] = {
```
Comment (firestarman) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:107]:
```suggestion
  def elementAtRule(nullOnInvalidAccessToMap: Boolean): ExprRule[_ <: Expression] = {
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 8]
```diff
@@ -103,6 +103,68 @@ case class GpuMapConcat(children: Seq[Expression]) extends GpuComplexTypeMerging
...
+                  TypeSig.STRUCT + TypeSig.NULL + TypeSig.DECIMAL_128 + TypeSig.MAP +
+                  TypeSig.BINARY),
+                  TypeSig.ARRAY.nested(TypeSig.all)),
+                ("ordinal", TypeSig.INT, TypeSig.INT))
+            case _ => throw new IllegalStateException("Only Array or Map is supported as input.")
+          }
+          checks.tag(this)
+        }
+        override def convertToGpu(lhs: Expression, rhs: Expression): GpuExpression = {
+          val failOnError = if (NullOnInvalidAccessToMap) {
```
Comment (firestarman) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:157]:
```suggestion
          val failOnError = if (nullOnInvalidAccessToMap) {
```

File: integration_tests/src/main/python/map_test.py (hunk 5 above)
Comment (HaoYang670) [reply integration_tests/src/main/python/map_test.py:325]: The config `spark.sql.ansi.strictIndexOperator` has been removed in Spark340, see https://github.com/apache/spark/commit/95cbd61857

**Comment by HaoYang670** [comment]
build

**Comment by firestarman** [comment]
LGTM

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 9]
```diff
@@ -103,6 +103,68 @@ case class GpuMapConcat(children: Seq[Expression]) extends GpuComplexTypeMerging
...
+                  TypeSig.STRUCT + TypeSig.NULL + TypeSig.DECIMAL_128 + TypeSig.MAP +
+                  TypeSig.BINARY),
+                  TypeSig.ARRAY.nested(TypeSig.all)),
+                ("ordinal", TypeSig.INT, TypeSig.INT))
+            case _ => throw new IllegalStateException("Only Array or Map is supported as input.")
+          }
+          checks.tag(this)
+        }
+        override def convertToGpu(lhs: Expression, rhs: Expression): GpuExpression = {
+          val failOnError = if (nullOnInvalidAccessToMap) {
```
Comment (firestarman) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:157]: NIT: 
It would be better to add a comment here to explain why `nullOnInvalidAccessToMap` is introduced.

**Review by firestarman — DISMISSED** [review]

**Comment by HaoYang670** [comment]
Hi @jlowe. Is it ready to merge this?

**Comment by jlowe** [comment]
> Is it ready to merge this?

We're holding off on changes for Spark 3.4 to reduce code churn while the Databricks 11.3 shim #7152  is being developed.

**Comment by HaoYang670** [comment]
Ok, then I'll convert this to a draft.

**Comment by HaoYang670** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 9 above)
Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:163]: Added

**Comment by HaoYang670** [comment]
@firestarman @jlowe Could you please help to review again?

File: integration_tests/src/main/python/map_test.py [hunk 10]
```diff
@@ -323,6 +323,14 @@ def test_simple_get_map_value_ansi_fail(data_gen):
             conf=ansi_enabled_conf,
```
Comment (jlowe) [inline integration_tests/src/main/python/map_test.py:323]: 2023 copyrights

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 11]
```diff
@@ -103,6 +103,74 @@ case class GpuMapConcat(children: Seq[Expression]) extends GpuComplexTypeMerging
...
+      "Returns element of array at given(1-based) index in value if column is array. " +
+        "Returns value for the given key in value if column is map.",
+      ExprChecks.binaryProject(
+        (TypeSig.commonCudfTypes + TypeSig.ARRAY + TypeSig.STRUCT + TypeSig.NULL +
+          TypeSig.DECIMAL_128 + TypeSig.MAP + TypeSig.BINARY).nested(), TypeSig.all,
+        ("array/map", TypeSig.ARRAY.nested(TypeSig.commonCudfTypes + TypeSig.ARRAY +
+          TypeSig.STRUCT + TypeSig.NULL + TypeSig.DECIMAL_128 + TypeSig.MAP + TypeSig.BINARY) +
+          TypeSig.MAP.nested(TypeSig.commonCudfTypes + TypeSig.ARRAY + TypeSig.STRUCT +
+            TypeSig.NULL + TypeSig.DECIMAL_128 + TypeSig.MAP + TypeSig.BINARY)
+            .withPsNote(TypeEnum.MAP ,"If it's map, only primitive key types are supported."),
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:124]:
```suggestion
            .withPsNote(TypeEnum.MAP, "If it's map, only primitive key types are supported."),
```

File: integration_tests/src/main/python/map_test.py (hunk 10 above)
Comment (HaoYang670) [reply integration_tests/src/main/python/map_test.py:323]: Thank you for finding it. I accidentally turned the `auto-copyright` off. Have updated.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 11 above)
Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala]: Updated.

**Comment by HaoYang670** [comment]
build

File: integration_tests/src/main/python/map_test.py [hunk 12]
```diff
@@ -409,20 +417,31 @@ def test_get_map_value_element_at_map_string_col_keys(data_gen):
         conf={'spark.sql.ansi.enabled': False})
 
 
+@pytest.mark.skipif(is_spark_340_or_later(),
+                    reason="Only in Spark 3.1.X ~3.3.X + ANSI mode, map key throws on no such element")
```
Comment (jlowe) [inline integration_tests/src/main/python/map_test.py:421]: This is already handled a couple of lines below.  Only caught this because last night's 340 build passed, and I was wondering how it could have without this going in.  Maybe the headline should be changed to reflect that this isn't fixing failures but adding new tests?
```suggestion
```

File: integration_tests/src/main/python/map_test.py [hunk 13]
```diff
@@ -409,20 +417,31 @@ def test_get_map_value_element_at_map_string_col_keys(data_gen):
...
-    # For 3.3.0+ strictIndexOperator should not affect element_at
+    # For 3.3.X strictIndexOperator should not affect element_at
     test_conf = copy_and_update(ansi_enabled_conf, {'spark.sql.ansi.strictIndexOperator': 'false'})
     assert_gpu_and_cpu_error(
         lambda spark: two_col_df(spark, data_gen, keys).selectExpr(
             'element_at(a, b)').collect(),
         conf=test_conf,
         error_message=message)
 
+@pytest.mark.skipif(is_before_spark_340(),
```
Comment (jlowe) [inline integration_tests/src/main/python/map_test.py:436]: Related to the previous comment, should this condition add `and not is_databricks113_or_later()`?

File: integration_tests/src/main/python/map_test.py [hunk 14]
```diff
@@ -436,6 +455,15 @@ def test_get_map_value_string_col_keys_ansi_fail(data_gen):
         conf=ansi_enabled_conf,
         error_message=message)
 
+@pytest.mark.skipif(is_before_spark_340(),
```
Comment (jlowe) [inline integration_tests/src/main/python/map_test.py:458]: Same `and not is_databricks113_or_later()` question here.

File: integration_tests/src/main/python/map_test.py [hunk 15]
```diff
@@ -475,6 +502,14 @@ def test_map_element_at_ansi_fail(data_gen):
             conf=test_conf,
             error_message=message)
 
+@pytest.mark.skipif(is_before_spark_340(),
```
Comment (jlowe) [inline integration_tests/src/main/python/map_test.py:505]: same `and not is_databricks113_or_later()` question here.

Comment (HaoYang670) [reply integration_tests/src/main/python/map_test.py]: These 2 tests fail on db11.3, 
```
FAILED ../../src/main/python/map_test.py::test_element_at_map_string_col_keys_ansi_null[Map(String(not_null),String)] - py4j.protocol.Py4JJavaError: An error occurred while calling o70730.collect...
FAILED ../../src/main/python/map_test.py::test_map_element_at_ansi_null[Map(String(not_null),String)] - py4j.protocol.Py4JJavaError: An error occurred while calling o76588.collect...
```

Comment (HaoYang670) [reply integration_tests/src/main/python/map_test.py]: I need to create a separate test case for bd11.3 I guess. Because it seems like that db11.3 removes `spark.sql.ansi.strictIndexOperator` but still throws exceptions. (I need to double confirm this)

**Comment by HaoYang670** [comment]
build

**Comment by HaoYang670** [comment]
I've tested with Spark340 locally and with db113 cluster, which in both cases, `map_test` can pass.

**Review by jlowe — APPROVED** [review]

File: integration_tests/src/main/python/map_test.py (hunk 15 above)
Comment (HaoYang670) [reply integration_tests/src/main/python/map_test.py]: Hi @sameerz @jlowe @GaryShen2008, As Gary mentioned, should we create another PR to fix the behavior of `invalid access on map` on DB11.3 and merge it in the branch 23.02?

Comment (sameerz) [reply integration_tests/src/main/python/map_test.py]: We discussed this and decided it can go in 23.04, since it is a fix for a specific mode of Spark SQL (ANSI) and the error does not result in data corruption.
