### PR TITLE
Drop ".dev0" suffix from Spark SNASHOT distro builds

### LINKED ISSUE #6872: [BUG] awk: cmd. line:1: warning: regexp escape sequence `\ ' is not a known regexp operator
**Describe the bug**
Running locally
./integration_tests/run_pyspark_from_build.sh

```
+ [[ ! -x /usr/bin/zip ]]
++ /home/user/dist/spark-3.1.1-bin-hadoop3.2/bin/pyspark --version
++ grep -v Scala
++ awk '/version\ [0-9.]+/{print $NF}'
awk: cmd. line:1: warning: regexp escape sequence `\ ' is not a known regexp operator
```

### LINKED ISSUE #8588: [BUG] Spark 3.3.x integration tests failed due to missing jars
Last night's rapids_it-3.3.x-SNAPSHOT-dev build failed due to missing jars, e.g.:
```
Caused by: java.lang.ClassNotFoundException: com.nvidia.spark.rapids.tests.datasourcev2.parquet.ArrowColumnarDataSourceV2.DefaultSource
```
and
```
E               pyspark.sql.utils.AnalysisException: Can not load class 'com.nvidia.spark.rapids.tests.udf.hive.EmptyHiveSimpleUDF' when registering the function 'emptysimple', please make sure it is on the classpath
```

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #8588
Fixes #6872  

Alternative to #8589 

Drop [PEP 440](https://peps.python.org/pep-0440/#implicit-development-release-number) suffix for Python-based version extraction

Local testing with 3.3.0 downloaded from Apache and 3.3.0-SNAPSHOT built locally

```Python
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 SPARK_HOME=~/gits/apache/spark/dist  TEST_PARALLEL=0 ./integration_tests/run_pyspark_from_build.sh -k 'array_exists'
```

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

File: integration_tests/run_pyspark_from_build.sh [hunk 1]
```diff
@@ -26,8 +26,14 @@ then
 else
     echo "WILL RUN TESTS WITH SPARK_HOME: ${SPARK_HOME}"
     [[ ! -x "$(command -v zip)" ]] && { echo "fail to find zip command in $PATH"; exit 1; }
-    VERSION_STRING=`$SPARK_HOME/bin/pyspark --version 2>&1|grep -v Scala|awk '/version\ [0-9.]+/{print $NF}'`
-    VERSION_STRING="${VERSION_STRING/-SNAPSHOT/}"
+    PY4J_TMP=("${SPARK_HOME}"/python/lib/py4j-*-src.zip)
+    PY4J_FILE=${PY4J_TMP[0]}
+    # PySpark uses ".dev0" for "-SNAPSHOT",  ".dev" for "preview"
```
Comment (jlowe) [inline integration_tests/run_pyspark_from_build.sh:31]: Have we verified that Cloudera and other non-standard Spark versioning schemes work with this change?

Comment (gerashegalov) [reply integration_tests/run_pyspark_from_build.sh:31]: only on Databricks

Comment (gerashegalov) [reply integration_tests/run_pyspark_from_build.sh:31]: Judging by #5146 we use `INTEGRATION_TEST_VERSION_OVERRIDE` for Cloudera

I assume it's similarly overridden for EMR because the current code does not handle it correctly:

```bash
$ /usr/lib/spark/bin/pyspark --version 2>&1 | grep -v Scala | awk '/version\ [0-9.]+/{print $NF}'
3.3.2-amzn-0
```

Updated code results in a similar string with '-' replaced by '+'
```bash
$ export SPARK_HOME=/usr/lib/spark
$ PY4J_TMP=("${SPARK_HOME}"/python/lib/py4j-*-src.zip)
$ PYTHONPATH=${SPARK_HOME}/python:${PY4J_FILE} python -c "import pyspark, re; print(re.sub('\.dev0?$', '', pyspark.__version__))"
3.3.2+amzn.0
```

Comment (jlowe) [reply integration_tests/run_pyspark_from_build.sh:31]: Then it seems like this change is no worse than what we were already doing.  Thanks for digging, @gerashegalov!

**Review by jlowe — APPROVED** [review]

File: integration_tests/run_pyspark_from_build.sh (hunk 1 above)
Comment (gerashegalov) [reply integration_tests/run_pyspark_from_build.sh:31]: @pxLi @zhanga5 can you confirm that we don't need to worry about distros with modified versions   `INTEGRATION_TEST_VERSION_OVERRIDE` for non-standard builds?

**Review by pxLi — APPROVED** [review]
