### PR TITLE
Enhance IcebergProbeImpl with jar source logging and version fallback

### LINKED ISSUE #14487: [BUG] Iceberg version detection may fail if a vendor build does not include properties behind IcebergBuild
**Describe the bug**
Currently IcebergBuild is the preferred way to probe for the version but it may not provide any versioning information with some custom builds

**Steps/Code to reproduce bug**
Run in an environment such as EMR

**Expected behavior**
An easy fallback is to extract the version from the jar file name.

**Environment details (please complete the following information)**
custom builds

**Additional context**

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #14487

Requires #14494 

### Description

Fallback on the version in the jar file name 

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [ ] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

File: iceberg/common/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProbeImpl.scala [hunk 1]
```diff
@@ -42,9 +43,25 @@ class IcebergProbeImpl extends IcebergProbe {
     "ccb8bc435062171e64bc8b7e5f56e6aed9c5b934" -> "1.10.1"
   )
 
+  // e.g. iceberg-spark-runtime-3.5_2.12-1.10.0-*.jar -> "1.10.0"
+  private val jarVersionPattern = """iceberg-.*-(\d+\.\d+\.\d+)""".r.unanchored
+
   override def getDetectedVersion: String = {
+    val sourceLocation = Option(classOf[IcebergBuild].getProtectionDomain.getCodeSource)
+      .map(_.getLocation.toString)
+      .getOrElse("unknown")
```
[the remark this answers is not in the document]
Comment (jihoonson) [reply iceberg/common/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProbeImpl.scala]: Good call. We should check null.

File: iceberg/common/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProbeImpl.scala [hunk 2]
```diff
@@ -33,9 +44,26 @@ class IcebergProbeImpl extends IcebergProbe {
     "ccb8bc435062171e64bc8b7e5f56e6aed9c5b934" -> "1.10.1"
   )
 
+  // e.g. iceberg-spark-runtime-3.5_2.12-1.10.0-*.jar -> "1.10.0"
+  private val jarVersionPattern = """iceberg-.*-(\d+\.\d+\.\d+)""".r.unanchored
```
Comment (liurenjie1024) [inline iceberg/common/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProbeImpl.scala]: Regex is somehow difficult to read and debug. I would prefer easy to read methods like assert it starts with `iceberg-spark-runtime-`, followed by spark major version, scala binary version, and iceberg version.

File: iceberg/common/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProbeImpl.scala [hunk 3]
```diff
@@ -33,9 +44,26 @@ class IcebergProbeImpl extends IcebergProbe {
...
+
   override def getDetectedVersion: String = {
+    val sourceLocation = Option(classOf[IcebergBuild].getProtectionDomain.getCodeSource)
```
Comment (liurenjie1024) [inline iceberg/common/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProbeImpl.scala]: Should we use ShimLoader here?

Comment (liurenjie1024) [reply iceberg/common/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProbeImpl.scala]: A little perf improvement: we could do this when commitId not found?

Comment (gerashegalov) [reply iceberg/common/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProbeImpl.scala]: > Should we use ShimLoader here?

no since the classloader was already defined when loading this IcebergProbeImpl. It is the reason we don't need it before this PR [either](https://github.com/gerashegalov/spark-rapids/commit/58524f4e2e1f6c0a21de0cb64d46d4867eab00aa#diff-01f1dca0bfcbc0484192e431f88e4c096ed23b16d44bdacf2be3d8dbc820986aR37)

**Comment by gerashegalov** [comment]
build
