### PR TITLE
Fix CI: can't find script when there is pushd in script [skip ci]

### LINKED ISSUE #10118: [BUG] non-UTC Nightly CI failed
**Describe the bug**

jenkins/spark-tests.sh: line 276: jenkins/test-timezones.sh: No such file or directory

**Steps/Code to reproduce bug**
Refer to the last line of the below log
```
[2023-12-28T15:53:41.904Z] ----------------------------START TEST------------------------------------
[2023-12-28T15:53:41.904Z] + pushd /home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/integration_tests/
[2023-12-28T15:53:41.904Z] /home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/integration_tests /home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22
[2023-12-28T15:53:41.904Z] + export TEST_TYPE=nightly
[2023-12-28T15:53:41.904Z] + TEST_TYPE=nightly
[2023-12-28T15:53:41.904Z] + export LOCAL_JAR_PATH=/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars
[2023-12-28T15:53:41.904Z] + LOCAL_JAR_PATH=/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars
[2023-12-28T15:53:41.904Z] + export SPARK_TASK_MAXFAILURES=1
[2023-12-28T15:53:41.904Z] + SPARK_TASK_MAXFAILURES=1
[2023-12-28T15:53:41.904Z] + export PATH=/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/bin:/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/sbin:/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/bin:/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/sbin:/opt/conda/bin:/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[2023-12-28T15:53:41.904Z] + PATH=/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/bin:/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/sbin:/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/bin:/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/sbin:/opt/conda/bin:/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[2023-12-28T15:53:41.905Z] + export 'SPARK_WORKER_OPTS= -Dspark.worker.cleanup.enabled=true -Dspark.worker.cleanup.interval=120 -Dspark.worker.cleanup.appDataTtl=60'
[2023-12-28T15:53:41.905Z] + SPARK_WORKER_OPTS=' -Dspark.worker.cleanup.enabled=true -Dspark.worker.cleanup.interval=120 -Dspark.worker.cleanup.appDataTtl=60'
[2023-12-28T15:53:41.905Z] + stop-worker.sh
[2023-12-28T15:53:42.160Z] no org.apache.spark.deploy.worker.Worker to stop
[2023-12-28T15:53:42.160Z] + stop-master.sh
[2023-12-28T15:53:42.160Z] no org.apache.spark.deploy.master.Master to stop
[2023-12-28T15:53:42.160Z] + start-master.sh
[2023-12-28T15:53:42.160Z] starting org.apache.spark.deploy.master.Master, logging to /home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/logs/spark--org.apache.spark.deploy.master.Master-1-it-jenkins-rapids-it-non-utc-dev-22-2w9h7-qnkzm.out
[2023-12-28T15:53:44.674Z] + start-worker.sh spark://it-jenkins-rapids-it-non-utc-dev-22-2w9h7-qnkzm:7077
[2023-12-28T15:53:44.674Z] starting org.apache.spark.deploy.worker.Worker, logging to /home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/spark-3.1.1-bin-hadoop3.2/logs/spark--org.apache.spark.deploy.worker.Worker-1-it-jenkins-rapids-it-non-utc-dev-22-2w9h7-qnkzm.out
[2023-12-28T15:53:47.192Z] + jps
[2023-12-28T15:53:47.192Z] 1248 Jps
[2023-12-28T15:53:47.192Z] 1086 Master
[2023-12-28T15:53:47.192Z] 1167 Worker
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_master=spark://it-jenkins-rapids-it-non-utc-dev-22-2w9h7-qnkzm:7077
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_master=spark://it-jenkins-rapids-it-non-utc-dev-22-2w9h7-qnkzm:7077
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_sql_shuffle_partitions=12
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_sql_shuffle_partitions=12
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_task_maxFailures=1
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_task_maxFailures=1
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_dynamicAllocation_enabled=false
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_dynamicAllocation_enabled=false
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_driver_extraJavaOptions=-Duser.timezone=UTC
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_driver_extraJavaOptions=-Duser.timezone=UTC
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_executor_extraJavaOptions=-Duser.timezone=UTC
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_executor_extraJavaOptions=-Duser.timezone=UTC
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_sql_session_timeZone=UTC
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_sql_session_timeZone=UTC
[2023-12-28T15:53:47.192Z] + [[ true == \t\r\u\e ]]
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_cores_max=1
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_cores_max=1
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_executor_memory=4g
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_executor_memory=4g
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_executor_cores=1
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_executor_cores=1
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_task_cores=1
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_task_cores=1
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_rapids_sql_concurrentGpuTasks=1
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_rapids_sql_concurrentGpuTasks=1
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_rapids_memory_gpu_minAllocFraction=0
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_rapids_memory_gpu_minAllocFraction=0
[2023-12-28T15:53:47.192Z] + [[ '' == '' ]]
[2023-12-28T15:53:47.192Z] ++ nvidia-smi --query-gpu=memory.free --format=csv,noheader
[2023-12-28T15:53:47.192Z] ++ awk '{if (MAX < $1){ MAX = $1}} END {print int(MAX / (2 * 1024))}'
[2023-12-28T15:53:47.192Z] + PARALLELISM=11
[2023-12-28T15:53:47.192Z] + [[ 11 -gt 5 ]]
[2023-12-28T15:53:47.192Z] + PARALLELISM=5
[2023-12-28T15:53:47.192Z] ++ python -c 'print(1/(5 + 0.1))'
[2023-12-28T15:53:47.192Z] + MEMORY_FRACTION=0.19607843137254904
[2023-12-28T15:53:47.192Z] + export TEST_PARALLEL=5
[2023-12-28T15:53:47.192Z] + TEST_PARALLEL=5
[2023-12-28T15:53:47.192Z] + export PYSP_TEST_spark_rapids_memory_gpu_allocFraction=0.19607843137254904
[2023-12-28T15:53:47.192Z] + PYSP_TEST_spark_rapids_memory_gpu_allocFraction=0.19607843137254904
[2023-12-28T15:53:47.193Z] + export PYSP_TEST_spark_rapids_memory_gpu_maxAllocFraction=0.19607843137254904
[2023-12-28T15:53:47.193Z] + PYSP_TEST_spark_rapids_memory_gpu_maxAllocFraction=0.19607843137254904
[2023-12-28T15:53:47.193Z] ++ pwd -P
[2023-12-28T15:53:47.193Z] + export SCRIPT_PATH=/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/integration_tests
[2023-12-28T15:53:47.193Z] + SCRIPT_PATH=/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/integration_tests
[2023-12-28T15:53:47.193Z] + export TARGET_DIR=/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/integration_tests/target
[2023-12-28T15:53:47.193Z] + TARGET_DIR=/home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/integration_tests/target
[2023-12-28T15:53:47.193Z] + mkdir -p /home/jenkins/agent/workspace/jenkins-rapids_it-non-utc-dev-22/jars/integration_tests/target
[2023-12-28T15:53:47.193Z] + TEST_MODE=NON_UTC_TZ
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \D\E\F\A\U\L\T ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \D\E\F\A\U\L\T ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \D\E\L\T\A\_\L\A\K\E\_\O\N\L\Y ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \D\E\F\A\U\L\T ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \I\C\E\B\E\R\G\_\O\N\L\Y ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \D\E\F\A\U\L\T ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \A\V\R\O\_\O\N\L\Y ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \D\E\F\A\U\L\T ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \M\U\L\T\I\T\H\R\E\A\D\E\D\_\S\H\U\F\F\L\E ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \C\U\D\F\_\U\D\F\_\O\N\L\Y ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \D\E\F\A\U\L\T ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \P\Y\A\R\R\O\W\_\O\N\L\Y ]]
[2023-12-28T15:53:47.193Z] + [[ NON_UTC_TZ == \N\O\N\_\U\T\C\_\T\Z ]]
[2023-12-28T15:53:47.193Z] + run_non_utc_time_zone_tests
[2023-12-28T15:53:47.193Z] ++ dirname jenkins/spark-tests.sh
[2023-12-28T15:53:47.193Z] + source jenkins/test-timezones.sh
[2023-12-28T15:53:47.193Z] jenkins/spark-tests.sh: line 276: jenkins/test-timezones.sh: No such file or directory
script returned exit code 1
```

### PR DESCRIPTION
**Pull request by res-life**
closes #10118

pushd will impact $(dirname $0), so first backup the workspace virable.

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Review by GaryShen2008 — DISMISSED** [review]

**Review by NvTimLiu — DISMISSED** [review]

File: jenkins/spark-tests.sh [hunk 1]
```diff
@@ -273,7 +275,7 @@ run_pyarrow_tests() {
 
 run_non_utc_time_zone_tests() {
   # select one time zone according to current day of week
-  source "$(dirname "$0")"/test-timezones.sh
+  source "${WORKSPACE}/jenkins/test-timezones.sh"
```
Comment (NvTimLiu) [inline jenkins/spark-tests.sh:278]: $0 is the relative path, when we run the test script `jenkins/spark_test.sh`, $0 is `jenkins/` but currently $PWD path is `integration-tests/jars/` with pushd: https://github.com/NVIDIA/spark-rapids/blob/branch-24.02/jenkins/spark-tests.sh#L137

Comment (NvTimLiu) [reply jenkins/spark-tests.sh:278]: change to use absolute path $WORKSPACE/jenkins/test-timezones.sh

File: jenkins/spark-tests.sh
Comment (jlowe) [inline jenkins/spark-tests.sh:1]: 2024 copyrights

Comment (res-life) [reply jenkins/spark-tests.sh:1]: Done. Nice catch.

**Comment by res-life** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
