### PR TITLE
Normalize file timezone and handle missing file timezone in datetimeRebaseUtils

### LINKED ISSUE #9669: [BUG] Rebase exception states not in UTC but timezone is Etc/UTC
Saw a failure in a nightly build:
```
06:50:57    "error":"Job aborted due to stage failure.\nCaused by: ExecutionException: java.lang.UnsupportedOperationException: LEGACY datetime rebase mode is only supported for files written in UTC timezone. Actual file timezone: Etc/UTC\nCaused by: UnsupportedOperationException: LEGACY datetime rebase mode is only supported for files written in UTC timezone. Actual file timezone: Etc/UTC",
```
Looks like we're not normalizing the timezone loaded from the file before checking for equivalence to the UTC timezone.

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #9669.  Timezone is now normalized before checking if it is supported, and handling of missing timezones is updated to reflect the behavior from Apache Spark where the default timezone is assumed.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by ttnghia — APPROVED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/datetimeRebaseUtils.scala [hunk 1]
```diff
@@ -87,11 +89,16 @@ object DateTimeRebaseUtils {
 
     // Check the timezone of the file if the mode is LEGACY.
     if (mode == DateTimeRebaseLegacy) {
-      val fileTimeZone = lookupFileMeta(SPARK_TIMEZONE_METADATA_KEY)
-      if (fileTimeZone != null && fileTimeZone != "UTC") {
+      val fileTimeZoneId = Option(lookupFileMeta(SPARK_TIMEZONE_METADATA_KEY)).map { str =>
+        DateTimeUtils.getZoneId(str)
+      }.getOrElse {
+        // Use the default JVM time zone for backward compatibility
+        TimeZone.getDefault.toZoneId
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/datetimeRebaseUtils.scala:96]: the fallback should be to sqlConf.sessionLocalTimeZone

Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/datetimeRebaseUtils.scala:96]: Not accordingf to Spark source, see https://github.com/apache/spark/blob/master/sql/api/src/main/scala/org/apache/spark/sql/catalyst/util/RebaseDateTime.scala#L45

Comment (ttnghia) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/datetimeRebaseUtils.scala:96]: But when writing parquet, this is used?
```
          SPARK_TIMEZONE_METADATA_KEY -> SQLConf.get.sessionLocalTimeZone)
```

Comment (ttnghia) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/datetimeRebaseUtils.scala:96]: It seems that there is some consistency/bug in Spark? Anyway, since Spark is using default `TimeZone.getDefault.toZoneId` when reading file, we should follow it too.

Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/datetimeRebaseUtils.scala:96]: being consistent with Spark's inconsistency is fine

**Review by gerashegalov — APPROVED** [review]
LGTM
