### PR TITLE
HybridParquetScan: Fix velox runtime error in hybrid scan when filter timestamp

### LINKED ISSUE #12111: [BUG] Hit velox runtime error when filtering df with timestamp column inside when enabling hybrid
**Describe the bug**
When hybrid scan on, reading parquet files with timestamp column and filtering on it will fail with `VeloxRuntimeError`.

**Steps/Code to reproduce bug**
```shell
$SPARK_HOME/bin/spark-shell --master local[*] --jars spark-rapids/dist/target/rapids-4-spark_2.12-25.02.0-SNAPSHOT-cuda11.jar,/home/haoyangl/gluten-velox-bundle-spark3.4_2.12-ubuntu_20.04_x86_64-1.2.0.jar,/home/haoyangl/gluten-thirdparty-lib-1.2.0-ubuntu-20.04-x86_64.jar,/home/haoyangl/rapids-4-spark-hybrid_2.12-25.02.0-20250108.021606-23.jar --conf spark.plugins=com.nvidia.spark.SQLPlugin --conf spark.rapids.sql.enabled=true --conf spark.rapids.sql.explain=ALL --conf spark.sql.sources.useV1SourceList=parquet --conf spark.rapids.sql.parquet.useHybridReader=true --conf spark.rapids.sql.hybrid.loadBackend=true --conf spark.memory.offHeap.enabled=true --conf spark.memory.offHeap.size=10g
```

```scala
val df = spark.range(0, 1000).select(current_timestamp().as("timestamp"))

df.write.parquet("TEMP")

spark.read.parquet("TEMP").filter(col("timestamp") < "2000-01-01 00:00:00").show()
```

Reported error:
```
25/02/12 17:27:28 ERROR TaskSetManager: Task 0 in stage 20.0 failed 1 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure:
 Task 0 in stage 20.0 failed 1 times, most recent failure: Lost task 0.0 in stage 20.0 (TID 44) (spark-haoyang executor driver): org.apache.gluten.exception.GlutenException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: NOT_IMPLEMENTED
Reason: Subfield filters creation not supported for input type 'TIMESTAMP' in setFilterInfo
Retriable: False
Function: setFilterInfo
File: /root/gluten-public/cpp/velox/substrait/SubstraitToVeloxPlan.cc
Line: 1921
Stack trace:
# 0  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)
# 1  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(facebook::velox::detail::VeloxCheckFailArgs const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 2  gluten::SubstraitToVeloxPlanConverter::setFilterInfo(substrait::Expression_ScalarFunction const&, std::vector<std::shared_ptr<facebook::velox::Type const>, std::allocator<std::shared_ptr<facebook::velox::Type const> > > const&, std::vector<gluten::SubstraitToVeloxPlanConverter::FilterInfo, std::allocator<gluten::SubstraitToVeloxPlanConverter::FilterInfo> >&, bool)
# 3  gluten::SubstraitToVeloxPlanConverter::createSubfieldFilters(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::shared_ptr<facebook::velox::Type const>, std::allocator<std::shared_ptr<facebook::velox::Type const> > > const&, std::vector<substrait::Expression_ScalarFunction, std::allocator<substrait::Expression_ScalarFunction> > const&, std::vector<substrait::Expression_SingularOrList, std::allocator<substrait::Expression_SingularOrList> > const&)
# 4  gluten::SubstraitToVeloxPlanConverter::toVeloxPlan(substrait::ReadRel const&)
# 5  gluten::SubstraitToVeloxPlanConverter::toVeloxPlan(substrait::Rel const&)
# 6  gluten::SubstraitToVeloxPlanConverter::toVeloxPlan(substrait::RelRoot const&)
# 7  gluten::SubstraitToVeloxPlanConverter::toVeloxPlan(substrait::Plan const&)
# 8  gluten::VeloxPlanConverter::toVeloxPlan(substrait::Plan const&, std::vector<substrait::ReadRel_LocalFiles, std::allocator<substrait::ReadRel_LocalFiles> >)
# 9  gluten::VeloxRuntime::createResultIterator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::shared_ptr<gluten::ResultIterator>, std::allocator<std::shared_ptr<gluten::ResultIterator> > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)
# 10 Java_org_apache_gluten_vectorized_PlanEvaluatorJniWrapper_nativeCreateKernelWithIterator
# 11 0x00007f2594ac35ba

	at org.apache.gluten.vectorized.PlanEvaluatorJniWrapper.nativeCreateKernelWithIterator(Native Method)
	at org.apache.gluten.vectorized.NativePlanEvaluator.createKernelWithBatchIterator(NativePlanEvaluator.java:70)
	at org.apache.gluten.backendsapi.velox.VeloxIteratorApi.genFirstStageIterator(VeloxIteratorApi.scala:199)
	at org.apache.gluten.execution.GlutenWholeStageColumnarRDD.$anonfun$compute$1(GlutenWholeStageColumnarRDD.scala:88)
	at org.apache.gluten.utils.Arm$.withResource(Arm.scala:25)
	at org.apache.gluten.metrics.GlutenTimeMetric$.millis(GlutenTimeMetric.scala:37)
	at org.apache.gluten.execution.GlutenWholeStageColumnarRDD.compute(GlutenWholeStageColumnarRDD.scala:77)
	at org.apache.spark.rapids.hybrid.HybridParquetScanRDD.compute(HybridParquetScanRDD.scala:39)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:92)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:139)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Expected behavior**
Match spark

### PR DESCRIPTION
**Pull request by thirtiseven**
Fix #12111 

Timestamp is not fully supported in Hybrid Filter, so conditions with Timestamp should not pushed to Hybrid Scan in filter splitter.

This pr fixes it.

### CODE REVIEW

File: integration_tests/src/main/python/hybrid_parquet_test.py [hunk 1]
```diff
@@ -227,3 +227,19 @@ def udf_fallback(s):
     assert_gpu_and_cpu_are_equal_collect(
         lambda spark: spark.read.parquet(data_path).filter("ascii(a) >= 50 and udf_fallback(a) = 'udf_100'"),
         conf=filter_split_conf)
+
+@allow_non_gpu(*non_utc_allow)
+def test_hybrid_parquet_filter_pushdown_timestamp(spark_tmp_path):
```
Comment (revans2) [inline integration_tests/src/main/python/hybrid_parquet_test.py:232]: Does this need to be marked as a hybrid test?

**Review by revans2 — APPROVED** [review]
I see that we are missing a lot of tests around predicate push down for various data types that we say we support. Can you please file a follow on issue to test predicate push down for all data types that we support?

byte, short, int, long, float, double, date, decimal_32, decimal_64, string, struct, array, ...

I also see that we support a large number of expressions.

https://github.com/NVIDIA/spark-rapids/blob/9db03388c0b3397d1231b99e5f564696fab414c7/sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/HybridExecutionUtils.scala#L138-L295

But I don't see hardly any test coverage for these expressions as a part of predicate push down.

I don't fee comfortable saying we support something with no tests for it. Could you file an issue to add in at least some basic tests for each of these expressions too? I am okay if it is the same issue as above.

File: integration_tests/src/main/python/hybrid_parquet_test.py (hunk 1 above)
Comment (thirtiseven) [reply integration_tests/src/main/python/hybrid_parquet_test.py:235]: nice catch, thanks

**Comment by thirtiseven** [comment]
build

**Comment by thirtiseven** [comment]
Follow-up issue filed https://github.com/NVIDIA/spark-rapids/issues/12124

**Review by res-life — APPROVED** [review]

**Comment by pxLi** [comment]
build
