### PR TITLE
Use parser from spark to normalize json path in GetJsonObject

### LINKED ISSUE #10213: [BUG] GetJsonObject supports array index notation without a root
**Describe the bug**
According to both Spark and https://jsonpath.com/ a path like `[0]` or `['a']` are invalid. They need to be `$[0]` or `$['a']` to be correct.

### LINKED ISSUE #10214: [BUG] GetJsonObject does not support unquoted array like notation
**Describe the bug**
I'm not sure the correct name for this, but Spark and https://jsonpath.com/ happily support paths like `$[a]` or `$[a1]`. Our implementation throws an exception about them not being a valid number.

```
Invalid numeric index specified in JSONPath
```

### LINKED ISSUE #10215: [BUG] GetJsonObject removes leading space characters
**Describe the bug**
Spark and https://jsonpath.com/ agree that white space should not be stripped from the path. Our implementation treats `$. a` and `$.a` the same, but no other implementation I have found does that. What is more, even if the string is quoted we still end up doing the same thing `$[' b']` is the same as `$['b']`.

### PR DESCRIPTION
**Pull request by thirtiseven**
Fix #10213 
Fix #10214
Fix #10215
Contributes to https://github.com/NVIDIA/spark-rapids/issues/10216 and https://github.com/NVIDIA/spark-rapids/issues/10217

Spark has implemented a JsonPathParser to parse the json path in getJsonObject, which will have some different behavior than https://jsonpath.com/ and the cudf implementation. 

https://github.com/apache/spark/blob/78f7c30e140fd8cf4a80b783dd7e9ee4d1b4d7e2/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/jsonExpressions.scala#L59

This PR uses JsonPathParser to normalize the json path before passing it to the kernel, so GetJsonObject will better match Spark in some cases related to json path.

This PR also fallback GetJsonObject when json paths contain wildcard ("*"), as the plugin may produce different results in this case. Note that `. *` and `[ *]` will be parsed to a `Named("*")` by Spark parser, so it also checked `Named("*")` from path.

The reason why I didn't put it in kernel is I think this feature is only for Spark and we only support scalar for this parameter, so it will consume constant time to do this preprocessing.

In 10213, path not starting with a `$` like `[0]` or `['a']` should be invalid. The parser will reject these cases so this issue can be fixed.

In 10214, Spark and https://jsonpath.com/ happily support paths like `$[a]` or `$[a1]` while our implementation throws an exception about them not being a valid number. In fact, such cases should be invalid and rejected by the parser, so this PR will return nulls for them instead of passing them to the kernel and throwing an exception. So this issue can also be fixed in this PR.

In 10215, gpu and https://jsonpath.com/ agree that whitespace should not be stripped from the path, but Spark will treats `$. a` and `$.a` the same. This PR normalizes those cases so that the whitespace is stripped according to Spark's way.

In [SPARK-46761](https://issues.apache.org/jira/browse/SPARK-46761), Spark does not support `?` characters. With the parser in this PR, these cases will be rejected so that the behavior matches Spark.

### CODE REVIEW

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala [hunk 1]
```diff
@@ -32,8 +32,20 @@ case class GpuGetJsonObject(json: Expression, path: Expression)
...
-  override def doColumnar(lhs: GpuColumnVector, rhs: GpuScalar): ColumnVector = {    
-    lhs.getBase().getJSONObject(rhs.getBase, 
+  def normalizeJsonPath(path: GpuScalar): Scalar = {
+    val pathStr = if (path.isValid) {
+      path.getValue.toString()
+    } else {
+      throw new IllegalArgumentException("Invalid path")
+    }
+    // Remove all leading whitespaces before names, so we erase all whitespaces after . or ['
+    val normalizedPath = pathStr.replaceAll("""\.(\s+)""", ".").replaceAll("""\['(\s+)""", "['")
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala:42]: I don't like us using regular expressions here. It might work, but I don't see it as a good long term solution. Could we please take the code that Spark uses to parse a JSON path.

https://github.com/apache/spark/blob/78f7c30e140fd8cf4a80b783dd7e9ee4d1b4d7e2/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/jsonExpressions.scala#L59

And modify it so that we output a normalized JSON path instead.  That would also give us the ability to detect errors in the path before we send it to CUDF and make sure that we are compatible with what CUDF supports.

Meaning we really just reuse their code and then convert the `Option[List[PathInstruction]]` back to a string.

```
parsedPath match {
  case None => // ERROR return a column of nulls
  case Some(lp) =>
    val ret = new StringBuffer()
    ret.append('$')
    lp.foreach {
      case Subscript | Key => // Ignored we don't care about these
      case Wildcard => ret.append("[*]")
      case Named(name) => ret.append(s"['${name}']")
      case Index(idx) => ret.append(s"[$idx]")
      case _ => ERROR!!!!
    }
}
```

Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala]: Thanks! Updated to use JsonPathParser, this approach also looks to fix some other issue related to json path.

**Comment by thirtiseven** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala (hunk 1 above)
Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala]: Updated the PR description to explain why this PR can fix these issues.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala [hunk 2]
```diff
@@ -32,9 +106,23 @@ case class GpuGetJsonObject(json: Expression, path: Expression)
   override def nullable: Boolean = true
   override def prettyName: String = "get_json_object"
 
-  override def doColumnar(lhs: GpuColumnVector, rhs: GpuScalar): ColumnVector = {    
-    lhs.getBase().getJSONObject(rhs.getBase, 
-    GetJsonObjectOptions.builder().allowSingleQuotes(true).build());
+  def normalizeJsonPath(path: GpuScalar): Option[Scalar] = {
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala:109]: The way this code is written it looks like it is going to leak the Scalar.  Can we make this an `Option[String]` instead? That would also let us cache it, because we know that it is a constant value.

**Review by revans2 — COMMENTED** [review]
Looks good, just want to make sure we don't leak the scalar value.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala (hunk 2 above)
Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala]: Thanks, done

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala [hunk 3]
```diff
@@ -32,9 +106,30 @@ case class GpuGetJsonObject(json: Expression, path: Expression)
...
-  override def doColumnar(lhs: GpuColumnVector, rhs: GpuScalar): ColumnVector = {    
-    lhs.getBase().getJSONObject(rhs.getBase, 
-    GetJsonObjectOptions.builder().allowSingleQuotes(true).build());
+  private var cachedNormalizedPath: Option[Option[String]] = None
+
+  def normalizeJsonPath(path: GpuScalar): Option[String] = {
+    val pathStr = if (path.isValid) {
+      path.getValue.toString()
+    } else {
+      throw new IllegalArgumentException("Invalid path")
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala:115]: I don't know how big of a deal this is, but it means that the path is null. We should not throw an exception here, but we should return `None` as a null path should result in a null for all resulting values instead of an exception.

Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala]: done

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala [hunk 4]
```diff
@@ -16,11 +16,115 @@
...
+        None
+    }
+  }
+
+  def containsUnsupportedPath(instructions: List[PathInstruction]): Boolean = {
+    // Gpu GetJsonObject is not supported if JSON path contains wildcard [*]
+    // see https://github.com/NVIDIA/spark-rapids/issues/10216
+    instructions.exists {
+      case Wildcard => true
+      case Named(name) if name == "*" => true
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala:91]: I don't think this is ever possible with how Spark currently parses the path, but it is better to be safe than sorry.

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala (hunk 4 above)
Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala:91]: Spark parse Wildcard with:
```
  // child wildcards: `..`, `.*` or `['*']`
  def wildcard: Parser[List[PathInstruction]] =
    (".*" | "['*']") ^^^ List(Wildcard)
```
So things like `. *` and `[ *]` are parsed to `Named(*)` and normalized to `['*']`. In this case, Spark and gpu are also mismatched in some cases:

`{"a":{"a":"d","*":"c"}}` and `$.a. *` => cpu: `c`, gpu: `["d","c"]`

Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala:91]: Thanks
