### PR TITLE
Throw exception if casting from double to datetime 

### LINKED ISSUE #4342: Add a config to allow cast between Datetime and Numeric in ANSI mode
As part of https://github.com/apache/spark/commit/2afa52d203. Spark has added a config to cast numeric <> datetime. 

We should support this

### PR DESCRIPTION
**Pull request by razajafri**
For Spark 3.3.0+ there is a check added to throw an exception if casting from double to datetime in ANSI mode. 

fixes #4342 

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

File: sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala [hunk 1]
```diff
@@ -30,4 +30,8 @@ object RapidsErrorUtils {
     throw new NoSuchElementException(s"Key: ${elementKey} " +
       s"does not exist in any one of the rows in the map column")
   }
+
+  def preprocessCastFloatToTimestamp(input: ColumnView): Unit = {
```
Comment (jlowe) [inline sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala:34]: `RapidsErrorUtils` seems like a random class to throw this method into.  I thought the point of this class is to encapsulate how exceptions are thrown once someone has decided to throw an exception rather than house every possible method that might throw on some version of Spark?

Comment (jlowe) [inline sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala:34]: Nit: It would be nice if this method were a bit more descriptive.  `preprocess` and no return type doesn't say much about what it's doing.  Maybe something like `checkAnsiCastFloatToTimestamp`?

File: integration_tests/src/main/python/cast_test.py [hunk 2]
```diff
@@ -289,3 +289,12 @@ def test_cast_string_to_negative_scale_decimal():
...
             f.col('a').cast(DecimalType(8, -3))))
+
+@pytest.mark.skipif(is_before_spark_330(), reason="ansi cast throws exception only in 3.3.0+")
+@pytest.mark.parametrize('type', [DoubleType(), FloatType()])
+def test_cast_double_to_timestamp(type):
+    def fun(spark):
+        data=[float("inf"),float("-inf"),float("nan")]
+        df = spark.createDataFrame(data, DoubleType())
+        return df.select(f.col('value').cast(TimestampType())).collect()
+    assert_gpu_and_cpu_error(fun, {"spark.sql.ansi.enabled": True}, "java.time.DateTimeException")
```
Comment (jlowe) [inline integration_tests/src/main/python/cast_test.py:300]:
```suggestion
    assert_gpu_and_cpu_error(fun, ansi_enabled_conf, "java.time.DateTimeException")
```

File: sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala [hunk 3]
```diff
@@ -33,7 +33,7 @@ import org.apache.spark.sql.execution.datasources.v2.orc.OrcScan
 import org.apache.spark.sql.execution.datasources.v2.parquet.ParquetScan
 import org.apache.spark.sql.types.StructType
 
-trait Spark33XShims extends Spark33XFileOptionsShims {
+trait Spark33XShims extends Spark33XFileOptionsShims with Arm {
```
Comment (jlowe) [inline sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala:36]: Is this change relevant to the PR anymore?

File: integration_tests/src/main/python/cast_test.py [hunk 4]
```diff
@@ -289,3 +289,15 @@ def test_cast_string_to_negative_scale_decimal():
...
+@pytest.mark.parametrize('type', [DoubleType(), FloatType()])
+def test_cast_double_to_timestamp(type):
+    def fun(spark):
+        data=[float("inf"), float("-inf"), float("nan")]
+        df=spark.createDataFrame(
+            SparkContext.getOrCreate().parallelize([data]),
+            StructType([StructField('a', type)])
+        )
+        return df.select(f.col('a').cast(TimestampType())).collect()
+    assert_gpu_and_cpu_error(fun, {"spark.sql.ansi.enabled": True}, "org.apache.spark.SparkException")
```
[the remark this answers is not in the document]
Comment (jlowe) [reply integration_tests/src/main/python/cast_test.py]: This comment was not addressed?

[the remark this answers is not in the document]
Comment (razajafri) [reply integration_tests/src/main/python/cast_test.py]: This conf was removed as part of https://github.com/apache/spark/pull/34985. It now only relies on the ANSI mode

File: sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala (hunk 1 above)
Comment (razajafri) [reply sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala:34]: I am fine with that name. I can rename it

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/FloatUtils.scala [hunk 5]
```diff
@@ -63,21 +63,21 @@ object FloatUtils extends Arm {
...
   }
 
-  def infinityToNulls(vec: ColumnVector): ColumnVector = {
-    def getInfinityVector: ColumnVector = {
-      if (vec.getType == DType.FLOAT64) {
-        ColumnVector.fromDoubles(Double.PositiveInfinity, Double.NegativeInfinity)
-      } else {
-        ColumnVector.fromFloats(Float.PositiveInfinity, Float.NegativeInfinity)
-      }
+  def getInfinityVector(vec: ColumnView): ColumnVector = {
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/FloatUtils.scala:66]: This should just take a `DType`.  Requiring a `ColumnView` is a bit excessive when all it needs is a type, and it makes for a confusing read of the caller's code, since it's not immediately clear why `getInfinityVector` would need the input column to do its job, whereas passing the type as a parameter is very clear.

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Review by andygrove — APPROVED** [review]
