### PR TITLE
Fix index out of bound bug in iceberg parquet reader.

### LINKED ISSUE #13361: [BUG] Array index out of bounds when running iceberg query
**Describe the bug**

User faced following error when running iceberg query against tpch:

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.nvidia.spark.rapids.iceberg.parquet.GpuIcebergParquetReader.$anonfun$filterParquetBlocks$3(reader.scala:206)
	at com.nvidia.spark.rapids.iceberg.parquet.GpuIcebergParquetReader.$anonfun$filterParquetBlocks$3$adapted(reader.scala:206)

**Steps/Code to reproduce bug**

Run against tpch dataset.

**Expected behavior**

Should not throw error.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by liurenjie1024**
Fixes #13361 

### Description

In iceberg parquet reader we used row group metadata's ordinal field to get row group's position in parquet file. However this field seems unreliable and our customer runs into issues. This pr removed its usage. 

Since it's a small refactor, existing tests should already cover it.

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [ ] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Review by res-life — APPROVED** [review]
LGTM

**Comment by liurenjie1024** [comment]
build

**Comment by pxLi** [comment]
build - rekicked due to lost jenkins agent intermittently

File: iceberg/src/main/scala/com/nvidia/spark/rapids/iceberg/parquet/reader.scala [hunk 1]
```diff
@@ -203,8 +204,8 @@ trait GpuIcebergParquetReader extends Iterator[ColumnarBatch] with AutoCloseable
       }
       val (typeWithIds, fileReadSchema) = projectSchema(fileSchema, requiredSchema)
       val filteredBlocks = filterRowGroups(reader, requiredSchema, typeWithIds, file.filter)
-      val blockFirstRowIndices = filteredBlocks.map(b => rowGroupFirstRowIndices(b.getOrdinal))
-      val blocks = clipBlocksToSchema(fileReadSchema, filteredBlocks)
+      val blockFirstRowIndices = filteredBlocks.map(b => rowGroupFirstRowIndices(b._2))
```
Comment (gerashegalov) [inline iceberg/src/main/scala/com/nvidia/spark/rapids/iceberg/parquet/reader.scala:207]: I think we should use the ordinal if it the writer provided it, and fall back on the order of occurrence otherwise

**Comment by pxLi** [comment]
build

File: iceberg/src/main/scala/com/nvidia/spark/rapids/iceberg/parquet/reader.scala (hunk 1 above)
Comment (liurenjie1024) [reply iceberg/src/main/scala/com/nvidia/spark/rapids/iceberg/parquet/reader.scala:207]: There is no way to tell if the writer has set the value.

Comment (liurenjie1024) [reply iceberg/src/main/scala/com/nvidia/spark/rapids/iceberg/parquet/reader.scala:207]: cc @gerashegalov Any other concerns?

Comment (gerashegalov) [reply iceberg/src/main/scala/com/nvidia/spark/rapids/iceberg/parquet/reader.scala:207]: if getOrdinal returns 1 in the issue, I assume the writer set it.

Comment (gerashegalov) [reply iceberg/src/main/scala/com/nvidia/spark/rapids/iceberg/parquet/reader.scala:207]: I see this field was introduced for modular encryption  https://github.com/apache/parquet-format/commit/82d6253673576fcbf0590a1c1c6ff37e97c2cde8

Since it does not seem to involve out-of-order row groups just some suffix calculation, looks good
