### PR TITLE
Refactor: Fix PCBS does not fully follow the pattern for public classes

### LINKED ISSUE #3677: [BUG] PCBS does not fully follow the pattern for public classes
**Describe the bug**
PCBS stands out in the series of similar classes in that 
- it calls ShimLoadernewInstanceOf directly https://github.com/NVIDIA/spark-rapids/blob/b3f977397336ed8530e211d8c8e9fce98fbc9aa5/sql-plugin/src/main/311%2B-all/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala#L55
- "manually" implements lazy wrapping without extending scala.Proxy trait

**Steps/Code to reproduce bug**
- inspect source code

**Expected behavior**
- Tighten ShimLoader API by making `newInstanceOf` and alike `private`
- Introduce a dedicated lazy Proxy trait to uniformly tag classes like PCBS and make them implment `lazy val self`

**Environment details (please complete the following information)**
 - local
 
**Additional context**
https://github.com/NVIDIA/spark-rapids/blob/384d956390702f4f3e9157cc85ecc21ecd50e2f3/shims/README.md#L97

### PR DESCRIPTION
**Pull request by thirtiseven**
PCBS stands out in the series of similar classes in that 
- it calls ShimLoadernewInstanceOf directly https://github.com/NVIDIA/spark-rapids/blob/b3f977397336ed8530e211d8c8e9fce98fbc9aa5/sql-plugin/src/main/311%2B-all/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala#L55
- "manually" implements lazy wrapping without extending `scala.Proxy` trait
 
This PR:  
- Introduced a dedicated lazy Proxy trait to PCBS and make them implement  `lazy val self`.
- Made `ShimLoader.newInstanceOf` private.  
- Added `ShimLoader.newOptimizerClass`  to load the optimizer class specifically .  This function will only be called at `GpuOverrides.scala` once.

Signed-off-by: thirtiseven <ntlihy@gmail.com>

Fixes #3677

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala [hunk 1]
```diff
@@ -39,11 +39,9 @@ trait GpuCachedBatchSerializer extends CachedBatchSerializer {
 /**
  * User facing wrapper class that calls into the internal version.
  */
-class ParquetCachedBatchSerializer extends GpuCachedBatchSerializer {
+class ParquetCachedBatchSerializer extends GpuCachedBatchSerializer with Proxy {
```
Comment (res-life) [inline sql-plugin/src/main/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala:42]: Nit: 
Proxy is deprecated in Scala 2.13: https://www.scala-lang.org/api/2.13.x/scala/Proxy.html
Although we are using 2.12 currently, we'll get a warning in the future after Scala is upgraded to 2.13.
```
<scala.binary.version>2.12</scala.binary.version>
```

**Review by razajafri — APPROVED** [review]

**Comment by thirtiseven** [comment]
build

**Review by res-life — APPROVED** [review]
