### PR TITLE
Move classes out of Apache Spark packages

### LINKED ISSUE #3235: Classes directly in Apache Spark packages
Most classes are either under the com.nvidia.spark.rapids, org.apache.spark.sql.rapids, or some other Spark package prefix that ends in `.rapids`, but there are a few classes in the plugin that appear directly within an Apache Spark package:
- org.apache.spark.sql.catalyst.CudfUnsafeRow
- org.apache.spark.shuffle.RapidsShuffleExceptions.scala

Ideally these classes should be moved to an existing `*.rapids` package.

### PR DESCRIPTION
**Pull request by jbrennan333**
Fixes #3235

### CODE REVIEW

**Comment by jbrennan333** [comment]
build

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/catalyst/CudfUnsafeRow.java [hunk 1]
```diff
@@ -14,9 +14,10 @@
  * limitations under the License.
  */
 
-package org.apache.spark.sql.catalyst;
+package com.nvidia.spark.rapids.catalyst;
```
Comment (jlowe) [inline sql-plugin/src/main/java/com/nvidia/spark/rapids/catalyst/CudfUnsafeRow.java:17]: Nit: Why isn't this just under com.nvidia.spark.rapids?  The `com.nvidia.spark.rapids.catalyst` package doesn't exist before this PR, and arguably many things under the former would be candidates for the latter since they deal with Catalyst.

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/catalyst/CudfUnsafeRow.java [hunk 2]
```diff
@@ -14,9 +14,10 @@
...
 
 import com.nvidia.spark.rapids.GpuColumnVector;
+import org.apache.spark.sql.catalyst.InternalRow;
```
Comment (jlowe) [inline sql-plugin/src/main/java/com/nvidia/spark/rapids/catalyst/CudfUnsafeRow.java:20]: There's supposed to be a whitespace between the Spark imports.  See https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/CONTRIBUTING.md#code-formatting and the sample code formatting file.

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/catalyst/CudfUnsafeRow.java (hunk 1 above)
Comment (jbrennan333) [reply sql-plugin/src/main/java/com/nvidia/spark/rapids/catalyst/CudfUnsafeRow.java:17]: Agreed.  I will move it to com.nvidia.spark.rapids

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/catalyst/CudfUnsafeRow.java (hunk 2 above)
Comment (jbrennan333) [reply sql-plugin/src/main/java/com/nvidia/spark/rapids/catalyst/CudfUnsafeRow.java:20]: Thanks!  This helped me realize I was not using the correct profile in IntelliJ.

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build
