### PR TITLE
Handle caused-by retry exceptions in withRestoreOnRetry

### LINKED ISSUE #7971: [BUG] withRestoreOnRetry should look at Throwable causes in addition to retry OOMs
Re: https://github.com/NVIDIA/spark-rapids/pull/7958

While debugging an issue with https://github.com/NVIDIA/spark-rapids/pull/7925 I ran into an issue where an UDF was failing to allocate a GPU buffer due to an injected OOM, but then it turns around and wraps it into its own exception:

```
Caused by: org.apache.spark.SparkException: Failed to execute user defined function: (emptygeneric: (string) => string)
```

This means the retry is hidden in the cause by, so I had to change the logic in the retry iterator to account for it. @jbrennan333, we'll need to adapt the new `withRestoreOnRetry` as well to account for this.

### PR DESCRIPTION
**Pull request by jbrennan333**
Closes #7971.

In `withRestoreOnRetry`, we should restore on exceptions that are caused by `RetryOOM` or `SplitAndRetryOOM`, in addition to checking the top-level exception.  This brings it in line with the handling in `RmmRapidsRetryIterator`.
This include a little refactoring to avoid some code duplication.

### CODE REVIEW

**Comment by jbrennan333** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala [hunk 1]
```diff
@@ -197,12 +227,19 @@ object RmmRapidsRetryIterator extends Arm with Logging {
...
-      case t: RetryOOM =>
-        r.restore()
-        throw t
-      case t: SplitAndRetryOOM =>
-        r.restore()
-        throw t
+      case ex: Throwable =>
+        // Only restore on retry exceptions
+        val (topLevelIsRetry, _) = isRetryOrSplitAndRetry(ex)
+        val causedByRetry = topLevelIsRetry match {
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:233]: given the or in line 239, I don't think this match is necessary.
```
val (causedByRetry, _) = causedByRetryOrSplit(ex)
```

Then the the or is "top level OR caused", so this would be equivalent.

**Review by abellina — COMMENTED** [review]
just a nit

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 1 above)
Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:233]: I was trying to avoid calling `causedByRetryOrSplit` unless needed.  Does the OR accomplish this by itself?  It's a light enough function that it is probably worth just calling it to make code simplet.

Comment (abellina) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:233]: good point, fine not to. It's fine not to change this it was just a nit.

**Review by abellina — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Review by abellina — APPROVED** [review]

**Comment by jbrennan333** [comment]
build
