### PR TITLE
ParquetCachedBatchSerializer: Close the hostBatch in ColumnBatchToCachedBatchIterator when the iterator has exhausted

### LINKED ISSUE #6425: [BUG] Host column leak detected in ParquetCachedBatchSerializer tests
Saw this in a CI test log which indicates there's a host column leak in `CachedBatchWriterSuite.testColumnarBatchToCachedBatchIterator`
```
[2022-08-25T14:18:08.780Z] 22/08/25 14:18:08.512 Cleaner Thread ERROR HostColumnVector: A HOST COLUMN VECTOR WAS LEAKED (ID: 39495)
[2022-08-25T14:18:08.781Z] 22/08/25 14:18:08.516 Cleaner Thread ERROR MemoryCleaner: Leaked vector (ID: 39495): 2022-08-25 14:18:08.0166 UTC: INC
[2022-08-25T14:18:08.781Z] java.lang.Thread.getStackTrace(Thread.java:1564)
[2022-08-25T14:18:08.781Z] ai.rapids.cudf.MemoryCleaner$RefCountDebugItem.<init>(MemoryCleaner.java:333)
[2022-08-25T14:18:08.781Z] ai.rapids.cudf.MemoryCleaner$Cleaner.addRef(MemoryCleaner.java:91)
[2022-08-25T14:18:08.781Z] ai.rapids.cudf.HostColumnVector.incRefCountInternal(HostColumnVector.java:147)
[2022-08-25T14:18:08.781Z] ai.rapids.cudf.HostColumnVector.<init>(HostColumnVector.java:93)
[2022-08-25T14:18:08.781Z] ai.rapids.cudf.ColumnView.copyToHost(ColumnView.java:4709)
[2022-08-25T14:18:08.781Z] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-08-25T14:18:08.781Z] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-08-25T14:18:08.781Z] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-08-25T14:18:08.781Z] java.lang.reflect.Method.invoke(Method.java:498)
[2022-08-25T14:18:08.781Z] org.mockito.internal.util.reflection.ReflectionMemberAccessor.invoke(ReflectionMemberAccessor.java:45)
[2022-08-25T14:18:08.781Z] org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:43)
[2022-08-25T14:18:08.781Z] org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:329)
[2022-08-25T14:18:08.781Z] org.mockito.internal.creation.bytebuddy.MockMethodAdvice.access$500(MockMethodAdvice.java:56)
[2022-08-25T14:18:08.781Z] org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:249)
[2022-08-25T14:18:08.781Z] org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:141)
[2022-08-25T14:18:08.781Z] org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
[2022-08-25T14:18:08.781Z] org.mockito.Answers.answer(Answers.java:98)
[2022-08-25T14:18:08.781Z] org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:106)
[2022-08-25T14:18:08.781Z] org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
[2022-08-25T14:18:08.781Z] org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
[2022-08-25T14:18:08.781Z] org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
[2022-08-25T14:18:08.781Z] org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:147)
[2022-08-25T14:18:08.781Z] ai.rapids.cudf.ColumnView.copyToHost(ColumnView.java:4678)
[2022-08-25T14:18:08.781Z] com.nvidia.spark.rapids.GpuColumnVector.copyToHost(GpuColumnVector.java:1128)
[2022-08-25T14:18:08.781Z] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-08-25T14:18:08.781Z] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-08-25T14:18:08.781Z] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-08-25T14:18:08.781Z] java.lang.reflect.Method.invoke(Method.java:498)
[2022-08-25T14:18:08.781Z] org.mockito.internal.util.reflection.ReflectionMemberAccessor.invoke(ReflectionMemberAccessor.java:45)
[2022-08-25T14:18:08.781Z] org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:43)
[2022-08-25T14:18:08.781Z] org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:329)
[2022-08-25T14:18:08.781Z] org.mockito.internal.creation.bytebuddy.MockMethodAdvice.access$500(MockMethodAdvice.java:56)
[2022-08-25T14:18:08.781Z] org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:249)
[2022-08-25T14:18:08.781Z] org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:141)
[2022-08-25T14:18:08.781Z] org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
[2022-08-25T14:18:08.782Z] org.mockito.Answers.answer(Answers.java:98)
[2022-08-25T14:18:08.782Z] org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:106)
[2022-08-25T14:18:08.782Z] org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
[2022-08-25T14:18:08.782Z] org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
[2022-08-25T14:18:08.782Z] org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
[2022-08-25T14:18:08.782Z] org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:147)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.GpuColumnVector.copyToHost(GpuColumnVector.java:1128)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$ColumnarBatchToCachedBatchIterator$$anon$7.$anonfun$hostBatch$2(ParquetCachedBatchSerializer.scala:1108)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableFromBatchColumns.$anonfun$safeMap$2(implicits.scala:282)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableFromBatchColumns.$anonfun$safeMap$2$adapted(implicits.scala:282)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:216)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:213)
[2022-08-25T14:18:08.782Z] scala.collection.immutable.Range.foreach(Range.scala:158)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:213)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableFromBatchColumns.safeMap(implicits.scala:282)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$ColumnarBatchToCachedBatchIterator$$anon$7.$anonfun$hostBatch$1(ParquetCachedBatchSerializer.scala:1108)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.ParquetCachedBatchSerializer.withResource(ParquetCachedBatchSerializer.scala:260)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$ColumnarBatchToCachedBatchIterator$$anon$7.<init>(ParquetCachedBatchSerializer.scala:1107)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$ColumnarBatchToCachedBatchIterator.getIterator(ParquetCachedBatchSerializer.scala:1101)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$InternalRowToCachedBatchIterator.next(ParquetCachedBatchSerializer.scala:1038)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$InternalRowToCachedBatchIterator.next(ParquetCachedBatchSerializer.scala:923)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.CachedBatchWriterSuite.testColumnarBatchToCachedBatchIterator(CachedBatchWriterSuite.scala:250)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.CachedBatchWriterSuite.$anonfun$new$8(CachedBatchWriterSuite.scala:86)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.CachedBatchWriterSuite.$anonfun$new$8$adapted(CachedBatchWriterSuite.scala:80)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.CachedBatchWriterSuite.withResource(CachedBatchWriterSuite.scala:38)
[2022-08-25T14:18:08.782Z] com.nvidia.spark.rapids.CachedBatchWriterSuite.$anonfun$new$7(CachedBatchWriterSuite.scala:80)
```

### PR DESCRIPTION
**Pull request by razajafri**
We are leaking host batches in unit tests because there is no TaskContext which we use to determine the end of a task before closing these batches. 

To avoid polluting the logs with leak logs this PR closes the hostBatches as the iterator is exhausted

fixes #6425

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

**Comment by razajafri** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala [hunk 1]
```diff
@@ -1096,14 +1096,17 @@ protected class ParquetCachedBatchSerializer extends GpuCachedBatchSerializer wi
      * is called on this iterator
      */
     class ColumnarBatchToCachedBatchIterator extends InternalRowToCachedBatchIterator {
+      // Exposing this just for tests to close the batch
+      var hostBatch: ColumnarBatch = null
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1100]: A cleaner way to handle this is to have `ColumnarBatchToCachedBatchIterator` implement `AutoCloseable` so the calling code can call `close()` to clean up anything that needs to be cleaned rather than reaching into the internals.

Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1100]: Not necessarily for this PR, but should `hostBatch` be closed proactively when the iterator is exhausted?  We don't want to unnecessarily hold onto host batches until the task finishes.

Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1100]: But who will call close? We are returning this `ColumnarBatchToCachedBatchIterator` to `InMemoryRelation` which is calling this from `buildBuffers`. Only once the persistence is done is when we can possibly close the batch and there is no callback for that right now.

Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1100]: We are mapping the GPU column to HOST column and that happens lazily. Even though the iterator is exhausted, the hostBatch is still needed later downstream which is why we are using the `TaskContext`.

Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1100]: The close would be called by the testing code, just like it's trying to close the hostBatch now.  It's avoiding the need to expose internals on how to cleanup and then make the test know more than it should about how to cleanup the instance.

Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1100]: But eventually downstream will iterate past the hostBatch, and then the hostBatch should close.  Or am I missing some place where it is still needed?  Curious why we need to wait until the entire task completes to know it's safe to close the hostBatch.  We should not rely on the task completion to close the host batch in the typical case where everything is consumed.

Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1100]: I wasn't referring to test. but anyways, I finally understand what you are saying. Will push an update

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala [hunk 2]
```diff
@@ -1095,13 +1105,11 @@ protected class ParquetCachedBatchSerializer extends GpuCachedBatchSerializer wi
      * relationship. Each ColumnarBatch is converted to a single ParquetCachedBatch when next()
      * is called on this iterator
      */
-    class ColumnarBatchToCachedBatchIterator extends InternalRowToCachedBatchIterator {
-      override def getIterator: Iterator[InternalRow] = {
-
-        new Iterator[InternalRow] {
-          // We have to check for null context because of the unit test
-          Option(TaskContext.get).foreach(_.addTaskCompletionListener[Unit](_ => hostBatch.close()))
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1103]: We cannot remove this, because there's no guarantee the iterator is completely drained before the task completes (e.g.: limit query, task exception, etc.).

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala [hunk 3]
```diff
@@ -1095,13 +1105,11 @@ protected class ParquetCachedBatchSerializer extends GpuCachedBatchSerializer wi
...
+    class ColumnarBatchToCachedBatchIterator extends InternalRowToCachedBatchIterator
+        with AutoCloseable {
+      val hostBatches = new ListBuffer[ColumnarBatch]()
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1110]: Nothing is ever added to `hostBatches`.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala (hunk 2 above)
Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1103]: aah. didn't think of an early exit. 

I have added this back.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala (hunk 3 above)
Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1110]: Thanks, I have added a test to make sure we throw

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala [hunk 4]
```diff
@@ -1095,32 +1105,44 @@ protected class ParquetCachedBatchSerializer extends GpuCachedBatchSerializer wi
...
-          override def next: InternalRow = rowIterator.next
+        override def next: InternalRow = rowIterator.next
 
-          override def hasNext: Boolean = rowIterator.hasNext
+        override def hasNext: Boolean = rowIterator.hasNext
+      }
 
-        }
+      override def close(): Unit = {
+        hostBatches.foreach(_.close())
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1143]: This needs to guard against double-close, because now we're closing it when the iteration completes _and_ when the task completes.  That means by default the task will crash under normal operation.  One easy way to resolve this:
```suggestion
      override def close(): Unit = {
        hostBatches.foreach(_.close())
        hostBatches.clear()
```

File: tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala [hunk 5]
```diff
@@ -250,6 +242,8 @@ class CachedBatchWriterSuite extends SparkQueryCompareTestSuite {
       val cb = cachedBatchIter.next()
       totalRows += cb.numRows
     }
+    assertThrows[IllegalStateException](
+      cachedBatchIter.asInstanceOf[producer.ColumnarBatchToCachedBatchIterator].close())
```
Comment (jlowe) [inline tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala:246]: The close shouldn't throw per the discussion above about close being called twice under normal circumstances.  I think the line above that is:
```scala
  val cachedBatchIter = producer.getColumnarBatchToCachedBatchIterator
```
should be
```scala
  withResource(producer.getColumnarBatchToCachedBatchIterator) { cachedBatchIter =>
```

Comment (razajafri) [reply tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala:246]: I thought the suggestion was to close the iterator automatically when it is exhausted. No need to call close on it then

Comment (jlowe) [reply tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala:246]: If the test crashes (i.e.: one way test does not pass) then we would like to clean up, if possible.

**Comment by razajafri** [comment]
build

File: tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala [hunk 6]
```diff
@@ -242,15 +235,17 @@ class CachedBatchWriterSuite extends SparkQueryCompareTestSuite {
...
-      totalRows += cb.numRows
+    withResource(producer.getColumnarBatchToCachedBatchIterator
+        .asInstanceOf[Iterator[CachedBatch] with AutoCloseable]) { cachedBatchIter =>
+        cachedBatchIter.asInstanceOf[producer.ColumnarBatchToCachedBatchIterator]
+            .setParquetOutputFileFormat(mockParquetOutputFileFormat)
+        var totalRows = 0
+        while (cachedBatchIter.hasNext) {
+          val cb = cachedBatchIter.next()
+          totalRows += cb.numRows
+        }
```
[the remark this answers is not in the document]
Comment (gerashegalov) [reply tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala:246]: nit: map with sum results in two loops. I recommend a fold
```scala 
val totalRows = cachedBatchIter.foldLeft(0)(_ + _.numRows)
```

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM
