### PR TITLE
[AutoSparkUT] Fix GpuDivideYMInterval to throw correct divide-by-zero exception

### LINKED ISSUE #14155: [AutoSparkUT]"SPARK-34868: divide year-month interval by numeric" in ColumnExpressionSuite failed
**Describe the bug**
["SPARK-34868: divide year-month interval by numeric"](https://github.com/apache/spark/blob/v3.3.0/sql/core/src/test/scala/org/apache/spark/sql/ColumnExpressionSuite.scala#L2738) in ColumnExpressionSuite failed.

GPU threw the exception with different content from CPU.

**Steps/Code to reproduce bug**
spark-shell:
```
/data/spark-3.3.0-bin-hadoop3/bin/spark-shell   --master local[2]   --conf spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation,org.apache.spark.sql.catalyst.optimizer.ConstantFolding   --conf spark.rapids.sql.enabled=true   --conf spark.plugins=com.nvidia.spark.SQLPlugin   --conf spark.sql.queryExecutionListeners=org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback   --conf spark.rapids.sql.explain=ALL   --conf spark.rapids.sql.test.isFoldableNonLitAllowed=true   --conf spark.rapids.sql.csv.read.decimal.enabled=true   --conf spark.rapids.sql.format.avro.enabled=true   --conf spark.rapids.sql.format.avro.read.enabled=true   --conf spark.rapids.sql.format.json.enabled=true   --conf spark.rapids.sql.format.json.read.enabled=true   --conf spark.rapids.sql.incompatibleDateFormats.enabled=true   --conf spark.rapids.sql.python.gpu.enabled=true   --conf spark.rapids.sql.rowBasedUDF.enabled=true   --conf spark.rapids.sql.window.collectList.enabled=true   --conf spark.rapids.sql.window.collectSet.enabled=true   --conf spark.rapids.sql.window.range.byte.enabled=true   --conf spark.rapids.sql.window.range.short.enabled=true   --conf spark.rapids.sql.expression.Ascii=true   --conf spark.rapids.sql.expression.Conv=true   --conf spark.rapids.sql.expression.GetJsonObject=true   --conf spark.rapids.sql.expression.JsonToStructs=true   --conf spark.rapids.sql.expression.StructsToJson=true   --conf spark.rapids.sql.exec.CollectLimitExec=true   --conf spark.rapids.sql.exec.FlatMapCoGroupsInPandasExec=true   --conf spark.rapids.sql.exec.WindowInPandasExec=true   --conf spark.rapids.sql.hasExtendedYearValues=false   --conf spark.unsafe.exceptionOnMemoryLeak=true   --conf spark.sql.session.timeZone=UTC
```

Scala code:
```
import java.time.Period

// java.lang.ArithmeticException: overflow: interval / zero, but expect "Division by zero"
Seq((Period.ofYears(9999), 0)).toDF("i", "n").select($"i" / $"n").collect()
Seq((Period.ofYears(9999), 0d)).toDF("i", "n").select($"i" / $"n").collect()
```

**Expected behavior**
GPU should throw same exception as CPU does.

**Environment details (please complete the following information)**
 - Environment location: [Spark 330 local mode]

### PR DESCRIPTION
**Pull request by wjxiz1992**
## Summary

- **Fix**: `GpuDivideYMInterval` was missing the zero-divisor guard that `GpuDivideDTInterval` already had. When dividing a year-month interval by zero, the GPU threw incorrect exceptions (`ArithmeticException("overflow: interval / zero")` for int, `ArithmeticException("Has infinity")` for double) instead of `SparkArithmeticException("Division by zero")`.
- **Change**: Added early zero-divisor checks in all `doColumnar` overloads of `GpuDivideYMInterval` using `RapidsErrorUtils.intervalDivByZeroError(origin)`, matching the pattern already used in `GpuDivideDTInterval`.
- **Test**: Removed the `.exclude()` for `"SPARK-34868: divide year-month interval by numeric"` from `RapidsTestSettings` — the original inherited test now passes on GPU.

Closes #14155

## Test plan

- [x] `mvn test -pl tests -Dbuildver=330 -Dsuites=org.apache.spark.sql.rapids.suites.RapidsColumnExpressionSuite`
  - Before: Tests: succeeded 145, failed 0, ignored 4
  - After: Tests: succeeded 146, failed 0, ignored 3
  - Target test `SPARK-34868: divide year-month interval by numeric` passed
  - No new failures introduced

## Traceability

| Field | Value |
|---|---|
| RAPIDS test | `RapidsColumnExpressionSuite` (inherited from `ColumnExpressionSuite`) |
| Spark original test | `SPARK-34868: divide year-month interval by numeric` |
| Spark source file | `sql/core/src/test/scala/org/apache/spark/sql/ColumnExpressionSuite.scala` |
| Line range | 2888-2929 |
| Source link (master) | [ColumnExpressionSuite.scala#L2888](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/ColumnExpressionSuite.scala#L2888) |

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by wjxiz1992** [comment]
build

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala [hunk 1]
```diff
@@ -488,44 +488,86 @@ case class GpuDivideYMInterval(
...
-    doColumnar(interval.getBase, num.getBase, num.dataType)
-  }
-
-  override def doColumnar(intervalScalar: GpuScalar, num: GpuColumnVector): ColumnVector = {
-    doColumnar(intervalScalar.getBase, num.getBase, num.dataType)
+  override def doColumnar(
+      interval: GpuColumnVector,
+      numScalar: GpuScalar): ColumnVector = {
+    withResource(
+      makeZeroScalar(numScalar.getBase.getType)) {
```
Comment (thirtiseven) [inline sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala]: There is a lot of duplicated logic for this. Maybe we can just put the zero check to `doColumnar(BinaryOperable, BinaryOperable, DataType)` and do a pattern matching:
```scala
private def doColumnar(interval: BinaryOperable, numOperable: BinaryOperable,
    numType: DataType): ColumnVector = {
  numOperable match {
    case s: Scalar =>
      withResource(makeZeroScalar(s.getType)) { zero =>
        if (s.equals(zero)) throw RapidsErrorUtils.intervalDivByZeroError(origin)
      }
    case cv: ColumnVector =>
      withResource(makeZeroScalar(cv.getType)) { zero =>
        if (cv.contains(zero)) throw RapidsErrorUtils.intervalDivByZeroError(origin)
      }
  }
...
```

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala [hunk 2]
```diff
@@ -488,44 +488,86 @@ case class GpuDivideYMInterval(
...
-    doColumnar(interval.getBase, numScalar.getBase, num.dataType)
-  }
-
-  override def doColumnar(interval: GpuColumnVector, num: GpuColumnVector): ColumnVector = {
-    doColumnar(interval.getBase, num.getBase, num.dataType)
-  }
-
-  override def doColumnar(intervalScalar: GpuScalar, num: GpuColumnVector): ColumnVector = {
-    doColumnar(intervalScalar.getBase, num.getBase, num.dataType)
+  override def doColumnar(
```
Comment (thirtiseven) [inline sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala]: The code style in the whole PR is very different from the rest of the file. I suppose it's due to a line length limit rule. Our limit is 100 characters.

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala [hunk 3]
```diff
@@ -488,44 +488,86 @@ case class GpuDivideYMInterval(
...
-  private def doColumnar(interval: BinaryOperable, numOperable: BinaryOperable,
+  private def doColumnar(
+      interval: BinaryOperable,
+      numOperable: BinaryOperable,
       numType: DataType): ColumnVector = {
 
     numType match {
       case ByteType | ShortType | IntegerType | LongType =>
-        // interval is long; num is byte, short, int or long
-        // For overflow check: num is 0; interval == Long.Min && num == -1
```
Comment (thirtiseven) [inline sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala:516]: Not sure why we remove this. They still look useful.

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala (hunk 2 above)
Comment (wjxiz1992) [reply sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala]: Cursor actually changes its style after I asked to respect 100 line length, after I found a length failure check in  https://github.com/NVIDIA/spark-rapids/pull/14349/changes/e93b7f46f6e074879bd4c1d6c6a19902448fc30d, but it  seems to be too aggressive. Let me see if I can make it relax alittle bit

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala (hunk 1 above)
Comment (wjxiz1992) [reply sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala]: Done. Consolidated the zero check into the private `doColumnar(BinaryOperable, BinaryOperable, DataType)` with pattern matching exactly as suggested. Also restored the original code style (no aggressive line splitting) and kept the comments in the `numType match` branches. Additionally fixed the stale comment (`interval is long` → `interval is int`, `Long.Min` → `Int.Min`) since YM interval is INT32.

Merged origin/main to resolve the conflict, and local test passes:
```
Tests: succeeded 147, failed 0, ignored 2
SPARK-34868: divide year-month interval by numeric  ✓
```

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala (hunk 3 above)
Comment (wjxiz1992) [reply sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala:516]: Restored. Also corrected `interval is long` → `interval is int` and `Long.Min` → `Int.Min` since YM interval stores months as INT32, not INT64 like DT interval.

**Comment by wjxiz1992** [comment]
build
