### PR TITLE
Fix scalar leak in RankFixer

### LINKED ISSUE #10473: [BUG] Leak when running RANK query
The following query when run on NDS data will trigger a leftover RMM allocation warning when the spark-shell session is shutdown.
```
select * from ( select rank() over ( order by ss_sold_date_sk, ss_item_sk, ss_ticket_number, ss_customer_sk ) as rank from store_sales ) a where rank < 100
[...]
24/02/22 21:07:51 WARN GpuDeviceManager: Waiting for outstanding RMM allocations to be released...
24/02/22 21:08:01 WARN GpuDeviceManager: Shutting down RMM even though there are outstanding allocations 512
```

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #10473.  Updates the RankFixer.close() method to close the BatchedRunningWindowBinaryFixer instance which is caching a scalar.

### CODE REVIEW

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala [hunk 1]
```diff
@@ -1711,6 +1711,7 @@ class RankFixer extends BatchedRunningWindowFixer with Logging {
   override def close(): Unit = {
     previousRank.foreach(_.close())
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala:1712]: Should we also change?

```suggestion
    previousRank.foreach(_.safeClose())
```

**Comment by jlowe** [comment]
build

**Review by mythrocks — APPROVED** [review]
Yikes.  Good catch.  Thanks for finding this, @jlowe.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala (hunk 1 above)
Comment (mythrocks) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala]: Ah, it turns out that `cudf.Scalar` objects cannot be `safeClose()`d:
```
Error: ] /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala:1712: value safeClose is not a member of ai.rapids.cudf.Scalar
2345
Error: [ERROR] one error found
```

**Comment by gerashegalov** [comment]
@mythrocks it just needs an RapidsPluginImplicits import

**Comment by gerashegalov** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Review by mythrocks — APPROVED** [review]
Thanks! TIL `RapidsPluginImplicits`.
