### PR TITLE
Normalize nans in GpuSortArray

### LINKED ISSUE #6438: [BUG] `GpuSortArray` doesn't match the behavior of Spark when handling `Nan`s
**Describe the bug**
When apply the `GpuSortArray` on an array containing `nan`s, the `nan` values aren't always sorted to the end of the array.

**Steps/Code to reproduce bug**
```
>>> import struct
>>> bytes1 = struct.pack('L', 0x7ff83cec2c05b870)
>>> bytes2 = struct.pack('L', 0xfff5101d3f1cd31b)
>>> bytes3 = struct.pack('L', 0x7c22453f18c407a8)
>>> nan1 = struct.unpack('d', bytes1)[0]
>>> nan2 = struct.unpack('d', bytes2)[0]
>>> other = struct.unpack('d', bytes3)[0]
>>> (nan1, nan2, other)
(nan, nan, 8.902585073221772e+289)

>>> data = [([nan2] + [other for _ in range(256)] + [nan1],)]
>>> df = sc.parallelize(data).toDF()

>>> spark.conf.set('spark.rapids.sql.enabled', 'false')
>>> df.selectExpr('sort_array(_1)').collect()
[Row(sort_array(_1, true)=[8.902585073221772e+289,  ..., 8.902585073221772e+289, 8.902585073221772e+289, 8.902585073221772e+289, nan, nan])]

>>> spark.conf.set('spark.rapids.sql.enabled', 'true')
>>> df.selectExpr('sort_array(_1)').collect()
22/08/29 12:26:35 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> sort_array(_1#18, true) AS sort_array(_1, true)#22 will run on GPU
    *Expression <SortArray> sort_array(_1#18, true) will run on GPU
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> _1#18 could run on GPU

[Row(sort_array(_1, true)=[nan, 8.902585073221772e+289, ..., 8.902585073221772e+289, 8.902585073221772e+289, nan])]
```
When enabling the GPU, one `nan` is sorted to the head, the other is sorted to the end.
I am not sure whether this is related to the different bit representations of `nan`. Or maybe this is a bug in cuDF.

**Expected behavior**
The `GpuSortArray` should always treat `nan`s as the max values. 

**Environment details (please complete the following information)**
 - Environment location: local
 - Spark configuration settings related to the issue
PySpark 3.3.0
spark-rapids 22.10

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>
Close #6438.

## Changes in this PR.
In `GpuSortArray`, we call `normalize_nans_and_zeros` on the child column of the input before sorting. 

### Pros
`Nans` can have different orderings in `sort_array` because of the different bit representation. The normalization can make the ordering of sorting result to be stable when the array contains nans.

### Cons
`normalize_nans_and_zeros` will also normalize `0.0` and `-0.0`, which makes them indistinguishable. But as this is a known compatibility issue (https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/compatibility.md#00-vs--00), it will not introduce new bugs.

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

**Review by revans2 — DISMISSED** [review]
I am okay with this as a fix, but I really would like to hear from others in CUDF if this is expected behavior. I saw on a slack channel not too long ago that NaN handling is consistent now for comparisons, but this does not feel consistent, because we don't have to normalize the nans for other sort or comparison operations.

**Comment by HaoYang670** [comment]
Agree with you @revans2. We need a review from a cuDF maintainer.
Actually, the data_gen of `test_sort_array` has covered the `Nan` case, but doesn't detect the bug. (So, I am not sure whether other comparison expressions also have this bug.)

**Comment by revans2** [comment]
I am guessing that `test_sort_array` does not show the bug because of probability.  I am not an expert on probability, and this is a complicated question, but my guess is that because we use psudo random numbers and the length of the array is not that big and the probability of inserting a NaN into the array is not that big, and neither is the probability of inserting a -NaN into the array, that we just got unlucky.

But for a regular sort we just need to have a -NaN and a +NaN in the column we are sorting by. So if we are picking 2048 times instead of 20 times it feels much more likely to have happened. But we might want to add in some special cases to verify that it is working exactly as expected without data generation.

**Comment by ttnghia** [comment]
In cudf there are two code paths for sorting arrays. If the average array size is no more than `100`, one code path is executed which can handle `NaN` stably using cudf's row comparator. If the average array size exceeds `100`, `cub` radix sort is executed which relies entirely on the bit representation of the input.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 1]
```diff
@@ -407,13 +407,38 @@ case class GpuSortArray(base: Expression, ascendingOrder: Expression)
...
+      case ArrayType(FloatType | DoubleType, _) =>
+        withResource(base.getChildColumnView(0)) {child =>
+          withResource(child.normalizeNANsAndZeros()) {normalizedChild =>
+            withResource(base.replaceListChild(normalizedChild)) {normalizedList =>
+              normalizedList.listSortRows(isDescending, true)
+            }
+          }
+        }
+      case _ =>
+        base.listSortRows(isDescending, true)
```
Comment (ttnghia) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: I'm a bit confused. If `dataType` is not array then how can we call `base.listSortRows`? I thought that this is only callable for `ArrayType`, isn't it?

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 2]
```diff
@@ -407,13 +407,38 @@ case class GpuSortArray(base: Expression, ascendingOrder: Expression)
...
+          withResource(base.getChildColumnView(0)) {child =>
+            withResource(child.normalizeNANsAndZeros()) {normalizedChild =>
+              withResource(base.replaceListChild(normalizedChild)) {normalizedList =>
+                normalizedList.listSortRows(isDescending, true)
+              }
+            }
+          }
+        case _ =>
+          base.listSortRows(isDescending, true)
+      }
```
Comment (ttnghia) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:441]: Just `return doColumnar(cv, rhs)`?

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 1 above)
Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: We have the `checkInputDatatype` function to make sure the data type can only be `ArrayType`
```scala
  override def checkInputDataTypes(): TypeCheckResult = base.dataType match {
    case ArrayType(dt, _) if RowOrdering.isOrderable(dt) =>
      ascendingOrder match {
        // replace Literal with GpuLiteral here
        case GpuLiteral(_: Boolean, BooleanType) =>
          TypeCheckResult.TypeCheckSuccess
        case order =>
          TypeCheckResult.TypeCheckFailure(
            s"Sort order in second argument requires a boolean literal, but found $order")
      }
    case ArrayType(dt, _) =>
      val dtSimple = dt.catalogString
      TypeCheckResult.TypeCheckFailure(
        s"$prettyName does not support sorting array of type $dtSimple which is not orderable")
    case dt =>
      TypeCheckResult.TypeCheckFailure(s"$prettyName only supports array input, but found $dt")
  }
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 2 above)
Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala]: Updated.

**Comment by HaoYang670** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 1 above)
Comment (ttnghia) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: Even if that's the case, I think we should make sure the type is correct here again to reduce dependency. How about this:
```
case ArrayType(FloatType | DoubleType, _) => ....
case ArrayType(_, _) => ....
case _ => throw new [SomeTypeException]("...")

```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 3]
```diff
@@ -407,13 +407,24 @@ case class GpuSortArray(base: Expression, ascendingOrder: Expression)
 
   override def doColumnar(lhs: GpuColumnVector, rhs: GpuScalar): cudf.ColumnVector = {
     val isDescending = isDescendingOrder(rhs)
-    lhs.getBase.listSortRows(isDescending, true)
+    val base = lhs.getBase()
+    dataType match {
+      case ArrayType(FloatType | DoubleType, _) =>
+        withResource(base.getChildColumnView(0)) {child =>
+          withResource(child.normalizeNANsAndZeros()) {normalizedChild =>
+            withResource(base.replaceListChild(normalizedChild)) {normalizedList =>
```
Comment (ttnghia) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:415]: @revans2 Does this code `base.replaceListChild` permanently modify the input column? If so, would this cause data corruption?

Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:415]: Hi @ttnghia , i guess this function doesn't modify `base`, because `column vector` and `column view` are immutable.

In my opinion, `base.replaceListChild` creates a new columnVector to copy the `offsets buffer` of the `base` (this should be cheap because it just increases the reference count of the underlying bytes and copies the `offset` and `length` of the buffer). And it will update the child array to point to the `new_child`. (This should also be fast and cheap because it just increases the reference to the underlying array data).

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 1 above)
Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: Actually, we have done the data type checking in GpuOverrides.scala: https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala#L2771-L2779

So that we can always make sure that the value of `DataType` is `ArrayType(...)` when calling `GpuSortArray`.

The `checkInputDataTypes()` in `GpuSortArray` is to check if values are orderable, I guess. Maybe we should rename it as `checkOrderable` to avoid misunderstanding.

Comment (revans2) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: I filed https://github.com/rapidsai/cudf/issues/11630 against CUDF.

**Review by revans2 — APPROVED** [review]
I understand the problem better now and it looks like it is a minor corner case in radix sort for float and double values.  I am fine with the patch as is. But it might be nice to add some comments explaining when and how this happens, both to the test and the code.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 4]
```diff
@@ -407,13 +407,24 @@ case class GpuSortArray(base: Expression, ascendingOrder: Expression)
...
+              normalizedList.listSortRows(isDescending, true)
+            }
+          }
+        }
+      case _ =>
+        base.listSortRows(isDescending, true)
```
Comment (ttnghia) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: I just realize that this still has bug when the input is array of nested types having `-NaN`. The solution for this is to recursively applying `normalizeNANsAndZeros` on all children columns of type float/double. That can be done using `ColumnCastUtil.deepTransform`.

**Review by ttnghia — CHANGES_REQUESTED** [review]

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 4 above)
Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: I guess `GpuSortArray` haven't supported nested array (aka array of array). But array of struct is supported. (https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala#L2771-L2779)

Could `ColumnCastUtil.deepTransform` be used on array of struct?

Comment (ttnghia) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: It can be used for any type because it is "deep".

Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:421]: > The solution for this is to recursively applying normalizeNANsAndZeros on all children columns of type float/double. That can be done using ColumnCastUtil.deepTransform.

As `Struct` is sorted by the first field, we should only apply `normalizeNansAndZeros` on the first child column of the struct. If `ColumnCastUtil.deepTransform` is recursively called on all the child arrays, it will introduce much overhead and might lead to a wrong result.

File: integration_tests/src/main/python/collection_ops_test.py [hunk 5]
```diff
@@ -149,6 +149,18 @@ def test_sort_array_lit(data_gen):
             f.sort_array(f.lit(array_lit), True),
             f.sort_array(f.lit(array_lit), False)))
 
+def test_sort_array_normalize_nans():
```
[the remark this answers is not in the document]
Comment (HaoYang670) [reply integration_tests/src/main/python/collection_ops_test.py:153]: Added

**Comment by HaoYang670** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 4 above)
Comment (ttnghia) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala]: > As Struct is sorted by the first field

No, structs are sorted by all fields. If the rows of the first field are equal, the rows of the second field will be compared and so on.

Overhead here is unavoidable if we want correctness.

Comment (HaoYang670) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala]: Updated.

**Comment by HaoYang670** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]
