### PR TITLE
Fix hash_aggregate test failures due to TypedImperativeAggregate

### LINKED ISSUE #3131: [BUG] hash_aggregate_test TypedImperativeAggregate tests failed
**Describe the bug**
tests added in https://github.com/NVIDIA/spark-rapids/pull/2971. We first saw this in databricks runtime 7.3 and 8.2 (nightly pipeline)

**Caused by: ai.rapids.cudf.CudfException: vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)**

failures list,
```
[2021-08-04T05:18:30.416Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Boolean)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.416Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Integer)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.416Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Long)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.416Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Short)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.416Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Date)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.416Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Timestamp)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Byte)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(String)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]0][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Double)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Decimal(8,3))), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_single_distinct[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]1][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Boolean)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Integer)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Long)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Short)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Date)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Timestamp)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Byte)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(String)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]0][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Double)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Decimal(8,3))), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
[2021-08-04T05:18:30.417Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]1][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
```

detailed log,
```
[2021-08-04T05:18:30.156Z] ----------------------------- Captured stdout call -----------------------------
[2021-08-04T05:18:30.156Z] ### CPU RUN ###
[2021-08-04T05:18:30.156Z] ### GPU RUN ###
[2021-08-04T05:18:30.156Z] [31m[1m_ test_hash_groupby_single_distinct_collect[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]1] _[0m
[2021-08-04T05:18:30.156Z] [gw4] linux -- Python 3.7.10 /databricks/conda/envs/databricks-ml-gpu/bin/python
[2021-08-04T05:18:30.156Z] 
[2021-08-04T05:18:30.156Z] data_gen = [('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]
[2021-08-04T05:18:30.156Z] 
[2021-08-04T05:18:30.156Z]     [37m@approximate_float[39;49;00m
[2021-08-04T05:18:30.156Z]     [37m@ignore_order[39;49;00m(local=[94mTrue[39;49;00m)
[2021-08-04T05:18:30.156Z]     [37m@incompat[39;49;00m
[2021-08-04T05:18:30.156Z]     [37m@pytest[39;49;00m.mark.parametrize([33m'[39;49;00m[33mdata_gen[39;49;00m[33m'[39;49;00m, _gen_data_for_collect_op, ids=idfn)
[2021-08-04T05:18:30.156Z]     [94mdef[39;49;00m [92mtest_hash_groupby_single_distinct_collect[39;49;00m(data_gen):
[2021-08-04T05:18:30.156Z]         [90m# test distinct collect with other aggregations[39;49;00m
[2021-08-04T05:18:30.156Z]         sql = [33m"""[39;49;00m[33mselect a,[39;49;00m[33m[39;49;00m
[2021-08-04T05:18:30.156Z]     [33m                    sort_array(collect_list(distinct b)),[39;49;00m[33m[39;49;00m
[2021-08-04T05:18:30.156Z]     [33m                    sort_array(collect_set(b)),[39;49;00m[33m[39;49;00m
[2021-08-04T05:18:30.156Z]     [33m                    count(distinct b),[39;49;00m[33m[39;49;00m
[2021-08-04T05:18:30.156Z]     [33m                    count(c)[39;49;00m[33m[39;49;00m
[2021-08-04T05:18:30.156Z]     [33m            from tbl group by a[39;49;00m[33m"""[39;49;00m
[2021-08-04T05:18:30.156Z]         assert_gpu_and_cpu_are_equal_sql(
[2021-08-04T05:18:30.156Z]             df_fun=[94mlambda[39;49;00m spark: gen_df(spark, data_gen, length=[94m100[39;49;00m),
[2021-08-04T05:18:30.156Z] >           table_name=[33m"[39;49;00m[33mtbl[39;49;00m[33m"[39;49;00m, sql=sql)
[2021-08-04T05:18:30.156Z] 
[2021-08-04T05:18:30.156Z] [1m[31m../../src/main/python/hash_aggregate_test.py[0m:455: 
[2021-08-04T05:18:30.156Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-08-04T05:18:30.156Z] [1m[31m../../src/main/python/asserts.py[0m:476: in assert_gpu_and_cpu_are_equal_sql
[2021-08-04T05:18:30.156Z]     assert_gpu_and_cpu_are_equal_collect(do_it_all, conf, is_cpu_first=is_cpu_first)
[2021-08-04T05:18:30.156Z] [1m[31m../../src/main/python/asserts.py[0m:434: in assert_gpu_and_cpu_are_equal_collect
[2021-08-04T05:18:30.156Z]     _assert_gpu_and_cpu_are_equal(func, [33m'[39;49;00m[33mCOLLECT[39;49;00m[33m'[39;49;00m, conf=conf, is_cpu_first=is_cpu_first)
[2021-08-04T05:18:30.156Z] [1m[31m../../src/main/python/asserts.py[0m:415: in _assert_gpu_and_cpu_are_equal
[2021-08-04T05:18:30.156Z]     run_on_gpu()
[2021-08-04T05:18:30.156Z] [1m[31m../../src/main/python/asserts.py[0m:409: in run_on_gpu
[2021-08-04T05:18:30.156Z]     from_gpu = with_gpu_session(bring_back, conf=conf)
[2021-08-04T05:18:30.156Z] [1m[31m../../src/main/python/spark_session.py[0m:105: in with_gpu_session
[2021-08-04T05:18:30.156Z]     [94mreturn[39;49;00m with_spark_session(func, conf=copy)
[2021-08-04T05:18:30.157Z] [1m[31m../../src/main/python/spark_session.py[0m:70: in with_spark_session
[2021-08-04T05:18:30.157Z]     ret = func(_spark)
[2021-08-04T05:18:30.157Z] [1m[31m../../src/main/python/asserts.py[0m:190: in <lambda>
[2021-08-04T05:18:30.157Z]     bring_back = [94mlambda[39;49;00m spark: limit_func(spark).collect()
[2021-08-04T05:18:30.157Z] [1m[31m/databricks/spark/python/pyspark/sql/dataframe.py[0m:611: in collect
[2021-08-04T05:18:30.157Z]     sock_info = [96mself[39;49;00m._jdf.collectToPython()
[2021-08-04T05:18:30.157Z] [1m[31m/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py[0m:1305: in __call__
[2021-08-04T05:18:30.157Z]     answer, [96mself[39;49;00m.gateway_client, [96mself[39;49;00m.target_id, [96mself[39;49;00m.name)
[2021-08-04T05:18:30.157Z] [1m[31m/databricks/spark/python/pyspark/sql/utils.py[0m:127: in deco
[2021-08-04T05:18:30.157Z]     [94mreturn[39;49;00m f(*a, **kw)
[2021-08-04T05:18:30.157Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-08-04T05:18:30.157Z] 
[2021-08-04T05:18:30.157Z] answer = 'xro192091'
[2021-08-04T05:18:30.157Z] gateway_client = <py4j.java_gateway.GatewayClient object at 0x7f5cc49f7450>
[2021-08-04T05:18:30.157Z] target_id = 'o192088', name = 'collectToPython'
[2021-08-04T05:18:30.157Z] 
[2021-08-04T05:18:30.413Z]     [94mdef[39;49;00m [92mget_return_value[39;49;00m(answer, gateway_client, target_id=[94mNone[39;49;00m, name=[94mNone[39;49;00m):
[2021-08-04T05:18:30.413Z]         [33m"""Converts an answer received from the Java gateway into a Python object.[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m    For example, string representation of integers are converted to Python[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m    integer, string representation of objects are converted to JavaObject[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m    instances, etc.[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m    :param answer: the string returned by the Java gateway[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m    :param gateway_client: the gateway client used to communicate with the Java[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m        Gateway. Only necessary if the answer is a reference (e.g., object,[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m        list, map)[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m    :param target_id: the name of the object from which the answer comes from[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m        (e.g., *object1* in `object1.hello()`). Optional.[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m    :param name: the name of the member from which the answer comes from[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m        (e.g., *hello* in `object1.hello()`). Optional.[39;49;00m
[2021-08-04T05:18:30.413Z]     [33m    """[39;49;00m
[2021-08-04T05:18:30.413Z]         [94mif[39;49;00m is_error(answer)[[94m0[39;49;00m]:
[2021-08-04T05:18:30.413Z]             [94mif[39;49;00m [96mlen[39;49;00m(answer) > [94m1[39;49;00m:
[2021-08-04T05:18:30.413Z]                 [96mtype[39;49;00m = answer[[94m1[39;49;00m]
[2021-08-04T05:18:30.413Z]                 value = OUTPUT_CONVERTER[[96mtype[39;49;00m](answer[[94m2[39;49;00m:], gateway_client)
[2021-08-04T05:18:30.413Z]                 [94mif[39;49;00m answer[[94m1[39;49;00m] == REFERENCE_TYPE:
[2021-08-04T05:18:30.413Z]                     [94mraise[39;49;00m Py4JJavaError(
[2021-08-04T05:18:30.413Z]                         [33m"[39;49;00m[33mAn error occurred while calling [39;49;00m[33m{0}[39;49;00m[33m{1}[39;49;00m[33m{2}[39;49;00m[33m.[39;49;00m[33m\n[39;49;00m[33m"[39;49;00m.
[2021-08-04T05:18:30.413Z] >                       [96mformat[39;49;00m(target_id, [33m"[39;49;00m[33m.[39;49;00m[33m"[39;49;00m, name), value)
[2021-08-04T05:18:30.413Z] [1m[31mE                   py4j.protocol.Py4JJavaError: An error occurred while calling o192088.collectToPython.[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6982.0 failed 4 times, most recent failure: Lost task 0.3 in stage 6982.0 (TID 33637, ip-10-59-181-194.us-west-2.compute.internal, executor driver): ai.rapids.cudf.CudfException: vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at ai.rapids.cudf.Table.groupByAggregate(Native Method)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at ai.rapids.cudf.Table.access$3000(Table.java:39)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at ai.rapids.cudf.Table$GroupByOperation.aggregate(Table.java:2490)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$computeAggregate$7(aggregate.scala:762)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:209)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$computeAggregate$1(aggregate.scala:761)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:209)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.com$nvidia$spark$rapids$GpuHashAggregateIterator$$computeAggregate(aggregate.scala:740)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$aggregateInputBatches$2(aggregate.scala:319)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$aggregateInputBatches$2$adapted(aggregate.scala:318)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:46)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:44)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:209)[0m
[2021-08-04T05:18:30.413Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:318)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:269)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at scala.Option.getOrElse(Option.scala:189)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:266)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:209)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:224)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:177)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:221)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:198)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:238)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processPartition$1(Collector.scala:179)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.SparkContext.$anonfun$runJob$6(SparkContext.scala:2433)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:144)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.run(Task.scala:117)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$9(Executor.scala:640)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1581)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:643)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:748)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   [0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   Driver stacktrace:[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2519)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2466)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2460)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2460)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1152)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1152)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at scala.Option.foreach(Option.scala:407)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1152)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2721)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2668)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2656)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:938)[0m
[2021-08-04T05:18:30.414Z] [1m[31mE                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2339)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2434)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:273)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:308)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:82)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:88)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:508)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:480)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:401)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3497)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3709)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:116)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:249)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:101)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:199)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3707)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3495)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at java.lang.reflect.Method.invoke(Method.java:498)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at py4j.Gateway.invoke(Gateway.java:295)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at py4j.GatewayConnection.run(GatewayConnection.java:251)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:748)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   Caused by: ai.rapids.cudf.CudfException: vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at ai.rapids.cudf.Table.groupByAggregate(Native Method)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at ai.rapids.cudf.Table.access$3000(Table.java:39)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at ai.rapids.cudf.Table$GroupByOperation.aggregate(Table.java:2490)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$computeAggregate$7(aggregate.scala:762)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:209)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$computeAggregate$1(aggregate.scala:761)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:209)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.com$nvidia$spark$rapids$GpuHashAggregateIterator$$computeAggregate(aggregate.scala:740)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$aggregateInputBatches$2(aggregate.scala:319)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$aggregateInputBatches$2$adapted(aggregate.scala:318)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:46)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:44)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:209)[0m
[2021-08-04T05:18:30.415Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:318)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:269)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at scala.Option.getOrElse(Option.scala:189)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:266)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:209)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:224)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:177)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:221)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:198)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:238)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processPartition$1(Collector.scala:179)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.SparkContext.$anonfun$runJob$6(SparkContext.scala:2433)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:144)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.run(Task.scala:117)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$9(Executor.scala:640)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1581)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:643)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
[2021-08-04T05:18:30.416Z] [1m[31mE                   	... 1 more[0m
```

**UPDATE:**
we have 12 more failures for databricks 8.2 runtime and spark 3.0.3+

**pyspark.sql.utils.IllegalArgumentException: The expression coalesce(first(if ((gid#1738853 = 0)) collect_list(`b`)#1738857 else null) ignore nulls#1738858, []) is not columnar class org.apache.spark.sql.catalyst.expressions.Coalesce**

failures list,
```
[2021-08-04T06:38:01.432Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Boolean)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.432Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Integer)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.432Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Long)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.432Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Short)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.433Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Date)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.433Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Timestamp)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.433Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Byte)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.433Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(String)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.433Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]0][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.433Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Double)), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.433Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Decimal(8,3))), ('c', LongRange(not_null))]][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
[2021-08-04T06:38:01.433Z] FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]1][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(SortAggregateExec,SortArray,Alias,Literal,First,If,EqualTo,Count,CollectList,CollectSet,AggregateExpression)]
```

detailed log,
```
[2021-08-04T06:38:01.430Z] ----------------------------- Captured stdout call -----------------------------
[2021-08-04T06:38:01.430Z] ### CPU RUN ###
[2021-08-04T06:38:01.430Z] ### GPU RUN ###
[2021-08-04T06:38:01.430Z] [31m[1m_ test_hash_groupby_collect_with_multi_distinct_fallback[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]1] _[0m
[2021-08-04T06:38:01.430Z] [gw3] linux -- Python 3.8.8 /databricks/conda/envs/databricks-ml-gpu/bin/python
[2021-08-04T06:38:01.430Z] 
[2021-08-04T06:38:01.430Z] data_gen = [('a', RepeatSeq(Long)), ('b', RepeatSeq(Float)), ('c', LongRange(not_null))]
[2021-08-04T06:38:01.430Z] 
[2021-08-04T06:38:01.430Z]     [37m@approximate_float[39;49;00m
[2021-08-04T06:38:01.430Z]     [37m@ignore_order[39;49;00m(local=[94mTrue[39;49;00m)
[2021-08-04T06:38:01.430Z]     [37m@allow_non_gpu[39;49;00m([33m'[39;49;00m[33mSortAggregateExec[39;49;00m[33m'[39;49;00m,
[2021-08-04T06:38:01.430Z]                    [33m'[39;49;00m[33mSortArray[39;49;00m[33m'[39;49;00m, [33m'[39;49;00m[33mAlias[39;49;00m[33m'[39;49;00m, [33m'[39;49;00m[33mLiteral[39;49;00m[33m'[39;49;00m, [33m'[39;49;00m[33mFirst[39;49;00m[33m'[39;49;00m, [33m'[39;49;00m[33mIf[39;49;00m[33m'[39;49;00m, [33m'[39;49;00m[33mEqualTo[39;49;00m[33m'[39;49;00m, [33m'[39;49;00m[33mCount[39;49;00m[33m'[39;49;00m,
[2021-08-04T06:38:01.431Z]                    [33m'[39;49;00m[33mCollectList[39;49;00m[33m'[39;49;00m, [33m'[39;49;00m[33mCollectSet[39;49;00m[33m'[39;49;00m, [33m'[39;49;00m[33mAggregateExpression[39;49;00m[33m'[39;49;00m)
[2021-08-04T06:38:01.431Z]     [37m@incompat[39;49;00m
[2021-08-04T06:38:01.431Z]     [37m@pytest[39;49;00m.mark.parametrize([33m'[39;49;00m[33mdata_gen[39;49;00m[33m'[39;49;00m, _gen_data_for_collect_op, ids=idfn)
[2021-08-04T06:38:01.431Z]     [94mdef[39;49;00m [92mtest_hash_groupby_collect_with_multi_distinct_fallback[39;49;00m(data_gen):
[2021-08-04T06:38:01.431Z]         [94mdef[39;49;00m [92mspark_fn[39;49;00m(spark_session):
[2021-08-04T06:38:01.431Z]             [94mreturn[39;49;00m gen_df(spark_session, data_gen, length=[94m100[39;49;00m).groupby([33m'[39;49;00m[33ma[39;49;00m[33m'[39;49;00m).agg(
[2021-08-04T06:38:01.431Z]                 f.sort_array(f.collect_list([33m'[39;49;00m[33mb[39;49;00m[33m'[39;49;00m)),
[2021-08-04T06:38:01.431Z]                 f.sort_array(f.collect_set([33m'[39;49;00m[33mb[39;49;00m[33m'[39;49;00m)),
[2021-08-04T06:38:01.431Z]                 f.countDistinct([33m'[39;49;00m[33mb[39;49;00m[33m'[39;49;00m),
[2021-08-04T06:38:01.431Z]                 f.countDistinct([33m'[39;49;00m[33mc[39;49;00m[33m'[39;49;00m))
[2021-08-04T06:38:01.431Z] >       assert_gpu_fallback_collect(func=spark_fn, cpu_fallback_class_name=[33m'[39;49;00m[33mSortAggregateExec[39;49;00m[33m'[39;49;00m)
[2021-08-04T06:38:01.431Z] 
[2021-08-04T06:38:01.431Z] [1m[31m../../src/main/python/hash_aggregate_test.py[0m:476: 
[2021-08-04T06:38:01.431Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-08-04T06:38:01.431Z] [1m[31m../../src/main/python/asserts.py[0m:364: in assert_gpu_fallback_collect
[2021-08-04T06:38:01.431Z]     from_gpu, gpu_df = with_gpu_session(bring_back, conf=conf)
[2021-08-04T06:38:01.431Z] [1m[31m../../src/main/python/spark_session.py[0m:105: in with_gpu_session
[2021-08-04T06:38:01.431Z]     [94mreturn[39;49;00m with_spark_session(func, conf=copy)
[2021-08-04T06:38:01.431Z] [1m[31m../../src/main/python/spark_session.py[0m:70: in with_spark_session
[2021-08-04T06:38:01.431Z]     ret = func(_spark)
[2021-08-04T06:38:01.431Z] [1m[31m../../src/main/python/asserts.py[0m:198: in bring_back
[2021-08-04T06:38:01.431Z]     [94mreturn[39;49;00m (df.collect(), df)
[2021-08-04T06:38:01.431Z] [1m[31m/databricks/spark/python/pyspark/sql/dataframe.py[0m:697: in collect
[2021-08-04T06:38:01.431Z]     sock_info = [96mself[39;49;00m._jdf.collectToPython()
[2021-08-04T06:38:01.431Z] [1m[31m/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py[0m:1304: in __call__
[2021-08-04T06:38:01.431Z]     return_value = get_return_value(
[2021-08-04T06:38:01.431Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-08-04T06:38:01.431Z] 
[2021-08-04T06:38:01.431Z] a = ('xro179879', <py4j.java_gateway.GatewayClient object at 0x7fb5a5b8b610>, 'o179876', 'collectToPython')
[2021-08-04T06:38:01.431Z] kw = {}
[2021-08-04T06:38:01.431Z] converted = IllegalArgumentException('The expression coalesce(first(if ((gid#1739491 = 0)) collect_list(`b`)#1739495 else null) ig...:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:251)\n\tat java.lang.Thread.run(Thread.java:748)\n', None)
[2021-08-04T06:38:01.431Z] 
[2021-08-04T06:38:01.431Z]     [94mdef[39;49;00m [92mdeco[39;49;00m(*a, **kw):
[2021-08-04T06:38:01.431Z]         [94mtry[39;49;00m:
[2021-08-04T06:38:01.431Z]             [94mreturn[39;49;00m f(*a, **kw)
[2021-08-04T06:38:01.431Z]         [94mexcept[39;49;00m py4j.protocol.Py4JJavaError [94mas[39;49;00m e:
[2021-08-04T06:38:01.431Z]             converted = convert_exception(e.java_exception)
[2021-08-04T06:38:01.431Z]             [94mif[39;49;00m [95mnot[39;49;00m [96misinstance[39;49;00m(converted, UnknownException):
[2021-08-04T06:38:01.431Z]                 [90m# Hide where the exception came from that shows a non-Pythonic[39;49;00m
[2021-08-04T06:38:01.431Z]                 [90m# JVM exception message.[39;49;00m
[2021-08-04T06:38:01.431Z] >               [94mraise[39;49;00m converted [94mfrom[39;49;00m [96mNone[39;49;00m
[2021-08-04T06:38:01.431Z] [1m[31mE               pyspark.sql.utils.IllegalArgumentException: The expression coalesce(first(if ((gid#1739491 = 0)) collect_list(`b`)#1739495 else null) ignore nulls#1739496, []) is not columnar class org.apache.spark.sql.catalyst.expressions.Coalesce[0m
[2021-08-04T06:38:01.431Z] 
[2021-08-04T06:38:01.431Z] [1m[31m/databricks/spark/python/pyspark/sql/utils.py[0m:116: IllegalArgumentException
```

### PR DESCRIPTION
**Pull request by sperlingxx**
Fixes #3131

#3131 reported two kinds of bugs introduced by the PR for GpuCollectList as TypedImperativeAggregate.

One of them is merely a bug on test codes: missing `allow_non_gpu` with `Coalesce`, which failed test_hash_groupby_collect_with_multi_distinct_fallback because `Coalesce` expressions inserted by RewriteDistinctAggregates are not Columnar supported. This bug can be fixed via filling the missing `allow_non_gpu` value (Coalese).

Another one is about incorrect input projections in the final stage of aggregation. After dumping the plan tree of original CPU plan, we found Databricks runtime overridden the planning of single distinct aggregate. In terms of Apache Spark, the method `AggUtils.planAggregateWithOneDistinct` would create 4 stages of physical plans for each aggregation (logical plan). Meanwhile, the dumped result of Databricks runtime only contains 2 stages (joint-Partial and joint-Final). For query
```sql
select a, sort_array(collect_list(b)), sort_array(collect_set(b)),
          count(b),
          count(distinct c)
from tbl group by a
```
, the plan tree turned out to be:
```
ObjectHashAggregate(keys=[a#1052L], functions=[finalmerge_collect_list(merge buf#1075) AS collect_list(b#1053, 0, 0)#1061, finalmerge_collect_set(merge buf#1077) AS collect_set(b#1053, 0, 0)#1062, finalmerge_count(merge count#1081L) AS count(1)#1063L, count(distinct c#1054L)], output=[a#1052L, sort_array(collect_list(b), true)#1064, sort_array(collect_set(b), true)#1065, count(c)#1066L, count(c)#1067L])
+- Exchange hashpartitioning(a#1052L, 12), true, [id=#512]
   +- ObjectHashAggregate(keys=[a#1052L, c#1054L], functions=[partial_collect_list(b#1053, 0, 0) AS buf#1075, partial_collect_set(b#1053, 0, 0) AS buf#1077, partial_count(1) AS count#1081L], output=[a#1052L, c#1054L, buf#1075, buf#1077, count#1081L])
      +- Exchange hashpartitioning(a#1052L, c#1054L, 12), true, [id=#509]
         +- Project [a#1052L, c#1054L, b#1053]
            +- Scan ExistingRDD[a#1052L,b#1053,c#1054L]
```
According to the dumped plan tree, we can infer that the stage 1 and stage 2 produced by Spark's AggregateWithOneDistinct are fused into a joint Partial stage in Databricks runtime. Similarly, the stage 3 and stage 4 are fused into a joint Merge stage.

In this PR, we tried to fix the bug without increasing the complexity of Databricks shim. To adapt the optimization of AggregateWithOneDistinct in Databricks runtime, we changed the condition of `boundInputReferences` to extend this ability on handling stages including both nonDistinctAggExpressions and DistinctAggExpressions. And this approach has been manually verified with Databricks runtime 3.0.1.

### CODE REVIEW

**Comment by sperlingxx** [comment]
build

**Review by abellina — DISMISSED** [review]
main comment I have is I wonder if it's time for us to check whether we are indeed in databricks. We do have the shims, and we should be able to check or add a check for "isDatabricks". The comments are helpful @sperlingxx.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala [hunk 1]
```diff
@@ -628,21 +628,43 @@ class GpuHashAggregateIterator(
...
+    //   inputProjections for nonDistinctAggExpressions.
+    // - Final mode, PartialMerge-only mode or no AggExpressions: we pick the columns in the order
+    //   as handed to us.
+    // - Partial mode or Complete mode: we use the inputProjections.
     val boundInputReferences =
-    if (modeInfo.hasPartialMergeMode && modeInfo.hasPartialMode) {
-      // The 3rd stage of AggWithOneDistinct, which combines (partial) reduce-side
-      // nonDistinctAggExpressions and map-side distinctAggExpressions. For this stage, we need to
-      // switch the position of distinctAttributes and nonDistinctAttributes.
+    if (modeInfo.uniqueModes.length > 1 && aggregateExpressions.exists(_.isDistinct)) {
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:638]: This makes me a little nervous that we are missing something.  The Spark aggregation code does not look at distinct at all.  It really just looks at the individual modes for each operation.  Why is it that we need to do this to get the aggregation right, but the Spark code does not?

Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:638]: For `AggWithOneDistinct`, the Spark plans 4-stage stack of `AggregateExec`. Each stage owns an unique Modes:
 * Stage 1:  `Partial` mode, only includes nonDistinct ones
 * Stage 2:  `PartialMerge` mode, only includes nonDistinct ones
 * Stage 3:  `PartialMerge` mode for nonDistinct ones and `Partial` mode for Distinct ones
 * Stage 4:  `Final` mode for both nonDistinct and Distinct AggregateExpressions

In contrast, Databricks runtime seems to apply a quite different planning strategy to `AggWithOneDistinct`. With the dumped plan trees,  we infer Databricks runtime only plans 2-stage stack for `AggWithOneDistinct`: Map-stage and Reduce-stage. 
* Map-stage: `Partial` mode, includes nonDistinct ones
* Reduce-stage: `Final` mode for nonDistinct ones and `Complete` mode for Distinct ones

Apparently, the Map-stage corresponds to Stage 1 and Stage 2; the Reduce-stage corresponds to Stage 3 and Stage 4.
The condition here used to match Stage 3, so it checked whether modeInfo contains both `PartialMerge` and `Partial`. Currently, we want to adapt Databricks runtime. In terms of Reduce-stage, the input projections of Reduce-stage are exactly same as Stage 3, though they contain different AggregateModes. Therefore, we change the condition here to match the Reduce-stage of Databrick runtimes as well as the Stage 3 of Spark. As far as we know, the condition `modeInfo.uniqueModes.length > 1` along is enough to distinguish Stage 3 and Reduce-stage from other stages. The latter condition `aggregateExpressions.exists(_.isDistinct)` is to increase the robustness in case of some unknown special cases.

In addition, the input projections for Stage 1 fully fits the Map-stage of Databricks runtime. We don't need to change anything to adapt Databricks runtime.

Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:638]: Alternatively, perhaps the condition like `(modeInfo.hasPartialMergeMode && modeInfo.hasPartialMode) || (modeInfo.hasFinalMode && modeInfo.hasCompleteMode)` is more straightforward and easier to understand.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala [hunk 2]
```diff
@@ -656,32 +678,39 @@ class GpuHashAggregateIterator(
...
       val distinctExpressions = distinctAggExpressions.flatMap(_.aggregateFunction.inputProjection)
 
       // Align the expressions of input projections and input attributes
       val inputProjections = groupingExpressions ++ nonDistinctExpressions ++ distinctExpressions
       val inputAttributes = groupingAttributes ++ distinctAttributes ++ nonDistinctAttributes
       GpuBindReferences.bindGpuReferences(inputProjections, inputAttributes)
     } else if (modeInfo.hasFinalMode ||
-        (modeInfo.hasPartialMergeMode && modeInfo.uniqueModes.length == 1)) {
-      // two possible conditions:
+      (modeInfo.hasPartialMergeMode && modeInfo.uniqueModes.length == 1)) {
```
[the remark this answers is not in the document]
Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala]: Thanks. I also corrected the wrong style in other places of `aggregate.scala`.

**Comment by sperlingxx** [comment]
build

**Comment by sperlingxx** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala (hunk 1 above)
Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:638]: I am okay with this as a short term fix.  The problem is not with your logic.  The problem is that we keep hacking special cases onto something that should not need them.

Each aggregation comes with a mode.  Each mode tells the aggregation what to do as a part of that stage. Originally the code assumed that there would only ever be one mode for all of the aggregations. I thought we had ripped that all out and each aggregation does the right thing.

To successfully do an aggregation there are a few steps used.
1) Initial projection to get input data setup properly.
2) Initial aggregation to produce partial result(s)
3) Merge aggregation to combine partial results (This requires that the input schema and the output schema be the same)
4) Final projection to take the combined partial results and produce a final result.

In general the steps take the pattern 1, 2, 3*, 4. Which means 1, 2 and 4 are required and step 3 can be done as often as needed because the input and output schemas are the same.

Step 4 requires that all of the data for a given group by key is on the same task and has been merged into a single output row.  There are several different ways to do this, which is why we end up with several aggregation modes.

* `Partial` mode means that we do Step 1 and Step 2. Then we can do Step 3 as many times as needed depending on how we are doing memory management, and how many batches are needed.
* `PartialMerge` mode means we can do Step 3 at least once and possibly more times depending on how we are doing memory management and how many batches are needed.
* `Final` mode means that we do the same steps as with `PartialMerge` but do Step 4 when we are done doing the partial merges.
* `Complete` mode is something only Databricks does, but it essentially means we do Step 1, Step 2, Step 3* (depending on memory management requirements), and Step 4 all at once.

I know that the details are a lot more complicated, but conceptually it should not be too difficult. I will file a follow on issue for us to figure this out.

Comment (abellina) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:638]: I think the main ask is to not do this wholesale, assuming that a hash aggregate exec has a certain shape. If this function could decide per aggregate expression mode what the right binding should be, it should be more robust to new aggregate exec setups that mix and match modes (if we encounter new ones). That said, I don't think this is your fault as the `setupReferences` code was built that way, it needs to be reworked separately.

**Review by abellina — APPROVED** [review]
