### PR TITLE
Use Shims v2 for ShuffledBatchRDD

### LINKED ISSUE #3372: [BUG] 3.2.0 shim: ShuffledBatchRDD.scala:141: match may not be exhaustive.
**Describe the bug**
3.2 has a new partition spec we don't handle in the plugin
```
ShuffledBatchRDD.scala:141: match may not be exhaustive.
It would fail on the following input: CoalescedMapperPartitionSpec(_, _, _)
[WARNING] [Warn] /home/gshegalov/gits/NVIDIA/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala:165: match may not be exhaustive.
It would fail on the following input: CoalescedMapperPartitionSpec(_, _, _)
```

**Steps/Code to reproduce bug**
build the 3.2 shim using 
```bash
$ mvn clean package -Dbuildver=320 -Dskip -DskipTests -pl integration_tests -am 
```

**Expected behavior**
Build must not have semantically significant warnings

**Environment details (please complete the following information)**
 local

**Additional context**
#3323

### PR DESCRIPTION
**Pull request by revans2**
This fixes #3372

### CODE REVIEW

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala [hunk 1]
```diff
@@ -49,10 +52,10 @@ class BatchPartitionIdPassthrough(override val numPartitions: Int) extends Parti
 class CoalescedBatchPartitioner(val parent: Partitioner, val partitionStartIndices: Array[Int])
   extends Partitioner {
 
-  @transient private lazy val parentPartitionMapping = {
+  @transient private lazy val parentPartitionMapping: Array[Int] = {
     val n = parent.numPartitions
     val result = new Array[Int](n)
-    for (i <- partitionStartIndices.indices) {
+    for (i <- 0 until partitionStartIndices.length) {
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala:58]: Just a note. There are several changes here, like this one, that make it look like the code is going backwards based off of the IDEs warnings.  This is because I made the code match as closely as possible to the Spark 3.2.0-RC2 code. This was so that differences between it and other versions of the code are much more obvious.

File: sql-plugin/src/main/320/scala/org/apache/spark/rapids/shims/v2/ShuffledBatchRDDUtil.scala [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+      case CoalescedMapperPartitionSpec(startMapIndex, endMapIndex, numReducers) =>
+        val reader = SparkEnv.get.shuffleManager.getReader(
+          dependency.shuffleHandle,
+          startMapIndex,
+          endMapIndex,
+          0,
+          numReducers,
+          context,
+          sqlMetricsReporter)
+        val blocksByAddress = shim.getMapSizesByExecutorId(
```
Comment (revans2) [inline sql-plugin/src/main/320/scala/org/apache/spark/rapids/shims/v2/ShuffledBatchRDDUtil.scala:117]: This is the only place that I have really added new code from scratch.  The rest has been refactoring existing code and pulling in things either from Spark or from existing code in our plugin. I am not really sure how to trigger this part of the code base to test it. If someone really wants me to get tests for this I'll try to find a way to make sure that I cover all of the existing code paths.

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
Converted to draft because I need to work out some issues with datbricks build.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
Build failed trying to get the code coverage dependency, so I kicked it again.

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
build

**Comment by pxLi** [comment]
build
