### PR TITLE
Fix date parsing in Hive Delimited Text reader

### LINKED ISSUE #7089: [BUG] Reading invalid `DATE` strings yields exceptions instead of nulls
### Scope
This behaviour affects reads of both CSV and Hive delimited text input.

### Description
When an invalid `DATE` string (e.g. "2020-50-16", or even "abcde") is read through the Spark RAPIDS plugin, one sees the following exception:
```
Caused by: java.time.DateTimeException: One or more values is not a valid date
  at com.nvidia.spark.rapids.GpuTextBasedPartitionReader.$anonfun$castStringToDate$3(GpuTextBasedPartitionReader.scala:261)
  at com.nvidia.spark.rapids.GpuTextBasedPartitionReader.$anonfun$castStringToDate$3$adapted(GpuTextBasedPartitionReader.scala:259)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.GpuTextBasedPartitionReader.withResource(GpuTextBasedPartitionReader.scala:52)
  at com.nvidia.spark.rapids.GpuTextBasedPartitionReader.$anonfun$castStringToDate$2(GpuTextBasedPartitionReader.scala:259)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.GpuTextBasedPartitionReader.withResource(GpuTextBasedPartitionReader.scala.52)
```

### Repro
This may be reproduced by reading the following input either as CSV or as Hive delimited text:
```
2020-09-16
2020-10-16
2021-09-16
 2021-09-16
2021-09-16
2020-50-16
asdf
```

### Expected behaviour
Invalid strings should produce `null` when interpreted as `DATE`, as it does with Apache Spark.

### Caveats
This behaviour does not happen with date values serialized through the Hive `LazySimpleSerDe`, which are read correctly through `GpuHiveTableScanExec`.

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #7089. (Invalid date strings causing exceptions when parsed as Hive delimited text.)

There were two problems:
  1. Strings between field delimiters should not be trimmed before casting to dates.
  2. Invalid date strings should not be causing exceptions. They should return null
     values, as is the convention in Hive's `LazySimpleSerDe`. 

This change should fix the problem(s).

### CODE REVIEW

**Comment by mythrocks** [comment]
This PR builds on the work in #7207, and includes those changes. The material change in this PR trivial. That should be apparent once #7207.

**Comment by mythrocks** [comment]
I have rebased this change. Should be ready for review.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala [hunk 1]
```diff
@@ -379,6 +379,10 @@ abstract class GpuTextBasedPartitionReader[BUFF <: LineBufferer, FACT <: LineBuf
   def dateFormat: String
   def timestampFormat: String
 
+  def castStringToDate(input: ColumnVector, dt: DType): ColumnVector = {
+   castStringToDate(input, dt, failOnInvalid = true)
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala:383]: nit: Indentation appears to be off

File: sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala [hunk 2]
```diff
@@ -535,4 +535,23 @@ class GpuHiveDelimitedTextPartitionReader(conf: Configuration,
...
+  /**
+   * Override of [[com.nvidia.spark.rapids.GpuTextBasedPartitionReader.castStringToDate()]],
+   * to convert parsed string columns to Dates.
+   * Two key differences from the base implementation, to comply with Hive LazySimpleSerDe
+   * semantics:
+   *   1. The input strings are not trimmed of whitespace.
+   *   2. Invalid date strings do not cause exceptions.
+   */
+  override def castStringToDate(input: ColumnVector, dt: DType): ColumnVector = {
+    val cudfFormat = DateUtils.toStrf(dateFormat, parseString = true)
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala:548]: Do we need to validate the date format works before we put this on the GPU? Is it even configurable in hive?  Should we just hard code it instead of relying on the CSV options to pick the format?

Comment (mythrocks) [reply sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala:548]: It did not seem configurable. I'd better double-check, given that I got it wrong for `Timestamp`.

**Review by revans2 — APPROVED** [review]

File: sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala (hunk 2 above)
Comment (revans2) [reply sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala]: Or I got it wrong it timestamp. There are multiple times that I have read the code and what actually happens is different.  Like with the date parsing, so I don't know if I can trust myself.

**Comment by revans2** [comment]
build

**Comment by mythrocks** [comment]
Thanks for the review, @revans2. I've merged this change.
