### PR TITLE
Spark 4 parquet_writer_test.py fixes

### LINKED ISSUE #11024: Fix tests failures in parquet_write_test.py
```
FAILED ../../../../integration_tests/src/main/python/parquet_write_test.py::test_hive_timestamp_value
FAILED ../../../../integration_tests/src/main/python/parquet_write_test.py::test_non_empty_ctas
FAILED ../../../../integration_tests/src/main/python/parquet_write_test.py::test_parquet_write_fails_legacy_datetime
FAILED ../../../../integration_tests/src/main/python/parquet_write_test.py::test_parquet_write_roundtrip_datetime_with_legacy_rebase
FAILED ../../../../integration_tests/src/main/python/parquet_write_test.py::test_ts_write_fails_datetime_exception
```

### PR DESCRIPTION
**Pull request by rwlee**
Resolves #11024 

Fixes test failures caused by some renamed configurations and renamed member variables in spark classes. Also includes a few fixes to the shim loader and integration test runner that allow them to run the preview as if they were the release version.

### CODE REVIEW

**Comment by rwlee** [comment]
build

File: sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala [hunk 1]
```diff
@@ -310,6 +310,9 @@ object ShimLoader {
     // hack for databricks, try to find something more reliable?
     if (SPARK_BUILD_USER.equals("Databricks")) {
       SPARK_VERSION + "-databricks"
+    // hack for preview versions to act as the base version
+    } else if (SPARK_VERSION matches """\d+\.\d+\.\d+-preview\d+""") {
+      SPARK_VERSION.split('-')(0)
```
Comment (gerashegalov) [inline sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala:315]: Is this for is_spark_400_or_later ?

Comment (rwlee) [reply sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala:315]: What aspect of it?

Preview versions of spark are not supported by us, but this change is necessary for us to test preview versions of spark as if they are the actual version. The version numbering system holds true for Spark 3, but they have been inconsistent about numbering the preview version (I think partly because they're not sure how many previews they will need).

Comment (gerashegalov) [reply sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala:315]: I think we should just change the 400 provider to accept SNAPSHOT and the latest `preview2`, dropping preview1 https://github.com/NVIDIA/spark-rapids/blob/a41a6160ee3783a9cffd623b46e00992c1204eff/sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/spark400/SparkShimServiceProvider.scala#L26

**Review by gerashegalov — APPROVED** [review]
LGTM

**Comment by rwlee** [comment]
build
