### PR TITLE
Remove scaladoc on an internal method to avoid warning during build

### LINKED ISSUE #2495: [BUG] scaladoc warning  GpuParquetScan.scala:727 "discarding unmoored doc comment"
**Describe the bug***
local build displays a warning 
```
<LOCAL_REPO_PATH>/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:727: warning: discarding unmoored doc comment
    /**
    ^
```

**Steps/Code to reproduce bug**
```
mvn clean scala:doc -pl sql-plugin
```

**Expected behavior**
build should produce as few distracting messages as possible

**Environment details (please complete the following information)**
- local dev environment

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by razajafri**
Internal method to a private method doesn't need scaladocs. I have kept the comment as a multi-line comment. 
I couldn't take this function up one level because we created the wrapper just so no one can misuse this function accidentally. 

fixes #2495 

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

**Comment by razajafri** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala [hunk 1]
```diff
@@ -724,14 +724,10 @@ trait ParquetPartitionReaderBase extends Logging with Arm with ScanWithMetrics
...
-     *
-     * @param cv          ColumnView to be checked if it has Decimal32 values stored as Decimal64
-     * @param precision   precision list of all the Decimal columns in this ColumnVector
-     * @param toClose     The ColumnViews to be closed after this method is done. This will also
-     *                    contain the returned view
+    /*
+      'convertDecimal64ToDecimal32' method returns a ColumnView that should be copied out to a
+      ColumnVector  before closing the `toClose` views otherwise it will close the returned view
+      and it's children as well.
      */
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:731]: Don't drop the leading `*` on each line, only need to drop the `**`.
```suggestion
    /*
     * 'convertDecimal64ToDecimal32' method returns a ColumnView that should be copied out to a
     * ColumnVector  before closing the `toClose` views otherwise it will close the returned view
     * and it's children as well.
     */
```

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build
