### PR TITLE
Fixing exception when appStartInfo isn't available due to incomplete event log

### LINKED ISSUE #6933: [BUG] Tools run with filter arguments should handle corrupted log that doesn't have SparkListenerApplicationStart event
**Describe the bug**
When running the qualification tool with filter arguments, it fails on an event log that is incomplete (missing SparkListenerApplicationStart).

```
Exception in thread "main" java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:529)
    at scala.None$.get(Option.scala:527)
    at org.apache.spark.sql.rapids.tool.AppFilterImpl.$anonfun$filterEventLogsInternal$23(AppFilterImpl.scala:222)
    at org.apache.spark.sql.rapids.tool.AppFilterImpl.$anonfun$filterEventLogsInternal$23$adapted(AppFilterImpl.scala:222)
    at scala.math.Ordering$$anon$2.compare(Ordering.scala:125)
    at java.util.TimSort.binarySort(TimSort.java:296)
    at java.util.TimSort.sort(TimSort.java:239)
    at java.util.Arrays.sort(Arrays.java:1438)
    at scala.collection.SeqLike.sorted(SeqLike.scala:659)
    at scala.collection.SeqLike.sorted$(SeqLike.scala:647)
    at scala.collection.AbstractSeq.sorted(Seq.scala:45)
    at scala.collection.SeqLike.sortBy(SeqLike.scala:634)
    at scala.collection.SeqLike.sortBy$(SeqLike.scala:634)
    at scala.collection.AbstractSeq.sortBy(Seq.scala:45)
    at org.apache.spark.sql.rapids.tool.AppFilterImpl.filterEventLogsInternal(AppFilterImpl.scala:221)
    at org.apache.spark.sql.rapids.tool.AppFilterImpl.filterEventLogs(AppFilterImpl.scala:82)
    at com.nvidia.spark.rapids.tool.qualification.QualificationMain$.mainInternal(QualificationMain.scala:80)
    at com.nvidia.spark.rapids.tool.qualification.QualificationMain$.main(QualificationMain.scala:34)
    at com.nvidia.spark.rapids.tool.qualification.QualificationMain.main(QualificationMain.scala)
```

**Steps/Code to reproduce bug**
Run qualification tool on event log without SparkListenerApplicationStart event and with filter arguments.

**Expected behavior**
Tool should ignore incomplete log and display warning message about skipping incomplete log, but it should not fail with an exception.

### PR DESCRIPTION
**Pull request by mattahrens**
Signed-off-by: Matt Ahrens <matthewahrens@gmail.com>

Closes #6933

### CODE REVIEW

**Comment by mattahrens** [comment]
build

File: tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala [hunk 1]
```diff
@@ -783,4 +783,34 @@ class AppFilterSuite extends FunSuite {
       }
     }
   }
+  
+  test("Test missing start event") {
```
Comment (tgravescs) [inline tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala:787]:
```suggestion
  test("Test filtering eventlog with missing start event") {
```

**Comment by mattahrens** [comment]
build

**Review by nartal1 — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]
