### PR TITLE
xfail all the impacted cases when using non-UTC time zone [databricks]

### LINKED ISSUE #9737: [FEA] Enable running integration tests with a non-UTC timezone, and handle tests that fail when the timezone is not UTC
To track what needs to be updated for supporting timezones that are not UTC, we need to figure out what operations will need to updated to keep running on the GPU. For now, we can run the integration tests in a non-UTC timezone, and xfail the failed tests. This can be a xfail with `if_non_utc_tz`. 

This way we can track operations to fall back properly and also when checks become per-operator we can ensure that there is no data corruption that results from it.

### PR DESCRIPTION
**Pull request by res-life**
closes #9737

- xfail all the impacted cases when using non-UTC time zone.
```
@pytest.mark.xfail(condition = is_not_utc(), reason = 'xfail non-UTC time zone tests because of https://github.com/NVIDIA/spark-rapids/issues/9653')
```
Signed-off-by: Chong Gao <res_life@163.com>

Note:
About DB cases, will post another PR.

### CODE REVIEW

**Comment by res-life** [comment]
build

File: integration_tests/run_pyspark_from_build.sh [hunk 1]
```diff
@@ -224,7 +224,7 @@ else
     fi
 
     # time zone will be tested; use export TZ=time_zone_name before run this script
-    TZ=${TZ:-UTC}
+    export TZ=Iran
```
Comment (winningsix) [inline integration_tests/run_pyspark_from_build.sh:227]: revert this before when commit.

**Review by revans2 — COMMENTED** [review]
Looks good

File: integration_tests/src/main/python/parquet_write_test.py [hunk 2]
```diff
@@ -283,6 +291,7 @@ def writeParquetUpgradeCatchException(spark, df, data_path, spark_tmp_table_fact
                          ('TIMESTAMP_MICROS', TimestampGen(start=datetime(1, 1, 1, tzinfo=timezone.utc), end=datetime(1899, 12, 31, tzinfo=timezone.utc))),
                          ('TIMESTAMP_MILLIS', TimestampGen(start=datetime(1, 1, 1, tzinfo=timezone.utc), end=datetime(1899, 12, 31, tzinfo=timezone.utc)))])
 @pytest.mark.parametrize('rebase', ["CORRECTED","EXCEPTION"])
```
Comment (winningsix) [inline integration_tests/src/main/python/parquet_write_test.py:293]: It seems we don't need another PR to cover databricks? Related test cases already cover different behaviors for ```spark.sql.parquet.datetimeRebaseModeInRead```.

**Review by winningsix — COMMENTED** [review]
The xfailed case number seems less than previous mentioned number. Any difference from what we tested before?

File: integration_tests/src/main/python/parquet_write_test.py (hunk 2 above)
Comment (revans2) [reply integration_tests/src/main/python/parquet_write_test.py:293]: We probably still need to cover databricks eventually. This is for one write test. There are all of the read tests and there are also other write tests too. The issue shows up for any test where we are relying on the default rebase settings. I have not dug into them to see which they are. I would be happy to see us not rely on the default settings any more. But then we need to be sure that we don't lose any test coverage.

**Review by NVnavkumar — COMMENTED** [review]
Looks good so far. Awaiting any updates based on databricks testing.

**Comment by NVnavkumar** [comment]
build

**Comment by res-life** [comment]
>The xfailed case number seems less than previous mentioned number. Any difference from what we tested before?

Totally 347 cases in 43 files. 347 cases are parametrized case.
Previously in https://github.com/NVIDIA/spark-rapids/pull/9482, there are only about 10 files involved.
After removing the `skip_if_not_utc` in `gen_df`, more files(about 30 files) appeared.
```python
def gen_df(spark, data_gen, length=2048, seed=0, num_slices=None):
        ......
        if src.contains_ts():      # Remove
             skip_if_not_utc()     # Remove
```

**Comment by res-life** [comment]
build

File: integration_tests/src/main/python/parquet_write_test.py (hunk 2 above)
Comment (res-life) [reply integration_tests/src/main/python/parquet_write_test.py:293]: I'll first xfail the impacted cases for DB in this PR.
Filed a follow-up issue: https://github.com/NVIDIA/spark-rapids/issues/9792,  for this issue, I'll fix the cases and then add cases to ensure the coverage.

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by winningsix** [comment]
FYI. Those cases failed in my local test using Spark 3.4.1. I will verify more in my local.

<head>
Most related to ```test_json_ts_formats_round_trip_ntz_v1``` and ```test_json_ts_formats_round_trip_ntz_v2```
<details>
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-dd-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM/dd-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-yyyy-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/yyyy-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-dd-yyyy-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/dd/yyyy-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd-MM-yyyy-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd/MM/yyyy-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v1[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(FileSourceScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-dd-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-dd-'T'HH:mm][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM/dd-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM/dd-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy-MM-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-yyyy/MM-'T'HH:mm][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-yyyy-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/yyyy-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-dd-yyyy-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM-dd-yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/dd/yyyy-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-MM/dd/yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd-MM-yyyy-][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd-MM-yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd/MM/yyyy-][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss.SSSXXX][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss[.SSS][XXX]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss.SSS][DATAGEN_SEED=1700475048, INJECT_OOM, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss[.SSS]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm:ss][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm[:ss]][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
FAILED ../../src/main/python/json_test.py::test_json_ts_formats_round_trip_ntz_v2[TIMESTAMP_LTZ-dd/MM/yyyy-'T'HH:mm][DATAGEN_SEED=1700475048, ALLOW_NON_GPU(BatchScanExec,ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.s...
</details>
</head>

**Comment by winningsix** [comment]
Per discussed offline, Spark 311, 330 and 341 are mandatory to verify.

File: integration_tests/src/main/python/cast_test.py [hunk 3]
```diff
@@ -151,6 +151,7 @@ def test_cast_string_date_non_ansi():
                                       StringGen('[0-9]{1,4}-[0-3][0-9]-[0-5][0-9][ |T][0-3][0-9]:[0-6][0-9]:[0-6][0-9]'),
```
Comment (winningsix) [inline integration_tests/src/main/python/cast_test.py:151]: Not sure why ```test_cast_string_date_valid_format```(In L65 above) and ```test_cast_string_date_non_ansi```(In L144 above) are not touched. No requirement for Spark.

File: integration_tests/src/main/python/cast_test.py [hunk 4]
```diff
@@ -151,6 +151,7 @@ def test_cast_string_date_non_ansi():
...
                                       StringGen('[0-9]{1,4}-[0-3][0-9]-[0-5][0-9][ |T][0-3][0-9]:[0-6][0-9]:[0-6][0-9].[0-9]{0,6}Z?')],
                         ids=idfn)
```
Comment (winningsix) [inline integration_tests/src/main/python/cast_test.py:153]: FYI. ```test_cast_string_date_valid_ansi``` and ```test_cast_string_date_valid_format``` need for xfail as well. It's skipped before Spark 320.

File: integration_tests/src/main/python/conditionals_test.py [hunk 5]
```diff
@@ -232,6 +241,7 @@ def test_conditional_with_side_effects_case_when(data_gen):
                 conf = test_conf)
 
 @pytest.mark.parametrize('data_gen', [mk_str_gen('[a-z]{0,3}')], ids=idfn)
+@pytest.mark.xfail(condition = is_not_utc(), reason = 'xfail non-UTC time zone tests because of https://github.com/NVIDIA/spark-rapids/issues/9653')
 def test_conditional_with_side_effects_sequence(data_gen):
     assert_gpu_and_cpu_are_equal_collect(
         lambda spark : unary_op_df(spark, data_gen).selectExpr(
```
Comment (winningsix) [inline integration_tests/src/main/python/conditionals_test.py:247]: ```test_conditional_with_side_effects_sequence_cast``` needed (L255). It's skipped before Spark 320.

**Comment by winningsix** [comment]
@res-life I went through failed cases in my local. I think most of them should be captured by xfail. See full list here https://github.com/NVIDIA/spark-rapids/pull/9719#issuecomment-1819940336 

Most of them are due to uncovered Spark version. But I do some cases not related to Spark version. I left comments within PR reviews.

**Comment by res-life** [comment]
build

File: integration_tests/src/main/python/cast_test.py (hunk 4 above)
Comment (res-life) [reply integration_tests/src/main/python/cast_test.py:153]: This should be an existing bug.

Comment (winningsix) [reply integration_tests/src/main/python/cast_test.py:153]: Yes, per offline discussed. Previous type check missed some cases about date data type which is also timezone aware.

**Comment by res-life** [comment]
For pre-merge CI 2, OOM occured:
```
[2023-11-21T12:23:14.166Z] ----------------------------- Captured stderr call -----------------------------
[2023-11-21T12:23:14.166Z] 2023-11-21 15:50:18 INFO     Error while receiving.
[2023-11-21T12:23:14.166Z] Traceback (most recent call last):
[2023-11-21T12:23:14.166Z]   File "/home/jenkins/agent/workspace/jenkins-rapids_premerge-github-8481-ci-2/.download/spark-3.1.1-bin-hadoop3.2/python/pyspark/sql/utils.py", line 111, in deco
[2023-11-21T12:23:14.166Z]     return f(*a, **kw)
[2023-11-21T12:23:14.166Z]   File "/home/jenkins/agent/workspace/jenkins-rapids_premerge-github-8481-ci-2/.download/spark-3.1.1-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
[2023-11-21T12:23:14.166Z]     raise Py4JJavaError(
[2023-11-21T12:23:14.166Z] py4j.protocol.Py4JJavaError: An error occurred while calling o650151.collectToPython.
[2023-11-21T12:23:14.166Z] : java.lang.OutOfMemoryError: Java heap space
[2023-11-21T12:23:14.166Z] 

```

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
Committed following code in `spark-premerge-build` to pass the non-UTC test to avoid [OOM issue](https://github.com/NVIDIA/spark-rapids/issues/9829)
```
    export TEST_PARALLEL=1
    TZ=Asia/Shanghai ./integration_tests/run_pyspark_from_build.sh -k 'aqe_test.py or arithmetic_ops_test.py or array_test.py or ast_test.py or cache_test.py or cast_test.py or cmp_test.py'
    TZ=Asia/Shanghai ./integration_tests/run_pyspark_from_build.sh -k 'collection_ops_test.py or conditionals_test.py or csv_test.py or datasourcev2_read_test.py or date_time_test.py or expand_exec_test.py or explain_test.py'
    TZ=Asia/Shanghai ./integration_tests/run_pyspark_from_build.sh -k 'fastparquet_compatibility_test.py or generate_expr_test.py or hash_aggregate_test.py or hashing_test.py or hive_delimited_text_test.py or hive_write_test.py or join_test.py'
    TZ=Asia/Shanghai ./integration_tests/run_pyspark_from_build.sh -k 'json_test.py or limit_test.py or map_test.py or mortgage_test.py or orc_cast_test.py or orc_test.py or orc_write_test.py'
    TZ=Asia/Shanghai ./integration_tests/run_pyspark_from_build.sh -k 'parquet_test.py or parquet_write_test.py or qa_nightly_select_test.py or repart_test.py or row-based_udf_test.py or row_conversion_test.py or sample_test.py'
    TZ=Asia/Shanghai ./integration_tests/run_pyspark_from_build.sh -k 'schema_evolution_test.py or sort_test.py or struct_test.py or subquery_test.py or time_window_test.py or udf_test.py or window_function_test.py'

```

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

File: jenkins/spark-premerge-build.sh [hunk 6]
```diff
@@ -154,7 +154,18 @@ ci_2() {
 
     # Download a Scala 2.12 build of spark
     prepare_spark $SPARK_VER 2.12
-    ./integration_tests/run_pyspark_from_build.sh
+
+
+    # Temporarily test non-UTC TZ
+    # Only test the impacted 43 files
+    # Split multiple parts to test to avoid OOM: refer to: https://github.com/NVIDIA/spark-rapids/issues/9829
```
Comment (winningsix) [inline jenkins/spark-premerge-build.sh:161]: How long does this cost after adding new test suites?

cc @pxLi

Comment (pxLi) [reply jenkins/spark-premerge-build.sh:161]: hmm seems adding too much duration. The ci_2 now cost ~3h5m even without default run_pyspark_from_build. for testing please also comment out cases after TZ ones to save time

Comment (res-life) [reply jenkins/spark-premerge-build.sh:161]: Here is testing the 43 files impacted by non-UTC time zone.
I'll select a sub-set of them.

Comment (winningsix) [reply jenkins/spark-premerge-build.sh:161]: Per discussed offline, let's only include 1 test for each type of result. Minimal list:
- parquet scan
- orc scan
- csv scan
- cast
- one for TimeZoneAwareExpression
- one for UTCTimestamp

Comment (pxLi) [reply jenkins/spark-premerge-build.sh:161]: super huge log which cannot be loaded in browser, I downloaded and checked TZ part

but we got some numbers for these TZ cases
```
start: [2023-11-24T01:47:31.478Z]
end: [2023-11-24T03:30:27.328Z]
```
~1h45m

**Comment by res-life** [comment]
Aready passed the CI for these commits [commit](https://github.com/NVIDIA/spark-rapids/pull/9773/commits/1311ffeb1e5362b9a3b42131e512b5788cbf9a59), which is testing the impacted 43 files for non-UTC timezone. 


The last commit revert to the original test and selected a portion of cases for non-UTC.

**Comment by res-life** [comment]
build

**Review by winningsix — APPROVED** [review]
LGTM. Waiting for pre-merge result.

**Review by pxLi — APPROVED** [review]
LGTM for pre-merge CI

**Comment by winningsix** [comment]
Could you help list ```short test summary info``` before/after your change in https://github.com/NVIDIA/spark-rapids/issues/6839 ?
e.g.,
```
= 0 failed, 8053 passed, 1026 skipped, 1742 xfailed, 11337 xpassed, 95 warnings in 14848.34s (4:07:28) =
```

**Comment by winningsix** [comment]
build

File: jenkins/spark-premerge-build.sh [hunk 7]
```diff
@@ -155,6 +155,12 @@ ci_2() {
     # Download a Scala 2.12 build of spark
     prepare_spark $SPARK_VER 2.12
     ./integration_tests/run_pyspark_from_build.sh
+
+    # Test a portion of cases for non-UTC time zone because of limited GPU resources.
+    # Here testing: parquet scan, orc scan, csv scan, cast, TimeZoneAwareExpression, FromUTCTimestamp
+    # Nightly CIs will cover all the cases.
+    TZ=Iran TEST='test_parquet_read_round_trip or test_read_round_trip or test_basic_csv_read or test_cast_string_ts_valid_format or test_unix_timestamp or test_from_utc_timestamp' ./integration_tests/run_pyspark_from_build.sh
```
Comment (winningsix) [inline jenkins/spark-premerge-build.sh:162]: I just renamed the title with "databricks" postfix and re-trigger a pre-merge. Let's ensure we don't break databrick shim before merging this PR.

**Review by winningsix — CHANGES_REQUESTED** [review]
Sorry for approving prematurely it. Let's on hold for merge before Databricks shim test.

File: jenkins/spark-premerge-build.sh (hunk 7 above)
Comment (pxLi) [reply jenkins/spark-premerge-build.sh:162]: it would not, databricks does not run this script. instead its relying 
on a dedicated test script https://github.com/NVIDIA/spark-rapids/blob/branch-23.12/jenkins/databricks/test.sh

**Comment by pxLi** [comment]
@res-life filed an issue to track the nightly update https://github.com/NVIDIA/spark-rapids/issues/9855

Please notify me when the script is ready thanks

File: jenkins/spark-premerge-build.sh (hunk 7 above)
Comment (winningsix) [reply jenkins/spark-premerge-build.sh:162]: Yes, let's double confirm DBX runtime was passed. Hopefully I am over worried on this.

**Comment by res-life** [comment]
build

**Review by winningsix — APPROVED** [review]
LGTM
