### PR TITLE
Make map column non-nullable when it's a key in another map.

### LINKED ISSUE #9129: [BUG] Writing Parquet map(map) column can not set the outer key as non-null.
**Describe the bug**
Reports the following error when writing map(map) column.
```
key column can not be nullable
```

The SchemaUtils.writerOptionsFromField can not handle map(map) column.
`SchemaUtils` uses `structBuilder` to simulate mapBuilder, but does not set the outer key as non-null. For the inner key, it's OK.

**Steps/Code to reproduce bug**
```
val data = Seq(
  (Map(Map(111->111, 112->112) -> 1, Map(121->121, 122->122) -> 2), 1),
  (Map(Map(211->111, 212->112) -> 1, Map(221->121, 222->122) -> 2), 2)
)
val df = spark.createDataFrame(data).toDF("c1", "c2")
df.write.parquet("/tmp/a.parquet")
```

Error:
```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0) (chongg-pc executor driver): java.lang.IllegalArgumentException: key column can not be nullable
	at ai.rapids.cudf.ColumnWriterOptions.mapColumn(ColumnWriterOptions.java:530)
	at com.nvidia.spark.rapids.SchemaUtils$.writerOptionsFromField(SchemaUtils.scala:298)
	at com.nvidia.spark.rapids.SchemaUtils$.$anonfun$writerOptionsFromSchema$1(SchemaUtils.scala:329)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:102)
	at com.nvidia.spark.rapids.SchemaUtils$.writerOptionsFromSchema(SchemaUtils.scala:327)
	at com.nvidia.spark.rapids.GpuParquetWriter.<init>(GpuParquetFileFormat.scala:374)
	at com.nvidia.spark.rapids.GpuParquetFileFormat$$anon$1.newInstance(GpuParquetFileFormat.scala:287)
	at org.apache.spark.sql.rapids.GpuSingleDirectoryDataWriter.newOutputWriter(GpuFileFormatDataWriter.scala:235)
	at org.apache.spark.sql.rapids.GpuSingleDirectoryDataWriter.<init>(GpuFileFormatDataWriter.scala:217)
	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.executeTask(GpuFileFormatWriter.scala:326)
	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$write$15(GpuFileFormatWriter.scala:266)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Environment details (please complete the following information)**
Branch 23.10

### PR DESCRIPTION
**Pull request by res-life**
fixes #9129

Fix map column can not be non-nullable.
Depends on https://github.com/rapidsai/cudf/pull/14003.

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala [hunk 1]
```diff
@@ -275,27 +276,35 @@ object SchemaUtils {
             a.elementType,
             name,
             a.containsNull,
-            writeInt96, fieldMeta, parquetFieldIdWriteEnabled).build())
+            writeInt96, fieldMeta, parquetFieldIdWriteEnabled, isMapKey = false).build())
       case m: MapType =>
+        // if this is a key of another map. e.g.: map1(map2(int,int), int), the map2 is the map
+        // key of map1, map2 should be non-nullable
+        val isMapNullable = if (isMapKey) false else nullable
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala:283]: Why do we need to set isMapKey instead of just going off of nullable? We set nullable to false specifically each place we set isMapKey to true.

Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala:283]: Consider 2 scenarios.
First scenario:
```
struct(
  field(column_1, map(int, int), nullable = true),
  field(column_1, map(int, int), nullable = false)
)
```
We should honor the nullable in the else branch
```
if (isMapKey) false else nullable
```

Second scenario:
```
struct(
  field(column_1, map1(map2(int, int), int), nullable = true)
)
```
The `isMapKey`  means `this map is a map key in another map?`.
The `isMapKey` here means the `m: MapType` is a map key of another map, and its type is also Map.
We can not know `isMapKey` unless that the outer `writerOptionsFromField` passes it in.
Consider the map1(map2(int, int), int), the logic is from outer to inner.
writerOptionsFromField first handles map1, then handle its (key(map2(int, int)), value), here isMapKey means (map2(int, int) is key of map1.
  writerOptionsFromField handles map2(int, int) (the key of outer map1), isMapKey is true, isMapKey is passed in from outer writerOptionsFromField.
  writerOptionsFromField handles int (the value of outer map1)

Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala:283]: I don't think you understand what I am saying. `isMapKey` is only ever set to true on line 296. On line 295 nullable is also always set to false for this same method call.

```
              nullable = false,
              writeInt96, fieldMeta, parquetFieldIdWriteEnabled, isMapKey = true).build()
```

There is never a situation if the current code when 

```
is (isMapKey) false else nullable
```

will return anything different from `nullable` by itself. If it did, then it would be an error in the code, because all map keys, no matter the type, are required to never be nullable. There is not even an option in the Spark MapType to make them nullable, which is why line 295 is hard coded.

Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala]: Thanks for your detailed review. Fixed.
And also tested succefully with https://github.com/rapidsai/cudf/pull/14003.
Once this PR is approved, I'll merge https://github.com/rapidsai/cudf/pull/14003 and this PR.

Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala]: The test code is in: https://github.com/NVIDIA/spark-rapids/pull/9090
```
  test("Statistics tests for Parquet files written by GPU, map(map)") {
    assume(false, "https://github.com/NVIDIA/spark-rapids/issues/9129")
    assume(true, "Move to scale test")
```
After this PR is merged, I'll update https://github.com/NVIDIA/spark-rapids/pull/9090

**Review by revans2 — APPROVED** [review]

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build
