### PR TITLE
Experimental support for BloomFilterAggregate expression in a reduction context [databricks]

### LINKED ISSUE #8955: [BUG] Bloom filter join tests can fail with multiple join columns
The Bloom filter join tests added in #8892 can fail when the GPU performs the Bloom filter aggregation and there are multiple join keys.  Example failure:
```
CPU OUTPUT: [Row(id=0, id2='0', second_id=0, id=0, second_id=0), Row(id=3, id2='3', second_id=3, id=3, second_id=3), Row(id=6, id2='6', second_id=1, id=6, second_id=1), Row(id=9, id2='9', second_id=4, id=9, second_id=4)]
GPU OUTPUT: [Row(id=0, id2='0', second_id=0, id=0, second_id=0), Row(id=3, id2='3', second_id=3, id=3, second_id=3)]
```

### PR DESCRIPTION
**Pull request by jlowe**
Relates to #7803. Depends on #8775. Closes #8955.

Implements GPU support for BloomFilterAggregate in a reduction context.  This is used by Bloom filter optimized joins which are available in Spark 3.3.0 and enabled by default in Spark 3.4.0.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by abellina — APPROVED** [review]

**Comment by jlowe** [comment]
build

File: tests/src/test/spark330/scala/com/nvidia/spark/rapids/BloomFilterAggregateQuerySuite.scala [hunk 1]
```diff
@@ -65,74 +68,149 @@ class BloomFilterAggregateQuerySuite extends SparkQueryCompareTestSuite {
...
+          """.stripMargin
+      df.createOrReplaceTempView(table)
+      withExposedSqlFuncs(df.sparkSession) { spark =>
+        spark.sql(sqlString)
+      }
+  }
+
+  private def getPlanValidator(exec: String): (SparkPlan, SparkPlan) => Unit = {
+    def searchPlan(p: SparkPlan): Boolean = {
+      if (ExecutionPlanCaptureCallback.didFallBack(p, exec)) {
```
Comment (abellina) [inline tests/src/test/spark330/scala/com/nvidia/spark/rapids/BloomFilterAggregateQuerySuite.scala:107]: nit, this could be simplified a bit:
```
ExecutionPlanCaptureCallback.didFallBack(p, exec) || 
  p.children.exists(searchPlan) || 
  p.subqueries.exists(searchPlan)
```

File: tests/src/test/spark330/scala/com/nvidia/spark/rapids/BloomFilterAggregateQuerySuite.scala [hunk 2]
```diff
@@ -65,74 +68,149 @@ class BloomFilterAggregateQuerySuite extends SparkQueryCompareTestSuite {
...
+      val executedPlan = ExecutionPlanCaptureCallback.extractExecutedPlan(gpuPlan)
+      assert(searchPlan(executedPlan), s"Could not find $exec in the GPU plan:\n$executedPlan")
+    }
+  }
+
+  // test with GPU bloom build, GPU bloom probe
+  for (numEstimated <- Seq(4096L, 4194304L,
     SQLConf.RUNTIME_BLOOM_FILTER_MAX_NUM_ITEMS.defaultValue.get)) {
-    for (numBits <- Seq(4096L, 4194304L, Long.MaxValue,
+    for (numBits <- Seq(4096L, 4194304L,
```
Comment (abellina) [inline tests/src/test/spark330/scala/com/nvidia/spark/rapids/BloomFilterAggregateQuerySuite.scala:126]: before we would check `Long.MaxValue` here in addition to `RUNTIME_BLOOM_FILTER_MAX_NUM_BITS.defaultValue`. I am mostly on curious on why we made the change, but I do wonder if we should go above `defaultValue`?

**Review by abellina — COMMENTED** [review]
I missed a couple of things last time, I am mostly curious about. The last changes in the integration tests LGTM.

File: tests/src/test/spark330/scala/com/nvidia/spark/rapids/BloomFilterAggregateQuerySuite.scala (hunk 2 above)
Comment (jlowe) [reply tests/src/test/spark330/scala/com/nvidia/spark/rapids/BloomFilterAggregateQuerySuite.scala:126]: I pulled out Long.MaxValue here primarily to save on test time.  These tests take a while as it is, and it adds literally minutes to add the extra Long.MaxValue cases.  Happy to add them back if we think it's worth it.

Comment (abellina) [reply tests/src/test/spark330/scala/com/nvidia/spark/rapids/BloomFilterAggregateQuerySuite.scala:126]: Ok that makes sense to me. I am fine without it, thanks for the feedback

**Review by abellina — DISMISSED** [review]

**Comment by jlowe** [comment]
Converting to draft as it needs the fixes from #8944 and the need to upmerge to the new tests there.

File: sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterShims.scala [hunk 3]
```diff
@@ -45,7 +46,24 @@ object BloomFilterShims {
...
             GpuBloomFilterMightContain(lhs, rhs)
-        })
+        }),
+      GpuOverrides.expr[BloomFilterAggregate](
+        "Bloom filter build",
+        ExprChecksImpl(Map(
+          (ReductionAggExprContext,
+            ContextChecks(TypeSig.BINARY, TypeSig.BINARY,
+              Seq(ParamCheck("child", TypeSig.LONG, TypeSig.LONG),
+                ParamCheck("estimatedItems", TypeSig.lit(TypeEnum.LONG), TypeSig.LONG),
```
Comment (revans2) [inline sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterShims.scala:56]: nit: Technically Spark is also checking to be sure that estimatedItems and estimatedBits are literals, actually foldable and > 0 and <= the config. So we could mark those as lit too and then the docs just show that we fully support it instead of adding a comment that we do not.

**Review by revans2 — COMMENTED** [review]
Generally looks good.

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]
