### PR TITLE
Disable hash partitioning on arrays

### LINKED ISSUE #2279: [BUG] Hash Partitioning can fail for very small batches
I am not 100% sure what the issue is, but we can get an invalid partition range for hash partitioning in some cases with the following patch.

This also triggers #2278 so only look at 

FAILED ../../src/main/python/join_test.py::test_sortmerge_join_array[100-Left-Array(String)][IGNORE_ORDER({'local': True})]
FAILED ../../src/main/python/join_test.py::test_sortmerge_join_array[100-Right-Array(String)][IGNORE_ORDER({'local': True})]
FAILED ../../src/main/python/join_test.py::test_sortmerge_join_array[100-Inner-Array(String)][IGNORE_ORDER({'local': True})]
FAILED ../../src/main/python/join_test.py::test_sortmerge_join_array[100-LeftSemi-Array(String)][IGNORE_ORDER({'local': True})]
FAILED ../../src/main/python/join_test.py::test_sortmerge_join_array[100-Cross-Array(String)][IGNORE_ORDER({'local': True})]

```diff
diff --git a/integration_tests/src/main/python/join_test.py b/integration_tests/src/main/python/join_test.py
index 745ba40dd..ee4e75dac 100644
--- a/integration_tests/src/main/python/join_test.py
+++ b/integration_tests/src/main/python/join_test.py
@@ -81,20 +81,26 @@ def create_nested_df(spark, key_data_gen, data_gen, left_length, right_length):
 @ignore_order(local=True)
 @pytest.mark.parametrize('data_gen', all_gen, ids=idfn)
 @pytest.mark.parametrize('join_type', ['Left', 'Right', 'Inner', 'LeftSemi', 'LeftAnti', 'Cross', 'FullOuter'], ids=idfn)
-def test_sortmerge_join(data_gen, join_type):
+@pytest.mark.parametrize('batch_size', ['100', '1g'], ids=idfn) # set the batch size so we can test out of core joins too
+def test_sortmerge_join(data_gen, join_type, batch_size):
     def do_join(spark):
         left, right = create_df(spark, data_gen, 500, 500)
         return left.join(right, left.a == right.r_a, join_type)
-    assert_gpu_and_cpu_are_equal_collect(do_join, conf=_sortmerge_join_conf)
+    conf = {'spark.rapids.sql.batchSizeBytes': batch_size}
+    conf.update(_sortmerge_join_conf)
+    assert_gpu_and_cpu_are_equal_collect(do_join, conf=conf)
 
 @ignore_order(local=True)
 @pytest.mark.parametrize('data_gen', single_level_array_gens_no_decimal, ids=idfn)
 @pytest.mark.parametrize('join_type', ['Left', 'Right', 'Inner', 'LeftSemi', 'LeftAnti', 'Cross', 'FullOuter'], ids=idfn)
-def test_sortmerge_join_array(data_gen, join_type):
+@pytest.mark.parametrize('batch_size', ['100', '1g'], ids=idfn) # set the batch size so we can test out of core joins too
+def test_sortmerge_join_array(data_gen, join_type, batch_size):
     def do_join(spark):
         left, right = create_nested_df(spark, short_gen, data_gen, 500, 500)
         return left.join(right, left.key == right.r_key, join_type)
-    assert_gpu_and_cpu_are_equal_collect(do_join, conf=_sortmerge_join_conf)
+    conf = {'spark.rapids.sql.batchSizeBytes': batch_size}
+    conf.update(_sortmerge_join_conf)
+    assert_gpu_and_cpu_are_equal_collect(do_join, conf=conf)
 
 @allow_non_gpu('SortMergeJoinExec', 'SortExec', 'KnownFloatingPointNormalized', 'ArrayTransform', 'LambdaFunction', 'NamedLambdaVariable', 'NormalizeNaNAndZero')
 @ignore_order(local=True)
@@ -109,11 +115,14 @@ def test_sortmerge_join_array_as_key(data_gen, join_type):
 @ignore_order(local=True)
 @pytest.mark.parametrize('data_gen', [all_basic_struct_gen], ids=idfn)
 @pytest.mark.parametrize('join_type', ['Left', 'Right', 'Inner', 'LeftSemi', 'LeftAnti', 'Cross', 'FullOuter'], ids=idfn)
-def test_sortmerge_join_struct(data_gen, join_type):
+@pytest.mark.parametrize('batch_size', ['100', '1g'], ids=idfn) # set the batch size so we can test out of core joins too
+def test_sortmerge_join_struct(data_gen, join_type, batch_size):
     def do_join(spark):
         left, right = create_nested_df(spark, short_gen, data_gen, 500, 500)
         return left.join(right, left.key == right.r_key, join_type)
-    assert_gpu_and_cpu_are_equal_collect(do_join, conf=_sortmerge_join_conf)
+    conf = {'spark.rapids.sql.batchSizeBytes': batch_size}
+    conf.update(_sortmerge_join_conf)
+    assert_gpu_and_cpu_are_equal_collect(do_join, conf=conf)
 
 @allow_non_gpu('SortMergeJoinExec', 'SortExec', 'KnownFloatingPointNormalized', 'NormalizeNaNAndZero', 'CreateNamedStruct', 'GetStructField', 'Literal', 'If', 'IsNull')
 @ignore_order(local=True)
```

The exception I get back is

```
21/04/28 13:24:55 ERROR Executor: Exception in task 0.0 in stage 1743.0 (TID 2316)
ai.rapids.cudf.CudfException: cuDF failure at: ../include/cudf/strings/detail/utilities.cuh:52: Invalid iterator range
        at ai.rapids.cudf.Table.partition(Native Method)
        at ai.rapids.cudf.Table.partition(Table.java:1294)
        at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$6(GpuHashPartitioning.scala:61)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
        at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$5(GpuHashPartitioning.scala:60)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
        at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$1(GpuHashPartitioning.scala:59)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
        at com.nvidia.spark.rapids.GpuHashPartitioning.partitionInternalAndClose(GpuHashPartitioning.scala:51)
        at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$2(GpuHashPartitioning.scala:82)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
        at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$1(GpuHashPartitioning.scala:81)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
        at com.nvidia.spark.rapids.GpuHashPartitioning.columnarEval(GpuHashPartitioning.scala:78)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$.$anonfun$prepareBatchShuffleDependency$3(GpuShuffleExchangeExec.scala:203)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:224)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:235)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:155)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I'm not sure if it is an issue with cudf or what.

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #2279 

This disables hash partitioning for arrays as a workaround until https://github.com/rapidsai/cudf/issues/8098 is fixed.

I verified that the updated integration test fails if the GPU tagging change is not applied and passes with it, but only if the fix for #2318 is present so this is dependent upon that change before CI will pass.

### CODE REVIEW

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala [hunk 1]
```diff
@@ -62,6 +62,9 @@ class GpuShuffleMeta(
           .foreach { dataType =>
             willNotWorkOnGpu(s"round-robin partitioning cannot sort $dataType")
           }
+    } else if (shuffle.outputPartitioning.isInstanceOf[HashPartitioning] &&
+        shuffle.output.exists(_.dataType.isInstanceOf[ArrayType])) {
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala:66]: I'm not sure this fixes all cases.  What about a struct of array types? The reason the RoundRobin one could be simple because both structs and arrays were not allowed so all nested types were eliminated. It might be simpler to use TypeSig to show what is allowed.

```
val allowed = (TypeSig.commonCudfTypes + TypeSig.NULL + TypeSig.DECIMAL + TypeSig.STRUCT).nested()
shuffle.output.foreach { att => 
  if (!allowed.isSupportedType(att.dataType)) {
    willNotWorkOnGpu("hash partitioning does not support ${att.dataType}")
  }
}
```

Comment (revans2) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala:66]: Also in both your check and my check we are really being overly restrictive.  The only cases where this is an issue is an Array with an Array or string under it.  So if we really wanted to allow as much as possible we could write something specific that walks through all of the nested types looking for arrays, and if it finds one, then it switches to look under it for arrays or strings, and if it finds those, then it fails.

Comment (jlowe) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala]: I've refined the check to only exclude arrays of nested types and strings.

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]
Looks great
