### PR TITLE
Fix read old data from alluxio regardless of S3 changes when using CONVERT_TIME replacement algorithm

### LINKED ISSUE #6779: [BUG] Always read old data from alluxio regardless of S3 changes when using CONVERT_TIME replacement algorithm
**Describe the bug**
When using the CONVERT_TIME Alluxio replacement algorithm, auto mount method, and adding new files into s3, 
Spark rapids can't read the new files.
The query path is replaced with the Alluxio path, and Alluxio does not fetch new files from S3, thus this issue occurs.

For example:
Read from `s3://bucket/tab`, the replaced path is `alluxio://master_ip:19998/tab`
Adding files to `s3://bucket/tab` will reproduce this issue.

**Steps/Code to reproduce bug**
Read from an s3 path
``` scala
val base_path = "s3a://liangcail/chongg-test"
spark.conf.set("spark.rapids.alluxio.replacement.algo", "CONVERT_TIME")
spark.conf.set("spark.sql.adaptive.enabled", "false")

spark.read.parquet(base_path).createOrReplaceTempView("tbl")
spark.sql("select (sum(ws_sold_time_sk) + sum(ws_ship_date_sk)) / 3800809931000 / 2 from tbl").show()
```
Add files to the s3 path
```
aws s3 put x.parquet s3://liangcail/chongg-test/new_name.parquet
```

Logs:
```
22/10/13 09:57:47 DEBUG AlluxioUtils: 
Replace s3a://liangcail/chongg-test to alluxio://10.59.255.53:19998/liangcail/chongg-test
22/10/13 09:57:47 DEBUG AlluxioUtils: 
Automount replacing paths: AlluxioPathReplaceConvertTime(alluxio://10.59.255.53:19998/liangcail/chongg-test,Some(s3a://))

22/10/13 09:57:47 DEBUG FileSystemMasterClient: Exit (OK): ListStatus(path=/liangcail/chongg-test,options=loadMetadataType: ONCE
commonOptions {
  syncIntervalMs: -1
  ttl: -1
  ttlAction: DELETE
}
loadMetadataOnly: false
) in 5 ms
```

Seems Alluxio did not sync the directory list from S3 when doing ListStatus.

**Environment details (please complete the following information)**
Databricks with Alluxio open

**Additional context**
For the default installation of Alluxio, Alluxio will never synchronize the files list from S3 for any directories.
Seems The alluxio ListStatus operation also does not sync by default.

Note:  `createOrReplaceTempView` before each query also has this issue.

Adding the following config works:
```
alluxio.user.file.metadata.sync.interval=5s
```

Not sure about the delay time, maybe 2 ways:
- When the query running, immediately sync and the query result is correct.
- Query use old meta, thus query result is incorrect. Start an async thread to sync, after 5s the following query will be OK.

### PR DESCRIPTION
**Pull request by res-life**
Closes #6779 

### Root cause

There are 2 ways to create `InMemoryFileIndex`: 
[First](https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala#L634ToL640)
```
          val fi = new InMemoryFileIndex(
            relation.sparkSession,
            inputFiles,     // This is actually sub files under the root path

```

[second](https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala#L564ToL569)
```
        val replacedPathsAndIndicator = rootPaths.map(replaceFunc.get)
...
        val fi = new InMemoryFileIndex(
          relation.sparkSession,
          replacedPaths,   // This is actually replaced root path.

```

For the second case,  actually filled no sub-files,  this will depend on `InMemoryFileIndex` listing leaf files.
As you know Alluxio by default does not sync the file lists(It just lists Alluxio local cache files), so will query old data from Alluxio.

```
// log is like:
INFO InMemoryFileIndex: Start listing leaf files and directories. Size of Paths: 0; threshold: 32
DEBUG FileSystemMasterClient: Exit (OK): ListStatus(path=/liangcail/chongg-test,options=loadMetadataType: ONCE
commonOptions {
  syncIntervalMs: -1
  ttl: -1
  ttlAction: DELETE
}
loadMetadataOnly: false
) in 5 ms
```

###  Solution
- This PR passes all the sub-files to `InMemoryFileIndex`,  the file list is from the s3 metadata
There are 3 types of external file change: Add, delete, Update.
CONVERT_TIME can't handle all the 3: Add/delete/Update.
After this PR, CONVERT_TIME can handle Add/delete.

For the Update case, We can add Alluxio syncing at 1-hour interval
```
alluxio.user.file.metadata.sync.interval=3600s
```
For the Update case, we don't know the update frequency, it depends on the user's case.
This PR does not handle this update case.

- Keep the original code, just add sync configure.
In order to trace the Add/Delete/Update change, should set a relative small sync interval, like:
alluxio.user.file.metadata.sync.interval=60s
But the performance is bad,  See: https://github.com/NVIDIA/spark-rapids/issues/6779#issuecomment-1298525831

I prefer the 1st solution and this PR is the 1st.

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala [hunk 1]
```diff
@@ -578,9 +578,6 @@ object AlluxioUtils extends Logging {
       // we know then fall back to inferring. The latter happens on certain CSPs
       // like Databricks where they have customer file index types.
       relation.location match {
-        case pfi: PartitioningAwareFileIndex =>
-          logDebug("Handling PartitioningAwareFileIndex")
-          createNewFileIndexWithPathsReplaced(pfi.partitionSpec(), pfi.rootPaths)
         case cfi: CatalogFileIndex =>
```
Comment (tgravescs) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala:581]: I'm assuming same condition can happen here since we use the same FileIndex replacement

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala [hunk 2]
```diff
@@ -578,9 +578,6 @@ object AlluxioUtils extends Logging {
       // we know then fall back to inferring. The latter happens on certain CSPs
       // like Databricks where they have customer file index types.
       relation.location match {
```
Comment (tgravescs) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala:580]: Overall I did this for performance to specifically get rid of the listleaf files call.   I guess now that we have the Task time replacement algorithm, I would be ok with just removing this code and having ti do the list leaf files all the time to fix this issue and then allow locality to apply.  So please go ahead and remove both case statements and cleanup unneeded code.

**Comment by res-life** [comment]
Close this, please refer to https://github.com/NVIDIA/spark-rapids/pull/6993

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala (hunk 2 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala:582]: Updated the case statements.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala (hunk 1 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala:583]: The information of `CatalogFileIndex` is from catalog table.
Refer to the code: [Link1](https://github.com/apache/spark/blob/v3.3.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/CatalogFileIndex.scala#L73)

``` scala
val selectedPartitions = ExternalCatalogUtils.listPartitionsByFilter(
        sparkSession.sessionState.conf, sparkSession.sessionState.catalog, table, filters)
```

If we create table before executing a query, then the table will be refreshed.
If do refresh operation on this table, it also refresh.

IMO, we can keep it as it is now.

File: sql-plugin/src/main/311until320-all/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala [hunk 3]
```diff
@@ -835,6 +838,7 @@ private class RapidsBufferReleasingInputStream(
     }
   }
 
+  @scala.annotation.nowarn("msg=method closeQuietly in class IOUtils is deprecated")
```
Comment (tgravescs) [inline sql-plugin/src/main/311until320-all/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala:841]: I'd rather see these put up as separate PRs in the future so they can be tracked properly.  Its fine for now.

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
build
