### PR TITLE
Fixed Decimal 128 bug in ParquetCachedBatchSerializer

### LINKED ISSUE #4826: [BUG] cache_test failures when testing with 128-bit decimal
While testing #4823 on Spark 3.2, cache tests were failing when 128-bit decimals were added to `decimal_gens`.  Specifically two tests were failing:
```
[2022-02-18T19:25:33.459Z] FAILED ../../src/main/python/cache_test.py::test_cache_partial_load[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}-Decimal(20,2)][ALLOW_NON_GPU(CollectLimitExec)]
[2022-02-18T19:25:33.459Z] FAILED ../../src/main/python/cache_test.py::test_cache_cpu_gpu_mixed[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}-Decimal(20,2)]
```

`test_cache_partial_load` was failing with "not all the plan is on the GPU" while `test_cache_cpu_gpu_mixed` was failing with:
```
E                   Caused by: java.lang.ArithmeticException: Decimal precision 21 exceeds max precision 20
E                   	at org.apache.spark.sql.types.Decimal.set(Decimal.scala:122)
E                   	at org.apache.spark.sql.types.Decimal$.apply(Decimal.scala:571)
E                   	at org.apache.spark.sql.types.Decimal.apply(Decimal.scala)
E                   	at org.apache.spark.sql.execution.vectorized.WritableColumnVector.getDecimal(WritableColumnVector.java:378)
E                   	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
E                   	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
E                   	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:757)
E                   	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
E                   	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:178)
E                   	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
E                   	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
E                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
E                   	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
E                   	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)
E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
E                   	at org.apache.spark.scheduler.Task.run(Task.scala:91)
E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:813)
E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1620)
E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:816)
E                   	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:672)
E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
E                   	... 1 more
```

### PR DESCRIPTION
**Pull request by razajafri**
This PR fixes the way we were reading the parquet schema on the CPU. The problem was that the `SparkToParquetSchemaConverter` doesn't honor the 8-byte alignment, instead it changes the schema to the minimum bits needed to store the value which was causing PCBS to not read the entire value thus resulting in test failures

fixes #4826 

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Review by revans2 — DISMISSED** [review]

File: sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala [hunk 1]
```diff
@@ -907,8 +907,10 @@ protected class ParquetCachedBatchSerializer extends GpuCachedBatchSerializer wi
           index -> inMemReqSparkSchema.fields.indexOf(reqSparkSchemaInCacheOrder.fields(index))
         }.toMap
 
-        val reqParquetSchemaInCacheOrder =
-          sparkToParquetSchemaConverter.convert(reqSparkSchemaInCacheOrder)
+        val reqParquetSchemaInCacheOrder = new org.apache.parquet.schema.MessageType(
```
Comment (gerashegalov) [inline sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala:910]: it would be good to break up L870-956 code in smaller methods.

Have a method/class encapsulating SparkToParquetSchemaConverter and handling both cases of StructType to Parquet schema conversions with a comment

Comment (razajafri) [reply sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala:910]: If this is just a NIT, can we do this as a follow-on please?

Comment (gerashegalov) [reply sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala:910]: not a nit, now we use two different methods to map a Spark schema to Parquet without any explanation. If we had a dedicated method for this it would be easy to put a comment explaining this, and the code would be more readable.

Comment (razajafri) [reply sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala:906]: I have removed the ParquetToSparkSchemaConverter as I agree it was causing confusion. PTAL and let me know if this is more clear.

**Comment by razajafri** [comment]
build

**Review by gerashegalov — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Comment by firestarman** [comment]
Would we also need to update it for the 320+ shims ? 
https://github.com/NVIDIA/spark-rapids/blob/branch-22.04/sql-plugin%2Fsrc%2Fmain%2F320%2B%2Fscala%2Fcom%2Fnvidia%2Fspark%2Frapids%2Fshims%2FSpark320PlusShims.scala#L601
