### PR TITLE
Fix for AQE+DPP issue on AWS EMR [databricks]

### LINKED ISSUE #6978: [BUG] NDS query 16 fails on EMR 6.8.0 with AQE enabled
**Describe the bug**
When running NDS query 16 on EMR 6.8.0 with AQE enabled, the following exception is encountered: 
```
py4j.protocol.Py4JJavaError: An error occurred while calling o192.collectToPython.
: java.lang.UnsupportedOperationException: WholeStageCodegen (2) does not implement doExecuteBroadcast
        at org.apache.spark.sql.errors.QueryExecutionErrors$.doExecuteBroadcastNotImplementedError(QueryExecutionErrors.scala:1924)
        at org.apache.spark.sql.execution.SparkPlan.doExecuteBroadcast(SparkPlan.scala:331)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$doExecuteBroadcast$1(AdaptiveSparkPlanExec.scala:500)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:506)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.doExecuteBroadcast(AdaptiveSparkPlanExec.scala:499)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:226)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:251)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:248)
        at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:222)
        at org.apache.spark.sql.execution.exchange.BaseOutputAdapterExec.doExecuteBroadcast(Exchange.scala:136)
        at org.apache.spark.sql.execution.exchange.BaseOutputAdapterExec.doExecuteBroadcast$(Exchange.scala:135)
        at org.apache.spark.sql.execution.OutputAdapterExec.doExecuteBroadcast(OutputAdapterExec.scala:35)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:226)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:251)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:248)
        at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:222)
        at org.apache.spark.sql.execution.SubqueryBroadcastExec.doExecuteCollect(SubqueryBroadcastExec.scala:77)
        at org.apache.spark.sql.execution.AsyncSubqueryExec$$anon$2.doCompute(basicPhysicalOperators.scala:931)
        at org.apache.spark.sql.execution.AsyncSubqueryExec$$anon$2.doCompute(basicPhysicalOperators.scala:928)
        at org.apache.spark.sql.execution.AsyncDriverOperation.$anonfun$compute$1(AsyncDriverOperation.scala:73)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
        at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
        at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:216)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:199)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:245)
        at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:196)
        at org.apache.spark.sql.execution.AsyncDriverOperation.compute(AsyncDriverOperation.scala:67)
        at org.apache.spark.sql.execution.AsyncDriverOperation.$anonfun$computeFuture$1(AsyncDriverOperation.scala:53)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$1(SQLExecution.scala:267)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

Note that when the default datasourceV2 is used for Parquet, this exception is not encountered.  Additionally, NDS query 16 on CPU with AQE does not fail.
 
**Environment details (please complete the following information)**
EMR 6.8.0 which is using Spark RAPIDS 22.06 jar
DatasourceV1 is enabled for Parquet with this setting: spark.sql.sources.useV1SourceList=parquet

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #6978 and #7133.

This fixes GpuBroadcastToRowExec by allowing to support HashedRelationBroadcastMode in addition to IdentityBroadcastMode.  The situation that manifests the bug happens when a CPU-based SubqueryBroadcastExec has a ReusedExchangeExec as its child which re-uses a GpuBroadcastExchangeExec. This occurs in AQE+DPP enabled environments since in AQE, the original GpuBroadcastExchangeExec would be submitted as a separate BroadcastQueryStage and the SubqueryBroadcastExchangeExec and ReusedExchangeExec might actually re-use it. 

This is tested via a scalatest that uses a query that is used with AQE+DPP enabled and is modified to move the SubqueryBroadcastExchangeExec to the CPU, which simulates the issue that happens in AWS EMR.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by NVnavkumar** [comment]
build

**Comment by NVnavkumar** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2021-2022, NVIDIA CORPORATION.
+ * Copyright (c) 2022-2023, NVIDIA CORPORATION.
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala:2]:
```suggestion
 * Copyright (c) 2021-2023, NVIDIA CORPORATION.
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala [hunk 2]
```diff
@@ -27,22 +27,27 @@ import com.nvidia.spark.rapids.shims.{ShimBroadcastExchangeLike, ShimUnaryExecNo
...
 case class GpuBroadcastToRowExec(
-  index: Int,
   buildKeys: Seq[Expression],
-  child: SparkPlan)(modeKeys: Option[Seq[Expression]])
-  extends ShimBroadcastExchangeLike with ShimUnaryExecNode with GpuExec {
+  broadcastMode: BroadcastMode,
+  child: SparkPlan)(index: Option[Int], modeKeys: Option[Seq[Expression]])
+  extends ShimBroadcastExchangeLike with ShimUnaryExecNode with GpuExec with Logging {
+
+  override def otherCopyArgs: Seq[AnyRef] = modeKeys :: Nil
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala:50]:
```suggestion
  override def otherCopyArgs: Seq[AnyRef] = index :: modeKeys :: Nil
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala [hunk 3]
```diff
@@ -75,43 +80,51 @@ case class GpuBroadcastToRowExec(
...
     gpuLongMetric("dataSize") += serBatch.dataSize
     gpuLongMetric(COLLECT_TIME) += System.nanoTime() - beforeCollect
 
-    result
+    broadcastMode match {
+      case map @ HashedRelationBroadcastMode(_, _) =>
+        SparkShimImpl.broadcastModeTransform(map, result)
+      case _ =>
+        result
+    }
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala:127]: Shouldn't this be simplified to just always call the broadcastModeTransform?  broadcastModeTransform already does nothing if it's an IdentityBroadcastMode.

File: tests/src/test/320+-noncdh-nondb/scala/com/nvidia/spark/rapids/DynamicPruningSuite.scala [hunk 4]
```diff
@@ -0,0 +1,224 @@
+/*
+ * Copyright (c) 2020-2022, NVIDIA CORPORATION.
```
Comment (jlowe) [inline tests/src/test/320+-noncdh-nondb/scala/com/nvidia/spark/rapids/DynamicPruningSuite.scala:2]:
```suggestion
 * Copyright (c) 2023, NVIDIA CORPORATION.
```

File: tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala [hunk 5]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2020-2021, NVIDIA CORPORATION.
+ * Copyright (c) 2020-2022, NVIDIA CORPORATION.
```
Comment (jlowe) [inline tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala:2]:
```suggestion
 * Copyright (c) 2020-2023, NVIDIA CORPORATION.
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala (hunk 1 above)
Comment (NVnavkumar) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala:2]: So on this one, the original copyright year was incorrect. It should have only been 2022. So that's why this was changed to 2022-2023

**Review by jlowe — APPROVED** [review]
