### PR TITLE
Fix LEAD/LAG failures in Spark 3.1.1

### LINKED ISSUE #999: [BUG] test_multi_types_window_aggs_for_rows_lead_lag fails against Spark 3.1.0
**Describe the bug**
Nightly build of integration tests against Spark 3.1.0 are failing in the test_multi_types_window_aggs_for_lead_lag tests.

**Steps/Code to reproduce bug**
Run integration tests against latest Spark 3.1.0-SNAPSHOT

**Expected behavior**
Tests do not fail.

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #999.

Fixes class-loader related errors of LEAD/LAG operators, which caused test failures like:
```
: java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
com/nvidia/spark/rapids/OffsetWindowFunctionMeta.<init>(Lorg/apache/spark/sql/catalyst/expressions/OffsetWindowFunction;Lcom/nvidia/spark/rapids/RapidsConf;Lscala/Option;Lcom/nvidia/spark/rapids/ConfKeysAndIncompat;)V @11: invokespecial
Reason:
Type 'org/apache/spark/sql/catalyst/expressions/OffsetWindowFunction' (current frame, stack[1]) is not assignable to 'org/apache/spark/sql/catalyst/expressions/Expression'
```

Also corrects for the reversal in offset semantics for `LAG()` expressions in Spark 3.1.1, causing `Lag.offset` to be negative.

Signed-off-by: Mithun RK <mythrocks@gmail.com>

### CODE REVIEW

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+    conf: RapidsConf,
+    parent: Option[RapidsMeta[_, _, _]],
+    rule: DataFromReplacementRule)
+  extends ExprMeta[INPUT](expr, conf, parent, rule) {
+  val input: BaseExprMeta[_] = GpuOverrides.wrapExpr(expr.input, conf, Some(this))
+  // For LAG() expressions, negate the offset value.
+  val adjustedOffset: Expression = {
+    expr match {
+      case lag: Lag =>
+        lag.offset match {
```
Comment (revans2) [inline shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala:45]: Is ti possible to ever have an alias here? I think it would be cleaner to just use GpuOverrides.extractLit

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala [hunk 2]
```diff
@@ -45,6 +45,21 @@ import org.apache.spark.sql.rapids.shims.spark311._
 import org.apache.spark.sql.types._
 import org.apache.spark.storage.{BlockId, BlockManagerId}
 
+abstract class OffsetWindowFunctionMeta2[INPUT <: OffsetWindowFunction] (
```
Comment (revans2) [inline shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala:48]: This is never used. Can it be deleted?

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+          case Literal(v: Int, IntegerType) =>
+            Literal(-v)
+          case _ => expr.offset
```
Comment (revans2) [inline shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala:48]: Wouldn't this cause an error if this path was ever taken?  Can we throw an exception instead?

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala (hunk 2 above)
Comment (mythrocks) [reply shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala:48]: Yes, of course. Apologies, this is sloppy.

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala (hunk 3 above)
Comment (mythrocks) [reply shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala]: Agreed. Fixed.

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala (hunk 1 above)
Comment (mythrocks) [reply shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala]: I haven't been able to make this turn into an alias in my testing. But it's best to defend against this possibility.

**Review by revans2 — APPROVED** [review]

**Comment by mythrocks** [comment]
At the risk of blowing this up a little, we might consider a couple of changes more:
1. Add similarly robust offset checks in `com.nvidia.spark.rapids.OffsetWindowFunctionMeta`.
2. Add a `tagSelfForGpu()`, and fail GPU pushdown in case the offsets in the window are not suitable for acceleration.

**Comment by revans2** [comment]
> At the risk of blowing this up a little, we might consider a couple of changes more:
> 
>     1. Add similarly robust offset checks in `com.nvidia.spark.rapids.OffsetWindowFunctionMeta`.
> 
>     2. Add a `tagSelfForGpu()`, and fail GPU pushdown in case the offsets in the window are not suitable for acceleration.

Do it

**Comment by mythrocks** [comment]
Hmm... I wonder if adding `tagExprForGpu` might help. 

@revans2, is there a guarantee that `tagExprForGpu()` will be called before `OffsetWindowFunctionMeta::childExprs` is evaluated? If not, the exceptions we throw when calculating the `adjustedOffset` would've been thrown anyway.

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+    parent: Option[RapidsMeta[_, _, _]],
+    rule: DataFromReplacementRule)
+  extends ExprMeta[INPUT](expr, conf, parent, rule) {
+  val input: BaseExprMeta[_] = GpuOverrides.wrapExpr(expr.input, conf, Some(this))
+  // For LAG() expressions, negate the offset value.
+  val adjustedOffset: Expression = {
+    expr match {
+      case lag: Lag =>
+        GpuOverrides.extractLit(lag.offset) match {
+         case Some(Literal(offset:Int, IntegerType)) =>
```
Comment (gerashegalov) [inline shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala:46]: nit: space
```suggestion
         case Some(Literal(offset: Int, IntegerType)) =>
```

**Review by gerashegalov — COMMENTED** [review]
LGTM

**Review by gerashegalov — APPROVED** [review]

File: shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala (hunk 4 above)
Comment (mythrocks) [reply shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala]: Thanks, @gerashegalov. Fixed.

**Comment by mythrocks** [comment]
> If not, the exceptions we throw when calculating the adjustedOffset would've been thrown anyway.

Apologies for the delay. I have now added `tagExprForGpu()`, and set it up so that the expressions aren't converted for GPU on construction.

Could I please bother @gerashegalov  and @revans2 to see if this is agreeable?

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Comment by mythrocks** [comment]
Thanks for the reviews, @revans2, @gerashegalov.
