### PR TITLE
Fix spark400 build due to LogicalRelation signature changes [databricks]

### LINKED ISSUE #11684: [BUG] 24.12 Precommit fails with wrong number of arguments in `GpuDataSource`
**Describe the bug**
Precommit build fails with the following error for PRs targeted to 24.12 

```
/home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala:87: wrong number of arguments for pattern org.apache.spark.sql.execution.datasources.LogicalRelation(relation: 
org.apache.spark.sql.sources.BaseRelation, output: Seq[org.apache.spark.sql.catalyst.expressions.AttributeReference], catalogTable: Option[org.apache.spark.sql.catalyst.catalog.CatalogTable], isStreaming: Boolean, stream: Option[org.apache.spark.sql.connector.read.streaming.SparkDataStream])
```
This looks related to Spark 4. 0 changes. 

I am unable to reproduce this locally -- will update when I can 

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #11684.  [SPARK-50144](https://issues.apache.org/jira/browse/SPARK-50144) added a new parameter to LogicalRelation, breaking old unapply usages.  Added a new shim for gathering the locations for a logical plan which was the one place using LogicalRelation.unapply.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by razajafri — APPROVED** [review]

**Comment by mythrocks** [comment]
Hey, thanks for picking this up, @jlowe.  I was about to raise a PR for this.  I do like yours better.

**Review by mythrocks — APPROVED** [review]

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala [hunk 1]
```diff
@@ -83,9 +84,7 @@ case class GpuDataSource(
     PartitioningUtils.validatePartitionColumn(data.schema, partitionColumns, caseSensitive)
 
     val fileIndex = catalogTable.map(_.identifier).map { tableIdent =>
-      sparkSession.table(tableIdent).queryExecution.analyzed.collect {
-        case LogicalRelation(t: HadoopFsRelation, _, _, _) => t.location
-      }.head
+      LogicalPlanShims.getLocations(sparkSession.table(tableIdent).queryExecution.analyzed).head
```
Comment (gerashegalov) [inline sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala:87]: It is not a nice Scala but I recommend to future-proof and avoid small shim burden:
```Scala
    val fileIndex = catalogTable.map(_.identifier).map { tableIdent =>
      sparkSession.table(tableIdent).queryExecution.analyzed.collect {
        case lr: LogicalRelation if lr.relation.isInstanceOf[HadoopFsRelation] => 
          lr.relation.asInstanceOf[HadoopFsRelation].location
      }.head
    }
```

Comment (jlowe) [reply sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala:87]: I considered this at first, but I'm not sure this is "future-proof."  I think we'd rather prefer to have the compiler and/or runtime inform us if a Spark platform changed this interface, since we may need to do more than just ignore the added parameters.  In those cases Spark would have to change this corresponding code, and we would need to change it in a compatible way.  Maybe that change is to ignore the added or removed parameters, maybe not.
