### PR TITLE
Use per-batch retry block in R2C with lightweight OOM recovery

### LINKED ISSUE #14368: [BUG] Per-row retry in GpuRowToColumnarExec (#13842) may introduce noticeable overhead
**Describe the bug**

PR #13842 (`c98e80005`, "Make convert in R2C retryable to prevent Host OOM") introduced per-row retry logic in `RowToColumnarIterator.buildBatch`. The conversion loop now wraps each row with `withRetryNoSplit` + `withRestoreOnRetry`:

```scala
while (rowIter.hasNext && ...) {
  converter.attempt(rowIter.next())
  val bytesWritten = withRetryNoSplit {
    withRestoreOnRetry(converter) {
      converters.convert(converter.currentRow, builders)
    }
  }
  byteCount += bytesWritten
  rowCount += 1
}
```

Previously this was simply:
```scala
while (rowIter.hasNext && ...) {
  val row = rowIter.next()
  byteCount += converters.convert(row, builders)
  rowCount += 1
}
```

Although the design defers expensive operations (row copy, builder snapshot) to the OOM path, the `withRetryNoSplit` / `withRestoreOnRetry` wrapper itself is invoked **per row**. For workloads with a large number of rows flowing through `GpuRowToColumnarExec`, the per-row overhead of entering/exiting the retry framework may be non-trivial.

**Expected behavior**

The retry mechanism should not introduce observable regression in the common (no-OOM) path. If per-row wrapping is too expensive, consider batching the retry at a coarser granularity (e.g., per-batch or per-chunk-of-rows).

**Additional context**

Screenshots / profiling data will be attached in follow-up comments.

### PR DESCRIPTION
**Pull request by thirtiseven**
Fixes #14368

### Description

PR #13842 wrapped each row in `RowToColumnarIterator.buildBatch` with `withRetryNoSplit` + `withRestoreOnRetry`, which introduced significant per-row overhead (~19x slower) from JNI calls, synchronized blocks, and object allocations on every row — even in the common no-OOM path.

This PR replaces the per-row retry framework usage with a single per-batch retry block and a lightweight catch-based OOM recovery:

**Design: per-batch retry block + inline OOM handling**

The conversion loop runs inside `RmmRapidsRetryIterator.withRetryBlock`, which enters the RMM retry block once per batch (not per row). A per-row `captureState()` / `restoreState()` on the column builders enables rollback on OOM — these are lightweight offset snapshots with negligible overhead.

On OOM, a single catch arm handles all cases:

| Scenario | Action |
|----------|--------|
| RetryOOM/SplitAndRetryOOM with rows already converted (non-RequireSingleBatch) | Emit partial batch, save failed row as `pendingRow` for next batch |
| RetryOOM with no rows yet (or RequireSingleBatch) | `blockUntilMemoryFreed()` — wait for spill, then while-loop retries naturally |
| SplitAndRetryOOM with no rows yet | Propagate — can't split a single row |

This is an **optimistic strategy**: pay minimal overhead (one `captureState` per row) in the common case, and only block/wait when absolutely necessary.

**New retry framework utilities**

Two general-purpose methods are added to `RmmRapidsRetryIterator` for incremental operations where partial progress is valuable (doesn't fit the standard atomic-retry model of `withRetryNoSplit`):

- `withRetryBlock[T](fn: => T): T` — manages the retry block lifecycle without automatic retry
- `blockUntilMemoryFreed()` — follows the standard protocol (exit retry block → `blockThreadUntilReady` → re-enter) for use within `withRetryBlock`

**Other changes**

- `ENABLE_R2C_RETRY` config default flipped from `false` to `true` — retry is now on by default with negligible overhead. The config is retained as an internal kill-switch to disable retry if needed.
- Removed `RetryableRowConverter` class — no longer needed without per-row `withRetryNoSplit`

**Performance**

[Benchmark script](https://github.com/NVIDIA/spark-rapids/issues/14368#issuecomment-4073575488)

| Configuration | Median | vs no-retry |
|---------------|--------|-------------|
| No retry | 829 ms | baseline |
| Per-row retry (old) | 15,526 ms | **~19x slower** |
| Per-batch retry (this PR) | 876 ms | **~5% slower** |

### Checklists

- [x] This PR has added documentation for new or modified features or behaviors.
- [x] This PR has added new tests or modified existing tests to cover new code paths.
  - `test simple GPU/CPU OOM retry` — OOM during conversion with RequireSingleBatch
  - `test CPU OOM retry preserves all rows for non-RequireSingleBatch` — emit-early path
  - `test first-row CPU OOM with TargetSize/RequireSingleBatch falls back to retry` — blockUntilMemoryFreed path
  - `test CPU SplitAndRetryOOM emit-early for non-RequireSingleBatch` — SplitAndRetryOOM emit-early path
  - `test simple OOM split and retry` — SplitAndRetryOOM propagation
- [x] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by thirtiseven** [comment]
@greptile

Thanks for the detailed review, but most of the concerns raised here are based on misreadings of the code or the exception class hierarchy. Let me address them one by one.

**Exception hierarchy (important context for several comments):**

`CpuSplitAndRetryOOM extends OffHeapOOM` and `CpuRetryOOM extends OffHeapOOM` — they are **siblings**, not parent-child. Same for the GPU variants (`GpuSplitAndRetryOOM extends GpuOOM`, `GpuRetryOOM extends GpuOOM`). This means `case _: CpuRetryOOM` does **not** match `CpuSplitAndRetryOOM`.

---

**Comment #1 (P1): Nested `currentThreadStartRetryBlock` calls**

The code already handles this. Lines 693–695 explicitly call `currentThreadEndRetryBlock()` before entering `withRetryNoSplit`, and the `finally` block at line 711 re-enters the outer retry block. There is no nesting.

**Comment #2 (P1): `CpuSplitAndRetryOOM` / `GpuSplitAndRetryOOM` silently swallowed by first catch arm**

Incorrect — see the class hierarchy above. The first catch arm (`case _: CpuRetryOOM | _: GpuRetryOOM`) does not match `SplitAndRetryOOM` types. They always fall through to the second arm, which is exactly the intended behavior.

**Comment #3 (P2): `rowIter.next()` outside the per-row `try/catch`**

Incorrect. `rowIter.next()` is at line 659, inside the `try` block that starts at line 651. The line numbers referenced in this comment appear to be wrong.

**Comment #4 (P1): `pendingRow` cleared before OOM can be caught from `rowIter.next()`**

Incorrect. `pendingRow = null` (line 656) and `rowIter.next()` (line 659) are in **mutually exclusive** `if/else` branches — the code never executes both. Lines 652–653 document this explicitly: *"These two branches are mutually exclusive: we either consume pendingRow or call rowIter.next(), never both."* If `pendingRow` was non-null, we consume it and never call `rowIter.next()`. If `pendingRow` was already null, there is nothing to lose.

**Comment #5 (P2): Allocation window outside retry block**

The concern specifically mentions `new RetryableRowConverter(...)` and `converter.attempt(pendingRow)` being in the window. This is wrong — both execute at lines 691–692, **before** `currentThreadEndRetryBlock()` at line 695, so they are inside the retry block. The actual unprotected window is only the JVM overhead of entering the `try` block and the `withRetryNoSplit` call setup, which involves no native allocations.

**Comment #6 (P2): `pendingRow` remains set after `withRetryNoSplit` throws**

Already documented in the code at lines 698–701: *"If withRetryNoSplit throws … pendingRow stays non-null. This is fine because the exception will fail the entire task — Spark will not call next() again on this iterator."*

**Comment #7 (P1): `SplitAndRetryOOM` should emit partial batch instead of falling through to `withRetryNoSplit`**

This is an intentional design decision, documented at lines 683–688. When a `SplitAndRetryOOM` occurs, memory is critically low. Ending the batch early and calling `tryBuild()` (which requires GPU memory allocation) would likely OOM as well. The correct response is to block and wait for spill to free memory via the `withRetryNoSplit` fallback. If the retry ultimately fails, the task fails anyway, so discarding the already-converted rows is acceptable.

---

**Summary-level items:**

- **P1 (row==null silent drop):** Theoretically possible only if an upstream iterator advances internal state before throwing from `next()`. In practice, Spark `InternalRow` iterators feeding into `RowToColumnar` don't do RMM-tracked allocations in `next()`, so `CpuRetryOOM` from `rowIter.next()` is extremely unlikely. The assumption is documented in the code comments at lines 673–675.
- **P2 (captureState overhead):** This is the deliberate trade-off — from ~19× overhead down to ~5%. The alternative (deferred snapshot on first OOM) would require significantly more complex state management.
- **P2 (no test for row==null path):** Fair point. Could add one, though triggering this path is difficult since it requires `rowIter.next()` itself to throw a retryable OOM.
- **P2 (stale blank line in RapidsConf.scala):** Will fix.
- **Confidence 2/5:** Overly conservative given that the P1 concerns are based on incorrect premises.

---
*— Claude (automated analysis)*

**Comment by thirtiseven** [comment]
@greptile

Thanks for the continued review. Addressing the two new comments:

**Comment #1 (P1): `row` silently discarded on `SplitAndRetryOOM` before re-throw**

This is not a data-loss scenario. `SplitAndRetryOOM` with `rowCount == 0` is a **task-fatal exception** — it propagates all the way to Spark's task runner, which aborts the task and reschedules it from scratch. All input data is re-read from the source. There is no "outer recovery mechanism" that calls `hasNext()`/`next()` after a `SplitAndRetryOOM`.

Additionally, intentionally NOT calling `copyRow(row)` before throwing is the right choice here: we are in a `SplitAndRetryOOM` state (memory critically low), and allocating memory for a row copy could trigger another OOM, making things worse — all for a row that will never be used since the task is about to fail.

**Comment #2 (P2): Non-local `return` inside by-name Scala closure**

This concern relies on the premise that `currentThreadEndRetryBlock()` could throw inside `withRetryBlock`'s `finally`. This JNI call simply sets `this->is_in_retry = false` in native code — it cannot throw. The standard retry framework (`NoInputSpliterator.next()`) also does not guard against `startRetryBlock()`/`endRetryBlock()` throwing. If the JNI/native layer is in a state where these calls fail, no amount of Scala-level guards will help.

The suggestion to revert to a `batchDone` flag is exactly the pattern we intentionally refactored away from in this PR for readability.

---
*— Claude (automated analysis)*

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala [hunk 1]
```diff
@@ -438,15 +438,6 @@ object RapidsConf extends Logging {
       .integerConf
       .createWithDefault(2)
 
-  val ENABLE_R2C_RETRY = conf("spark.rapids.sql.rowToColumnar.retry.enabled")
```
Comment (zpuller) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala:441]: Do we not want the new behavior to also be configurable?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala [hunk 2]
```diff
@@ -592,7 +590,11 @@ class RowToColumnarIterator(
   private var totalOutputRows: Long = 0
   private lazy val rowCopyProjection: UnsafeProjection = UnsafeProjection.create(localSchema)
 
+  // Carries a failed row across batch boundaries when OOM interrupted conversion.
+  private var pendingRow: InternalRow = _
+
   override def hasNext: Boolean = {
+    if (pendingRow != null) return true
```
Comment (zpuller) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala]: can we avoid using `return`, just do regular `if-else` block?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala [hunk 3]
```diff
@@ -606,56 +608,95 @@ class RowToColumnarIterator(
...
+        } catch {
+          case oom @ (_: CpuRetryOOM | _: CpuSplitAndRetryOOM |
+                      _: GpuRetryOOM | _: GpuSplitAndRetryOOM) =>
+            builders.restoreState(snapshots)
+            if (rowCount > 0 && !localGoal.isInstanceOf[RequireSingleBatchLike]) {
+              // Emit partial batch. This also handles SplitAndRetryOOM: emitting
+              // a smaller batch IS the right response to memory pressure, and
+              // tryBuild() has its own withRetryNoSplit to handle GPU OOM.
+              if (row != null) pendingRow = copyRow(row)
+              return (rowCount, byteCount)
```
Comment (zpuller) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala]: can we remove this `return`

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala (hunk 1 above)
Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala:441]: Usually we don't do that for retry, but it would be good to keep the config in case there is still a performance regression. I added it back.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala (hunk 3 above)
Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala]: done.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala (hunk 2 above)
Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala]: thanks, done.

**Comment by thirtiseven** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala [hunk 4]
```diff
@@ -188,6 +188,40 @@ object RmmRapidsRetryIterator extends Logging {
...
+   * Use this for incremental operations (e.g. row-by-row accumulation) where
+   * partial progress is valuable and the standard atomic-retry model doesn't fit.
+   *
+   * @param fn the work to perform inside the retry block
+   * @tparam T result type
+   * @return the result of `fn`
+   */
+  def withRetryBlock[T](fn: => T): T = {
+    RmmSpark.currentThreadStartRetryBlock()
+    try fn finally RmmSpark.currentThreadEndRetryBlock()
```
Comment (amahussein) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala]: Do we miss styling checker here for block missing braces?
```scala
  try {
    ...
  } finally {
    ..
  }
```

Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala]: Thank you! 

for `try`: In `scalastyle-config.xml` we have BraceChecker for `if` but not `try`. So AI and I missed this case. Let me try to add one checker in another pr.

for single line if-else:
It's allowed in our scalastyle-config:
```
    <check level="error" class="org.scalastyle.scalariform.IfBraceChecker" enabled="true">
        <parameters>
            <parameter name="singleLineAllowed"><![CDATA[true]]></parameter>
            <parameter name="doubleLineAllowed"><![CDATA[true]]></parameter>
        </parameters>
    </check>
```
Should we reconsider this rule?

Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala]: Oh, there is no check rule like `TryBraceChecker` in scalastyle. https://www.scalastyle.org/rules-1.0.0.html

**Comment by nvauto** [comment]
**NOTE: release/26.04 has been created from main. Please retarget your PR to release/26.04 if it should be included in the release.**

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 4 above)
Comment (thirtiseven) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala]: Anyway I think it's a good point that we might missing some styling checkers. I filed #14481 for discussion and filed #14480 to add a few safe rules, please take a look.

Comment (amahussein) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala]: Thanks @thirtiseven for filing the issue!

**Comment by thirtiseven** [comment]
build

**Review by binmahone — APPROVED** [review]
LGTM
