### PR TITLE
Fix parquet binary reads to do the transformation in the plugin [databricks]

### LINKED ISSUE #6281: [BUG] Reading binary columns from nested types does not work.
**Describe the bug**
Recently support for reading binary columns was added to CUDF and Spark (https://github.com/NVIDIA/spark-rapids/pull/6161). But the tests did not cover nested types, and the code appears to crash when nested types are read.

**Steps/Code to reproduce bug**
```
 spark.range(100).selectExpr("CAST(id AS String) as s").selectExpr("CAST(S AS BINARY) as b").selectExpr("struct(b) as st").write.mode("overwrite").parquet("./target/TEST")
spark.read.parquet("./target/TEST").show()
```

Results in a crash
```
...
Caused by: java.lang.AssertionError: Type conversion is not allowed from Table{columns=[ColumnVector{rows=100, type=STRUCT, nullCount=Optional.empty, offHeap=(ID: 14 7fa1c0dbe310)}], cudfTable=140332701702640, rows=100} to [StructType(StructField(b,BinaryType,true))] columns 0 to 1
  at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:776)
  at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:657)
  at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$4(GpuMultiFileReader.scala:787)
  at scala.Option.map(Option.scala:230)
  at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$1(GpuMultiFileReader.scala:787)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
```

and with asserts disabled it might be even worse...

**Expected behavior**
No crash no data corruption. We either fall back to the CPU or we do the right thing.

**Environment details (please complete the following information)**

This looks like it is happening on 22.08 and 22.10

### PR DESCRIPTION
**Pull request by revans2**
From testing we found a number of issues with nested types and reading binary data. There were bugs in the cudf code, even with the API that made this unworkable in the short term. So this has all of the transformation to binary from string happen in the plugin instead of doing it in CUDF. Hopefully in 22.10 when the CUDF code + API is fixed we can switch over to using it and it will be cleaner and more efficient.

This replaces #6283.

This fixes #6281

### CODE REVIEW

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala [hunk 1]
```diff
@@ -510,7 +510,18 @@ object ParquetSchemaUtils extends Arm {
...
+
+  private def existsBinaryType(dt: DataType): Boolean = dt match {
+    case BinaryType => true
+    case ArrayType(elementType, _) => existsBinaryType(elementType)
+    case MapType(keyType, valueType, _) =>
+      existsBinaryType(keyType) || existsBinaryType(valueType)
+    case StructType(fields) =>
+      fields.exists(f => existsBinaryType(f.dataType))
+    case _ => false
   }
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala:525]: Can use TrampolineUtil.dataTypeExistsRecursively

File: integration_tests/src/main/python/data_gen.py [hunk 2]
```diff
@@ -651,6 +651,19 @@ def _gen_random(self, rand):
...
+    """Generate BinaryType values"""
+    def __init__(self, min_length=0, max_length=20, nullable=True):
+        super().__init__(BinaryType(), nullable=nullable)
+        self._min_length = min_length
+        self._max_length = max_length
+
+    def start(self, rand):
+        def gen_bytes():
+            length = rand.randint(self._min_length, self._max_length)
+            return bytearray([ rand.randint(0, 255) for _ in range(length) ])
```
Comment (jlowe) [inline integration_tests/src/main/python/data_gen.py:664]: This should use `bytes` instead of `bytearray` since the former is the immutable version.
```suggestion
            return bytes([ rand.randint(0, 255) for _ in range(length) ])
```

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@jlowe please take another look
