### PR TITLE
Refine column size estimation based on previous batch for Host2Gpu

### LINKED ISSUE #13449: [BUG] Device memory allocation failure when running the delete command for Delta tables with deletion vector enabled
**Describe the bug**
The spark application fails with an exception as below while running the delete command for Delta tables. 

```
Caused by: java.lang.IllegalArgumentException: requirement failed: onAllocFailure invoked with invalid allocSize -2147483392
  at scala.Predef$.require(Predef.scala:281)
  at com.nvidia.spark.rapids.DeviceMemoryEventHandler.onAllocFailure(DeviceMemoryEventHandler.scala:110)
  at ai.rapids.cudf.Rmm.allocInternal(Native Method)
  at ai.rapids.cudf.Rmm.alloc(Rmm.java:524)
  at ai.rapids.cudf.DeviceMemoryBuffer.allocate(DeviceMemoryBuffer.java:147)
  at ai.rapids.cudf.DeviceMemoryBuffer.allocate(DeviceMemoryBuffer.java:137)
  at ai.rapids.cudf.HostColumnVector.copyToDevice(HostColumnVector.java:247)
  at com.nvidia.spark.rapids.GpuColumnVector$GpuColumnarBatchBuilder.lambda$tryBuild$0(GpuColumnVector.java:320)
  at com.nvidia.spark.rapids.GpuColumnVector$GpuColumnarBatchBuilderBase.build(GpuColumnVector.java:152)
  at com.nvidia.spark.rapids.GpuColumnVector$GpuColumnarBatchBuilder.tryBuild(GpuColumnVector.java:320)
  at com.nvidia.spark.rapids.HostToGpuCoalesceIterator.$anonfun$concatAllAndPutOnGPU$1(HostColumnarToGpu.scala:274)
  at com.nvidia.spark.rapids.RmmRapidsRetryIterator$NoInputSpliterator.next(RmmRapidsRetryIterator.scala:415)
  at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:690)
  at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:577)
  at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.drainSingleWithVerification(RmmRapidsRetryIterator.scala:294)
  at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRetryNoSplit(RmmRapidsRetryIterator.scala:188)
  at com.nvidia.spark.rapids.HostToGpuCoalesceIterator.concatAllAndPutOnGPU(HostColumnarToGpu.scala:274)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$next$2(GpuCoalesceBatches.scala:639)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$next$1(GpuCoalesceBatches.scala:623)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.next(GpuCoalesceBatches.scala:598)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.next(GpuCoalesceBatches.scala:248)
  at com.nvidia.spark.rapids.AbstractProjectSplitIterator.next(basicPhysicalOperators.scala:270)
  at com.nvidia.spark.rapids.AbstractProjectSplitIterator.next(basicPhysicalOperators.scala:251)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$hasNext$1(GpuMetrics.scala:370)
  at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$hasNext$1$adapted(GpuMetrics.scala:369)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
  at com.nvidia.spark.rapids.CollectTimeIterator.hasNext(GpuMetrics.scala:369)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.getHasOnDeck(GpuCoalesceBatches.scala:311)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:328)
  at com.nvidia.spark.rapids.AbstractProjectSplitIterator.hasNext(basicPhysicalOperators.scala:256)
...
```

The data and the query used are:

```
create table lineitem_test_delete using delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true') as select * from lineitem limit 16519105
```

```
delete from lineitem_test_delete where l_discount = 0.01
```

Note that the exception seems related to the total row count in the table rather than the number of rows to delete. I ran the same queries with different sizes of `lineitem_test_delete` and with filters of different selectivities. One find is that the delete command _segfaults_ when `lineitem_test_delete` has more than 16519105 rows. I assume that at 16519105 rows, an integer overflow occurs in the problematic logic which is caught by some sanity check that throws an exception, but when there are more rows, the sanity check would not be catching the invalid memory size to allocate.

**Steps/Code to reproduce bug**

This bug is reproducible in local clusters. You can first generate the TPC-H lineitem table at sf=100, and then run the queries above.

**Expected behavior**
The delete command should run successfully.

### PR DESCRIPTION
**Pull request by jihoonson**
Fixes #13449.

### Description

When we move data from host to GPU, we can concat multiple input batches to reduce the number of data moves. For concatting batches, we use a row-based limit which is based on schema size estimation. The row limit is computed based on the user-configurable bytes limit and the schema size estimate. As for the schema size estimation, for the first output batch, we use a sort of naive approach as we don't have much information about actual data size. This is implemented in [here](https://github.com/NVIDIA/spark-rapids/blob/branch-25.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchUtils.scala#L97-L129). This naive approach can be problematic especially for variable-sized types like the string or the blob as it uses the default size of those types which is some fixed number. As such, the inaccurate size estimation may let too many rows be in the first output batch, which causes some overflow error while allocating GPU memory. Note that we don't have the same issue for subsequent batches other than the first one as we refine the limit based on the actual output batch size.

The fix proposed in this PR is to refine the limit as we go based on the input batch size. As a new batch is added to concat, we measure the actual byte size to concat. The measuring is done as part of the existing logic that iterates all rows in all columns. That being said, we still have the same inaccurate size estimation issue for the very first input batch. If the first input batch is very large, we will still see the overflow error.

```sql
create table lineitem_test_delete using delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true') as select * from lineitem;

delete from lineitem_test_delete where l_discount = 0.01;
```

Since the overflow error occurs only with a reasonably large data, I tested this change manually using the queries used in #13449 (also shown above). I used the TPC-H lineitem table at sf=100. The delete ran successfully.

```sql
create table lineitem_test_delete using delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true') as select * from lineitem limit 16519100;

delete from lineitem_test_delete where l_discount = 0.01;
```

I also ran some performance tests to measure the overhead of this change. I used the above query and the same table. I did not observe any performance change between the 25.10 branch (837ba27df6b92120a64d9dad6c33679bc422019f) and this PR.

Configs used:

```
export SPARK_CONF=("--master" "local[16]"
                   "--conf" "spark.driver.maxResultSize=2GB"
                   "--conf" "spark.driver.memory=50G"
                   "--conf" "spark.executor.memory=16G"
                   "--conf" "spark.sql.files.maxPartitionBytes=2gb"
                   "--conf" "spark.sql.adaptive.enabled=true"
                   "--conf" "spark.plugins=com.nvidia.spark.SQLPlugin"
                   "--conf" "spark.rapids.memory.host.spillStorageSize=16G"
                   "--conf" "spark.rapids.memory.pinnedPool.size=8g"
                   "--conf" "spark.rapids.sql.concurrentGpuTasks=3"
                   "--packages" "io.delta:delta-spark_2.12:3.3.1"
                   "--conf" "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension"
                   "--conf" "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
                   "--conf" "spark.driver.extraClassPath=$SPARK_RAPIDS_PLUGIN_JAR:$NDS_LISTENER_JAR"
                   "--conf" "spark.executor.extraClassPath=$SPARK_RAPIDS_PLUGIN_JAR:$NDS_LISTENER_JAR")
```

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [ ] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [x] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by jihoonson** [comment]
build

**Comment by jihoonson** [comment]
build

**Review by gerashegalov — COMMENTED** [review]
On the one hand the way bytesCopied is just a byproduct of copying is elegant. 

On the other hand it adds 0(numRows * numCols) instructions to execution paths wheres the actual values can easily be computed as a closed form multiplication for most loops I checked.

**Comment by jihoonson** [comment]
> On the other hand it adds 0(numRows) instructions to execution paths wheres the actual values can easily be computed as a closed form multiplication for most loops I checked.

Sure, but I'd prefer the current code as it is more consistent. There shouldn't be much performance difference anyway.

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java [hunk 1]
```diff
@@ -383,26 +383,30 @@ private void setNullAt(long index) {
...
     nullHandler.run();
-    return this;
+    return valid.getLength() - prevValidSize;
   }
 
   //For structs
-  private RapidsHostColumnBuilder append(HostColumnVector.StructData structData) {
+  private long append(HostColumnVector.StructData structData) {
     assert type.isNestedType();
     if (type.equals(DType.STRUCT)) {
```
Comment (razajafri) [inline sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java:395]: Why don't we assert on type.equals(DType.STRUCT) just like we assert on the `isNestedType` my concern is this could lead to silent problems and leave us scratching our heads

**Comment by razajafri** [comment]
> On the one hand the way bytesCopied is just a byproduct of copying is elegant.
> 
> On the other hand it adds 0(numRows * numCols) instructions to execution paths wheres the actual values can easily be computed as a closed form multiplication for most loops I checked.

Good point, but we will be doing the O(numRows x numCols) anyway as we are inserting the values one-by-one.

**Comment by gerashegalov** [comment]
> Sure, but I'd prefer the current code as it is more consistent. There shouldn't be much performance difference anyway.

Maybe the JIT compiler figures it out

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala [hunk 2]
```diff
@@ -105,7 +105,16 @@ object HostColumnarToGpu extends Logging {
         // swallow the exception and assume no offsets buffer
     }
     ab.addBatch(rows, nullCount, dataBuf, validity, offsets)
-    referenceManagers.result().asJava
+    def getSize(buf: ByteBuffer): Long = {
+      if (buf != null) {
+        buf.limit() - buf.position()
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala]:
```suggestion
        buf.remaining()
```

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java (hunk 1 above)
Comment (jihoonson) [reply sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java:395]: Well, I do not know as I didn't write this code.. That being said, please file an issue for it. It's unrelated to this PR, but what you suggest sounds reasonable.

**Comment by jihoonson** [comment]
build

**Comment by gerashegalov** [comment]
> > On the one hand the way bytesCopied is just a byproduct of copying is elegant.
> > On the other hand it adds 0(numRows * numCols) instructions to execution paths wheres the actual values can easily be computed as a closed form multiplication for most loops I checked.
> 
> Good point, but we will be doing the O(numRows x numCols) anyway as we are inserting the values one-by-one.

But should we add to it if we don't have to ?

**Comment by jihoonson** [comment]
AFAIU, the multiplication approach can be used in limited cases only. It won't be available for variable-sized types because you will have to examine the size of every value. That being said, it might be an optimization. Let's do it if the current implementation turns out to have some performance issue.

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java (hunk 1 above)
Comment (razajafri) [reply sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java:395]: Here is the issue https://github.com/NVIDIA/spark-rapids/issues/13509

**Comment by razajafri** [comment]
> AFAIU, the multiplication approach can be used in limited cases only. It won't be available for variable-sized types because you will have to examine the size of every value. That being said, it might be an optimization. Let's do it if the current implementation turns out to have some performance issue.

I doubt there will be a huge difference in performance, but how will we keep track of this since you mentioned coming back if there is a performance degradation?

**Comment by jihoonson** [comment]
> I doubt there will be a huge difference in performance, but how will we keep track of this since you mentioned coming back if there is a performance degradation?

I don't think there will be, as I don't see any performance difference in my test with the current implementation. Even if there is, it would be negligible. So I don't think we need to actively track this issue. If we notice it or someone reports something related to this, we can investigate it.
