### PR TITLE
Fix join bug on csv datasources

### LINKED ISSUE #13873: [BUG]  `join` an empty table brings errors on the GPU engines
**Describe the bug**
An error (data with no columns should have been filtered out already) occurred when `join` an empty table reading from the csv file on the GPU engines.

**Steps/Code to reproduce bug**
```python
import os
os.environ['JAVA_HOME'] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ['SPARK_HOME'] = "./spark-4.0.1-bin-hadoop3"
os.environ['PYSPARK_SUBMIT_ARGS'] = "--jars ./rapids-4-spark_2.13-25.10.0.jar,./cudf-25.10.0-cuda12.jar --master local[*] pyspark-shell"

import findspark
findspark.init()
from pyspark.sql import SparkSession
from pyspark.conf import SparkConf
from pyspark.sql import functions as F

spark = SparkSession.builder.appName('SparkRAPIDS').config('spark.plugins','com.nvidia.spark.SQLPlugin').config("spark.executor.memory", "8g").config("spark.driver.memory", "8g").getOrCreate()
spark.sparkContext.addPyFile('./rapids-4-spark_2.13-25.10.0.jar')
spark.sparkContext.addPyFile('./cudf-25.10.0-cuda12.jar')
spark.conf.set('spark.rapids.sql.incompatibleOps.enabled', 'true')
spark.conf.set('spark.rapids.sql.format.csv.read.enabled', 'true')
spark.conf.set('spark.rapids.sql.format.csv.enabled', 'true')
spark.conf.set("spark.executor.resource.gpu.amount", "1")
spark.conf.set("spark.task.resource.gpu.amount", "1")
spark.conf.set("spark.rapids.sql.concurrentGpuTasks", "1")
spark.conf.set("spark.rapids.sql.exec.CollectLimitExec", "true")
spark.conf.set('spark.rapids.sql.enabled', 'false')

df = spark.read.csv("t1.csv", header=True, inferSchema=True)
df.createOrReplaceTempView("t1")
df = spark.read.csv("t2.csv", header=True, inferSchema=True)
df.createOrReplaceTempView("t2")

print("CPU:")
cpu_result = spark.table("t1").join(spark.table("t2"), F.lit(True), "right_outer").select(F.col("t2.c0"))
cpu_result.show(truncate=False)

spark.conf.set('spark.rapids.sql.enabled', 'true')
print("GPU:")
gpu_result = spark.table("t1").join(spark.table("t2"), F.lit(True), "right_outer").select(F.col("t2.c0"))
gpu_result.show(truncate=False)
```
t1.csv:
```bash
c0
0

```
t2.csv:
```bash
c0

```
```bash
CPU:
+---+
|c0 |
+---+
+---+

GPU:
25/11/24 04:05:43 ERROR Executor: Exception in task 0.0 in stage 7.0 (TID 7)
java.lang.AssertionError: assertion failed: data with no columns should have been filtered out already
        at scala.Predef$.assert(Predef.scala:279)
        at com.nvidia.spark.rapids.JoinGathererImpl.<init>(JoinGatherer.scala:541)
        at com.nvidia.spark.rapids.JoinGatherer$.apply(JoinGatherer.scala:148)
        at org.apache.spark.sql.rapids.execution.CrossJoinIterator.$anonfun$setupNextGatherer$1(GpuBroadcastNestedLoopJoinExecBase.scala:178)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:359)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:347)
        at org.apache.spark.sql.rapids.execution.CrossJoinIterator.setupNextGatherer(GpuBroadcastNestedLoopJoinExecBase.scala:160)
        at com.nvidia.spark.rapids.AbstractGpuJoinIterator.hasNext(AbstractGpuJoinIterator.scala:102)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at com.nvidia.spark.rapids.AbstractProjectSplitIterator.hasNext(basicPhysicalOperators.scala:256)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at com.nvidia.spark.rapids.GpuBaseLimitIterator.hasNext(limit.scala:50)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:411)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:434)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
        at org.apache.spark.scheduler.Task.run(Task.scala:147)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
25/11/24 04:05:43 WARN TaskSetManager: Lost task 0.0 in stage 7.0 (TID 7) (70e244428b2c executor driver): java.lang.AssertionError: assertion failed: data with no columns should have been filtered out already
        at scala.Predef$.assert(Predef.scala:279)
        at com.nvidia.spark.rapids.JoinGathererImpl.<init>(JoinGatherer.scala:541)
        at com.nvidia.spark.rapids.JoinGatherer$.apply(JoinGatherer.scala:148)
        at org.apache.spark.sql.rapids.execution.CrossJoinIterator.$anonfun$setupNextGatherer$1(GpuBroadcastNestedLoopJoinExecBase.scala:178)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:359)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:347)
        at org.apache.spark.sql.rapids.execution.CrossJoinIterator.setupNextGatherer(GpuBroadcastNestedLoopJoinExecBase.scala:160)
        at com.nvidia.spark.rapids.AbstractGpuJoinIterator.hasNext(AbstractGpuJoinIterator.scala:102)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at com.nvidia.spark.rapids.AbstractProjectSplitIterator.hasNext(basicPhysicalOperators.scala:256)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at com.nvidia.spark.rapids.GpuBaseLimitIterator.hasNext(limit.scala:50)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:411)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:434)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
        at org.apache.spark.scheduler.Task.run(Task.scala:147)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

25/11/24 04:05:43 ERROR TaskSetManager: Task 0 in stage 7.0 failed 1 times; aborting job
Traceback (most recent call last):
  File "/xxx/bug.py", line 41, in <module>
    gpu_result.show(truncate=False)
  File "/xxx/../library/spark-4.0.1-bin-hadoop3/python/pyspark/sql/classic/dataframe.py", line 285, in show
    print(self._show_string(n, truncate, vertical))
  File "/xxx/../library/spark-4.0.1-bin-hadoop3/python/pyspark/sql/classic/dataframe.py", line 316, in _show_string
    return self._jdf.showString(n, int_truncate, vertical)
  File "../library/spark-4.0.1-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1362, in __call__
  File "/xxx/../library/spark-4.0.1-bin-hadoop3/python/pyspark/errors/exceptions/captured.py", line 282, in deco
    return f(*a, **kw)
  File "../library/spark-4.0.1-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/protocol.py", line 327, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o69.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 7.0 failed 1 times, most recent failure: Lost task 0.0 in stage 7.0 (TID 7) (70e244428b2c executor driver): java.lang.AssertionError: assertion failed: data with no columns should have been filtered out already
        at scala.Predef$.assert(Predef.scala:279)
        at com.nvidia.spark.rapids.JoinGathererImpl.<init>(JoinGatherer.scala:541)
        at com.nvidia.spark.rapids.JoinGatherer$.apply(JoinGatherer.scala:148)
        at org.apache.spark.sql.rapids.execution.CrossJoinIterator.$anonfun$setupNextGatherer$1(GpuBroadcastNestedLoopJoinExecBase.scala:178)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:359)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:347)
        at org.apache.spark.sql.rapids.execution.CrossJoinIterator.setupNextGatherer(GpuBroadcastNestedLoopJoinExecBase.scala:160)
        at com.nvidia.spark.rapids.AbstractGpuJoinIterator.hasNext(AbstractGpuJoinIterator.scala:102)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at com.nvidia.spark.rapids.AbstractProjectSplitIterator.hasNext(basicPhysicalOperators.scala:256)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at com.nvidia.spark.rapids.GpuBaseLimitIterator.hasNext(limit.scala:50)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:411)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:434)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
        at org.apache.spark.scheduler.Task.run(Task.scala:147)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$3(DAGScheduler.scala:2935)
        at scala.Option.getOrElse(Option.scala:201)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2935)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2927)
        at scala.collection.immutable.List.foreach(List.scala:334)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2927)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1295)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1295)
        at scala.Option.foreach(Option.scala:437)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1295)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3207)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3141)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3130)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:50)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1009)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2484)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2505)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2524)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2549)
        at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1057)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:417)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:1056)
        at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:462)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$executeCollect$1(AdaptiveSparkPlanExec.scala:402)
        at org.apache.spark.sql.execution.adaptive.ResultQueryStageExec.$anonfun$doMaterialize$1(QueryStageExec.scala:325)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$4(SQLExecution.scala:322)
        at org.apache.spark.sql.execution.SQLExecution$.withSessionTagsApplied(SQLExecution.scala:272)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$3(SQLExecution.scala:320)
        at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:94)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$2(SQLExecution.scala:316)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.AssertionError: assertion failed: data with no columns should have been filtered out already
        at scala.Predef$.assert(Predef.scala:279)
        at com.nvidia.spark.rapids.JoinGathererImpl.<init>(JoinGatherer.scala:541)
        at com.nvidia.spark.rapids.JoinGatherer$.apply(JoinGatherer.scala:148)
        at org.apache.spark.sql.rapids.execution.CrossJoinIterator.$anonfun$setupNextGatherer$1(GpuBroadcastNestedLoopJoinExecBase.scala:178)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:359)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:347)
        at org.apache.spark.sql.rapids.execution.CrossJoinIterator.setupNextGatherer(GpuBroadcastNestedLoopJoinExecBase.scala:160)
        at com.nvidia.spark.rapids.AbstractGpuJoinIterator.hasNext(AbstractGpuJoinIterator.scala:102)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at com.nvidia.spark.rapids.AbstractProjectSplitIterator.hasNext(basicPhysicalOperators.scala:256)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at com.nvidia.spark.rapids.GpuBaseLimitIterator.hasNext(limit.scala:50)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:411)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:434)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.$anonfun$hasNext$1(GpuExec.scala:68)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at com.nvidia.spark.rapids.GpuMetric.ns(GpuMetrics.scala:354)
        at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD$$anon$1.hasNext(GpuExec.scala:68)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
        at org.apache.spark.scheduler.Task.run(Task.scala:147)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
        ... 3 more
```

**Expected behavior**
No error occurs when using the GPU engines.
The result is consistent when using the CPU and GPU engines.

**Environment details (please complete the following information)**
 - Environment location: Standalone
 - Spark configuration settings related to the issue:
       java-17-openjdk-amd64
      spark-4.0.1-bin-hadoop3
      rapids-4-spark_2.13-25.10.0
      cudf-25.10.0-cuda12

**Additional context**

### PR DESCRIPTION
**Pull request by res-life**
fixes #13873

### bug analysis

This is a corner case described in the issue #13873.
If reading other type datasources instead of CSV files, the error does not occur.
If using `.collect()` instead of `.show()`, the error does not occur.
If the stream data is not empty, the error does not occur.

CSV file with only header and no data rows, empty table(num_rows = 0) will be returned, then after project, the column number of empty table becomes 0, finally empty table(num_rows=0, num_cols=0)  occurs in the iterator.

### bug fix
If num_rows of table is 0 when reading csv file, return None instead of empty table, the None indicates the iterator of CSV data is empty.

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by firestarman** [comment]
Personally it is not a good idea to fix the join error by changing the CSV reader. This error may happen again if the source is other type, e.g. parquet, orc...

I made a fix (https://github.com/NVIDIA/spark-rapids/pull/13817) before for similar issues, you can figure out the join type for this case and add it to the whitelist to allow it go into the degenerate path.

**Comment by res-life** [comment]
> This error may happen again if the source is other type, e.g. parquet, orc...

Already tested, other types do not have this error.

> you can figure out the join type for this case and add it to the whitelist to allow it go into the degenerate path.

IMO, this bug is not related to join types. When reading CSV file with no data(only one row header), the `iterator<ColumnBatch>` on this CSV file should have false value for `hasNext`. This PR is to fix the root cause in `iterator<ColumnBatch>`.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala [hunk 1]
```diff
@@ -643,7 +643,14 @@ abstract class GpuTextBasedPartitionReader[BUFF <: LineBufferer, FACT <: LineBuf
     //  val cols = (0 until  table.getNumberOfColumns).map(i => table.getColumn(i))
     //  Some(new Table(cols: _*))
     // }
-    Some(table)
+    if (table.getRowCount == 0) {
+      // CSV reader can return empty table, close it and return None
+      // E.g.: CSV file with only header and no data rows, empty table will be returned
+      table.close()
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala:649]: any concerns that this code can  throw instead of returning `None` even if close fails?

**Comment by firestarman** [comment]
> > This error may happen again if the source is other type, e.g. parquet, orc...
> 
> Already tested, other types do not have this error.
> 
> > you can figure out the join type for this case and add it to the whitelist to allow it go into the degenerate path.
> 
> IMO, this bug is not related to join types. When reading CSV file with no data(only one row header), the `iterator<ColumnBatch>` on this CSV file should have false value for `hasNext`. This PR is to fix the root cause in `iterator<ColumnBatch>`.

Yeah, this is a fix. 
I mean there are already some similar paths at https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala#L759 for this kind of case with outer joins.
And this issue still exists in the GpuBroadcastNestedLoopJoinExecBase even this PR is merged and we don't have a case to run into it yet.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala (hunk 1 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala:649]: The row count is zero, it means there is no GPU memory allocated although table has columns.
It is not likely to throw exceptions in practice.

**Comment by res-life** [comment]
@firestarman  I can not construct a right out condition join case as you tried, refer to [link](https://github.com/NVIDIA/spark-rapids/pull/13817#issuecomment-3555383195).
I can not add similar code as you did in https://github.com/NVIDIA/spark-rapids/pull/13817 because I do not know how to test.
Since this PR is a fix we can merge this first.

**Comment by res-life** [comment]
For conditional right outer join, e.g.: `left_table right join right_table on c0_column`, then the build table is left table and the build batch is not zero column.
For unconditional right outer join, e.g.: `left_table right join right_table`, this PR fixes the issue.

File: integration_tests/src/main/python/csv_test.py [hunk 2]
```diff
@@ -720,3 +721,22 @@ def test_csv_read_gbk_encoded_data(std_input_path):
             .schema("name string, age int, city string, job string")
             .csv(std_input_path + "/test_gbk.csv"),
         conf={"spark.sql.legacy.javaCharsets": legacy_charset})
+
+
+@allow_non_gpu('CollectLimitExec')
+def test_csv_stream_table_is_empty_when_join(std_input_path):
```
Comment (revans2) [inline integration_tests/src/main/python/csv_test.py]: I think we want to coordinate with https://github.com/NVIDIA/spark-rapids/pull/13938 as they both are near duplicates and fix the problem is slightly different ways. I don't might having both fixes, but I don't want duplicate files checked in.

File: integration_tests/src/main/python/csv_test.py [hunk 3]
```diff
@@ -720,3 +721,22 @@ def test_csv_read_gbk_encoded_data(std_input_path):
...
+
+    def _create_view(spark):
+        spark.read.csv(built_csv_path, header=True, inferSchema=True).createOrReplaceTempView("built_table")
+        spark.read.csv(stream_csv_path, header=True, inferSchema=True).createOrReplaceTempView("stream_table")
+
+    # create view first on CPU
+    with_cpu_session(lambda spark: _create_view(spark))
+
+    # then do the join on GPU
+    with_gpu_session(lambda spark:
```
Comment (revans2) [inline integration_tests/src/main/python/csv_test.py]: I would prefer a test that verifies we got the right result. Not just one that shows we didn't crash.

Comment (res-life) [reply integration_tests/src/main/python/csv_test.py]: If using .collect() instead of .show(), the error does not occur.

Comment (firestarman) [reply integration_tests/src/main/python/csv_test.py]: You can do a post project for the `collect` to simulate the "show" action. Just like the additional `cast(c as string)` at https://github.com/NVIDIA/spark-rapids/blob/main/integration_tests/src/main/python/join_test.py#L442

**Comment by res-life** [comment]
build

File: integration_tests/src/main/python/csv_test.py (hunk 3 above)
Comment (res-life) [reply integration_tests/src/main/python/csv_test.py]: done

File: integration_tests/src/main/python/join_test.py [hunk 4]
```diff
@@ -485,6 +485,28 @@ def do_join(spark):
...
+    stream_csv_path = std_input_path + '/t0.csv'
+
+    def create_views(spark):
+        spark.read.csv(built_csv_path, header=True, inferSchema=True).createOrReplaceTempView("built_table")
+        spark.read.csv(stream_csv_path, header=True, inferSchema=True).createOrReplaceTempView("stream_table")
+
+    # create views first on CPU
+    with_cpu_session(lambda spark: create_views(spark))
+
+    # limit to 10 rows to produce `LocalLimitExec` node
```
Comment (firestarman) [inline integration_tests/src/main/python/join_test.py:500]: NIT: Better add comment on why this limit node is needed.

File: integration_tests/src/main/python/join_test.py [hunk 5]
```diff
@@ -485,6 +485,28 @@ def do_join(spark):
         return t0.crossJoin(t1).limit(21)
     assert_gpu_and_cpu_are_equal_collect(do_join)
 
+@allow_non_gpu('CollectLimitExec')
+def test_empty_right_outer_side_with_limit(std_input_path):
+    built_csv_path = std_input_path + '/t1.csv'
```
Comment (firestarman) [inline integration_tests/src/main/python/join_test.py:490]: NIT: Better add comment on why this file will be read as the built batch ?
