### PR TITLE
Install-file log4j-core on Databricks 11.3 [databricks]

### LINKED ISSUE #7426: [BUG] bloop compile times out on Databricks 11.3
**Describe the bug**
VS Code / Metals/ Bloop IDE for is broken for Shim Development on Databricks 11.3.

The visible symptom is that compile sessions time out and restart after 30 seconds of failing to report the progress.

To see the root cause you need to install bloop CLI https://github.com/gerashegalov/rapids-shell/blob/master/src/bash/init-databricks-shimdev.sh#L11

```
bloop compile --verbose=true rapids-4-spark-sql_2.12
```

which fails in the background with

```
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.Filter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 52 more
```

which we have seen in #7098, but  the compile keeps blocking without exiting, which looks like a bug in Bloop

### PR DESCRIPTION
**Pull request by gerashegalov**
- Prevent bloop server sessions from crashing by installing log4j-core.
- Add WITH_BLOOP environment for easy generation of Bloop projects on Databricks

Fixes #7426

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

File: jenkins/databricks/build.sh [hunk 1]
```diff
@@ -285,6 +286,12 @@ set_dep_jars()
     artifacts[DELTA]="-DgroupId=io.delta -DartifactId=delta-core_${SCALA_VERSION}"
     dep_jars[DELTA]=${dep_jars[SQL]}
 
+    # log4j-core
+    if [[ "$BASE_SPARK_VERSION" == "3.3.0" ]]; then
```
Comment (nartal1) [inline jenkins/databricks/build.sh:290]: Just a question on this- Since it is comparing to a specific Spark base version. Do we have to deal with it again during next Databricks release?

Comment (gerashegalov) [reply jenkins/databricks/build.sh:290]: yes, this is correct

**Review by nartal1 — APPROVED** [review]
LGTM

**Review by jlowe — COMMENTED** [review]
This looks OK, other than I'm confused why we're only installing log4j-core specifically for 330db.  How is 321db or 312db working today for bloop without explicit log4j-core handling?

**Comment by gerashegalov** [comment]
> This looks OK, other than I'm confused why we're only installing log4j-core specifically for 330db. How is 321db or 312db working today for bloop without explicit log4j-core handling?

321db and 312db have no artifact in /databricks/jars containing `org/apache/logging/log4j/core/Filter`. And hence there is no code referencing it. In 330db, there is such an artifact and there is some class who references it in a method signature and bloop -> zinc stack stumbles on it:

```
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Filter
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetPublicMethods(Class.java:2902)
        at java.lang.Class.getMethods(Class.java:1615)
        at sbt.internal.inc.ClassToAPI$.toDefinitions0(ClassToAPI.scala:173)
        at sbt.internal.inc.ClassToAPI$.$anonfun$toDefinitions$1(ClassToAPI.scala:125)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
        at sbt.internal.inc.ClassToAPI$.toDefinitions(ClassToAPI.scala:125)
        at sbt.internal.inc.ClassToAPI$.$anonfun$process$1(ClassToAPI.scala:34)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at sbt.internal.inc.ClassToAPI$.process(ClassToAPI.scala:34)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.readAPI$1(AnalyzingJavaCompiler.scala:185)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$22(AnalyzingJavaCompiler.scala:215)
        at sbt.internal.inc.classfile.JavaAnalyze$.readInheritanceDependencies$1(JavaAnalyze.scala:186)
        at sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16(JavaAnalyze.scala:203)
        at sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16$adapted(JavaAnalyze.scala:108)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
        at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
        at sbt.internal.inc.classfile.JavaAnalyze$.apply(JavaAnalyze.scala:108)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21(AnalyzingJavaCompiler.scala:215)
```

**Review by jlowe — APPROVED** [review]
