### PR TITLE
Use long instead of int to track kudo buffer sizes and offsets in GpuShuffleCoalesce

### LINKED ISSUE #14380: [BUG] Intermittent failure on NDS trying to allocate host memory for shuffle
**Describe the bug**
```
java.lang.IllegalArgumentException
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at ai.rapids.cudf.UnsafeMemoryAccessor.allocate(UnsafeMemoryAccessor.java:68)
	at ai.rapids.cudf.HostMemoryBuffer.allocateRaw(HostMemoryBuffer.java:148)
	at com.nvidia.spark.rapids.HostAlloc.tryAllocNonPinned(HostAlloc.scala:128)
	at com.nvidia.spark.rapids.HostAlloc.$anonfun$tryAllocInternal$3(HostAlloc.scala:213)
	at scala.Option.orElse(Option.scala:447)
	at com.nvidia.spark.rapids.HostAlloc.tryAllocInternal(HostAlloc.scala:212)
	at com.nvidia.spark.rapids.HostAlloc.alloc(HostAlloc.scala:267)
	at com.nvidia.spark.rapids.HostAlloc.allocate(HostAlloc.scala:281)
	at ai.rapids.cudf.HostMemoryBuffer.allocate(HostMemoryBuffer.java:127)
	at ai.rapids.cudf.HostMemoryBuffer.allocate(HostMemoryBuffer.java:138)
	at com.nvidia.spark.rapids.KudoGpuTableOperator.$anonfun$concat$11(GpuShuffleCoalesceExec.scala:436)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:57)
	at com.nvidia.spark.rapids.KudoGpuTableOperator.concat(GpuShuffleCoalesceExec.scala:431)
	at com.nvidia.spark.rapids.KudoGpuTableOperator.concat(GpuShuffleCoalesceExec.scala:413)
	at com.nvidia.spark.rapids.CoalesceIteratorBase.$anonfun$concatenateTables$2(GpuShuffleCoalesceExec.scala:564)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.next(RmmRapidsRetryIterator.scala:537)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:700)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:585)
	at com.nvidia.spark.rapids.CoalesceIteratorBase.$anonfun$concatenateTables$1(GpuShuffleCoalesceExec.scala:568)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.CoalesceIteratorBase.concatenateTables(GpuShuffleCoalesceExec.scala:554)
	at com.nvidia.spark.rapids.GpuCoalesceIteratorBase.concatenateTablesInGpu(GpuShuffleCoalesceExec.scala:774)
	at com.nvidia.spark.rapids.GpuCoalesceIteratorBase.$anonfun$next$7(GpuShuffleCoalesceExec.scala:802)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.GpuCoalesceIteratorBase.next(GpuShuffleCoalesceExec.scala:801)
	at com.nvidia.spark.rapids.GpuCoalesceIteratorBase.next(GpuShuffleCoalesceExec.scala:757)
	at com.nvidia.spark.rapids.GpuShuffledHashJoinExec$.$anonfun$prepareBuildBatchesForJoin$2(GpuShuffledHashJoinExec.scala:344)
	at com.nvidia.spark.rapids.Arm$.closeOnExcept(Arm.scala:98)
	at com.nvidia.spark.rapids.GpuShuffledHashJoinExec$.prepareBuildBatchesForJoin(GpuShuffledHashJoinExec.scala:333)
	at com.nvidia.spark.rapids.GpuShuffledHashJoinExec.$anonfun$internalDoExecuteColumnar$2(GpuShuffledHashJoinExec.scala:258)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at com.nvidia.spark.rapids.GpuOpTimeTrackingRDD.compute(GpuExec.scala:61)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:621)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:624)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

This typically means we tried to allocate a negative amount of memory at

[https://github.com/NVIDIA/spark-rapids/blob/9685a7b4e7dd86cbe0bb1254d4296abd02c435[…]main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala](https://github.com/NVIDIA/spark-rapids/blob/9685a7b4e7dd86cbe0bb1254d4296abd02c435c3/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala#L436)

This is not 100% consistent either, so it might be a race condition as the jobs all passed, but some tasks failed.

**Steps/Code to reproduce bug**
Not totally sure, but it appears to be happening in NDS test runs

**Expected behavior**
No task failures.

### PR DESCRIPTION
**Pull request by zpuller**
Fixes #14380.

### Description

`getTotalDataLen()` and `getSerializedSize()` both return `Int`. The coalescer accumulation loop tracks batch size in `Long` (correct), but `KudoGpuTableOperator.concat` recomputes the total buffer size in 32-bit `Int` arithmetic — including both `getTotalDataLen` and `getSerializedSize` per table. Since `getSerializedSize` (~36 bytes of per-table header overhead) is not accounted for in the accumulation tracking, the sum in `concat` can exceed `Int.MaxValue` even at the default `batchSizeBytes`, wrapping to a large negative value and causing `HostMemoryBuffer.allocate` to throw `IllegalArgumentException`. `currentOffset` had the same issue.

Fix: widen `getTotalDataLen()` to `Long` before summing, declare `currentOffset` as `Long`, and use `8L *` for `offsetsBufSize` for consistency.

Validated with a manual repro (see issue for details) — deterministic failure on baseline, clean pass with the fix.

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [x] This PR has added new tests or modified existing tests to cover new code paths.
      (Validated manually; no automated test added as this requires a large dataset to trigger.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala [hunk 1]
```diff
@@ -430,12 +430,12 @@ class KudoGpuTableOperator(dataTypes: Array[DataType])
     } else {
       withResource(columns.safeMap(_.spillableKudoTable.makeKudoTable)) { kudoTables =>
         val dataBufSize = kudoTables.map { table =>
-          table.getHeader.getTotalDataLen + table.getHeader.getSerializedSize
+          table.getHeader.getTotalDataLen.toLong + table.getHeader.getSerializedSize
         }.sum
```
Comment (jihoonson) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala]: nit: if we really want to be safe, we can use `Math.addExact()` to prevent the overflow while computing the sum. But this is probably not a realistic concern.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala [hunk 2]
```diff
@@ -430,12 +430,12 @@ class KudoGpuTableOperator(dataTypes: Array[DataType])
...
         val offsetsBufSize = 8 * (kudoTables.length + 1)
```
[the remark this answers is not in the document]
Comment (jihoonson) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala]: This seems simple and worth to address.

**Comment by abellina** [comment]
So the repro consisted on changing configs outside of what the actual job was running. We never run batchSizeBytes=3GB. We never run spark.sql.shuffle.partitions=1. 

I don't disagree that we can widen these variables. But this does not sound like the root cause. In fact, I think we are going to hide further the corruption.

**Review by abellina — CHANGES_REQUESTED** [review]
I'd like to see more investigation here, per my comment.

**Review by revans2 — DISMISSED** [review]
Assuming it fixes the issue

**Review by abellina — DISMISSED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala (hunk 1 above)
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala]: This should save memory and CPU
```Scala
        val dataBufSize = kudoTables.foldLeft(0L) { (acc, table) =>
          acc + table.getHeader.getTotalDataLen + table.getHeader.getSerializedSize
        }
```

**Comment by zpuller** [comment]
After discussing offline, we agreed that this PR probably fixes the original occurence of the issue on NDS, but we're not 100% sure, but regardless it should be safe to merge and then we will retroactively confirm that it fixes the impacted CI job.

**Review by abellina — DISMISSED** [review]

**Comment by zpuller** [comment]
build

**Review by abellina — APPROVED** [review]

**Review by jihoonson — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]
LGTM
