### PR TITLE
Fix 340 shim of GpuCreateDataSourceTableAsSelectCommand and shim GpuDataSource for 3.4.0 [databricks]

### LINKED ISSUE #8019: [BUG] Spark-3.4 - Integration test failures due to GpuCreateDataSourceTableAsSelectCommand
**Describe the bug**
Some of the integration tests are failing due to Exception thrown from GpuCreateDataSourceTableAsSelectCommand. 

Failing tests:
- [ ] test_ts_write_fails_datetime_exception
- [ ] test_ts_write_twice_fails_exception
- [ ] test_write_save_table
- [ ] test_write_sql_save_table
- [ ] test_non_empty_ctas (originally part of https://github.com/NVIDIA/spark-rapids/issues/8016)

Exception stack trace:
```
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o326.saveAsTable.
E                   : java.lang.UnsupportedOperationException: org.apache.spark.sql.rapids.shims.GpuCreateDataSourceTableAsSelectCommand does not support row-based execution
E                   	at com.nvidia.spark.rapids.GpuRunnableCommand.run(GpuRunnableCommandExec.scala:49)
E                   	at com.nvidia.spark.rapids.GpuRunnableCommand.run$(GpuRunnableCommandExec.scala:47)
E                   	at org.apache.spark.sql.rapids.shims.GpuCreateDataSourceTableAsSelectCommand.run(GpuCreateDataSourceTableAsSelectCommandShims.scala:37)
E                   	at com.nvidia.spark.rapids.GpuExecutedCommandExec.sideEffectResult$lzycompute(GpuExecutedCommandExec.scala:52)
E                   	at com.nvidia.spark.rapids.GpuExecutedCommandExec.sideEffectResult(GpuExecutedCommandExec.scala:50)
E                   	at com.nvidia.spark.rapids.GpuExecutedCommandExec.executeCollect(GpuExecutedCommandExec.scala:61)
E                   	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:118)
```

Not certain if this is related but we do see CommandResultExec is not supported on GPU
```
! <CommandResultExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.CommandResultExec
  @Expression <AttributeReference> namespace#52 could run on GPU
  @Expression <AttributeReference> tableName#53 could run on GPU
  @Expression <AttributeReference> isTemporary#54 could run on GPU
```

**Steps/Code to reproduce bug**
Run integration tests for failing tests
cd  spark-rapids/integration_tests/
`./run_pyspark_from_build.sh -k <name of test>`       `//Example : ./run_pyspark_from_build.sh -k test_write_save_table`

**Expected behavior**
1. Tests should pass OR 
2. XFAIL the test or fallback to CPU if there is a valid reason.

**Environment details (please complete the following information)**
local

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #8019.

This PR updates the GpuCreateDataSourceTableAsSelectCommand 340 shim to subclass LeafRunnableCommand since 3.4.0 now executes this command using ExecuteCommandExec instead of DataWritingCommandExec.  This also shims `writeAndRead` from `GpuDataSource` to execute the writing command now more like Spark 3.4, which will execute the InsertIntoHadoopFsRelationCommand using the SparkSession, which will actually resolve to a brand new physical plan that will be also be transformed by plugin.

### CODE REVIEW

File: sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala [hunk 1]
```diff
@@ -48,7 +48,8 @@ final class CreateDataSourceTableAsSelectCommandMeta(
 
     val spark = SparkSession.active
     origProvider =
-      GpuDataSource.lookupDataSourceWithFallback(cmd.table.provider.get, spark.sessionState.conf)
+      GpuDataSourceBase.lookupDataSourceWithFallback(cmd.table.provider.get,
+        spark.sessionState.conf)
     // Note that the data source V2 always fallsback to the V1 currently.
     // If that changes then this will start failing because we don't have a mapping.
     gpuProvider = origProvider.getConstructor().newInstance() match {
```
Comment (NVnavkumar) [inline sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala:55]: To be honest, GpuFileFormat is not really necessary in the GpuDataSource shim for 340. Since the command ultimately returned is a regular InsertIntoHadoopFsRelationCommand, the GPU checks are performed twice now. But I haven't removed this yet, just in case there is a dependency that I have missed.

**Comment by NVnavkumar** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSourceBase.scala [hunk 2]
```diff
@@ -70,19 +67,19 @@ case class GpuDataSource(
     origProvider: Class[_],
     gpuFileFormat: ColumnarFileFormat) extends Logging {
 
-  private def originalProvidingInstance() = origProvider.getConstructor().newInstance()
+  private[rapids] def originalProvidingInstance() = origProvider.getConstructor().newInstance()
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSourceBase.scala:70]:
```suggestion
  protected def originalProvidingInstance() = origProvider.getConstructor().newInstance()
```

File: sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/shims/GpuCreateDataSourceTableAsSelectCommandShims.scala [hunk 3]
```diff
@@ -67,10 +64,10 @@ case class GpuCreateDataSourceTableAsSelectCommand(
       }
 
       saveDataIntoTable(
-        sparkSession, table, table.storage.locationUri, child, SaveMode.Append, tableExists = true)
+        sparkSession, table, table.storage.locationUri, SaveMode.Append, tableExists = true)
     } else {
       table.storage.locationUri.foreach { p =>
-        GpuRunnableCommand.assertEmptyRootPath(p, mode, sparkSession.sessionState.newHadoopConf)
+        GpuDataWritingCommand.assertEmptyRootPath(p, mode, sparkSession.sessionState.newHadoopConf)
```
Comment (NVnavkumar) [inline sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/shims/GpuCreateDataSourceTableAsSelectCommandShims.scala:70]: This actually parallelizes more of what Spark 3.4 does anyways. So no need for this in GpuRunnableCommand.

File: sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala [hunk 4]
```diff
@@ -48,33 +45,16 @@ final class CreateDataSourceTableAsSelectCommandMeta(
 
     val spark = SparkSession.active
     origProvider =
-      GpuDataSource.lookupDataSourceWithFallback(cmd.table.provider.get, spark.sessionState.conf)
-    // Note that the data source V2 always fallsback to the V1 currently.
-    // If that changes then this will start failing because we don't have a mapping.
-    gpuProvider = origProvider.getConstructor().newInstance() match {
-      case f: FileFormat if GpuOrcFileFormat.isSparkOrcFormat(f) =>
-        GpuOrcFileFormat.tagGpuSupport(this, spark, cmd.table.storage.properties, cmd.query.schema)
```
Comment (jlowe) [inline sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala:56]: This used to prevent replacing CreateDataSourceTableAsSelectCommand with a GPU version if we knew we couldn't replace the underlying data source.  Where is that happening now?  It seems like this will almost always replace the CreateDataSourceTableAsSelectCommand before it knows whether the data source can be replaced, and that could cause tests to "pass" thinking we replaced the write when in reality we did not replace the InsertIntoHadoopFsRelationCommand.

File: sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala [hunk 5]
```diff
@@ -48,10 +47,9 @@ final class CreateDataSourceTableAsSelectCommandMeta(
...
-      GpuDataSource.lookupDataSourceWithFallback(cmd.table.provider.get, spark.sessionState.conf)
-    // Note that the data source V2 always fallsback to the V1 currently.
-    // If that changes then this will start failing because we don't have a mapping.
-    gpuProvider = origProvider.getConstructor().newInstance() match {
+      GpuDataSourceBase.lookupDataSourceWithFallback(cmd.table.provider.get,
+        spark.sessionState.conf)
+    origProvider.getConstructor().newInstance() match {
       case f: FileFormat if GpuOrcFileFormat.isSparkOrcFormat(f) =>
         GpuOrcFileFormat.tagGpuSupport(this, spark, cmd.table.storage.properties, cmd.query.schema)
       case _: ParquetFileFormat =>
```
Comment (jlowe) [inline sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala:55]: Nit: There's now an extraneous `None` in the `case ds =>` below since the match result is no longer being used.

File: sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala (hunk 4 above)
Comment (jlowe) [reply sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala]: > I wonder if it could be rewritten to not create the object and just do the validation itself

Everything I see it doing is checking the type of class on the object, which makes it seem a bit silly to construct an object from a class just to check what class the object is.  We already have the class, and can just check it directly.  But that's the way it worked before, and we can clean that up in a followup.

**Review by jlowe — APPROVED** [review]

**Comment by NVnavkumar** [comment]
build
