### PR TITLE
Check for CPU cores and free memory in IT script

### LINKED ISSUE #3859: [BUG] IT script will fail if GPU's memory is big enough such as 50G.
**Describe the bug**
When GPU memory is 50G, TEST_PARALLEL will be 19 according to the logic in the script run_pyspark_from_build.sh,  then TEST_PARALLEL is bigger than CPU cores(16), and IT will failed.

Better to have additional check on TEST_PARALLEL and CPU cores.

**Steps/Code to reproduce bug**
1. 
GPU memory is big
./integration_tests/run_pyspark_from_build.sh -k <test_case>
2.  workaround
export TEST_PARALLEL=19
./integration_tests/run_pyspark_from_build.sh -k <test_case>

errors:
```
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/spark-3.0.1-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1207, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/spark-3.0.1-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1033, in send_command
    response = connection.send_command(command)
  File "/spark-3.0.1-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1211, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while receiving
[gw11] node down: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 570, in _importconftest
    mod = import_path(conftestpath, mode=importmode)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/pathlib.py", line 524, in import_path
    importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/home/chonggao/code/spark-rapids/integration_tests/src/main/python/conftest.py", line 17, in <module>
  File "/spark-rapids/integration_tests/src/main/python/spark_init_internal.py", line 98, in <module>
    _spark = _spark__init()
  File "/spark-rapids/integration_tests/src/main/python/spark_init_internal.py", line 51, in _spark__init
    _s = _sb.enableHiveSupport() \
  File "/spark-3.0.1-bin-hadoop3.2/python/pyspark/sql/session.py", line 186, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/spark-3.0.1-bin-hadoop3.2/python/pyspark/context.py", line 376, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/spark-3.0.1-bin-hadoop3.2/python/pyspark/context.py", line 135, in __init__
    self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,
  File "/spark-3.0.1-bin-hadoop3.2/python/pyspark/context.py", line 198, in _do_init
    self._jsc = jsc or self._initialize_context(self._conf._jconf)
  File "/spark-3.0.1-bin-hadoop3.2/python/pyspark/context.py", line 315, in _initialize_context
    return self._jvm.JavaSparkContext(jconf)
  File "/spark-3.0.1-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1568, in __call__
    return_value = get_return_value(
  File "/spark-3.0.1-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/usr/local/lib/python3.8/dist-packages/xdist/remote.py", line 256, in <module>
    config = _prepareconfig(args, None)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 1070, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 500, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 508, in _try_load_conftest
    self._getconftestmodules(anchor, importmode)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 536, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 574, in _importconftest
    raise ConftestImportFailure(conftestpath, exc_info) from e
_pytest.config.ConftestImportFailure: Py4JError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext (from /spark-rapids/integration_tests/src/main/python/conftest.py)


```

### PR DESCRIPTION
**Pull request by res-life**
This fixes #3859 

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

File: integration_tests/run_pyspark_from_build.sh [hunk 1]
```diff
@@ -70,6 +70,21 @@ else
         # to still launch a spark application.
         TEST_PARALLEL=`nvidia-smi --query-gpu=memory.free --format=csv,noheader | awk '{if (MAX < $1){ MAX = $1}} END {print int(MAX / (2.3 * 1024)) - 1}'`
         echo "AUTO DETECTED PARALLELISM OF $TEST_PARALLEL"
+
+        # adjust TEST_PARALLEL according to cpu cores and free memory
+        cpu_cores=$(nproc --all)
+        free_mem_mib=$(awk '/MemFree/ { printf "%d\n", $2/1024 }' /proc/meminfo)
+        max_parallel_for_cpu_cores=$(python -c "print($cpu_cores - 1)")
```
Comment (jlowe) [inline integration_tests/run_pyspark_from_build.sh:77]: Nit: Firing up Python here for some simple math seems like overkill, can use bash's [arithmetic evaluation](https://tldp.org/LDP/abs/html/arithexp.html) to do this directly in the shell.
 ```suggestion
        max_parallel_for_cpu_cores=$(($cpu_cores - 1))
```

File: integration_tests/run_pyspark_from_build.sh [hunk 2]
```diff
@@ -70,6 +70,21 @@ else
...
+        # assume 50M for each test thread
+        max_parallel_for_free_memory=$(python -c "print(int(($free_mem_mib - 1) / 50))")
```
Comment (jlowe) [inline integration_tests/run_pyspark_from_build.sh:79]:
```suggestion
        max_parallel_for_free_memory=$(( ($free_mem_mib - 1) / 50 ))
```

Comment (jlowe) [reply integration_tests/run_pyspark_from_build.sh:79]: Curious about the reasoning for the `- 1` _before_ dividing by 50MB per thread.  For most free memory values, the divide will eliminate any effect of the `- 1`.

Comment (revans2) [reply integration_tests/run_pyspark_from_build.sh:79]: I am also confused where the 50 MB/thread came from. I thought the default heap size for Spark is 1GiB

Comment (res-life) [reply integration_tests/run_pyspark_from_build.sh:79]: "-1" is to reserve some memory for other processes in the OS.
"-1" is no need, let's only adjust 50MB.

**Comment by pxLi** [comment]
since most of our nightly IT tests are in docker, the cpu num and mem size you see is the value of the host but not for the container which means you can hardly get the real limitation value (cgroup on host) here,

For memory, you may get it in docker but it varies differently in different linux kernel
/sys/fs/cgroup/memory/memory.limit_in_bytes (4.x-sth)
/sys/fs/cgroup/memory.max (5.x-sth)

I would recommend to not rely on /proc info here, and take the cpu_cores and mem_size as ENV variable for this script

**Comment by res-life** [comment]
Updated, please review again.

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
> since most of our nightly IT tests are in docker, the cpu num and mem size you see is the value of the host but not for the container which means you can hardly get the real limitation value (cgroup on host) here,
> 
> For memory, you may get it in docker but it varies in different linux kernels /sys/fs/cgroup/memory/memory.limit_in_bytes (3.x-sth) /sys/fs/cgroup/memory.max (5.x-sth)
> 
> I would recommend to not rely on /proc or other system info here, take the cpu_cores and mem_size from ENV variables if any (could give them some conservative defaults and let people to increase the value if needed), and then do the calculation in this script~

If set TEST_PARALLEL, this code will not invoke.  
As I know premerge always set TEST_PARALLEL.
```
   if [[ "${TEST_PARALLEL}" == "" ]]; then
   ......   // code changes
   fi
```

File: integration_tests/run_pyspark_from_build.sh [hunk 3]
```diff
@@ -70,6 +70,30 @@ else
         # to still launch a spark application.
         TEST_PARALLEL=`nvidia-smi --query-gpu=memory.free --format=csv,noheader | awk '{if (MAX < $1){ MAX = $1}} END {print int(MAX / (2.3 * 1024)) - 1}'`
         echo "AUTO DETECTED PARALLELISM OF $TEST_PARALLEL"
+
+        # adjust TEST_PARALLEL according to cpu cores and free memory;
+        # first read from ENV; Note it's hardly to get CPU cores and real free memory in docker
+        if [[ "${PYSP_TEST_CPU_CORES}" != "" ]]; then
+          cpu_cores=${PYSP_TEST_CPU_CORES}
+        else
+          cpu_cores=$(nproc --all)
```
Comment (jlowe) [inline integration_tests/run_pyspark_from_build.sh:79]: Why are we passing `--all` here?  Calling `nproc` with no parameters may address @pxLi's concern about a cgroup-constrained environment.  IIUC `nproc` normally parses `/sys/fs/cgroup/cpuset/cpuset.cpus` to determine the number of CPUs available except `--all` will force it to look at all installed processors rather than available processors.

File: integration_tests/run_pyspark_from_build.sh [hunk 4]
```diff
@@ -70,6 +70,30 @@ else
...
+        fi
+        if [[ "${PYSP_TEST_FREE_MEMORY}" != "" ]]; then
+          free_mem_mib=${PYSP_TEST_FREE_MEMORY}
+        else
+          free_mem_mib=$(awk '/MemFree/ { printf "%d\n", $2/1024 }' /proc/meminfo)
+        fi
+        max_parallel_for_cpu_cores=$((${cpu_cores} - 1))
```
Comment (jlowe) [inline integration_tests/run_pyspark_from_build.sh:86]: Adding a comment for why the `- 1` is here would help future maintainers.  Also do we want to subtract 1 even if an environment variable explicitly told us how many to use?

File: integration_tests/run_pyspark_from_build.sh (hunk 3 above)
Comment (pxLi) [reply integration_tests/run_pyspark_from_build.sh:79]: yeah, nproc is cgroup-aware if using "--cpuset-cpus" but for not "--cpus" or "--cpu-period" or "--cpu-quota", this could also be a little tricky here if want to support all scenarios

**Comment by pxLi** [comment]
> > since most of our nightly IT tests are in docker, the cpu num and mem size you see is the value of the host but not for the container which means you can hardly get the real limitation value (cgroup on host) here,
> > For memory, you may get it in docker but it varies in different linux kernels /sys/fs/cgroup/memory/memory.limit_in_bytes (3.x-sth) /sys/fs/cgroup/memory.max (5.x-sth)
> > I would recommend to not rely on /proc or other system info here, take the cpu_cores and mem_size from ENV variables if any (could give them some conservative defaults and let people to increase the value if needed), and then do the calculation in this script~
> 
> If set TEST_PARALLEL, this code will not invoke. As I know premerge always set TEST_PARALLEL.
> 
> ```
>    if [[ "${TEST_PARALLEL}" == "" ]]; then
>    ......   // code changes
>    fi
> ```
> 
> @pxLi

that was a workaround here, we would like to also benefit from auto-resource detection and auto-math here if any stable ones. But I am fine to keep setting `TEST_PARALLEL` by experience for now

File: integration_tests/run_pyspark_from_build.sh (hunk 4 above)
Comment (res-life) [reply integration_tests/run_pyspark_from_build.sh:92]: Added comment.  IIUC environment variable tells us the number of all available cores, but we do not want to use all of them.

**Comment by res-life** [comment]
build

**Review by jlowe — APPROVED** [review]
