### PR TITLE
Fix boolean, int, and float parsing. Improve decimal parsing for hive

### LINKED ISSUE #7085: [BUG] GPU Hive Text reader fails to read floating point input as integral types
#7013 introduces support for reading Hive (default) delimited text files via the Spark RAPIDS Plugin.

The Hive `LazySimpleSerDe` reads some floating point values as integral types, on a "best effort" basis. For example, here are some input strings (representing floating point values), alongside `LazySimpleSerDe`'s direct `INT` interpretation:
```
1.042         -> 1
98.343        -> 98
2248.23       -> 2248
184721.23     -> 184721
3.4028235e+38 -> null
```

The `GpuHiveTableScanExec` in the Spark RAPIDS Plugin, when invoked to read these as `INT`, deems them all `NULL`. (This behaviour happens to be in line with Spark's CSV interpretation.)

Note: 
1. This only happens when interpreting float-strings as integral types. `GpuHiveTableScanExec` does read these correctly as floating-point.
2. `GpuHiveTableScanExec` does read integral/floating point types correctly when written as integral/floating point through the Hive `LazySimpleSerDe`. i.e. Round-trip reads succeed for integral and floating point values.

### PR DESCRIPTION
**Pull request by revans2**
This depends on https://github.com/NVIDIA/spark-rapids-jni/pull/797

This fixes #7085

It also adds in a bunch of checks to fall back to the CPU if we see a hive table that we might not be able to support because of configs.

### CODE REVIEW

File: sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala [hunk 1]
```diff
@@ -323,12 +324,12 @@ case class GpuHiveTableScanExec(requestedAttributes: Seq[Attribute],
...
-    // Note: The populated `options` aren't strictly required for text, currently.
-    //       These are added in case they are required for table read in the future,
-    //       (like with Hive ORC tables).
     val options                   = hiveTableRelation.tableMeta.properties ++
                                     hiveTableRelation.tableMeta.storage.properties
-    val hadoopConf                = sparkSession.sessionState.newHadoopConfWithOptions(options)
+    val hadoopConf                = sparkSession.sessionState.newHadoopConf()
+    // In the CPU HiveTableScanExec the config will have a bunch of confs set for S3 keys
+    //  and predicate push down/etc. We don't need this because we are getting that information
+    //  directly.
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala:332]:
```suggestion
    // and predicate push down/etc. We don't need this because we are getting that information
    // directly.
```

**Review by jlowe — APPROVED** [review]

**Review by jlowe — DISMISSED** [review]

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]
