### PR TITLE
Fix ClassCastException for unsupported TypedImperativeAggregate functions

### LINKED ISSUE #3253: [BUG] ClassCastException for unsupported TypedImperativeAggregate functions
**Describe the bug**

If we attempt to use any `TypedImperativeAggregate` functions that we do not support yet (such as approx percentile) then the plugin throws a ClassCastException.

**Steps/Code to reproduce bug**
```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.1.2
      /_/
         
Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_292)
Type in expressions to have them evaluated.
Type :help for more information.

scala> val df1 = (600 to 1000).toDF("n")
df1: org.apache.spark.sql.DataFrame = [n: int]

scala> val df2 = df1.agg(expr("approx_percentile(n, array(0.25, 0.5, 0.75))").as("approx_percentiles"))
df2: org.apache.spark.sql.DataFrame = [approx_percentiles: array<int>]

scala> df2.show
java.lang.ClassCastException: com.nvidia.spark.rapids.RuleNotFoundExprMeta cannot be cast to com.nvidia.spark.rapids.TypedImperativeAggExprMeta
  at com.nvidia.spark.rapids.GpuTypedImperativeSupportedAggregateExecMeta.$anonfun$overrideAggBufTypes$1(aggregate.scala:1047)
  at com.nvidia.spark.rapids.GpuTypedImperativeSupportedAggregateExecMeta.$anonfun$overrideAggBufTypes$1$adapted(aggregate.scala:1043)
```

**Expected behavior**
We should fall back to CPU

**Environment details (please complete the following information)**
- Standalone / local mode

**Additional context**
None

### PR DESCRIPTION
**Pull request by sperlingxx**
Signed-off-by: sperlingxx <lovedreamf@gmail.com>

Fixes #3253 

The ClassCastException occurred during overriding the buffer types of TypedImperativeAggregate functions. The code for overriding assumed that  `TypedImperativeAggreagte` must be wrapped by `TypedImperativeAggExprMeta`. But there are exceptions: for  `TypedImperativeAggreagte` without GPU implementation , they are wrapped by `RuleNotFoundExprMeta`.

### CODE REVIEW

**Comment by sperlingxx** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala [hunk 1]
```diff
@@ -1071,19 +1071,13 @@ abstract class GpuTypedImperativeSupportedAggregateExecMeta[INPUT <: SparkPlan](
     val desiredInputAggBufTypes = mutable.HashMap.empty[ExprId, DataType]
     // Collects exprId from TypedImperativeAggBufferAttributes, and maps them to the data type
     // of `TypedImperativeAggExprMeta.aggBufferAttribute`.
-    agg.aggregateExpressions.zipWithIndex.foreach {
-      case (expr, i) if expr.aggregateFunction.isInstanceOf[TypedImperativeAggregate[_]] =>
+    aggregateExpressions.map(_.childExprs.head).foreach {
+      case aggMeta: TypedImperativeAggExprMeta[_] =>
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:1075]: Nit, this removes the need for the `asInstanceOf` for `wrapped`:

```
case aggMeta: TypedImperativeAggExprMeta[TypedImperativeAggregate[_]] =>
```

File: integration_tests/src/main/python/hash_aggregate_test.py [hunk 2]
```diff
@@ -547,6 +547,20 @@ def test_hash_groupby_collect_partial_replace_fallback_with_other_agg(conf, aqe_
     group by k1""",
         conf=local_conf)
 
+@ignore_order(local=True)
```
Comment (abellina) [inline integration_tests/src/main/python/hash_aggregate_test.py:550]: I believe `approx_percentile` is coming, and when it does show up we will fail this test and then whoever implements the function needs to figure out how to address, it would be better if we force the aggregate function to not be on the GPU. Could you explicitly turn off an already working typed imperative aggregate?

Comment (abellina) [reply integration_tests/src/main/python/hash_aggregate_test.py:550]: (i.e. `spark.rapids.sql.expression.CollectList=false`, or you should be able to get away with `spark.rapids.sql.expression.ApproximatePercentile=false`)

Comment (ttnghia) [reply integration_tests/src/main/python/hash_aggregate_test.py:550]: Newbie question: Why do we allow_non_gpu for these aggs?

Comment (abellina) [reply integration_tests/src/main/python/hash_aggregate_test.py:550]: The plugin can be placed in a mode that throws if some parts of the plan can't be replaced (`spark.rapids.sql.test.enabled`). The allow list (`spark.rapids.sql.test.allowedNonGpu`) specifies expressions that are OK even in this mode, as they are pertinent to the test.

Comment (revans2) [reply integration_tests/src/main/python/hash_aggregate_test.py:550]: The `spark.rapids.sql.expression.ApproximatePercentile=false` is not going to work for actually testing this. We have to have a `TypedImperativeAggregate` that does not exist in the GpuOverrides mapping. Because even with that config it would still create a `TypedImperativeAggExprMeta` to wrap it. It would just be turned off.

I would propose we go with an API that is less likely we are going to support any time soon. Specifically a udaf, but that is really hard to do inside the python tests.  As it is I am fine with this for now, but looking at the list of TypedImperativeAggregate functions there are not a lot to choose from.

**Review by revans2 — APPROVED** [review]
