### PR TITLE
Dedicated deploy-file with reduced pom in nightly build [skip ci]

### LINKED ISSUE #4347: [BUG] Dist jar pom lists aggregator jar as dependency
A recent spark-rapids-ml test job failed with the following error:
```
java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.expressions.TimeSub
```
This was caused because the spark301 plugin jars were on the classpath yet the Spark version being used was Spark 3.1.2.  It loos like the dist jar was pulling in the aggregator jar, and the pom specifies it defaults to spark.version=3.0.1.

The incorrect aggregator dependency on the published pom should have been fixed by #4265, but the pom being published for dist snapshots still has the aggregator jars.  From the most recent snapshot pom on 1206:
```
    <dependencies>
        <dependency>
            <groupId>com.nvidia</groupId>
            <artifactId>rapids-4-spark-aggregator_${scala.binary.version}</artifactId>
            <version>${project.version}</version>
            <classifier>${spark.version.classifier}</classifier>
            <scope>compile</scope>
        </dependency>

        <!--
            manually promoting provided cudf as a direct dependency
        -->
        <dependency>
            <groupId>ai.rapids</groupId>
            <artifactId>cudf</artifactId>
            <version>${cudf.version}</version>
            <classifier>${cuda.version}</classifier>
            <scope>compile</scope>
        </dependency>
    </dependencies>
```

I checked the `rapids4spark-version-info.properties` in the dist snapshot jar:
```
version=21.12.0-SNAPSHOT
cudf_version=21.12.0
user=
revision=7bea7c80362fe54055b7e0cd7ffa672098118f76
branch=HEAD
date=2021-12-06T08:04:04Z
url=https://github.com/NVIDIA/spark-rapids.git
```
which indicates it should have been built with the fix in #4265 yet the published dist pom contains the aggregator jar dependency.

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #4347 

replaces install/deploy that use the original pom with install-file/deploy-file where the pom can be overridden 

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

File: jenkins/spark-nightly-build.sh [hunk 1]
```diff
@@ -21,36 +21,80 @@ set -ex
...
+function mvnEval {
+    mvn help:evaluate -q -pl $DIST_PL $MVN_URM_MIRROR -Dmaven.repo.local=$M2DIR -Dcuda.version=$CUDA_CLASSIFIER -DforceStdout -Dexpression=$1
+}
+
+ART_ID=$(mvnEval project.artifactId)
+ART_GROUP_ID=$(mvnEval project.groupId)
+ART_VER=$(mvnEval project.version)
+
+DIST_FPATH="$DIST_PL/target/$ART_ID-$ART_VER"
+DIST_POM_FPATH="$DIST_PL/target/extra-resources/META-INF/maven/com.nvidia/$ART_ID/pom.xml"
```
Comment (tgravescs) [inline jenkins/spark-nightly-build.sh:35]: nit could use ART_GROUP_ID for com.nvidia

Comment (tgravescs) [reply jenkins/spark-nightly-build.sh:35]: DIST_POM_FPATH is never used

File: jenkins/spark-nightly-build.sh [hunk 2]
```diff
@@ -21,36 +21,80 @@ set -ex
...
-    mvn -B -pl '!tools' -Dbuildver=301 -PsnapshotsWithDatabricks clean deploy $MVN_URM_MIRROR -Dmaven.repo.local=$M2DIR -Dcuda.version=$CUDA_CLASSIFIER
-else
-    mvn -B -pl '!tools' -Dbuildver=301 -PsnapshotsWithDatabricks clean install $MVN_URM_MIRROR -Dmaven.repo.local=$M2DIR -Dcuda.version=$CUDA_CLASSIFIER
+    # deploy dist with reduced pom
+    mvn -B deploy:deploy-file
+        $MVN_URM_MIRROR -Dmaven.repo.local=$M2DIR \
+        -Dcuda.version=$CUDA_CLASSIFIER \
+        -Dfile="${DIST_FPATH}.jar" \
+        -DgroupId="${ART_GROUP_ID}" \
+        -DartifactId="${ART_ID}" \
```
Comment (tgravescs) [inline jenkins/spark-nightly-build.sh:90]: aren't we missing the actual reduced pom here?  -DpomFile="$POM_FPATH"
            
Maybe I'm missing something else?

File: jenkins/spark-nightly-build.sh [hunk 3]
```diff
@@ -21,36 +21,80 @@ set -ex
...
+    mvn -B install:install-file $MVN_URM_MIRROR \
+        -Dcuda.version=$CUDA_CLASSIFIER \
+        -Dmaven.repo.local=$M2DIR \
+        -Dfile="${DIST_FPATH}.jar" \
+        -DgroupId="${ART_GROUP_ID}" \
+        -DartifactId="${ART_ID}" \
+        -Dversion="${ART_VER}" \
+        -Dpackaging=jar
+    [[ $SKIP_DEPLOY != 'true' ]] && \
+        mvn -B deploy -pl '!tools,!dist' $MVN_URM_MIRROR \
```
Comment (tgravescs) [inline jenkins/spark-nightly-build.sh:59]: this is missing that tools gets deployed with 311

File: jenkins/spark-nightly-build.sh [hunk 4]
```diff
@@ -21,36 +21,80 @@ set -ex
...
+
+mvn -B clean install -pl '!tools' \
+    -PsnapshotsWithDatabricks \
+    -Dbuildver=$SPARK_BASE_SHIM_VERSION \
+    $MVN_URM_MIRROR \
+    -Dmaven.repo.local=$M2DIR \
+    -Dcuda.version=$CUDA_CLASSIFIER
+
+# fix up dist jar with reduced pom in the local m2
+mvn -B install:install-file $MVN_URM_MIRROR \
```
Comment (jlowe) [inline jenkins/spark-nightly-build.sh:74]: Can the comments elaborate a bit on why we need to use a custom install command _and_ a custom deploy command?  I would expect one or the other but not both.  Also the PR description doesn't help explain how this fix works.

File: jenkins/spark-nightly-build.sh (hunk 1 above)
Comment (gerashegalov) [reply jenkins/spark-nightly-build.sh:35]: will remove, I first wanted to use it as for releases but then remembered that #4265  fixed META-INF/maven pom entry inside the jar to be consistent with the published pom

File: jenkins/spark-nightly-build.sh (hunk 2 above)
Comment (gerashegalov) [reply jenkins/spark-nightly-build.sh:90]: we rely on Maven features quoted in the description to use the pom inside the jar that is now correct

**Review by jlowe — DISMISSED** [review]
Minor typo but not needed to fix if this can unblock the nightly builds

File: jenkins/spark-nightly-build.sh (hunk 2 above)
Comment (gerashegalov) [reply jenkins/spark-nightly-build.sh]: for future reference, I ended up putting -DpomFile back because upgrading the plugins to 3.0.0-M1 is triggering cascading changes to unrelated places in the build

**Comment by gerashegalov** [comment]
build

**Comment by pxLi** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by tgravescs** [comment]
so the test nightly job we had for this failed the deploy:

03:38:04  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy-file (default-cli) on project rapids-4-spark-parent: No transfer protocol found. -> [Help 1]

Is that related to 4371?    

I guess we will see if normal nightly passes
