### PR TITLE
Fix "Range is out of bounds" crash from GpuArraysZip when receiving a 0-row batch

### LINKED ISSUE #14592: arrays_zip crashes with 'Range is out of bounds' when input batch has 0 rows
**Describe the bug**

`GpuArraysZip` crashes with `CudfException: Range is out of bounds` when it receives a 0-row batch. This happens because cudf's `segmented_gather` does not handle LIST columns where `offsets.size() == 0` (the empty representation produced by `make_empty_lists_column`).

The root cause chain:
1. `GpuArraysZip.padArraysToMaxLength` calls `ColumnVector.sequence(zero, maxArraySize)` where both inputs have 0 rows
2. cudf `lists::sequences` with `n_lists == 0` returns `make_empty_lists_column`, which creates a LIST column with `offsets.size() = 0`
3. `segmentedGather` calls `copy_range_in_place` which tries to copy `size() + 1 = 1` elements from a source with `size() = 0`, failing the bounds check

In production, 0-row batches reach `arrays_zip` when a preceding `explode` eliminates all rows in a batch (e.g., all rows in a batch have empty inner arrays).

**Steps/Code to reproduce bug**

Save the following as `repro.scala` and run with `spark-shell -i repro.scala`:

```scala
import org.apache.spark.sql.Row
import org.apache.spark.sql.types._

val path = "/tmp/test_arrays_zip_bug"

val elementType = StructType(Seq(
  StructField("com_1", ArrayType(IntegerType)),
  StructField("com_2", ArrayType(StringType))
))
val advType = StructType(Seq(
  StructField("element_info", ArrayType(elementType))
))
val schema = StructType(Seq(
  StructField("id", IntegerType),
  StructField("adv_info", ArrayType(advType))
))

// Each row has adv_info with one element, but element_info is empty.
// explode(adv_info) produces rows, explode(element_info) produces 0 rows,
// then arrays_zip receives a 0-row batch and crashes.
val rows = (0 until 50).map(i => Row(i, Seq(Row(Seq.empty[Row]))))
val df = spark.createDataFrame(spark.sparkContext.parallelize(rows), schema)
df.coalesce(1).write.mode("overwrite").parquet(path)

spark.read.parquet(path).createOrReplaceTempView("test_data")

spark.sql("""
  SELECT id, zipped.*
  FROM test_data
  LATERAL VIEW explode(adv_info) t1 AS adv
  LATERAL VIEW explode(adv.element_info) t2 AS elem
  LATERAL VIEW explode(arrays_zip(
    elem.com_1,
    coalesce(elem.com_2, array(cast(null as string)))
  )) t3 AS zipped
""").show()
```

**Error:**
```
ai.rapids.cudf.CudfException: CUDF failure at:
  .../cudf/cpp/src/copying/copy_range.cu:200: Range is out of bounds.
    at ai.rapids.cudf.ColumnView.segmentedGather(Native Method)
    at ai.rapids.cudf.ColumnView.segmentedGather(ColumnView.java:1894)
    at ai.rapids.cudf.ColumnView.segmentedGather(ColumnView.java:1873)
    at org.apache.spark.sql.rapids.GpuArraysZip.$anonfun$padArraysToMaxLength$3(collectionOperations.scala:1273)
```

**Expected behavior**

The query should return an empty result set without crashing. CPU Spark handles this correctly.

**Environment details**
 - Environment location: Standalone
 - Spark 3.5.2
 - spark-rapids main branch

**Additional context**

The fix can be applied at the Spark plugin level (early return in `padArraysToMaxLength` for 0-row input) and/or at the cudf level (early return in `segmented_gather` for empty columns). The cudf issue is that `make_lists_column` allows `(num_rows == 0 && offsets.size() == 0)` as a valid representation, but `segmented_gather` assumes `offsets.size() >= size() + 1` unconditionally.

Relevant cudf code: `cpp/src/lists/copying/segmented_gather.cu` lines 89-97.

### PR DESCRIPTION
**Pull request by thirtiseven**
Fixes https://github.com/NVIDIA/spark-rapids/issues/14592.

### Description

This pr adds a check for empty `inputs` in `padArraysToMaxLength` to fix a cuDF crash from arrays_zip.

With this pr, the crash that was reproduced in #14592 disappeared.

### Checklists

Documentation
- [ ] Updated for new or modified user-facing features or behaviors
- [x] No user-facing change

Testing
- [ ] Added or modified tests to cover new code paths
- [ ] Covered by existing tests
      (Please provide the names of the existing tests in the PR description.)
- [x] Not required

Performance
- [ ] Tests ran and results are added in the PR description
- [ ] Issue filed with a link in the PR description
- [x] Not required

### CODE REVIEW

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 1]
```diff
@@ -1249,6 +1249,9 @@ case class GpuArraysZip(children: Seq[Expression]) extends GpuExpression with Sh
    * same offsets and the same validity. This assumes that the validity on the inputs all match.
    */
   private def padArraysToMaxLength(inputs: Seq[ColumnVector]): Seq[ColumnVector] = {
+    if (inputs.head.getRowCount == 0) {
+      return inputs.map(_.incRefCount())
```
Comment (firestarman) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala]:
```suggestion
      return inputs.safeMap(_.incRefCount())
```

Another concern, do we need to check all the column has `getRowCount == 0`, not only the head ?

**Comment by thirtiseven** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala (hunk 1 above)
Comment (thirtiseven) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala]: > safeMap

Nice catch thanks.

> do we need to check all the column has `getRowCount == 0`, not only the head ?

All columns in inputs are evaluated from the same ColumnarBatch, so they always have the same row count. Checking only the head is sufficient.

**Comment by thirtiseven** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala [hunk 2]
```diff
@@ -1249,6 +1249,9 @@ case class GpuArraysZip(children: Seq[Expression]) extends GpuExpression with Sh
    * same offsets and the same validity. This assumes that the validity on the inputs all match.
    */
   private def padArraysToMaxLength(inputs: Seq[ColumnVector]): Seq[ColumnVector] = {
+    if (inputs.head.getRowCount == 0) {
```
Comment (firestarman) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:1252]: Is it possible inputs is empty here ? If yes, `inputs.head` will crash the process.

Comment (thirtiseven) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala:1252]: It is not possible now. This function won't be called when `inputs` is not empty.

**Review by firestarman — APPROVED** [review]
LGTM
