### PR TITLE
Fix Hive Delimited Text timestamp parsing

### LINKED ISSUE #7086: [BUG] GPU Hive delimited text reader is more permissive than `LazySimpleSerDe` for timestamps
#7013 introduces support for reading Hive (default) delimited text tables.

The `GpuHiveTableScanExec` is currently *more* permissive/robust than the Hive `LazySimpleSerDe` in its interpretation of timestamp strings. Here is a list of example timestamp strings, alongside the `GpuHiveTableScanExec`'s interpretation as timestamp:
```
"2020-09-16"          -> 2020-09-16 00:00:00
"2020-09-16T22:32"    -> 2020-09-16 22:32:00
"2020-09-16 22:32"    -> 2020-09-16 22:32:00
"2020-09-16T22:32:01" -> 2020-09-16 22:32:01
" 2020-09-16T22:32:01"-> 2020-09-16 22:32:01
"2020-09-16T22:32:01" -> 2020-09-16 22:32:01
"2020-09-16 22:32:01" -> 2020-09-16 22:32:01
"2020-09-16T22:32:01Z"-> 2020-09-16 22:32:01
"2020-09-16 22:32:01Z"-> 2020-09-16 22:32:01
```

When the same strings are read through `LazySimpleSerDe`, only the 7th row has a non-null interpretation:
```
+-------------------+
|                 ts|
+-------------------+
|               null|
|               null|
|               null|
|               null|
|               null|
|               null|
|2020-09-16 22:32:01|
|               null|
|               null|
+-------------------+
```

This is a case of the `GpuHiveTableScanExec` failing *less* than `LazySimpleSerDe`, when timestamps are written in non-default formats.

Note: The "round trip" test does work for timestamps. i.e. Timestamps written through `LazySimpleSerDe` are read correctly through `GpuHiveTableScanExec`.

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #7086.

`GpuHiveTableScanExec`'s handling of timestamps is not in line with
Hive's `LazySimpleSerDe` in a couple of respects:
  1. It should not be trimming whitespace around the input field
     before parsing as timestamp.
     E.g. " 2020-09-16 22:32:01 " should produce a null timstamp.
  2. It should not support timestamps like "2020-09-16T22:32:01",
     where the date and time are separated by 'T'. These should
     be interpreted as nulls.
  3. It should not support timestamps like "2020-09-16 22:32:01Z",
     ending in 'Z'. These should be interpreted as nulls.
  4. It should not support timestamps with missing fields,
     E.g. "2020-09", "2020-09-16 22:32".
     Only the sub-second spec is optional. Otherwise, these should
     be interpreted as nulls.

This commit should fix the problems listed above.

Signed-off-by: MithunR <mythrocks@gmail.com>

### CODE REVIEW

**Comment by mythrocks** [comment]
This PR is built atop the work in #7221, and will be left in draft until #7221 is merged.

File: sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala [hunk 1]
```diff
@@ -535,4 +536,63 @@ class GpuHiveDelimitedTextPartitionReader(conf: Configuration,
...
+    withResource(input.isTimestamp(cudfFormat)) { isDate =>
+      withResource(input.asTimestamp(dt, cudfFormat)) { asDate =>
+        withResource(Scalar.fromNull(dt)) { nullScalar =>
+          isDate.ifElse(asDate, nullScalar)
+        }
+      }
+    }
+  }
+
+  // As per Hive's LazySimpleSerDe documentation, only the following timestamp pattern is supported:
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala:559]: That is odd because the code shows that the format is configurable.

https://github.com/apache/hive/blob/374564f49b345f214ab8845e84244ac4ea4f0668/serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazySerDeParameters.java#L125-L129

At a minimum I think we need to fall back to the CPU if "timestamp.formats" is set in the params.

File: sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala [hunk 2]
```diff
@@ -535,4 +536,63 @@ class GpuHiveDelimitedTextPartitionReader(conf: Configuration,
...
+  //  "uuuu-MM-dd HH:mm:ss[.SSS...]"
+  //
+  // Note: No support for "uuuu-MM-dd'T'HH:mm:ss[.SSS...][Z]"
+  override def timestampFormat: String = s"${DateFormatter.defaultPattern} HH:mm:ss[.SSS][XXX]"
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala:563]: This is never used???? Should we use it? should we comment about it, or make a change in some way that we don't set it?  It just feels odd that we need set it, but we don't use it.

Comment (mythrocks) [reply sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala:563]: Ah, this isn't used in the current iteration. It used to be used earlier, when deriving the filtering regex.

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
Build

**Review by revans2 — APPROVED** [review]
