### PR TITLE
Fix device vector leak in RmmRetryIterator.splitSpillableInHalfByRows

### LINKED ISSUE #8038: [BUG] vector leaked when running NDS 3TB with memory restricted
**Describe the bug**
While trying to repro #7581 by running NDS 3TB with memory restricted to 6GB, and refcount debugging enabled, I saw the following vector leak.

```
Executor task launch worker for task 75.2 in stage 749.0 (TID 36368) 23/04/05 14:35:54:337 WARN RapidsBufferCatalog: device memory store spilling to reduce usage from 353594624 total (117886720 spillable) to 0 bytes
Executor task launch worker for task 75.2 in stage 749.0 (TID 36368) 23/04/05 14:35:54:337 WARN RapidsBufferCatalog: Targeting a host memory size of 34241851648. Current total 3072052224. Current spillable 3072052224
Cleaner Thread 23/04/05 14:35:54:340 ERROR MemoryCleaner: Leaked vector (ID: 861372): 2023-04-05 14:35:52.0426 UTC: INC
java.lang.Thread.getStackTrace(Thread.java:1559)
ai.rapids.cudf.MemoryCleaner$RefCountDebugItem.<init>(MemoryCleaner.java:333)
ai.rapids.cudf.MemoryCleaner$Cleaner.addRef(MemoryCleaner.java:91)
ai.rapids.cudf.ColumnVector.incRefCountInternal(ColumnVector.java:251)
ai.rapids.cudf.ColumnVector.<init>(ColumnVector.java:159)
ai.rapids.cudf.ColumnVector.fromViewWithContiguousAllocation(ColumnVector.java:200)
ai.rapids.cudf.Table.fromPackedTable(Table.java:3550)
ai.rapids.cudf.ContiguousTable.getTable(ContiguousTable.java:76)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.$anonfun$splitSpillableInHalfByRows$6(RmmRapidsRetryIterator.scala:591)
scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
scala.collection.TraversableLike.map(TraversableLike.scala:286)
scala.collection.TraversableLike.map$(TraversableLike.scala:279)
scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.$anonfun$splitSpillableInHalfByRows$5(RmmRapidsRetryIterator.scala:591)
com.nvidia.spark.rapids.Arm.withResource(Arm.scala:55)
com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:53)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withResource(RmmRapidsRetryIterator.scala:28)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.$anonfun$splitSpillableInHalfByRows$4(RmmRapidsRetryIterator.scala:590)
com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withResource(RmmRapidsRetryIterator.scala:28)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.$anonfun$splitSpillableInHalfByRows$3(RmmRapidsRetryIterator.scala:588)
com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withResource(RmmRapidsRetryIterator.scala:28)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.$anonfun$splitSpillableInHalfByRows$2(RmmRapidsRetryIterator.scala:587)
com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withResource(RmmRapidsRetryIterator.scala:28)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$.$anonfun$splitSpillableInHalfByRows$1(RmmRapidsRetryIterator.scala:582)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.split(RmmRapidsRetryIterator.scala:414)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:519)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:460)
scala.collection.Iterator.toStream(Iterator.scala:1417)
scala.collection.Iterator.toStream$(Iterator.scala:1416)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.toStream(RmmRapidsRetryIterator.scala:479)
scala.collection.TraversableOnce.toSeq(TraversableOnce.scala:354)
scala.collection.TraversableOnce.toSeq$(TraversableOnce.scala:354)
com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.toSeq(RmmRapidsRetryIterator.scala:479)
com.nvidia.spark.rapids.GpuHashAggregateIterator$AggHelper.aggregate(aggregate.scala:289)
com.nvidia.spark.rapids.GpuHashAggregateIterator$.aggregate(aggregate.scala:395)
com.nvidia.spark.rapids.GpuHashAggregateIterator$.$anonfun$computeAggregateAndClose$1(aggregate.scala:424)
com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
com.nvidia.spark.rapids.GpuHashAggregateIterator$.withResource(aggregate.scala:156)
com.nvidia.spark.rapids.GpuHashAggregateIterator$.computeAggregateAndClose(aggregate.scala:415)
com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:603)
com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:555)
scala.Option.getOrElse(Option.scala:189)
com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:552)
com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:497)
org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:318)
org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:340)
org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$2(RapidsShuffleInternalManagerBase.scala:281)
org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$2$adapted(RapidsShuffleInternalManagerBase.scala:274)
com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.withResource(RapidsShuffleInternalManagerBase.scala:234)
org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$1(RapidsShuffleInternalManagerBase.scala:274)
org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$1$adapted(RapidsShuffleInternalManagerBase.scala:273)
com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.withResource(RapidsShuffleInternalManagerBase.scala:234)
org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.write(RapidsShuffleInternalManagerBase.scala:273)
org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
org.apache.spark.scheduler.Task.run(Task.scala:131)
org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by jbrennan333**
Fixes #8038.

If we throw while constructing a `SpillableColumnarBatch` in `RmmRetryIterator.splitSpillableInHalfByRows`, we can leak the unprocessed remaining ColumnarBatches in `batches`.   The proposed fix is to use `withResource` for `batches`, and increment the ref counts on each batch before passing it to `SpillableColumnarBatch`. 

I have verified when I run NDS at 3TB with memory restricted to 6GB, I no longer get these vector leaks.

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala [hunk 1]
```diff
@@ -589,18 +589,20 @@ object RmmRapidsRetryIterator extends Arm with Logging {
...
-              val batches = tables.safeMap(GpuColumnVector.from(_, spillable.dataTypes))
-              val spillables = batches.safeMap { b =>
-                SpillableColumnarBatch(
-                  b,
-                  SpillPriorities.ACTIVE_BATCHING_PRIORITY)
+              withResource(tables.safeMap(GpuColumnVector.from(_, spillable.dataTypes))) {
+                batches =>
+                  val spillables = batches.safeMap { b =>
+                    SpillableColumnarBatch(
+                      GpuColumnVector.incRefCounts(b),
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:596]: we shouldn't need to `incRefCounts` herel. I would consider something like this instead:
```
val batchArray = batches.toArray
val spillables = new Array[SpillableColumnarBatch](batchArray.size)
closeOnExcept(spillables) { _ => 
  closeOnExcept(batchArray) { _ => 
    batchArray.zipWithIndex.foreach { case (batch, ix) =>
      spillables[ix] = SpillableColumnarBatch(batch, SpillPriorities.ACTIVE_BATCHING_PRIORITY)
      batchArray[ix] = null
    }
  }
  require(spillables.length == 2,
                      s"Contiguous split returned ${spillables.length} tables but two were " +
                          s"expected!")
}
```

Comment (abellina) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:596]: never mind, after talking to you offline the approach you had originally is much better.

**Review by abellina — APPROVED** [review]

**Comment by jbrennan333** [comment]
build
