### PR TITLE
Fix the ordering of join gather maps, and make it harder to break

### LINKED ISSUE #13854: [BUG] Integration tests: 1121 broadcast join timeout failures with INJECT_OOM and timeout the CI
**Describe the bug**
Build: rapids_it-AQE-pre_release-github/486 (This also fails all other IT jobs)

1121 test failures occurred during integration testing with Spark AQE (Adaptive Query Execution) enabled. The primary error pattern shows broadcast join timeouts (300 seconds) with message: 'Could not execute broadcast in 300 secs'. Multiple test cases failed including:
- test_broadcast_join_right_table_ridealong with various data types (Boolean, Date, Byte, Short, Integer, Long, Float, Double, String, Timestamp, Decimal, Array types)
- All failures show java.util.concurrent.TimeoutException in BroadcastExchangeExec.doExecuteBroadcast

The test environment had INJECT_OOM (Out Of Memory injection) enabled for stress testing, which likely contributed to resource exhaustion and broadcast timeouts.

Error logs:
```
org.apache.spark.SparkException: Could not execute broadcast in 300 secs
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec.doExecuteBroadcast

FAILED join_test.py::test_broadcast_join_right_table_ridealong[INJECT_OOM]
= 1121 failed, 3489 passed, 72 skipped =

**Environment details**
- Spark version: 3.2.0
- AQE enabled: true
- Test mode: INJECT_OOM stress testing
- Parallelism: 4
- Broadcast timeout: 300s (default)
-->

### PR DESCRIPTION
**Pull request by revans2**
This fixes #13854 

I thought I had tested this completely, but clearly I had not. I am putting this up here, but I plan to run a lot more tests.

The issue was that I had made a mistake on one API where the gather maps returned were in the wrong order and that resulted in us trying to gather data that was out of bounds. What is worse it was for an inner join so it resulted in us walking off the end of the data and reading bogus data, which might be the reason for the hang.

### Description

This code is larger than it needs to be. I wanted to put something in that would ensure that we did this right and that we would not run into issues again in the future for this same issue. That said there are a lot of cases where the build side of the join is implied, especially by the AST condition. It would be nice to fix this too, but it is beyond the scope of this issue.

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [ ] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala [hunk 1]
```diff
@@ -353,14 +353,10 @@ abstract class SplittableJoinIterator(
...
-        case LeftOuter if maps.length == 1 =>
-          // Distinct left outer joins only produce a single gather map since left table rows
-          // are not rearranged by the join.
-          Some(maps.head)
-        case _ if maps.length == 1 => None
-        case _ => Some(maps(1))
+      val rightMap = if (rightData.numCols == 0 || !maps.hasRight) {
+        None
+      } else {
+        Some(maps.right)
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala:359]: could we keep the comment that this is only for LeftOuter joins? Should we assert that the join type is indeed LeftOuter here?

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala [hunk 2]
```diff
@@ -101,6 +101,324 @@ object JoinTypeChecks {
...
+   * @param inner the inner join results
+   * @param leftRowCount the number of rows in the left hand table
+   * @return a gather maps result for a left anti join
+   */
+  def makeLeftAnti(inner: GatherMapsResult, leftRowCount: Int): GatherMapsResult = {
+    val leftRet = JoinPrimitives.makeAnti(inner.left, leftRowCount)
+    GatherMapsResult.makeFromLeft(leftRet)
+  }
+
+  def innerHashJoinBuildLeft(leftKeys: Table, rightKeys: Table,
```
Comment (abellina) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala:309]: should probably have scaladocs for this one as it is also part of the public api.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala [hunk 3]
```diff
@@ -101,6 +101,324 @@ object JoinTypeChecks {
...
+  def innerHashJoinBuildRight(leftKeys: Table, rightKeys: Table,
+                              leftTable: Table, rightTable: Table,
+                              compiledCondition: CompiledExpression,
+                              nullEquality: NullEquality): GatherMapsResult = {
+    val arrayRet = Table.mixedInnerJoinGatherMaps(leftKeys, rightKeys, leftTable, rightTable,
+      compiledCondition, nullEquality)
+    GatherMapsResult(arrayRet(0), arrayRet(1))
+  }
+
+  def innerHashJoinBuildSmallest(leftKeys: Table, rightKeys: Table,
```
Comment (abellina) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala:384]: same for this, really any other function we want to use outside of this object class.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala (hunk 1 above)
Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala:359]: Really the logic for this was moved up into other parts of the code.  The original code could only see the join type and how many gather maps there were.  So they used LeftOuter + 1 gather map to let them infer that the one gather map is a right gather map, because a distinct left outer join only returns a single right map.  But because the GatherMapsResults knows which table the single gather map is for we don't need the extra join type checks. We just know that this is fine.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala [hunk 4]
```diff
@@ -283,41 +283,45 @@ class ConditionalNestedLoopJoinIterator(
...
+          left.conditionalLeftSemiJoinGatherMap(right, condition, rowCount)
         }.getOrElse {
-          Array(left.conditionalLeftSemiJoinGatherMap(right, condition))
+          left.conditionalLeftSemiJoinGatherMap(right, condition)
         }
+        GatherMapsResult.makeFromLeft(leftGather)
       case LeftAnti =>
-        numJoinRows.map { rowCount =>
-          Array(left.conditionalLeftAntiJoinGatherMap(right, condition, rowCount))
+        val leftGatherer = numJoinRows.map { rowCount =>
```
[the remark this answers is not in the document]
Comment (revans2) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala:319]: Though technically correct for consistency, this code is less concerning on correctness so I am fine with leaving this.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@abellina please take another look

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala (hunk 2 above)
Comment (mythrocks) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala:309]: (Is this safe to resolve?)

**Comment by pxLi** [comment]
pre-merge CI timeout un-related case, which we saw before at https://github.com/NVIDIA/spark-rapids/pull/13831#issuecomment-3556214255

rekick

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
Merging this to ensure today's nightly CI covers this change, thanks
