### PR TITLE
Shim MockTaskContext to fix Spark 3.5.1 build

### LINKED ISSUE #10094: [BUG] spark351 PR check failure MockTaskContext method isFailed in class TaskContext of type ()Boolean is not defined
**Describe the bug**
```
.../MockTaskContext.scala:32: class MockTaskContext needs to be abstract, since method isFailed in class TaskContext of type ()Boolean is not defined
Error: [ERROR] one error found
```

Repro:

```
mvn package -pl tests -am -Dbuildver=351 
```

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #10094.  Spark 3.5.1 incorporates [SPARK-46480](https://issues.apache.org/jira/browse/SPARK-46480) which adds a new `isFailed` method to the abstract TaskContext class.  A new MockTaskContextBase shim is used to override this new method on Spark 3.5.1.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by razajafri — APPROVED** [review]

File: tests/src/test/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContext.scala [hunk 1]
```diff
@@ -29,7 +29,7 @@ import org.apache.spark.scheduler.TaskLocality
 import org.apache.spark.shuffle.FetchFailedException
 import org.apache.spark.util.{AccumulatorV2, TaskCompletionListener, TaskFailureListener}
 
-class MockTaskContext(taskAttemptId: Long, partitionId: Int) extends TaskContext {
```
Comment (gerashegalov) [inline tests/src/test/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContext.scala:32]: When there is just a new method that has not been used previously, we do not really have to fork the implementation into two shims as long as we do not insist on using the override keyword.

```Scala
class MockTaskContext(taskAttemptId: Long, partitionId: Int) extends TaskContext {
   def isFailed(): Boolean = false
}
```
