### PR TITLE
Remove the cycle between next() and readBuffersToBatch() in MultiFileCloudPartitionReaderBase

### LINKED ISSUE #14194: [BUG] StackOverflowError MultiFileCloudPartitionReaderBase.readBuffersToBatch
**Describe the bug**

Custom job was failing with StackOverflow exception. They were running on Spark 3.5.3 with Spark Rapids 25.10.1.

It happened on multiple executors, the most useful stack showed the below over and over again... 

```
2026-01-23T14:01:57.96824353Z stderr F  at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1$adapted(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.968246531Z stderr F         at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
2026-01-23T14:01:57.968249437Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.next(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.968254569Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.readBuffersToBatch(GpuMultiFileReader.scala:485)
2026-01-23T14:01:57.968257997Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:700)
2026-01-23T14:01:57.968260801Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1$adapted(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.968263712Z stderr F         at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
2026-01-23T14:01:57.968266549Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.next(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.968269214Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.readBuffersToBatch(GpuMultiFileReader.scala:485)
2026-01-23T14:01:57.968272089Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:700)
2026-01-23T14:01:57.968276859Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1$adapted(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.968279816Z stderr F         at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
2026-01-23T14:01:57.968282853Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.next(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.9682859Z stderr F   at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.readBuffersToBatch(GpuMultiFileReader.scala:485)
2026-01-23T14:01:57.968288768Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:700)
2026-01-23T14:01:57.96829158Z stderr F  at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1$adapted(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.968294508Z stderr F         at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
2026-01-23T14:01:57.96829745Z stderr F  at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.next(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.96830033Z stderr F  at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.readBuffersToBatch(GpuMultiFileReader.scala:485)
2026-01-23T14:01:57.968303333Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:700)
2026-01-23T14:01:57.968306168Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1$adapted(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.9683092Z stderr F   at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
2026-01-23T14:01:57.968312393Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.next(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.968315421Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.readBuffersToBatch(GpuMultiFileReader.scala:485)
2026-01-23T14:01:57.968318595Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:700)
2026-01-23T14:01:57.968321559Z stderr F         at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1$adapted(GpuMultiFileReader.scala:635)
2026-01-23T14:01:57.96832458Z stderr F  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)

```

It looks like the task that got the overflow had a lot of files. The assumption is they are very small or 0 size.  maxPartiitonBytes was set to 2048M for this. This job was running fine with Spark 3.4.1 and Rapids 25.10.1 but its not clear if it was te spark version or if it was unlucky and the data just changed or something.

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by jihoonson**
Fixes #14194 

### Description

There is currently a cycle between `next()` and `readBuffersToBatch()` in `MultiFileCloudPartitionReaderBase` as they can call each other. This is not a good convention as it can cause the stack to grow too large in some cases as reported in https://github.com/NVIDIA/spark-rapids/issues/14194. This PR fixes it so that only `next()` can call `readBuffersToBatch()`. I intentionally did not touch any logic in `MultiFileCloudPartitionReaderBase` besides the call pattern of these functions. The changes can be summarized as

- Removed the `next()` call in `readBuffersToBatch()`.
- Add a while loop with a `continue` flag in `next()` and put the main logic in the while loop.

I manually tested the fix with a TPC-DS customer table at sf=1 with 1000 empty parquet files. The empty parquet files are valid parquet files as it has the valid footer. But they do not have actual data. I verified that a simple query I used runs successfully with this fix, but fails without the fix.

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [ ] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by jihoonson** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala [hunk 1]
```diff
@@ -832,88 +831,90 @@ abstract class MultiFileCloudPartitionReaderBase(
       // submit async tasks if it is not done
       initAndStartReaders()
 
-      if (batchIter.hasNext) {
-        // leave early we have something more to be read
-        return true
-      }
+      // Execute the loop at least one time.
+      var continue = true
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala:835]: please come up with a more meaningful name for this var. It almost sounds it can be while(true)

because continue = false is the end of the loop and the method so we could just return?

**Review by gerashegalov — APPROVED** [review]
LGTM

**Review by nartal1 — APPROVED** [review]
LGTM

**Review by liurenjie1024 — APPROVED** [review]
LGTM

**Comment by jihoonson** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala (hunk 1 above)
Comment (jihoonson) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala:835]: I'm surprised that this can be confusing. It seems quite obvious to me that this flag is the condition to control the while loop, and thus there should be an end condition to exit the loop. This is a third person's perspective as this code is written by the claude code not by me. Though I can rename it in some follow-up PR if this is confusing to you.

> because continue = false is the end of the loop and the method so we could just return?

`continue = false` is the end of the loop but not the end of the method.

Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala:835]: it is obvious but it resembles the Java/C reserved word, without conveying the intent of what to be continued. 

Not looking  at it in the IDE but Isn't the loop the last block of the method, and if you set continuer to false we are exiting the method ?

Comment (jihoonson) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala:835]: It evaluates `batchIter.hasNext` after the loop exits and returns the result.

**Comment by jihoonson** [comment]
@gerashegalov @nartal1 @liurenjie1024 thanks for the quick review
