### PR TITLE
Fix degenerate conditional nested loop join detection [databricks]

### LINKED ISSUE #11266: [BUG] test_broadcast_hash_join_constant_keys failed in databricks runtimes
**Describe the bug**
new case was added in https://github.com/NVIDIA/spark-rapids/pull/11244.

failed in all DB runtimes(11,12,13)

```
[2024-07-27T09:30:47.296Z] FAILED ../../src/main/python/join_test.py::test_broadcast_hash_join_constant_keys[Left][DATAGEN_SEED=1722066549, TZ=UTC] - py4j.protocol.Py4JJavaError: An error occurred while calling o324822.count.
[2024-07-27T09:30:47.296Z] FAILED ../../src/main/python/join_test.py::test_broadcast_hash_join_constant_keys[LeftAnti][DATAGEN_SEED=1722066549, TZ=UTC] - py4j.protocol.Py4JJavaError: An error occurred while calling o325323.count.
```

```
[2024-07-27T09:30:47.283Z] E                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6633.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6633.0 (TID 19790) (ip-10-59-241-231.us-west-2.compute.internal executor driver): java.lang.AssertionError: ColumnVectors can't be null or empty
[2024-07-27T09:30:47.283Z] E                   	at ai.rapids.cudf.Table.<init>(Table.java:57)
[2024-07-27T09:30:47.283Z] E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:524)
[2024-07-27T09:30:47.283Z] E                   	at org.apache.spark.sql.rapids.execution.ConditionalNestedLoopJoinIterator.$anonfun$computeNumJoinRows$2(GpuBroadcastNestedLoopJoinExecBase.scala:226)
[2024-07-27T09:30:47.283Z] E                   	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[2024-07-27T09:30:47.283Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRestoreOnRetry(RmmRapidsRetryIterator.scala:272)
[2024-07-27T09:30:47.283Z] E                   	at org.apache.spark.sql.rapids.execution.ConditionalNestedLoopJoinIterator.$anonfun$computeNumJoinRows$1(GpuBroadcastNestedLoopJoinExecBase.scala:226)
[2024-07-27T09:30:47.283Z] E                   	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$NoInputSpliterator.next(RmmRapidsRetryIterator.scala:395)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:613)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:517)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.drainSingleWithVerification(RmmRapidsRetryIterator.scala:291)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRetryNoSplit(RmmRapidsRetryIterator.scala:185)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.sql.rapids.execution.ConditionalNestedLoopJoinIterator.computeNumJoinRows(GpuBroadcastNestedLoopJoinExecBase.scala:225)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.SplittableJoinIterator.$anonfun$setupNextGatherer$2(AbstractGpuJoinIterator.scala:226)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.SplittableJoinIterator.$anonfun$setupNextGatherer$1(AbstractGpuJoinIterator.scala:225)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.GpuMetric.ns(GpuExec.scala:184)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.SplittableJoinIterator.setupNextGatherer(AbstractGpuJoinIterator.scala:225)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.AbstractGpuJoinIterator.hasNext(AbstractGpuJoinIterator.scala:102)
[2024-07-27T09:30:47.284Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.AbstractProjectSplitIterator.hasNext(basicPhysicalOperators.scala:233)
[2024-07-27T09:30:47.284Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.284Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.284Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.284Z] E                   	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
[2024-07-27T09:30:47.284Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.$anonfun$next$2(GpuAggregateExec.scala:766)
[2024-07-27T09:30:47.284Z] E                   	at scala.Option.getOrElse(Option.scala:189)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:762)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:718)
[2024-07-27T09:30:47.284Z] E                   	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.$anonfun$next$10(GpuAggregateExec.scala:2124)
[2024-07-27T09:30:47.284Z] E                   	at scala.Option.map(Option.scala:230)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(GpuAggregateExec.scala:2124)
[2024-07-27T09:30:47.284Z] E                   	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(GpuAggregateExec.scala:1975)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:333)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:355)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:151)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$3(ShuffleMapTask.scala:81)
[2024-07-27T09:30:47.284Z] E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$1(ShuffleMapTask.scala:81)
[2024-07-27T09:30:47.284Z] E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:174)
[2024-07-27T09:30:47.284Z] E                   	at org.apache.spark.scheduler.Task.$anonfun$run$4(Task.scala:137)
[2024-07-27T09:30:47.284Z] E                   	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:126)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:137)
[2024-07-27T09:30:47.285Z] E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.Task.run(Task.scala:96)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:902)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1697)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:905)
[2024-07-27T09:30:47.285Z] E                   	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-07-27T09:30:47.285Z] E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:760)
[2024-07-27T09:30:47.285Z] E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2024-07-27T09:30:47.285Z] E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2024-07-27T09:30:47.285Z] E                   	at java.lang.Thread.run(Thread.java:750)
[2024-07-27T09:30:47.285Z] E                   
[2024-07-27T09:30:47.285Z] E                   Driver stacktrace:
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3420)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3342)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3331)
[2024-07-27T09:30:47.285Z] E                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2024-07-27T09:30:47.285Z] E                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2024-07-27T09:30:47.285Z] E                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3331)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1439)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1439)
[2024-07-27T09:30:47.285Z] E                   	at scala.Option.foreach(Option.scala:407)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1439)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3631)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3569)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3557)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:51)
[2024-07-27T09:30:47.285Z] E                   Caused by: java.lang.AssertionError: ColumnVectors can't be null or empty
[2024-07-27T09:30:47.285Z] E                   	at ai.rapids.cudf.Table.<init>(Table.java:57)
[2024-07-27T09:30:47.285Z] E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:524)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.sql.rapids.execution.ConditionalNestedLoopJoinIterator.$anonfun$computeNumJoinRows$2(GpuBroadcastNestedLoopJoinExecBase.scala:226)
[2024-07-27T09:30:47.285Z] E                   	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[2024-07-27T09:30:47.285Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRestoreOnRetry(RmmRapidsRetryIterator.scala:272)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.sql.rapids.execution.ConditionalNestedLoopJoinIterator.$anonfun$computeNumJoinRows$1(GpuBroadcastNestedLoopJoinExecBase.scala:226)
[2024-07-27T09:30:47.285Z] E                   	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[2024-07-27T09:30:47.285Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$NoInputSpliterator.next(RmmRapidsRetryIterator.scala:395)
[2024-07-27T09:30:47.285Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:613)
[2024-07-27T09:30:47.285Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:517)
[2024-07-27T09:30:47.285Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.drainSingleWithVerification(RmmRapidsRetryIterator.scala:291)
[2024-07-27T09:30:47.285Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRetryNoSplit(RmmRapidsRetryIterator.scala:185)
[2024-07-27T09:30:47.285Z] E                   	at org.apache.spark.sql.rapids.execution.ConditionalNestedLoopJoinIterator.computeNumJoinRows(GpuBroadcastNestedLoopJoinExecBase.scala:225)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.SplittableJoinIterator.$anonfun$setupNextGatherer$2(AbstractGpuJoinIterator.scala:226)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.SplittableJoinIterator.$anonfun$setupNextGatherer$1(AbstractGpuJoinIterator.scala:225)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.GpuMetric.ns(GpuExec.scala:184)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.SplittableJoinIterator.setupNextGatherer(AbstractGpuJoinIterator.scala:225)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.AbstractGpuJoinIterator.hasNext(AbstractGpuJoinIterator.scala:102)
[2024-07-27T09:30:47.286Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.AbstractProjectSplitIterator.hasNext(basicPhysicalOperators.scala:233)
[2024-07-27T09:30:47.286Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.286Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.286Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.286Z] E                   	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
[2024-07-27T09:30:47.286Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.$anonfun$next$2(GpuAggregateExec.scala:766)
[2024-07-27T09:30:47.286Z] E                   	at scala.Option.getOrElse(Option.scala:189)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:762)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:718)
[2024-07-27T09:30:47.286Z] E                   	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.$anonfun$next$10(GpuAggregateExec.scala:2124)
[2024-07-27T09:30:47.286Z] E                   	at scala.Option.map(Option.scala:230)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(GpuAggregateExec.scala:2124)
[2024-07-27T09:30:47.286Z] E                   	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(GpuAggregateExec.scala:1975)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:333)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:355)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:151)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$3(ShuffleMapTask.scala:81)
[2024-07-27T09:30:47.286Z] E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$1(ShuffleMapTask.scala:81)
[2024-07-27T09:30:47.286Z] E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:174)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.scheduler.Task.$anonfun$run$4(Task.scala:137)
[2024-07-27T09:30:47.286Z] E                   	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:126)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:137)
[2024-07-27T09:30:47.286Z] E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.scheduler.Task.run(Task.scala:96)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:902)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1697)
[2024-07-27T09:30:47.286Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:905)
[2024-07-27T09:30:47.286Z] E                   	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-07-27T09:30:47.286Z] E                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-07-27T09:30:47.287Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:760)
[2024-07-27T09:30:47.287Z] E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2024-07-27T09:30:47.287Z] E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2024-07-27T09:30:47.287Z] E                   	at java.lang.Thread.run(Thread.java:750)
```

**Steps/Code to reproduce bug**
run the case in DB runtimes.

**Expected behavior**
Pass the test

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #11266.  The failure on Databricks is because the aggregate was pushed through the join, which resulted in a non-empty output from the join. The fix from #11244 was flawed in that it detected unconditional joins if the condition was true _and_ the output is empty (i.e.: a row-count-only join), but this last condition isn't necessary.  Nested loop joins are unconditional joins if the join condition is always true regardless of the outputs being produced by the join.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by kuhushukla — DISMISSED** [review]

**Review by revans2 — DISMISSED** [review]

**Comment by jlowe** [comment]
CI failed in test_right_broadcast_nested_loop_join_without_condition_empty, which exposed that we were not properly handling empty build-side batches in unconditional nested outer loop joins.  Previously we hacked around it by adding an always-true condition, but this adds support for it and removes the hack.

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala [hunk 1]
```diff
@@ -664,13 +655,23 @@ abstract class GpuBroadcastNestedLoopJoinExecBase(
...
-            new CrossJoinIterator(
-              spillableBuiltBatch,
-              lazyStream,
-              targetSizeBytes,
-              buildSide,
-              opTime = opTime,
-              joinTime = joinTime)
+
+            localJoinType match {
+              case LeftOuter if spillableBuiltBatch.numRows == 0 =>
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala:660]: Do we need to worry about a full outer join?

Comment (jlowe) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala:660]: In the future yes, but we do not support FullOuter joins for broadcasted nested loop joins.  Support for that is s tracked by #3269.

**Review by revans2 — APPROVED** [review]

**Review by kuhushukla — APPROVED** [review]

**Comment by jlowe** [comment]
CI failure appears to be related to rapidsai/cudf#16426.

**Comment by jlowe** [comment]
build

**Comment by pxLi** [comment]
some regex cases (https://github.com/NVIDIA/spark-rapids/blob/branch-24.08/jenkins/spark-premerge-build.sh#L223-L224) seems to be hanging there forever in scala213 CI, like
```
test_regexp_replace[DATAGEN_SEED=1722297411, TZ=UTC]
```


executor stop producing any further logs,
```
[INFO] 2024-07-29 23:57:06,351 org.sparkproject.jetty.util.log initialized - Logging initialized @13791ms to org.sparkproject.jetty.util.log.Slf4jLog
2024-07-29 23:57:11 INFO     Running test 'src/main/python/regexp_test.py::test_split_regexp_disabled_fallback[DATAGEN_SEED=1722297411, TZ=UTC, INJECT_OOM, ALLOW_NON_GPU(ProjectExec,StringSplit)]'
[WARN] 2024-07-29 23:57:17,340 com.nvidia.spark.rapids.GpuOverrides logWarning - 
!Exec <ProjectExec> cannot run on GPU because not all expressions can be replaced
  @Expression <Alias> split(a#16, [:], 2) AS split(a, [:], 2)#18 could run on GPU
    !Expression <StringSplit> split(a#16, [:], 2) cannot run on GPU because regular expression support is disabled. Set spark.rapids.sql.regexp.enabled=true to enable it
      @Expression <AttributeReference> a#16 could run on GPU
      @Expression <Literal> [:] could run on GPU
      @Expression <Literal> 2 could run on GPU
  @Expression <Alias> split(a#16, [o:], 5) AS split(a, [o:], 5)#19 could run on GPU
    !Expression <StringSplit> split(a#16, [o:], 5) cannot run on GPU because regular expression support is disabled. Set spark.rapids.sql.regexp.enabled=true to enable it
      @Expression <AttributeReference> a#16 could run on GPU
      @Expression <Literal> [o:] could run on GPU
      @Expression <Literal> 5 could run on GPU
  @Expression <Alias> split(a#16, [^:], 2) AS split(a, [^:], 2)#20 could run on GPU
    !Expression <StringSplit> split(a#16, [^:], 2) cannot run on GPU because regular expression support is disabled. Set spark.rapids.sql.regexp.enabled=true to enable it
      @Expression <AttributeReference> a#16 could run on GPU
      @Expression <Literal> [^:] could run on GPU
      @Expression <Literal> 2 could run on GPU
  @Expression <Alias> split(a#16, [^o], 55) AS split(a, [^o], 55)#21 could run on GPU
    !Expression <StringSplit> split(a#16, [^o], 55) cannot run on GPU because regular expression support is disabled. Set spark.rapids.sql.regexp.enabled=true to enable it
      @Expression <AttributeReference> a#16 could run on GPU
      @Expression <Literal> [^o] could run on GPU
      @Expression <Literal> 55 could run on GPU
  @Expression <Alias> split(a#16, [o]{1,2}, 999) AS split(a, [o]{1,2}, 999)#22 could run on GPU
    !Expression <StringSplit> split(a#16, [o]{1,2}, 999) cannot run on GPU because regular expression support is disabled. Set spark.rapids.sql.regexp.enabled=true to enable it
      @Expression <AttributeReference> a#16 could run on GPU
      @Expression <Literal> [o]{1,2} could run on GPU
      @Expression <Literal> 999 could run on GPU
  @Expression <Alias> split(a#16, [bf], 2) AS split(a, [bf], 2)#23 could run on GPU
    !Expression <StringSplit> split(a#16, [bf], 2) cannot run on GPU because regular expression support is disabled. Set spark.rapids.sql.regexp.enabled=true to enable it
      @Expression <AttributeReference> a#16 could run on GPU
      @Expression <Literal> [bf] could run on GPU
      @Expression <Literal> 2 could run on GPU
  @Expression <Alias> split(a#16, [o], 5) AS split(a, [o], 5)#24 could run on GPU
    !Expression <StringSplit> split(a#16, [o], 5) cannot run on GPU because regular expression support is disabled. Set spark.rapids.sql.regexp.enabled=true to enable it
      @Expression <AttributeReference> a#16 could run on GPU
      @Expression <Literal> [o] could run on GPU
      @Expression <Literal> 5 could run on GPU
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> a#16 could run on GPU

2024-07-29 23:57:17 INFO     Running test 'src/main/python/regexp_test.py::test_split_escaped_chars_in_character_class[DATAGEN_SEED=1722297411, TZ=UTC]'
[WARN] 2024-07-29 23:57:18,967 com.nvidia.spark.rapids.GpuOverrides logWarning - 
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> a#48 could run on GPU

2024-07-29 23:57:19 INFO     Running test 'src/main/python/regexp_test.py::test_regexp_replace[DATAGEN_SEED=1722297411, TZ=UTC]'
[WARN] 2024-07-29 23:57:20,955 com.nvidia.spark.rapids.GpuOverrides logWarning - 
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> a#76 could run on GPU
```

**Comment by pxLi** [comment]
As the above is the last case of CI, and it cannot be reproduced locally.
filed https://github.com/NVIDIA/spark-rapids/issues/11270 to track

Im going to merge this to unblock other changes, thanks
