### PR TITLE
Exception in SQLParser should not cause Qualification tool to skip app

### LINKED ISSUE #7044: [BUG] Qualification tool skips applications due to failure in expression parsing
**Describe the bug**
When running Qualification tool on Spark2.x eventlogs, it was found that the Qualification tool skips the application analysis when expression parser triggers an exception.
This means that all applications with usupported format won't be processed by the tool which is inconvenient for users who are willing to migrate from Spark2.x to Spark3.x

**Expected behavior**
I suggest that parser skips the expression that triggers the exception, then continue processing the app normally after displaying a warning/error messages to the log file.

Although we cannot reproduce the same failure on our side, the Qualification tool should not skip the entire application due an error in one of the expressions because:
- It is expected that different spark releases might change the expression format in the log.
- It is possible that the parser does not fully cover the expression formats.

**Additional context**

the error below is due to a missing match-case for “||” in [SQLPlanParser-line-436](https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala#L436) ; but the parser checks for  “OR”.

```
22/11/09 17:16:39 WARN com.nvidia.spark.rapids.tool.qualification.Qualification: Unexpected exception processing log gs://gcp_bucket_path/logss/application_1667271647355_0001_1.lz4, skipping!
scala.MatchError: || (of class java.lang.String)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.$anonfun$parseFilterExpressions$7(SQLPlanParser.scala:436)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parseFilterExpressions(SQLPlanParser.scala:413)
	at com.nvidia.spark.rapids.tool.planparser.FilterExecParser.parse(FilterExecParser.scala:34)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parsePlanNode(SQLPlanParser.scala:140)
	at com.nvidia.spark.rapids.tool.planparser.WholeStageExecParser.$anonfun$parse$3(WholeStageExecParser.scala:43)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.nvidia.spark.rapids.tool.planparser.WholeStageExecParser.parse(WholeStageExecParser.scala:42)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parsePlanNode(SQLPlanParser.scala:103)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.$anonfun$parseSQLPlan$1(SQLPlanParser.scala:80)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parseSQLPlan(SQLPlanParser.scala:79)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.$anonfun$aggregateStats$6(QualificationAppInfo.scala:354)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.$anonfun$aggregateStats$1(QualificationAppInfo.scala:352)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.aggregateStats(QualificationAppInfo.scala:332)
	at com.nvidia.spark.rapids.tool.qualification.Qualification.com$nvidia$spark$rapids$tool$qualification$Qualification$$qualifyApp(Qualification.scala:126)
	at com.nvidia.spark.rapids.tool.qualification.Qualification$QualifyThread.run(Qualification.scala:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### PR DESCRIPTION
**Pull request by amahussein**
Signed-off-by: Ahmed Hussein (amahussein) <a@ahussein.me>

fixes #7044 

This PR is to add try/catch around the block that constructs the execs-Info of an existing sql plan node.
The purpose is to allow users to get an approximate estimation even if the parser hits an unexpected scenario.

- A new unit test is added that checks that parsing faulty eventlog does not break the entire analysis.
- If an exec fails, then it is considered unsupported and a warning message showing the original exception.

### CODE REVIEW

**Comment by amahussein** [comment]
build

**Comment by amahussein** [comment]
build

File: tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala [hunk 1]
```diff
@@ -108,88 +108,103 @@ object SQLPlanParser extends Logging {
...
+        // the application will be skipped. We need to suppress exceptions here to avoid
+        // sacrificing the entire app analysis.
+        // Note that:
+        //  - The exec will be considered unsupported.
+        //  - No need to add the SQL to the failed SQLs, because this will cause the app to be
+        //    labeled as "Not Applicable" which is not preferred at this point.
+        case e: Throwable =>
+          logWarning(s"Unexpected error parsing plan node ${node.name}. " +
+          s" sqlID = ${sqlID}", e)
           new ExecInfo(sqlID, node.name, expr = "", 1, duration = None, node.id,
```
Comment (tgravescs) [inline tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala:208]: it would be nice to record that there was an error parsing this in the output so we can figure out why something we would possibly support shows up as not supported. I guess it would be nice to know that for the other things we parsed as well. like was this something we really didn't support vs we just haven't implemented the parsing of in the tool yet.  I'm fine with doing this separately to get this change in but can you file an issue for it?

File: tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala [hunk 2]
```diff
@@ -108,88 +108,103 @@ object SQLPlanParser extends Logging {
...
+        }
+      } catch {
+        // Error parsing expression could trigger an exception. If the exception is not handled,
+        // the application will be skipped. We need to suppress exceptions here to avoid
+        // sacrificing the entire app analysis.
+        // Note that:
+        //  - The exec will be considered unsupported.
+        //  - No need to add the SQL to the failed SQLs, because this will cause the app to be
+        //    labeled as "Not Applicable" which is not preferred at this point.
+        case e: Throwable =>
```
Comment (gerashegalov) [inline tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala:205]:
```suggestion
        case NonFatal(e) =>
```

Comment (amahussein) [reply tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala]: I was not aware of `NonFatal` in scala.
Thanks @gerashegalov !

File: tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala (hunk 1 above)
Comment (amahussein) [reply tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala:209]: Thanks @tgravescs 
I filed a new issue #7072 to address this since this requires to change all the children classes of `ExecParser`.

**Comment by amahussein** [comment]
build

File: tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala [hunk 3]
```diff
@@ -94,6 +97,49 @@ class SQLPlanParserSuite extends FunSuite with BeforeAndAfterEach with Logging {
...
 
+  test("Error parser does not cause entire app to fail") {
+    // The purpose of this test is to make sure that the SQLParser won't trigger an exception that
+    // causes the entire app analysis to fail.
+    // In order to simulate unexpected scenarios, the eventlog sqlparse_failure is injected with
+    // faulty expressions.
+    // For example:
+    //    Filter (((value#8 <> 100) AND (value#8 > 50)) OR (value#8 = 0))
+    //    One of the predicates is converted from "<" to "<>".
+    //    The latter is an invalid predicate causing the parser to throw a scala-match error.
```
Comment (gerashegalov) [inline tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala:108]: Can we do this corruption on the fly in a temp directory with some existing event log without adding another 82+KB binary resource ?

Comment (amahussein) [reply tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala:108]: Given the priorities of the task, I don't have a quick solution to inject faulty events in this PR.
I agree that we need something better.
One way is to extend `ToolTestUtils.generateEventLog` to give more control on the generated eventlog.
The other way which I prefer not to do is to alter the eventlog as a text file.

Comment (amahussein) [reply tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala:112]: Removed the eventlog files and used on-the-fly injection

**Comment by amahussein** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM
