### PR TITLE
Refine split-retry logs to expose the real reason

### LINKED ISSUE #12351: [BUG] CudfColumnSizeOverflowException could cause misleading logs
**Describe the bug**
When CudfColumnSizeOverflowException is thrown, the plugin will try to split the current batch and retry.
However, if it's currently in a WithRetryNoSplit, then the plugin will throw exception with message like this: "com.nvidia.spark.rapids.jni.CpuSplitAndRetryOOM: CPU OutOfMemory: could not split inputs and retry", which sometimes quite misleading because CPU memory shortage is not the root cause for now. 

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by binmahone**
This PR closes #12351

### CODE REVIEW

**Comment by binmahone** [comment]
build

**Comment by binmahone** [comment]
build

**Comment by firestarman** [comment]
Title and description are both truncated ?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala [hunk 1]
```diff
@@ -621,7 +627,8 @@ object RmmRapidsRetryIterator extends Logging {
       var lastException: Throwable = null
       var firstAttempt: Boolean = true
       var result: Option[K] = None
-      var doSplit = false
+      var doSplitForStateMachineReasons = false
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:630]: Could here use a single variable of SplitReason instead ? I think this will make this change smaller.
`var splitReason = SplitReason.NONE`, and trigger split when it is not a NONE.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala [hunk 2]
```diff
@@ -872,3 +900,8 @@ object RetryStateTracker {
 
   def clearCurThreadRetrying(): Unit = localIsRetrying.remove()
 }
+
+object SplitReason extends Enumeration {
+  type SplitReason = Value
+  val GPU_OOM, CPU_OOM, OTHER = Value
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:906]: Since we know the exact reason as "ColumnSizeOverflow", why name it as OTHER ?

Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:906]: this is in case in the future we'll have other special exceptions besides ColumnSizeOverflow

**Comment by binmahone** [comment]
> Title and description are both truncated ?

I think the title is truncated. Do we have a mandatory requirement to keep the title short?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 1 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:630]: but the idea of NONE might be confusing for cases where it is actually able to split. 

We are more thinking about withRetryNoSplit case, but there're also cases where ColumnSizeOverflow can be handled by split and retry, in a withRetry context

Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:630]: I mean we can have ,for example `GPU_OOM, CPU_OOM, COLUMN_OVER_FLOW, NONE`.
`NONE` here just is for the initial value, like false for a boolean.
Then we re-assign splitReason to other values accordingly, and trigger split when it is not NONE.

`doSplitForStateMachineReasons = true` can be replaced by `splitReason =GPU_OOM ` or `splitReason =CPU_OOM `.
While `splitReason=COLUMN_OVER_FLOW` is for `doSplitForNonStateMachineReasons = true`.

Two boolean variables can represent 4 states, so let splitReason have 4 values respectively.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala [hunk 3]
```diff
@@ -474,10 +478,12 @@ object RmmRapidsRetryIterator extends Logging {
...
           s"{${attemptStack.head}}"
-        if (isFromGpuOom) {
-          throw new GpuSplitAndRetryOOM(s"GPU OutOfMemory: $message")
-        } else {
-          throw new CpuSplitAndRetryOOM(s"CPU OutOfMemory: $message")
+        splitReason match {
+          case SplitReason.GPU_OOM => throw new GpuSplitAndRetryOOM(s"GPU OutOfMemory: $message")
+          case SplitReason.CPU_OOM => throw new CpuSplitAndRetryOOM(s"CPU OutOfMemory: $message")
+          case SplitReason.OTHER =>
+            throw new IllegalStateException("Non OOM State Machine reason caused split," +
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:485]: I think the specific reason ("Column overflow") would be better than just "Non OOM State Machine reason". And many users are likely to not know "State Machine". Better not mention it.
  @GaryShen2008 Any input for this message.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 2 above)
Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:906]: Good point, then we can have more SplitReason values to map them.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 1 above)
Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:630]: I may miss something, however 3 variables here are more error-prone than a single one. And I am still not fully get the relationship among them.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 2 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:906]: I'm not sure if we want so many states. To me, "Other" is a good enough category to include all kinds of future exceptions. If we as a troubleshooter wants to know what is happening, we may need to take a look at the log printed by https://github.com/NVIDIA/spark-rapids/pull/12352/files#diff-06c3cea1c7b935018328547859836a21d3b935b3c80da6e05f09f455abe043a6R697

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 3 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:485]: neither will they understand "CUDF overflow" or even "split and retry", it's just some useful information to the troubleshooter with domain knowledge.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 1 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:630]: same with in other thread,  I'm not sure if we want so many enums

Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:630]: what do you mean by 3 variables ?

Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:630]: i'll try to add some modifications to reduce variable num

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 3 above)
Comment (GaryShen2008) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:485]: Column overflow seems just one of the cases, not the only one case. Am I right?
If so, we can't just say the column overflow.

Here I think it's ok if we can't know the exact reason caused split. If we have multiple cases caused the exception here, we'd better to log it more clear.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 1 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala]: hi @firestarman  thx for the adivse, I have reduced the number of variables

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 3 above)
Comment (binmahone) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:485]: yes, the detail of the exception is logged a bit earlier. @GaryShen2008

**Comment by binmahone** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 2 above)
Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala]: I am OK with OTHER if other guys agreee with it.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala (hunk 3 above)
Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:485]: I am OK with OTHER if other guys agree with it.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala [hunk 4]
```diff
@@ -397,11 +397,15 @@ object RmmRapidsRetryIterator extends Logging {
...
-        throw new GpuSplitAndRetryOOM("GPU OutOfMemory: could not split inputs and retry")
-      } else {
-        throw new CpuSplitAndRetryOOM("CPU OutOfMemory: could not split inputs and retry")
+    override def split(splitReason: SplitReason): Unit = {
+      splitReason match {
+        case SplitReason.CPU_OOM =>
+          throw new CpuSplitAndRetryOOM("CPU OutOfMemory: could not split inputs and retry")
+        case SplitReason.GPU_OOM =>
+          throw new GpuSplitAndRetryOOM("GPU OutOfMemory: could not split inputs and retry")
+        case SplitReason.OTHER =>
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala:406]: I wish we called this just `SplitReason.CUDF_ROW_LIMIT`, instead of `OTHER`.

**Comment by binmahone** [comment]
build

**Comment by binmahone** [comment]
looks like everyone like more specific Split Code. I've changed accordingly, pls check again @abellina @firestarman

**Review by abellina — APPROVED** [review]
LGTM
