### PR TITLE
Fix the failure of `test_array_element_at_zero_index_fail` on Spark3.4 [databricks]

### LINKED ISSUE #7066: [SPARK-39432][BUG] The test `test_array_element_at_zero_index_fail` fails on Spark 3.4
**Describe the bug**
The test `test_array_element_at_zero_index_fail` fails on Spark 3.4.
Related Spark ticket: https://issues.apache.org/jira/browse/SPARK-39432

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.
```bash
./run_pyspark_from_build.sh -k array_test.py
```

**Expected behavior**
The test should pass.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>
Closes #7066.

## Changes in the PR
Add `sqlArrayIndexNotStartAtOneError()` in the `RapidsErrorUitls` of Spark 3.4, which is a wrapper of the function `ElementAtByIndexZeroError`. 
Undate the return type of `sqlArrayIndexNotStartAtOneError` to be `RuntimeException`, so that we can unify the return type of `ElementAtByIndexZeroError`.

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

File: sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala [hunk 1]
```diff
@@ -36,10 +36,6 @@ object RapidsErrorUtils {
     new NoSuchElementException(s"Key $key does not exist.")
   }
 
-  def sqlArrayIndexNotStartAtOneError(): ArrayIndexOutOfBoundsException = {
```
Comment (jlowe) [inline sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:39]: This seems backwards to me.  IIUC Spark 3.4 decided to fold this exception into another, existing exception.  Since our code base isn't focused on 3.4, it seems odd we're bending all the other Spark's to the 3.4 convention rather than keeping the existing error method and having the 3.4 shim map the `sqlArrayIndexNotStartAtOneError()` to  `QueryExecutionErrors.elementAtByIndexZeroError(context = null)`.  Seems like that would be a lot less change overall and make the calling code more closely match all other Spark versions (except 3.4).

Comment (HaoYang670) [reply sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:39]: >  a lot less change overall and make the calling code more closely match all other Spark versions (except 3.4).

This makes sense, thank you. I will update.

Comment (HaoYang670) [reply sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:39]: Updated.

**Comment by HaoYang670** [comment]
build

**Comment by jlowe** [comment]
And now this is going to get committed with a commit message of "address comments" which is a bit less than ideal.

**Review by jlowe — DISMISSED** [review]
Changes look OK, but it would be nice to fix the unhelpful commit message on the sole commit in this PR.  Yes, that requires a force-push at this point. 😞

**Comment by HaoYang670** [comment]
Thank you @jlowe, I'll pay attention next time.

**Comment by HaoYang670** [comment]
build

**Comment by HaoYang670** [comment]
build

**Comment by HaoYang670** [comment]
build

**Review by jlowe — APPROVED** [review]
