### PR TITLE
Export TZ in tests when default TZ is used

### LINKED ISSUE #10411: [BUG] Some fast parquet tests fail if the time zone is not UTC
**Describe the bug**
```
FAILED ../../src/main/python/fastparquet_compatibility_test.py::test_reading_file_written_by_spark_cpu[Timestamp(not_null)0][DATAGEN_SEED=0, INJECT_OOM] - AssertionError: GPU and CPU int values are different at [0, 'a']
FAILED ../../src/main/python/fastparquet_compatibility_test.py::test_reading_file_written_with_gpu[Timestamp(not_null)0][DATAGEN_SEED=0, INJECT_OOM] - AssertionError: GPU and CPU int values are different at [0, 'a']
```

```
SPARK_HOME=~/src/spark_3.4.2/ TEST_PARALLEL=0 DATAGEN_SEED=0 ./run_pyspark_from_build.sh -k 'test_reading_file_written_with_gpu or test_reading_file_written_by_spark_cpu'
```

Note that I am running on a computer with the timezone configured to 'America/Chicago' , but TZ itself is not set to anything.

```
$echo $TZ

```

If I set to `TZ='UTC'` or TZ='America/Chicago' then it works just fine, so I think this is a bug in how our test code detects time zones.  It is probably really minor.

### PR DESCRIPTION
**Pull request by revans2**
This fixes #10411 

Looks like we just needed to export the TZ so it properly took effect everywhere.

### CODE REVIEW

**Comment by revans2** [comment]
build

File: integration_tests/run_pyspark_from_build.sh [hunk 1]
```diff
@@ -224,7 +224,7 @@ else
     fi
 
     # time zone will be tested; use export TZ=time_zone_name before run this script
-    TZ=${TZ:-UTC}
+    export TZ=${TZ:-UTC}
```
Comment (gerashegalov) [inline integration_tests/run_pyspark_from_build.sh:227]: Are we possibly just sweeping under the rug that TZ is not properly translated / propagated to spark properties?  https://github.com/NVIDIA/spark-rapids/pull/10419/files#diff-146d61aa008bf60d3c970d1d76208d85b87070466a6d6021fa63eb7478037a27R234-R237

Comment (revans2) [reply integration_tests/run_pyspark_from_build.sh:227]: The issue here is a disconnect between Spark and python. It is not that we are setting the timezone incorrectly for Spark. Nor is it technically a problem with the tests detecting what we set it to.

https://github.com/NVIDIA/spark-rapids/blob/28bb2b470e097aa4285f13bb4a9b4f361f387f6a/integration_tests/src/main/python/conftest.py#L84-L91

The problem is that if we don't export `TZ` python does not pick up on it and gets the wrong time zone compared to what we told Spark to use. The following patch shows this.

```diff
diff --git a/integration_tests/src/main/python/conftest.py b/integration_tests/src/main/python/conftest.py
index 8251f4b91..85234035c 100644
--- a/integration_tests/src/main/python/conftest.py
+++ b/integration_tests/src/main/python/conftest.py
@@ -82,7 +82,11 @@ def is_dataproc_runtime():
     return runtime_env() == "dataproc"
 
 def get_test_tz():
-    return os.environ.get('TZ', 'UTC')
+    tz = os.environ.get('TZ', 'UTC')
+    print("TIME ZONE IS " + tz + " !!!!!!")
+    import datetime
+    print(datetime.datetime.now(datetime.timezone.utc).astimezone().tzinfo)
+    return tz
 
 def is_utc():
     return get_test_tz() == "UTC"
```

Without this fix the results show a disconnect and fastparquet is trying to normalize the timestamps differently than Spark is.
```
TIME ZONE IS UTC !!!!!!
CST
```

With this fix the results are now in sync
```
TIME ZONE IS UTC !!!!!!
UTC
```

If there is no export `TZ` ends up not being set for the python process which then falls back to the defaults (UTC for the test detection and whatever the real timezone is for the rest of python).  Most of the time pyspark handles converting timestamps between time zones as it goes back and forth between the JVM and python. But fastparquet does not have any of that so when the tests say that it is UTC, but python says it is not we end up with a disconnect and we get the wrong answer/don't skip the test when we should.

Comment (gerashegalov) [reply integration_tests/run_pyspark_from_build.sh:227]: Thanks for the explanation, this makes sense

**Review by gerashegalov — APPROVED** [review]
LGTM
