### PR TITLE
Test parquet predicate pushdown for basic types and fields having dots in names [databricks]

### LINKED ISSUE #9094: Add test to verify Parquet predicate pushdown for fields having dots in the names
https://github.com/apache/spark/blob/v3.4.1/sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilterSuite.scala#L1481

### LINKED ISSUE #9127: [Test] Test predicate pushdown (PPD) with timestamps, decimals, booleans, etc for Parquet file
**Describe the bug**
Test all types for the PPD for Paruqet.
Scenarios:
CPU write / GPU read
GPU write / GPU read
GPU write / CPU read

### PR DESCRIPTION
**Pull request by thirtiseven**
Closes #9127
Closes #9094 

This PR adds some tests to test parquet predicate pushdown for basic types and fields with dots in names. And also a follow on to orc's ppd test, using `assume' instead of commenting out failed cases.

For PPD testing, these cases are tested:
- CPU write GPU read, GPU write CPU read, and GPU write GPU read.
- Range partitioning on write and predicate is out of DataFrame range, if applicable.
- Data source V1 and V2.

Some contexts: #9119

### CODE REVIEW

**Comment by thirtiseven** [comment]
build

File: tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala [hunk 1]
```diff
@@ -0,0 +1,262 @@
...
+  }
+
+  def testRangePartitioningPpd(spark: SparkSession, writeDf: DataFrame,
+      partCol: String, predicate: Column, length: Int)(
+      writeGpu: Boolean, readGpu: Boolean): Unit = {
+    withAllParquetReaders {
+      withTempPath { path =>
+        withSQLConf(
+          SQLConf.PARQUET_OUTPUT_TIMESTAMP_TYPE.key -> "TIMESTAMP_MICROS",
+          "spark.rapids.sql.test.enabled" -> "false",
```
Comment (res-life) [inline tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala:79]:
```scala
 val TEST_CONF = conf("spark.rapids.sql.test.enabled")
    .doc("Intended to be used by unit tests, if enabled all operations must run on the " +
      "GPU or an error happens.")
    .internal()
    .booleanConf
    .createWithDefault(false)
```
If enable GPU, we should set this as true. Or we may enconter this kind of case: 
The test passed, but it's running on CPU silently, and we expect it's running on GPU.

Changes would like:

```scala
if (writeGpu || readGpu) {
  spark.rapids.sql.test.enabled = true
}
```

**Comment by res-life** [comment]
I also notice that [ParquetFilterSuite](
https://github.com/apache/spark/blob/v3.4.1/sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilterSuite.scala) has testing for the following operators: 
```
      checkFilterPredicate(intAttr === 1, classOf[Eq[_]], resultFun(1))
      checkFilterPredicate(intAttr <=> 1, classOf[Eq[_]], resultFun(1))
      checkFilterPredicate(intAttr =!= 1, classOf[NotEq[_]],
        (2 to 4).map(i => Row.apply(resultFun(i))))

      checkFilterPredicate(intAttr < 2, classOf[Lt[_]], resultFun(1))
      checkFilterPredicate(intAttr > 3, classOf[Gt[_]], resultFun(4))
      checkFilterPredicate(intAttr <= 1, classOf[LtEq[_]], resultFun(1))
      checkFilterPredicate(intAttr >= 4, classOf[GtEq[_]], resultFun(4))

      checkFilterPredicate(Literal(1) === intAttr, classOf[Eq[_]], resultFun(1))
      checkFilterPredicate(Literal(1) <=> intAttr, classOf[Eq[_]], resultFun(1))
      checkFilterPredicate(Literal(2) > intAttr, classOf[Lt[_]], resultFun(1))
      checkFilterPredicate(Literal(3) < intAttr, classOf[Gt[_]], resultFun(4))
      checkFilterPredicate(Literal(1) >= intAttr, classOf[LtEq[_]], resultFun(1))
      checkFilterPredicate(Literal(4) <= intAttr, classOf[GtEq[_]], resultFun(4))
```

And I notice `ParquetFilterSuite` also tests V1 and V2 datasources.

Not sure if it's necessary to add above tests.

**Comment by res-life** [comment]
Can we mark https://github.com/NVIDIA/spark-rapids/issues/9119 is invalid?

**Comment by thirtiseven** [comment]
> Not sure if it's necessary to add above tests.

Yes there are many cases to test PPD in Spark, I will try to go though them and add more.

> Can we mark https://github.com/NVIDIA/spark-rapids/issues/9119 is invalid?

Closed it.

File: tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala [hunk 2]
```diff
@@ -0,0 +1,262 @@
...
+      SQLConf.get.setConfString(k, v)
+    }
+    try f finally {
+      pairs.foreach { case (k, _) =>
+        SQLConf.get.unsetConf(k)
+      }
+    }
+  }
+
+  def withAllParquetReaders(code: => Unit): Unit = {
```
Comment (revans2) [inline tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala:50]: nit: This only matters when reading on the CPU. The GPU ignores this.

File: tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala (hunk 1 above)
Comment (revans2) [reply tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala:79]: Actually I think it should be

```
"spark.rapdis.slq.test.enabled" -> (!writeGpu).toString
```

or else if we are reading on the GPU, but writing on the CPU we will run into a problem where the we get an error for having things not be on the GPU.

File: tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala [hunk 3]
```diff
@@ -0,0 +1,262 @@
...
+              .write
+              .parquet(path.getAbsolutePath)
+        }
+        withSQLConf(
+          SQLConf.PARQUET_RECORD_FILTER_ENABLED.key -> "false",
+          SQLConf.PARQUET_FILTER_PUSHDOWN_ENABLED.key -> "true",
+          SQLConf.PARQUET_FILTER_PUSHDOWN_DATE_ENABLED.key -> "true",
+          SQLConf.PARQUET_FILTER_PUSHDOWN_TIMESTAMP_ENABLED.key -> "true",
+          SQLConf.PARQUET_FILTER_PUSHDOWN_DECIMAL_ENABLED.key -> "true",
+          "spark.rapids.sql.test.enabled" -> "false",
```
Comment (revans2) [inline tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala:92]: Same here we should update this one similarly to the comment above.

```
"spark.rapdis.slq.test.enabled" -> (!readGpu).toString,
```

File: tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala (hunk 1 above)
Comment (thirtiseven) [reply tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala]: Updated to
```scala
"spark.rapids.sql.test.enabled" -> writeGpu.toString
```
and
```scala
"spark.rapids.sql.test.enabled" -> readGpu.toString
```
to check all operations running on GPU during GPU read and write separately.

And removed binary test because we don't support binaryType right now.

**Comment by res-life** [comment]
Added [databricks] in the title to also test databricks.

**Review by revans2 — DISMISSED** [review]

**Comment by revans2** [comment]
build

**Comment by thirtiseven** [comment]
V2 source also needs `spark.sql.parquet.outputTimestampType=TIMESTAMP_MICROS` when reading to enable predicate pushdown. Also added date test.

**Review by revans2 — APPROVED** [review]

**Comment by thirtiseven** [comment]
build
