### PR TITLE
Restore output of unsupported column types

### LINKED ISSUE #2320: [BUG] TypeChecks diagnostics outputs column ids instead of unsupported types
**Describe the bug**
TypeCheck warnings report column names  without the type info, e.g.,

!Exec <HashAggregateExec> cannot run on GPU because Nested types in grouping expressions are not supported; unsupported data types in input: a#0; unsupported data types in output: a#0

**Steps/Code to reproduce bug**
Any query with an unsupported type involved e.g. #2274 

**Expected behavior**

!Exec <HashAggregateExec> cannot run on GPU because Nested types in grouping expressions are not supported; unsupported data types in input: StructType(StructField(a,IntegerType,true), StructField(b,IntegerType,true)); unsupported data types in output: StructType(StructField(a,IntegerType,true), StructField(b,IntegerType,true))

**Environment details (please complete the following information)**
reproduces locally

**Additional context**
Uncovered in #2274 , broken by https://github.com/NVIDIA/spark-rapids/commit/64f9d9b4414103fa424283712371e2b9bddcd8fe#diff-c5cb89e178628729e961e2e0e9be2689893254638c5ce467250a263f7867112dR558

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #2320

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala [hunk 1]
```diff
@@ -631,18 +631,20 @@ class ExecChecks private(
     val plan = meta.wrapped.asInstanceOf[SparkPlan]
     val allowDecimal = meta.conf.decimalTypeEnabled
 
-    val unsupportedOutputTypes = plan.output
-      .filterNot(attr => check.isSupportedByPlugin(attr.dataType, allowDecimal))
-      .toSet
+    val unsupportedOutputTypes = plan.output.collect {
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala:634]: I realize that returning the attribute instead of the type was a bug, but I have actually found it somewhat informative to have the name of the attribute in there as well.  Perhaps we could change `unsupportedOutputTypes` to be something more like `Map[DataType, Array[String]]` so we can output something more like.

```
!Exec cannot run on GPU because nested types in grouping expressions are not supported; unsupported data types in input: StructType(StructField(a,IntegerType,true), StructField(b,IntegerType,true)) [a#0]; unsupported data types in output: StructType(StructField(a,IntegerType,true), StructField(b,IntegerType,true)) [a#0]
```

**Comment by gerashegalov** [comment]
New output:
```
!Exec <HashAggregateExec> cannot run on GPU because unsupported data types in output: StructType(StructField(a,IntegerType,true), StructField(b,IntegerType,true)) [a#0]; unsupported data types in input: StructType(StructField(a,IntegerType,true), StructField(b,IntegerType,true)) [a#0]; Nested types in grouping expressions are not supported
```

**Comment by gerashegalov** [comment]
build

**Review by revans2 — APPROVED** [review]
Looks great thanks for doing this.

**Review by jlowe — APPROVED** [review]
