### PR TITLE
fix orc readers leak issue for ORC PERFILE type

### LINKED ISSUE #2850: [BUG] "java.io.InterruptedIOException: getFileStatus on s3a://xxx" for ORC reading in Databricks 8.2 runtime
**Describe the bug**
I have 400+ ORC files located in the `dbfs:/XXXX` , and I ran the simple query like

``` scala
spark.conf.set("spark.sql.files.maxPartitionBytes", "1g")
spark.conf.set("spark.sql.shuffle.partitions", "100")
spark.conf.set("spark.rapids.sql.enabled", "true")
spark.conf.set("spark.rapids.sql.exec.CollectLimitExec", "false")

val dfPerfile = spark.read.orc("dbfs:/XXXX")
spark.time(dfPerfile.foreach(_ => ()))
```

But some tasks are failed with the below exceptions

``` console
21/06/30 08:19:52 ERROR Executor: Exception in task 8.1 in stage 0.0 (TID 19)
java.io.InterruptedIOException: getFileStatus on s3a://rapidsai-databricks/XXXXX/partition_id_1=3/partition_id_2=2/part-00005-tid-5832222349885074749-82f13795-1dcc-4695-a487-4521b5830bd5-88-21.c000.snappy.orc: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AUtils.translateInterruptedException(S3AUtils.java:365)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:196)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:154)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3000)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:2967)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:2906)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.open(S3AFileSystem.java:1018)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$open$2(DatabricksFileSystemV2.scala:505)
	at com.databricks.s3a.S3AExeceptionUtils$.convertAWSExceptionToJavaIOException(DatabricksStreamUtils.scala:66)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$open$1(DatabricksFileSystemV2.scala:503)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$4(UsageLogging.scala:434)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:240)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:235)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:232)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:455)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:279)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:271)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:455)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:415)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:341)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperation(DatabricksFileSystemV2.scala:455)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.open(DatabricksFileSystemV2.scala:503)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.open(DatabricksFileSystemV2.scala:510)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystem.open(DatabricksFileSystem.scala:88)
	at com.nvidia.shaded.spark.orc.impl.ReaderImpl.extractFileTail(ReaderImpl.java:546)
	at com.nvidia.shaded.spark.orc.impl.ReaderImpl.(ReaderImpl.java:369)
	at com.nvidia.shaded.spark.orc.OrcFile.createReader(OrcFile.java:343)
	at com.nvidia.spark.rapids.GpuOrcPartitionReaderFactory.buildColumnarReader(GpuOrcScan.scala:148)
	at com.nvidia.spark.rapids.PartitionReaderIterator$.$anonfun$buildReader$1(PartitionReaderIterator.scala:58)
	at org.apache.spark.sql.rapids.shims.spark311db.GpuFileScanRDD$$anon$1.org$apache$spark$sql$rapids$shims$spark311db$GpuFileScanRDD$$anon$$readCurrentFile(GpuFileScanRDD.scala:96)
	at org.apache.spark.sql.rapids.shims.spark311db.GpuFileScanRDD$$anon$1.nextIterator(GpuFileScanRDD.scala:149)
	at org.apache.spark.sql.rapids.shims.spark311db.GpuFileScanRDD$$anon$1.hasNext(GpuFileScanRDD.scala:73)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:385)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:222)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:177)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:221)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:198)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:238)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at org.apache.spark.rdd.RDD.$anonfun$foreach$2(RDD.scala:1017)
	at org.apache.spark.rdd.RDD.$anonfun$foreach$2$adapted(RDD.scala:1017)
	at org.apache.spark.SparkContext.$anonfun$runJob$2(SparkContext.scala:2498)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:68)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:148)
	at org.apache.spark.scheduler.Task.run(Task.scala:117)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$10(Executor.scala:732)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1643)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:735)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4926)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4872)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1321)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$getObjectMetadata$4(S3AFileSystem.java:1623)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:285)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:1620)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:2988)
```

After checking the code from https://github.com/NVIDIA/spark-rapids/blob/branch-21.08/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala#L169 .

~~Looks like at the very beginning GpuDataSourceRDD will create GpuOrcPartitionReaders for all PartitionedFile (1 GpuOrcParitionFile for 1 PartitionedFile). Each  GpuOrcPartitionReaders will hold an OrcReader.~~ If the OrcReader is not been closed, then it will occupy the connection pool and result in other one that applies connection timeout.

### PR DESCRIPTION
**Pull request by wbo4958**
Signed-off-by: Bobby Wang <wbo4958@gmail.com>

This issue is to fix #2850

The **close** function of GpuOrcPartitionReader is not called when GpuOrcPartitionReader has finished reading which results in orc readers not be closed, like leaking. 

Eventually, the **close** function of GpuOrcPartitionReader will be called on Spark task completion, but it's too late. The orc readers occupy the connection pool and result in another one that applies connection timeout for the S3 case.

For example, If the max connection of s3a is set to 256 and we have 257 ORC files to read, let's assume we only have 1 task. then the first 256 ORC files can be read without any problem, but for the last orc file, it will timeout to apply connection from s3 pool since the 256 connections have been unavailable.

So the fix is releasing the orc readers after GpuOrcPartitionReader has finished the reading.

I did the testes for 600 Orc files and 1000 Orc files for PERFILE reader. And no task failed.

### CODE REVIEW

**Comment by wbo4958** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 1]
```diff
@@ -844,20 +844,18 @@ private case class GpuOrcFileFilterHandler(
       OrcProto.Stream.Kind.ROW_INDEX)
 
     def getOrcPartitionReaderContext: OrcPartitionReaderContext = {
-      closeOnExcept(orcReader) { _ =>
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:847]: Why do we not want to close the reader if an exception occurs?  How is it guaranteed that this reader will eventually be closed?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/PartitionReaderIterator.scala [hunk 2]
```diff
@@ -28,14 +27,17 @@ import org.apache.spark.sql.vectorized.ColumnarBatch
  */
 class PartitionReaderIterator(reader: PartitionReader[ColumnarBatch])
     extends Iterator[ColumnarBatch] with AutoCloseable {
-  Option(TaskContext.get()).foreach(_.addTaskCompletionListener[Unit](_ => close()))
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/PartitionReaderIterator.scala:31]: Iterators are not guaranteed to be read to completion which is why a task completion listener like this is installed.

**Review by jlowe — COMMENTED** [review]
There's no explanation in the PR description as to _how_ this fixes the reported issue.  Please describe how this resolves the problem, because as it is written, this seems to only _increase_ the chance that the reader will end up not being closed.  Is the issue that the iterator is being used outside of a task context thread in some cases?  If so then we need to ensure the iterator close method is called by the task completion listener of the controlling task thread.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 1 above)
Comment (wbo4958) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:847]: the caller who will close orcReader if exception happens

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/PartitionReaderIterator.scala (hunk 2 above)
Comment (wbo4958) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/PartitionReaderIterator.scala:31]: Hmm, Yeah, I will figure out a new way to fix it. Thx Jason

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 1 above)
Comment (wbo4958) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:847]: And updated the description for the PR

**Comment by wbo4958** [comment]
build

**Comment by wbo4958** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 3]
```diff
@@ -641,12 +641,16 @@ class GpuOrcPartitionReader(
...
+    // After finishing reading, we should clean up ctx just in case leaking orc readers
+    if (!ret) {
+      cleanUpOrc(ctx)
+    }
+    ret
   }
 
   override def close(): Unit = {
     super.close()
-    cleanUpOrc(ctx)
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:649]: Why wouldn't we clean up the reader when this is closed?  If the code downstream from the iterator ends up stopping early and not draining isn't drained and we never see the empty batch from the reader -- how does the orc reader get closed in that case?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 4]
```diff
@@ -641,12 +641,16 @@ class GpuOrcPartitionReader(
       }
       isFirstBatch = false
     }
-    batch.isDefined
+    val ret = batch.isDefined
+    // After finishing reading, we should clean up ctx just in case leaking orc readers
+    if (!ret) {
+      cleanUpOrc(ctx)
+    }
+    ret
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:649]: nit:
```suggestion
   batch.map(_ => true).getOrElse {
      // After finishing reading, we should clean up ctx just in case leaking orc readers
       cleanUpOrc(ctx)
       false
   }
```

Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:649]: can we add a fix to cleanUpOrc to do a `safeClose` to avoid leaks too?
```scala
  import com.nvidia.spark.rapids.RapidsPluginImplicits._
  ...
  def cleanUpOrc(ctx: OrcPartitionReaderContext) = {
    if (ctx != null) {
      Seq(ctx.orcReader, ctx.dataReader).safeClose()
    }
  }
```

Comment (wbo4958) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala]: Thx for the suggestion. Done

**Comment by wbo4958** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 3 above)
Comment (wbo4958) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:649]: Thx Jason for the findings. You are correct. Done.

**Review by gerashegalov — APPROVED** [review]
LGTM, ideally we should add a test

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 5]
```diff
@@ -641,12 +641,20 @@ class GpuOrcPartitionReader(
...
+      isOrcCleanedUp = true
+      false
+    }
   }
 
   override def close(): Unit = {
     super.close()
-    cleanUpOrc(ctx)
+    if (!isOrcCleanedUp) {
+      cleanUpOrc(ctx)
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:656]: I'm assuming this check is here because cleanupOrc is not idempotent.  Should this flag be part of the context and checked within `cleanUpOrc` rather than requiring callers to track this context-specific state separately?

**Comment by wbo4958** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 5 above)
Comment (wbo4958) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala]: Done

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 6]
```diff
@@ -367,7 +367,16 @@ private case class OrcPartitionReaderContext(
     dataReader: DataReader,
     orcReader: Reader,
     blockIterator: BufferedIterator[OrcOutputStripe],
-    requestedMapping: Option[Array[Int]])
+    requestedMapping: Option[Array[Int]]) {
+  private var isClosed = false
+
+  def cleanUp = {
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:373]: Nit: Lack of parentheses should be reserved for methods that have no side effects.  Since this mutates the state of the object, it should have parentheses and be called with parentheses.
```suggestion
  def cleanUp() = {
```

**Review by jlowe — APPROVED** [review]
Minor nit but otherwise looks good to me.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 6 above)
Comment (wbo4958) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala]: Thx Jason for the comment. Done

**Comment by wbo4958** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Review by jlowe — APPROVED** [review]
