### PR TITLE
Fix Parquet schema evolution when missing column is in a nested type [databricks]

### LINKED ISSUE #6005: [BUG] When old Hive partition has different schema than new partition& Hive Schema, read old partition fails with "Found no metadata for schema index"
**Env:**
Spark RAPIDS 22.06GA (also tested rapids-4-spark_2.12-22.08.0-20220715.110044-29.jar)
Spark Standalone cluster (also tested on Spark on YARN)

**Symptom**
When old Hive partition has different schema than new partition& Hive Schema, read old partition fails with "Found no metadata for schema index"

**Minimum reproduce**

```
1. Hive
drop table test_diff_schema;
create external table test_diff_schema(a string, b int, c STRUCT<`ca`: STRING, `cb`: STRING>) PARTITIONED BY (k string)
STORED AS PARQUET LOCATION '/home/hazhu/data/hive/test_diff_schema';

2. Generate sample data

import spark.implicits._
import org.apache.spark.sql.types._
import org.apache.spark.sql.Row

val data = Seq(
    Row("Adam",1000),
    Row("Bob",2000),
    Row("Cathy",9999)
)

val schema = StructType( Array(
                 StructField("a", StringType,true),
                 StructField("b", IntegerType,true)
             ))

val df = spark.createDataFrame(spark.sparkContext.parallelize(data),schema)
df.createOrReplaceTempView("df")
spark.sql("select a,b, struct(a as ca) as c from df").write.format("parquet").mode("overwrite").save("/home/hazhu/data/hive/test_diff_schema/2021")
spark.sql("select a,b, struct(a as ca,a as cb) as c from df").write.format("parquet").mode("overwrite").save("/home/hazhu/data/hive/test_diff_schema/2022")

3. Hive
ALTER TABLE test_diff_schema ADD PARTITION (k='2021') LOCATION '/home/hazhu/data/hive/test_diff_schema/2021';
ALTER TABLE test_diff_schema ADD PARTITION (k='2022') LOCATION '/home/hazhu/data/hive/test_diff_schema/2022';


4. Spark shell
--GPU run failed:
spark.conf.set("spark.rapids.sql.enabled",true)
spark.sql("""select * from test_diff_schema where k=2021 """).show

--CPU run works fine
spark.conf.set("spark.rapids.sql.enabled",false)
spark.sql("""select * from test_diff_schema where k=2021 """).show
+-----+----+-------------+----+
|    a|   b|            c|   k|
+-----+----+-------------+----+
|Cathy|9999|{Cathy, null}|2021|
| Adam|1000| {Adam, null}|2021|
|  Bob|2000|  {Bob, null}|2021|
+-----+----+-------------+----+
```

**Stacktrace:**
```
22/07/15 15:58:44 WARN TaskSetManager: Lost task 2.0 in stage 22.0 (TID 151) (xxx.xxx.xxx.xxx executor 0): ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni-release-1-cuda11/thirdparty/cudf/cpp/src/io/parquet/reader_impl.cu:422: Found no metadata for schema index
	at ai.rapids.cudf.Table.readParquet(Native Method)
	at ai.rapids.cudf.Table.readParquet(Table.java:1035)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.$anonfun$readBufferToTable$1(GpuParquetScan.scala:1702)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:264)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.readBufferToTable(GpuParquetScan.scala:1701)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readToTable$1(GpuMultiFileReader.scala:845)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:264)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.readToTable(GpuMultiFileReader.scala:841)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$1(GpuMultiFileReader.scala:815)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:264)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.readBatch(GpuMultiFileReader.scala:797)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.next(GpuMultiFileReader.scala:783)
	at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
	at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:420)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at com.nvidia.spark.rapids.GpuBaseLimitExec$$anon$1.hasNext(limit.scala:70)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:287)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:304)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #6005.

The existing Parquet schema evolution code was handling casts needed in nested types, but it was not handling the case where columns were missing from a nested type and nulls needed to be added in order to match the read schema.  This updates the Parquet schema evolution to leverage `SchemaUtils` that is already being used for ORC schema evolution.  The main sticking points with reusing the code were:
- the need to trim the Spark read schema to what is available in the file schema
- handle casts that cannot be detected by comparing Spark types

For the first point, it would be tempting to simply leverage Spark's `ParquetSchemaConverter` for this, but SchemaUtils assumes that it can map between the two schemas by column name only.  However Parquet has field IDs that can be optionally leveraged to lookup fields, and SchemaUtils has no support for that.  In addition, Spark's ParquetSchemaConverter does not propagate field IDs into the resulting Spark schema, so even if SchemaUtils was enhanced to support field ID lookup, the field IDs would be stripped during the transform to a Spark schema.  To solve it, the code leverages logic similar to Spark's ParquetToSchemaConverter but instead of building a schema from scratch, the read schema is trimmed to the fields matched in the Parquet schema.  Column names are preserved, but datatypes can be updated and columns that don't exist are removed.  This allows SchemaUtils to find most of the evolution casts that are needed for Parquet.  Since the Parquet types supported have shifted across Spark versions, this required shimming some of the code to convert Parquet types to Spark types.

The one type of Parquet schema evolution cast that cannot be detected by SchemaUtils' Spark-to-Spark schema comparison logic is the upcast from Parquet's unsigned types to the wider signed type.  Since Spark does not have unsigned data types, comparing expected Spark type to actual Spark type can fail to detect that an upcast is needed.  To solve it, the code adds an flag to SchemaUtils evolution so the struct traversal can be forced instead of short-circuited if the Spark types match.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by revans2 — COMMENTED** [review]
I did a pass through the code and it looks fine, but I have not gone into enough detail to feel okay with approving this yet.

**Comment by jlowe** [comment]
build

**Comment by sameerz** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
CI failure looks like a hiccup on one of the databricks builds, like a node was lost.

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
Latest build failed due to unrelated orc_test problem that is now fixed by #6090.

**Comment by jlowe** [comment]
build

**Review by firestarman — CHANGES_REQUESTED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala [hunk 1]
```diff
@@ -0,0 +1,574 @@
...
+import org.apache.spark.sql.types._
+
+object ParquetSchemaUtils extends Arm {
+  // Copied from Spark
+  private val SPARK_PARQUET_SCHEMA_NAME = "spark_schema"
+  // Copied from Spark
+  val EMPTY_MESSAGE: MessageType = Types.buildMessage().named(SPARK_PARQUET_SCHEMA_NAME)
+
+  /**
+   * Similar to Spark's ParquetReadSupport.clipParquetSchema but does NOT add fields missing
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala:38]: Seems the comment is incorrect ?
```suggestion
   * Similar to Spark's ParquetReadSupport.clipParquetSchema but does NOT add fields that only exist
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala [hunk 2]
```diff
@@ -0,0 +1,574 @@
...
+  }
+
+  def evolveSchemaIfNeededAndClose(
+      table: Table,
+      fileSchema: MessageType,
+      sparkSchema: StructType,
+      caseSensitive: Boolean,
+      useFieldId: Boolean): Table = {
+    val fileSparkSchema = closeOnExcept(table) { _ =>
+      clipSparkSchema(sparkSchema, fileSchema, caseSensitive, useFieldId)
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala:509]: I am wondering whether this `clipSparkSchema` can be removed after

- In `clipParquetSchema`, building the `clipedSchema` (the schema of the memory Parquet file) with each field is generated with the name from the corresponding field (matched by field id or column name) in `catalystSchema` (the read schema) but others still from the field in `parquetSchema` (the file schema).

   Assuming there is a field **_(name: "c1", id: 2, type: int)_** in `parquetSchema`, and a field **_(name: "cc", id: 2, type: long)_** in `catalystSchema`. They will match by id if `useFieldId` is true. Then the final output field will be _**(name: "cc", id: 2, type: int)**_.
```
        (name: "c1", id: 2, type: int)    // In fileSchema 
    +   (name: "cc", id: 2, type: long)  // In readSchema
    ->  (name: "cc", id: 2, type: int)
```
  Then inside the coming `SchemaUtils.evolveSchemaIfNeededAndClose`, the name comparsion will be enough for Parquet. 
  [We are doing this in ORC](https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala#L1214). So the name only comparsion works for ORC even ORC also supports [a positional way to match columns](https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala#L1192), which is similar to the Parquet field id.
- Building the column names for cuDF decoding from this `clipedSchema` instead of the `toCudfColumnNames` method. Since with the `SchemaUtils.evolveSchemaIfNeededAndClose`, the input table is not required to have the same column order with the reader schema any more.

File: sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+import org.apache.spark.sql.rapids.execution.TrampolineUtil
+import org.apache.spark.sql.types._
+
+object ParquetSchemaClipShims {
+  /** Stubs for configs not defined before Spark 330 */
+  def useFieldId(conf: SQLConf): Boolean = false
+
+  def ignoreMissingIds(conf: SQLConf): Boolean = false
+
+  def timestampNTZEnabled(conf: SQLConf): Boolean = false
```
Comment (firestarman) [inline sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala:33]: Seems this is no longer used. Beter to remove it.

File: sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+import org.apache.spark.sql.rapids.execution.TrampolineUtil
+import org.apache.spark.sql.types._
+
+object ParquetSchemaClipShims {
+  /** Stubs for configs not defined before Spark 330 */
+  def useFieldId(conf: SQLConf): Boolean = false
+
+  def ignoreMissingIds(conf: SQLConf): Boolean = false
+
+  def timestampNTZEnabled(conf: SQLConf): Boolean = false
```
Comment (firestarman) [inline sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala:33]: Seems this is no longer used. Beter to remove it.

File: sql-plugin/src/main/330until340/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala [hunk 5]
```diff
@@ -76,16 +81,121 @@ object ParquetSchemaClipShims {
   /** The stub for the config not defined in Spark 330 */
   def timestampNTZEnabled(conf: SQLConf): Boolean = false
```
Comment (firestarman) [inline sql-plugin/src/main/330until340/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala:82]: Seems this is no longer used. Beter to remove it.

File: sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala [hunk 6]
```diff
@@ -16,24 +16,189 @@
...
+  def fieldIdToNameMap(useFieldId: Boolean, fileType: Type): Map[Int, String] = {
+    if (useFieldId) {
+      fileType.asGroupType().getFields.asScala.filter(_.getId != null)
+          .map(f => f.getId.intValue() -> f.getName).toMap
+    } else {
+      Map.empty[Int, String]
+    }
+  }
+
   def timestampNTZEnabled(conf: SQLConf): Boolean = conf.parquetTimestampNTZEnabled
```
Comment (firestarman) [inline sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala:81]: Seems this is no longer used. Beter to remove it.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala (hunk 2 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala:509]: I don't think this will work as stated.  I see the following problems, please correct me if I'm missing something.

The `MessageType` that comes out of the new `checkSchemaCompat` may not match the column paths that are encoded in the `BlockMetaData` corresponding to the data blocks in the file.  When we emit the in-memory Parquet file using the new `MessageType` that is using Spark's names instead of the original file's column names, the libcudf Parquet reader won't be able to find the the column data for some columns (or worse, will use the _wrong_ column data for the corner case where column names were swapped).  Writing a footer schema that doesn't match the column data blocks is essentially the root cause of #6005.  The footer schema says there's a column for which there is no corresponding column data that matches that column.  We might be able to fixup the `BlockMetaData` for the new column name mapping, but I don't know offhand how hard this would be.

> Then it will become the table schema inside this SchemaUtils.evolveSchemaIfNeededAndClose function.

That method doesn't take a `MessageType`, it takes only Spark schemas since it isn't specific to Parquet.  We'd still need a way to convert a `MessageType` into a `StructType`, which would end up with code very similar to `clipSparkSchema`.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala (hunk 1 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala]: Nice catch! Fixed.

File: sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala (hunk 3 above)
Comment (jlowe) [reply sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala]: Removed this and the corresponding method in other shims.

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala (hunk 2 above)
Comment (firestarman) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala:509]: OK, I missed that. So we also need to rebuild the block meta if using this "new" schema.

**Review by firestarman — APPROVED** [review]

**Comment by firestarman** [comment]
build
