### PR TITLE
Fix the issue of ExtraPlugins loading multiple times

### LINKED ISSUE #12076: [BUG] ExtraPlugins might be loaded duplicated
**Describe the bug**
(https://github.com/NVIDIA/spark-rapids/blob/branch-25.02/sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala#L356)
```scala
  private def getExtraPlugins: Seq[SparkPlugin] = {
    val resourceName = "spark-rapids-extra-plugins"
    val classLoader = RapidsPluginUtils.getClass.getClassLoader
    val resourceUrls = classLoader.getResources(resourceName)
    val resourceUrlArray = resourceUrls.asScala.toArray

    if (resourceUrlArray.isEmpty) {
      logDebug(s"Could not find file $resourceName in the classpath, not loading extra plugins")
      Seq.empty
    } else {
      val plugins = scala.collection.mutable.ListBuffer[SparkPlugin]()
      for (resourceUrl <- resourceUrlArray) {
        val source = scala.io.Source.fromURL(resourceUrl)
        val pluginClasses = source.getLines().toList
        source.close()
        plugins ++= loadExtensions(classOf[SparkPlugin], pluginClasses)
      }
      plugins.toSeq
    }
  }
```

The `resourceUrls` may contain duplicated urls for the same extra plugin to be loaded. And the a lot of extra plugins will go weirdly when being loaded multiple times.

### PR DESCRIPTION
**Pull request by sperlingxx**
Fixes #12076

The PR is about to fix the multiple loading problem which is due to the duplicated URL paths for single extra plugin.

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 1]
```diff
@@ -353,7 +353,7 @@ object RapidsPluginUtils extends Logging {
     val resourceName = "spark-rapids-extra-plugins"
     val classLoader = RapidsPluginUtils.getClass.getClassLoader
     val resourceUrls = classLoader.getResources(resourceName)
-    val resourceUrlArray = resourceUrls.asScala.toArray
+    val resourceUrlArray = resourceUrls.asScala.toArray.distinct
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:356]: Please add a warning listing duplicates. 

This looks like a deployment error to me when there are multiple identical  entries on the classpath that the user might want to fix.

Comment (sperlingxx) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala]: Yes, I added the warning clause.

**Comment by sperlingxx** [comment]
build

**Review by res-life — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]
