### PR TITLE
Unify legacy and 3.1.x struct cast implementations

### LINKED ISSUE #2309: [BUG] legacy cast of a struct column to string with a single nested null column yields null instead of '[]'
**Describe the bug**
In Spark 3.0.x and Spark 3.1+ with the legacy mode, casting a struct with a single nested null-valued field produces a null string instead of `[]`

**Steps/Code to reproduce bug**
```python
import pyspark.sql.functions as F
import pyspark.sql.types as T

# for Spark 3.1+
spark.conf.set('spark.sql.legacy.castComplexTypesToString.enabled', True)

data = [ (('gera',),), ((None,),), (None,) ]
df = spark.createDataFrame(data)
df.select(df._1.cast(T.StringType())).collect()
```
Broken output:
```
[Row(_1='[gera]'), Row(_1=None), Row(_1=None)]
```

**Expected behavior**
Correct output:
```
[Row(_1='[gera]'), Row(_1='[]'), Row(_1=None)]
```
**Environment details (please complete the following information)**
Reproduces in a local REPL 

**Additional context**
CI test failures in #2274

### PR DESCRIPTION
**Pull request by gerashegalov**
Refactors struct cast to string such that there no need for a dedicated method handling the legacy mode cast. Fixes #2309 and #2315
    
Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 1]
```diff
@@ -510,126 +510,71 @@ case class GpuCast(
...
-  private def castStructToString(input: ColumnView,
-    legacyCastToString: Boolean, inputSchema: Array[StructField]): ColumnVector = {
-    if (legacyCastToString) {
-      legacyStructToString(input, inputSchema)
-    } else {
-      modernStructToString(input,inputSchema)
+    withResource(Array(
+      Scalar.fromString(emptyStr),
+      Scalar.fromString(nullStr),
+      Scalar.fromString(separatorStr),
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:568]: This will leak GPU resources if any of these `fromString` methods throw after the first.  Something like this would cover that possibility:
```scala
  withResource(Seq(emptyStr, nullStr, separatorStr, spaceStr, leftStr, rightStr).safeMap(Scalar.fromString).toArray) { ...
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala [hunk 2]
```diff
@@ -510,126 +510,71 @@ case class GpuCast(
...
+      Scalar.fromString(spaceStr),
+      Scalar.fromString(leftStr),
+      Scalar.fromString(rightStr)
+    )) { case Array(emptyScalar, nullScalar, columnScalars@_*) =>
+      withResource(columnScalars.map(s => ColumnVector.fromScalar(s, numRows)))(columns => {
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:573]: If the `map` throws while trying to build the sequence then we can leak
```suggestion
      withResource(columnScalars.safeMap(s => ColumnVector.fromScalar(s, numRows)))(columns => {
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala (hunk 1 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:568]: This isn't trying to close the strings but the Scalar instances constructed from those strings.  Note the `safeMap` after the `Seq`, so we're not trying to close a `Seq[String]` but a `Seq[Scalar]`.

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]
Small nit but otherwise lgtm

**Review by jlowe — CHANGES_REQUESTED** [review]
Actually now that #2274 has been merged, we should pull out the xfail markers in those tests to work around the bugs being fixed here.

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build
