### PR TITLE
Integration-test tests jar for hive UDF tests

### LINKED ISSUE #4883: [BUG] row-based_udf_test.py::test_hive_empty_* fail nightly tests
**Describe the bug**
integration test are failing

FAILED ../../src/main/python/row-based_udf_test.py::test_hive_empty_simple_udf
FAILED ../../src/main/python/row-based_udf_test.py::test_hive_empty_generic_udf

with 

 pyspark.sql.utils.AnalysisException: Can not load class 'com.nvidia.spark.rapids.tests.udf.hive.EmptyHiveGenericUDF' when registering the function 'emptygeneric', please make sure it is on the classpath;[0m

### PR DESCRIPTION
**Pull request by NvTimLiu**
Fixes #4883

We moved HiveUDF classes to the the dir `integration_tests/src/test` (built to integration-tests-sparkxxxtests.jar)  with https://github.com/NVIDIA/spark-rapids/pull/4619, so need to add this jar into the jars_path of the integration tests, to PASS hive UDF tests. 

1, Add commit version info for the integration-test tests jar.

2, Upload Databricks shims of integration-test tests jar to internal maven repo.

3, Download integration-test tests jar for the hive UDF integration tests.

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

File: jenkins/databricks/deploy.sh [hunk 1]
```diff
@@ -38,3 +38,7 @@ mvn -B deploy:deploy-file $MVN_URM_MIRROR -Durl=$SERVER_URL -DrepositoryId=$SERV
 DBINTTESTJARFPATH=./integration_tests/target/rapids-4-spark-integration-tests_$SCALA_VERSION-$SPARK_PLUGIN_JAR_VERSION-${DB_SHIM_NAME}.jar
 mvn -B deploy:deploy-file $MVN_URM_MIRROR -Durl=$SERVER_URL -DrepositoryId=$SERVER_ID \
     -Dfile=$DBINTTESTJARFPATH -DpomFile=integration_tests/pom.xml -Dclassifier=$DB_SHIM_NAME
+# Deploy integration-tests tests jar for hive UDF tests
+HIVEUDFTESTSJAR=./integration_tests/target/rapids-4-spark-integration-tests_$SCALA_VERSION-$SPARK_PLUGIN_JAR_VERSION-${DB_SHIM_NAME}'tests'.jar
+mvn -B deploy:deploy-file $MVN_URM_MIRROR -Durl=$SERVER_URL -DrepositoryId=$SERVER_ID \
```
Comment (NvTimLiu) [inline jenkins/databricks/deploy.sh:43]: Deploy Databricks shims (e.g. integration-test-spark301dbtests.jar) of integration-test tests jar in the nightly BUILD job. We will need this jar to run hive UDF tests nightly IT job on Databricks.

**Comment by NvTimLiu** [comment]
build

File: jenkins/databricks/deploy.sh [hunk 2]
```diff
@@ -38,3 +38,7 @@ mvn -B deploy:deploy-file $MVN_URM_MIRROR -Durl=$SERVER_URL -DrepositoryId=$SERV
...
+    -Dfile=$HIVEUDFTESTSJAR -DpomFile=integration_tests/pom.xml -Dclassifier=$DB_SHIM_NAME'tests'
```
Comment (res-life) [inline jenkins/databricks/deploy.sh:44]: nit: HIVE_UDF_TESTS_JAR is more readable than HIVEUDFTESTSJAR.

**Comment by res-life** [comment]
LGTM

**Review by res-life — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Review by jlowe — APPROVED** [review]
This looks OK, but it is highly confusing that we have both a main jar and a tests jar for the integration_tests artifact, especially when the code in the tests jar has nothing to do with testing the integration_tests main code.  I'll file a followup to make it consistent.

**Comment by pxLi** [comment]
Going to force merge this one to unblock nightly CI first
