### PR TITLE
Fix DecimalGen to generate full range and fix failing test cases

### LINKED ISSUE #6337: [BUG] DecimalGen does not produce negative values or MIN/MAX/0 values as special cases
**Describe the bug**
This reduces the quality of the tests.

I have a patch for this.

```diff
diff --git a/integration_tests/src/main/python/data_gen.py b/integration_tests/src/main/python/data_gen.py
index ac3c812a5..4f864691a 100644
--- a/integration_tests/src/main/python/data_gen.py
+++ b/integration_tests/src/main/python/data_gen.py
@@ -215,17 +215,19 @@ class IntegerGen(DataGen):
 
 class DecimalGen(DataGen):
     """Generate Decimals, with some built in corner cases."""
-    def __init__(self, precision=None, scale=None, nullable=True, special_cases=[]):
+    def __init__(self, precision=None, scale=None, nullable=True, special_cases=None):
         if precision is None:
             #Maximum number of decimal digits a Long can represent is 18
             precision = 18
             scale = 0
         DECIMAL_MIN = Decimal('-' + ('9' * precision) + 'e' + str(-scale))
         DECIMAL_MAX = Decimal(('9'* precision) + 'e' + str(-scale))
+        if (special_cases is None):
+            special_cases = [DECIMAL_MIN, DECIMAL_MAX, Decimal('0')]
         super().__init__(DecimalType(precision, scale), nullable=nullable, special_cases=special_cases)
         self.scale = scale
         self.precision = precision
-        pattern = "[0-9]{1,"+ str(precision) + "}e" + str(-scale)
+        pattern = "-?[0-9]{1,"+ str(precision) + "}e" + str(-scale)
         self.base_strs = sre_yield.AllStrings(pattern, flags=0, charset=sre_yield.CHARSET, max_count=_MAX_CHOICES)
 
     def __repr__(self):
```

But I have run into a number of different issues. In our code and in Spark

https://issues.apache.org/jira/browse/SPARK-40089
https://github.com/NVIDIA/spark-rapids/issues/6336

and I am working on filing a few more issues.

**Steps/Code to reproduce bug**
apply the patch and run...

### LINKED ISSUE #6340: [BUG] test_hash_grpby_sum_full_decimal can fail with negative numbers
**Describe the bug**
This is after https://github.com/NVIDIA/spark-rapids/issues/6337

After applying the patch I got two new failures.

```
FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_grpby_sum_full_decimal[{'spark.rapids.sql.variableFloatAgg.enabled': 'true', 'spark.rapids.sql.hasNans': 'false', 'spark.rapids.sql.castStringToFloat.enabled': 'true', 'spark.rapids.sql.batchSizeBytes': '250'}-[('a', RepeatSeq(Short)), ('b', Decimal(38,0)), ('c', Decimal(38,0))]][IGNORE_ORDER, INCOMPAT, APPROXIMATE_FLOAT]
FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_grpby_sum_full_decimal[{'spark.rapids.sql.variableFloatAgg.enabled': 'true', 'spark.rapids.sql.hasNans': 'false', 'spark.rapids.sql.castStringToFloat.enabled': 'true', 'spark.rapids.sql.batchSizeBytes': '250'}-[('a', RepeatSeq(Short)), ('b', Decimal(38,-10)), ('c', Decimal(38,-10))]][IGNORE_ORDER, INCOMPAT, APPROXIMATE_FLOAT]
```

I looked at the test with Decimal(38, -10) and found that the last entry failed.

CPU: `Row(a=32767, sum(b)=Decimal('-1.0069950567342662336581895246262384447E+47'))]`
GPU: `Row(a=32767, sum(b)=None)]`

So I output all of the input rows and grabbed the data with a key of 32767

```
Row(a=32767, b=Decimal('2.0360233429506710212497266346421905772E+47'), c=Decimal('2.765143365111033511029162424589954925E+46')), 
Row(a=32767, b=Decimal('-3.090071236354489657384647925632098444E+46'), c=Decimal('5.7254478143626627399120145071577005563E+47')), 
Row(a=32767, b=Decimal('-8.1852545046060538705441039408857918362E+47'), c=Decimal('5.7950365697792991048959277021156285406E+47')), 
Row(a=32767, b=Decimal('1.1034073307585606757483697925046552230E+47'), c=Decimal('6.9428689056725720374284055305827859561E+47')), 
Row(a=32767, b=Decimal('-3.2543002676046129590371963602717677470E+47'), c=Decimal('5.6304777872241017510011512841702571047E+47')), 
Row(a=32767, b=Decimal('7.6021361654026178646634791419476851827E+47'), c=Decimal('4.8960820250876759784925149535993449222E+47')), 
```

This was done on a version on Spark 3.2.0 that had a fix for sort problems.

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #6337, fixes #6340, relates to #6336, #6312, and #6339.

This updates DecimalGen to generate negative values along with the minimum, maximum and zero special cases.  Doing so exposed test failures in a number of places.  Many of the failures were due to the decimal sorting bug in Spark, see https://issues.apache.org/jira/browse/SPARK-40089.  In those cases the tests were updated to simply avoid generating the special cases to avoid triggering the CPU sorting bug or the test was updated to sort in Python rather than Spark if that was an option for the test.

Some other test failures required code changes.  First was the aggregation sum failures on decimals.  The problem was caused by checking for overflow in more places than Spark does.  With negative decimals involved, it's possible to sum an intermediate value that can still be held in 128 bits but requires more than 38 decimal digits to represent.  If further summing restores the value into 38 decimal digits without overflowing 128 bits then we're fine, but the excessive overflow checking was triggering a false overflow.  The fix is to only check for overflow during final aggregation evaluation as Spark does.

For the pmod test failures, this was worked around by avoiding placing pmod on the GPU if the decimal is at the maximum precision (38).  Tests were updated to avoid testing those large precision decimals when testing for GPU functionality and a test added to verify we fallback to the CPU at the max precision.

One last failure was timestamps failing in ORC after the DecimalGen change.  I verified that this was triggered by different calls to the random number generator that happened to generate "bad" timestamps that expose the known ORC timestamp bug in #6312.  To work around the test failures, orc_test was updated to avoid generating timestamps that are known to cause issues.

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala [hunk 1]
```diff
@@ -1851,6 +1851,13 @@ object GpuOverrides extends Logging {
         ("lhs", TypeSig.gpuNumeric, TypeSig.cpuNumeric),
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:1851]: nit: Can we add a psNote here?

**Review by revans2 — DISMISSED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala (hunk 1 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala]: done

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]
