### PR TITLE
Fix MT read memory limit defaulting to wrong size when off-heap limit is disabled

### LINKED ISSUE #14292: [BUG] multithreaded read limit defaults to wrong size, ignores non-pinned off heap memory
In this code

https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala#L484-L489

if off heap limit is not set, so it's "unlimited", the actual value of `nonPinnedLimit` here is set to -1, which HostAlloc interprets as unlimited, but the MT read limit interprets it as just -1, so effectively defaults to sizing off pinned limit only. It should instead be figuring out what the effective off heap limit actuall it based on the hardware, or otherwise come up with some kind of more sane default.

### PR DESCRIPTION
**Pull request by zpuller**
Fixes #14292.

### Description

When `spark.rapids.memory.host.offHeapLimit.enabled` is false (the default),
`getPinnedPoolAndOffHeapLimits` returns `-1` for the non-pinned limit (meaning unlimited).
The code that sets the default MT read memory limit was using this `-1` literally:

```scala
(0.9 * (pinnedSize + nonPinnedLimit)).toLong  // nonPinnedLimit == -1
```

With no pinned pool this produces `0`; with a pinned pool (e.g. 2 GiB) it produces `~0.9 *
pinnedSize`, sizing the limit off the pinned pool only and ignoring all non-pinned memory.

The fix extracts the hardware-derived off-heap limit computation from `getPinnedPoolAndOffHeapLimits`
into a shared `computeEffectiveOffHeapLimit` method, and uses it in `computeMtReadLimit` when
`nonPinnedLimit == -1` to derive a concrete total from hardware instead.

Note: `spark.rapids.sql.multiThreadedRead.memoryLimit.enabled` defaults to `false`, so impact is
limited to users who have explicitly enabled the feature. The hardware-derived calculation has a
known approximation limitation in certain environments (see #13628), called out in a new code
comment.

**Before (2 GiB pinned pool, off-heap limit disabled):** MT read limit ≈ 1.80 GiB (90% of pinned only)

**After:** MT read limit ≈ 78 GiB (90% of hardware-derived off-heap)

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [x] This PR has added new tests or modified existing tests to cover new code paths.
      `GpuDeviceManagerSuite` — "MT read limit should be 90% of total off heap when off heap limit
      disabled": calls `computeMtReadLimit` with `nonPinnedLimit=-1` and asserts the result equals
      90% of the hardware-derived off-heap total. Fails against pre-fix code, passes after.
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by zpuller** [comment]
build

**Comment by zpuller** [comment]
build

File: tests/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala
Comment (abellina) [inline tests/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala]: needs copyright updated.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala]: nit we should update this comment.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala [hunk 1]
```diff
@@ -485,22 +485,38 @@ object GpuDeviceManager extends Logging {
...
+      s"(90% of ${totalOffHeap / 1024 / 1024.0} MiB total off-heap)")
+    limit
+  }
+
+  private def computeEffectiveOffHeapLimit(conf: RapidsConf, sparkConf: SparkConf,
+      deviceCount: Int, memCheck: MemoryChecker): Long = {
     val confLimit = conf.offHeapLimit
-    val confLimitEnabled = conf.offHeapLimitEnabled
-    // This min limit of 4GB is somewhat arbitrary, but based on some testing which showed
-    // that the previous minimum of 15 MB * num cores was too little for certain benchmark
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala:502]: why remove this disclaimer?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala [hunk 2]
```diff
@@ -485,22 +485,38 @@ object GpuDeviceManager extends Logging {
...
+    }
+    val limit = (0.9 * totalOffHeap).toLong
+    logInfo(s"Setting MT read memory limit to ${limit / 1024 / 1024.0} MiB " +
+      s"(90% of ${totalOffHeap / 1024 / 1024.0} MiB total off-heap)")
+    limit
+  }
+
+  private def computeEffectiveOffHeapLimit(conf: RapidsConf, sparkConf: SparkConf,
+      deviceCount: Int, memCheck: MemoryChecker): Long = {
     val confLimit = conf.offHeapLimit
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala:520]: We have `conf.offHeapLimit` checked here and `conf.offHeapLimitEnabled` checked at the call site. It seems we then check for either enabled true/false or offHeapLimit >=0. It would be nice if we consistently checked for enabled, one way or the other, or had a function that returned true if offHeapLimit >= 0, and that's our only check?

Comment (zpuller) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala:520]: discussed offline: not able to consolidate because offHeapLimitEnabled and offHeap >= 0 are separate concerns, enabled controls when to enforce limits, >= 0 controls whether to auto-derive the limit size

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala (hunk 1 above)
Comment (zpuller) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala:502]: that was a mistake

**Comment by zpuller** [comment]
build

**Review by abellina — APPROVED** [review]
