### PR TITLE
Fix issues with canonicalization

### LINKED ISSUE #606: Multiple scans for same data source with TPC-DS query59 with delta format [BUG]
**Describe the bug**
image
when I use delta format of TPC-DS , query59 occurs this problem , but it  becomes normal when I set the format to parquet.

**Steps/Code to reproduce bug**
tpcdsTables.genData(
     location = "/user/work/data_100G_gpu",
     **format = "delta"**
     overwrite = true,
     partitionTables = true,
     useDoubleForDecimal = true,
     clusterByPartitionColumns = true,
     filterOutNullPartitionValues = false,
     tableFilter = Set.empty,
     numPartitions = 300,
     toolsLocation = Some("./tpc_toolkit"))

**Expected behavior**
when I use parquet format, big table named store_sales only scan once

**Environment details (please complete the following information)**
rapids-0.2

### PR DESCRIPTION
**Pull request by revans2**
This fixes #606 

While debugging this I ran into a number of errors in canonicalization of the plan that I fixed.  The one that was specifically causing #606 was how children was set in `GpuAggregateExpression`.  Spark does a lot of magic around Expression and SparkPlan, and if your `children` does not include parameters passed into your `case class` then some operations, like canonicalization, just skip them, and they stay unchanged.

### CODE REVIEW

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala [hunk 1]
```diff
@@ -834,14 +845,42 @@ case class GpuHashAggregateExec(
...
   //
   private[this] val aggregateBufferAttributes = {
     aggregateExpressions.flatMap(_.aggregateFunction.aggBufferAttributes)
   }
 
-  override def outputPartitioning: Partitioning = child.outputPartitioning
+  final override def outputPartitioning: Partitioning = {
+    if (hasAlias) {
+      child.outputPartitioning match {
+        case h: GpuHashPartitioning => h.copy(expressions = replaceAliases(h.expressions))
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:860]: nit (I think), so these both do the same? should do we do `GpuHashPartitioning | HashPartitioning`?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala [hunk 2]
```diff
@@ -834,14 +845,42 @@ case class GpuHashAggregateExec(
...
+        case h: HashPartitioning => h.copy(expressions = replaceAliases(h.expressions))
+        case other => other
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:862]: so why do other partitionings not need this?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+    case GetStructField(child, ordinal, Some(_)) => GetStructField(child, ordinal, None)
+    case _ => e
+  }
+
+  /** Remove TimeZoneId for Cast if needsTimeZone return false. */
+  def ignoreTimeZone(e: Expression): Expression = e match {
+    case c: CastBase if c.timeZoneId.nonEmpty && !c.needsTimeZone =>
+      c.withTimeZone(null)
+    case c: GpuCast if c.timeZoneId.nonEmpty =>
+      // TODO when we start to support time zones check for `&& !c.needsTimeZone`
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala:60]: need github issue for it?

Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala:60]: I would say it goes with general time zone support

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala (hunk 1 above)
Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala:860]: This all came from 

https://github.com/apache/spark/blob/branch-3.0/sql/core/src/main/scala/org/apache/spark/sql/execution/AliasAwareOutputPartitioning.scala

This is used by HashAggregate* and Project.  So technically we should look at putting this into Project as well too. In 3.1 it has been expanded and if you want we can look into this.  I don't think this is strictly needed for this issue.

**Comment by revans2** [comment]
@abellina are there changes you want me to make?

**Comment by abellina** [comment]
Sorry @revans2 I lost track of this one, nope. I am just going to resolve the conversations.
