### PR TITLE
Fix wrong row index offsets from native footer reader for deletion vectors [databricks]

### LINKED ISSUE #14564: [BUG] cuDF-based Delta DV reader returns incorrect results when NATIVE footer reader is used with split Parquet files
**Describe the bug**

  The cuDF-based Delta deletion vector reader returns incorrect query results when a Parquet file has multiple row groups and the `NATIVE` footer reader is used.

  The V2 DV reader (#14347, #14382, #14435, enabled by default in #14460) introduced a new dependency on `BlockMetaData.getRowIndexOffset()` to build file-global row indices for cuDF. Previously, the plugin
  never used this field — the V1 DV reader relied on Spark's `_metadata.row_index` column, and standard Parquet reads don't need row index offsets at all. As a result, `getRowIndexOffset()` returning incorrect
   values went unnoticed until the V2 reader started depending on it.

  The `NATIVE` footer reader path in `filterBlocks` produces `BlockMetaData` objects where `getRowIndexOffset()` returns wrong values:
  1. `readAndFilterFooter(file.start, file.length)` — C++ filters row groups by the split's byte range, returning only the matching row group(s)
  2. `serializeThriftFile()` — serializes this filtered footer
  3. `ParquetFileReader.readFooter(HMBInputFile, NO_FILTER)` — Java parses it and computes cumulative offsets via `generateRowGroupOffsets`

  Since `generateRowGroupOffsets` only sees the row groups in the split (not the full file), it computes offsets relative to the start of the split, not the start of the file. 

The `JAVA` footer reader in the plugin does not have this issue — it calls `ParquetFileReader.readFooter(conf,
  filePath, range(start, end))` which uses parquet-mr's `RangeMetadataFilter`. This filter computes offsets from the full file footer (all row groups) before filtering by byte range. The `NATIVE` reader reverses this order — filtering first in C++, then computing offsets from the already-filtered result.

  With wrong offsets, cuDF builds incorrect file-global row indices. The DV bitmap uses file-global indices, so it matches the wrong rows — some deletions are missed, others are applied incorrectly.

**Steps/Code to reproduce bug**

  // Create a single-file Delta table with multiple row groups
  spark.conf.set("parquet.block.size", "10000")
  spark.range(10000).selectExpr(
      "CAST(id AS INT) AS a",
      "CAST(id * 2 AS INT) AS b",
      "CAST(id * 3 AS INT) AS c"
  ).coalesce(1).write.format("delta") \
      .option("delta.enableDeletionVectors", "true") \
      .save(data_path)

  // Delete rows in later row groups
  spark.sql(f"DELETE FROM delta.`{data_path}` WHERE a >= 5000 AND a < 5100")

  // Read with NATIVE footer and small maxPartitionBytes to force splitting
  spark.conf.set("spark.rapids.sql.format.parquet.reader.footer.type", "NATIVE")
  spark.conf.set("spark.sql.files.maxPartitionBytes", "10000")
  spark.conf.set("spark.rapids.sql.delta.deletionVectors.predicatePushdown.enabled", "true")

  // CPU returns 9900 rows, GPU returns 10000 (deletions not applied)
  spark.sql(f"SELECT a FROM delta.`{data_path}`")

**Expected behavior**

GPU and CPU should return identical results.

### PR DESCRIPTION
**Pull request by jihoonson**
Fixes #14564.

### Description

  The native Parquet footer reader filters row groups by byte range in C++ before serialization. When `ParquetFileReader.readFooter` deserializes the result, it computes row index offsets assuming those row groups are the entire file. For splits that contain only a subset of the file's row groups, the offsets are wrong (e.g. always 0 for a single surviving row group). This breaks deletion vector filtering which relies on file-global row indices — some deletions are missed and others are applied to the wrong rows.

  The JAVA footer reader does not have this issue because parquet-mr's `RangeMetadataFilter` computes offsets from all row groups in the file before filtering by byte range.

  This PR uses the new `ParquetFooter.getRowIndexOffsets` JNI method (https://github.com/NVIDIA/spark-rapids-jni/pull/4445) to retrieve correct file-global offsets computed from all row groups before byte-range filtering, and apply them to the deserialized `BlockMetaData` objects after `ParquetFileReader.readFooter` reads the footer.

 Added `test_delta_deletion_vector_native_footer_multi_row_group` which demonstrates the bug. It creates a single-file Delta table with multiple row groups, deletes rows in later row groups, and forces per-row-group splits. It verifies whether the task assigned a non-first-row-group split correctly computes the row group offsets.

### Checklists

Documentation
- [ ] Updated for new or modified user-facing features or behaviors
- [x] No user-facing change

Testing
- [x] Added or modified tests to cover new code paths
- [ ] Covered by existing tests
      (Please provide the names of the existing tests in the PR description.)
- [ ] Not required

Performance
- [ ] Tests ran and results are added in the PR description
- [ ] Issue filed with a link in the PR description
- [x] Not required

### CODE REVIEW

**Comment by gerashegalov** [comment]
This should target 26.04 just like https://github.com/NVIDIA/spark-rapids-jni/pull/4445

**Comment by pxLi** [comment]
Note: Please re-trigger the CI checks once the new 26.04 nightly JNI build (from internal **spark-rapids-jni_nightly-pre_release** job) with [PR #4445](https://github.com/NVIDIA/spark-rapids-jni/pull/4445) is available.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala:736]: It is not this PR but this early return is a hack that makes one re-read this code many times because it's returning from `filterBlocks`  and not from withResource

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala [hunk 1]
```diff
@@ -733,16 +733,33 @@ protected case class GpuParquetFileFilterHandler(
...
+            // serialization, so readFooter can see only a subset and compute wrong
+            // offsets (e.g. always 0 for a single surviving row group). This breaks
+            // any logic relying on file-global row indices such as deletion vector
+            // filtering.
+            // So we compute the correct offsets from all row groups before filtering,
+            // and then apply them to the filtered blocks.
+            val blocks = footer.getBlocks
+            require(blocks.size() == rowIndexOffsets.length,
+              s"Row index offsets length (${rowIndexOffsets.length}) != " +
+              s"blocks count (${blocks.size()})")
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala]: How is the user to act on this message. Can the message be more helpful?

**Comment by jihoonson** [comment]
@greptile-apps I have addressed your comments. Please take another look.

File: integration_tests/src/main/python/delta_lake_test.py [hunk 2]
```diff
@@ -684,3 +670,58 @@ def read_table(spark):
...
+            .save(data_path)
+        # Delete rows in later row groups. With ~800 rows per row group,
+        # rows a >= 5000 are in row group 6+.
+        spark.sql(f"DELETE FROM delta.`{data_path}` WHERE a >= 5000 AND a < 5100")
+
+    with_cpu_session(setup_tables, conf=write_conf)
+
+    # Read only column 'a' from the 3-column table.
+    assert_gpu_and_cpu_are_equal_collect(
+        lambda spark: spark.sql(f"SELECT a FROM delta.`{data_path}`"),
```
Comment (gerashegalov) [inline integration_tests/src/main/python/delta_lake_test.py]: Do we need to test more projections. Two columns, zero columns because of the special treatment in the code.

**Review by gerashegalov — DISMISSED** [review]
LGTM, some things to consider

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala (hunk 1 above)
Comment (jihoonson) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala]: Hmm, this is an internal state sanity check, and should never happen in production. I'm not sure how we can make this message more helpful. If it ever happens, there is nothing the user can do but file an issue to us. Are you thinking of something like "please file an issue on spark-rapids github repo"?

File: integration_tests/src/main/python/delta_lake_test.py (hunk 2 above)
Comment (jihoonson) [reply integration_tests/src/main/python/delta_lake_test.py]: Good suggestion. I added tests as suggested. The zero-column test revealed another bug with the PERFILE reader. I filed https://github.com/NVIDIA/spark-rapids/issues/14574 for it.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala
Comment (jihoonson) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala:736]: I agree. This needs some refactoring.

**Comment by pxLi** [comment]
With new JNI, failed other compilation errors https://github.com/NVIDIA/spark-rapids/actions/runs/24177265116/job/70586032608?pr=14572

for spark 33x
`value setRowIndexOffset is not a member of org.apache.parquet.hadoop.metadata.BlockMetaData`

```
[INFO] --- scala:4.9.2:compile (scala-compile-first) @ rapids-4-spark-sql_2.12 ---
[INFO] Compiler bridge file: /home/runner/.m2/repository/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.12-1.10.0-bin_2.12.21__61.0-1.10.0_20240505T232140.jar
[INFO] compiling 546 Scala sources and 36 Java sources to /home/runner/work/spark-rapids/spark-rapids/sql-plugin/target/spark331/classes ...
Error: ] /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala:733: value setRowIndexOffset is not a member of org.apache.parquet.hadoop.metadata.BlockMetaData
Error: ] /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala:765: value setRowIndexOffset is not a member of org.apache.parquet.hadoop.metadata.BlockMetaData
Error: [ERROR] two errors found
```

**Comment by jihoonson** [comment]
I shimplified `BlockMetaData.setRowIndexOffset` in https://github.com/NVIDIA/spark-rapids/pull/14572/changes/69dd7b9b4feac6e1a48732f4199ea76e2e000322. I do not like this very much as `setRowIndexOffset` is just no-op for Spark 3.3.x, but I chose this as it's the simplest solution. A better approach will be shimplifying the [whole logic](https://github.com/NVIDIA/spark-rapids/blob/21358f33084264cc33998ebceeaf760a6f09e05f/sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala#L720-L754) to read the footer for the native reader. Filed https://github.com/NVIDIA/spark-rapids/issues/14577 for future improvement.

**Comment by jihoonson** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala
Comment (jihoonson) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala:736]: Filed https://github.com/NVIDIA/spark-rapids/issues/14577

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala (hunk 1 above)
Comment (gerashegalov) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala]: It would be great if we have additional context. What file is causing the issue? 

We can ask to verify if the file is readable on CPU, ask to file an issue in this case

Comment (jihoonson) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala]: Makes sense. Included the filePath and the file range.

**Comment by jihoonson** [comment]
build

File: integration_tests/src/main/python/delta_lake_test.py [hunk 3]
```diff
@@ -684,3 +670,115 @@ def read_table(spark):
...
+
+
+@allow_non_gpu(*delta_meta_allow)
+@delta_lake
+@ignore_order(local=True)
+@pytest.mark.parametrize("parquet_reader_type", ["PERFILE", "COALESCING", "MULTITHREADED"], ids=idfn)
+@pytest.mark.parametrize("footer_type", ["NATIVE", "JAVA"], ids=idfn)
+@pytest.mark.parametrize("query", [
+    "SELECT a FROM delta.`{path}`",
+    "SELECT a, b FROM delta.`{path}`",
```
Comment (gerashegalov) [inline integration_tests/src/main/python/delta_lake_test.py:682]: nit: could just parametrize the sets of projectected columns

**Review by gerashegalov — APPROVED** [review]
LGTM
