### PR TITLE
Fix removal of internal metadata information in 350 shim

### LINKED ISSUE #8844: [AUDIT][SPARK-43123][SQL] Internal field metadata should not be leaked to catalogs
This PR fixes the internal field metadata leakage by updating CTAS/RTAS commands to remove such metadata before table creation. Our definition of class `GpuCreateDataSourceTableAsSelectCommand` might require similar changes.

Apache Commit - [apache/spark@ 4c938d62d7](https://github.com/apache/spark/commit/4c938d62d7)

### PR DESCRIPTION
**Pull request by parthosa**
Fixes #8844. This PR adds fix for removing internal metadata information from the schema while using CTAS. This feature was added in Spark 3.5.0.

### Changes:
Created a new class `SchemaMetadataShims`. It includes a new method `getCleanedSchema()` which calls spark's `removeInternalMetadata()`.
   - This function removes the metadata properties having keys that are meant for internal usage (eg, `FILE_SOURCE_METADATA_COL_ATTR_KEY`)  
```
schema = SchemaMetadataShims.getCleanedSchema(result.schema)
```

### Testing
- Added unit test to use CTAS query to create a new table as select from another DF.
- Added a metadata property having internal keys.
- Tested if the metadata was finally removed (set as NULL).
- Tested in Spark 3.4.0, metadata does not get removed.

### CODE REVIEW

File: sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/GpuCreateDataSourceTableAsSelectCommandShims.scala [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+        table.storage.locationUri
+      }
+      val result = saveDataIntoTable(
+        sparkSession, table, tableLocation, SaveMode.Overwrite, tableExists = false)
+      val newTable = table.copy(
+        storage = table.storage.copy(locationUri = tableLocation),
+        // We will use the schema of resolved.relation as the schema of the table (instead of
+        // the schema of df). It is important since the nullability may be changed by the relation
+        // provider (for example, see org.apache.spark.sql.parquet.DefaultSource).
+        schema = removeInternalMetadata(result.schema))
```
Comment (razajafri) [inline sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/GpuCreateDataSourceTableAsSelectCommandShims.scala:88]: It's better to refactor this change into a separate call and call it from an unshimmed version

File: tests/src/test/spark350/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommandSuite.scala [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+import org.apache.spark.sql.connector.catalog.{Column, Identifier}
+import org.apache.spark.sql.connector.catalog.CatalogV2Implicits._
+import org.apache.spark.sql.types._
+import org.apache.spark.util.Utils
+
+class GpuCreateDataSourceTableAsSelectCommandSuite
+  extends SparkQueryCompareTestSuite
+  with FunSuiteWithTempDir {
+
+  test("SPARK-43123: Metadata column related field metadata should not be leaked to catalogs") {
```
Comment (razajafri) [inline tests/src/test/spark350/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommandSuite.scala:37]: Use our issue number here which will have the SPARK issue attached to it

File: sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/GpuCreateDataSourceTableAsSelectCommandShims.scala (hunk 1 above)
Comment (parthosa) [reply sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/GpuCreateDataSourceTableAsSelectCommandShims.scala]: Thanks @razajafri. Created a Helper class `SchemaMetadataShims` to avoid code duplication.

**Review by razajafri — APPROVED** [review]
LGTM

**Comment by razajafri** [comment]
build

**Review by jlowe — APPROVED** [review]
