### PR TITLE
Prevent fixup of GpuShuffleExchangeExec when using EXECUTOR_BROADCAST [databricks]

### LINKED ISSUE #7575: [BUG] On Databricks 11.3, Executor broadcast shuffles should stay on GPU even without columnar children
**Describe the bug**
On Databricks 11.3, the executor side broadcast was introduced (via shuffle origin `EXECUTOR_BROADCAST`) in broadcast joins. For joins on the GPU to be successful, both the exchange and the broadcast join must be on the GPU.  

Since we never handled the concept of broadcast join consuming a `ShuffleExchangeExec`, we have to handle exceptions to when the shuffles used here are sent back to CPU. In particular, this case:

```
                            !Exec <ShuffleExchangeExec> cannot run on GPU because Columnar exchange without columnar children is inefficient
```
In the executor_broadcast case, we still have to accept the shuffle in this case because it's part of the broadcast join, which is still more efficient to do on the GPU. 

**Steps/Code to reproduce bug**
Run NDS 2.0 queries q2 and q59 among potentially more on Databricks 11.3

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #7575.

This PR prevents fixup for GpuShuffleExchangeExec during AQE when shuffleOrigin is EXECUTOR_BROADCAST. Even though generally shuffle without columnar children is inefficient, it is still better to do an executor broadcast join on the GPU. This prevents the fixup code from sending it back to CPU based on previous assumptions of Exchanges.

Signed-off-by: Navin Kumar <navink@nvidia.com>

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala [hunk 1]
```diff
@@ -148,6 +148,8 @@ trait SparkShims {
 
   def aqeShuffleReaderExec: ExecRule[_ <: SparkPlan]
 
+  def shuffleCanBeFixedUp(shuffle: ShuffleExchangeLike): Boolean = true
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala:151]: This method name is too generic, and there's no docs to help explain it.  Honestly seems like this should be called `isNotExecutorBroadcastShuffle` given how it's written (and therefore would be a bit better to flip the predicate result and call it `isExecutorBroadcastShuffle` instead).

File: integration_tests/src/main/python/aqe_test.py [hunk 2]
```diff
@@ -128,6 +128,54 @@ def do_join(spark):
...
+
+    with_cpu_session(prep)
+
+    def do_it(spark):
+        newdf2 = spark.read.parquet(data_path)
+        newdf2.createOrReplaceTempView("df2")
+
+        # Using parse_url to fallback the project in the subquery that is joined here
+        # Since parse_url is an expression that will never likely be ported to GPU, it 
+        # makes for a suitable test here
```
Comment (jlowe) [inline integration_tests/src/main/python/aqe_test.py:164]: Not a must-fix, but a better, more future-proof way to accomplish this is to explicitly disable an expression.  For example, we could do a string concatenation with a literal string and then explicitly disable the concat expression via `spark.rapids.sql.expression.Concat=false`.

**Review by jlowe — DISMISSED** [review]

**Comment by NVnavkumar** [comment]
build

**Comment by NVnavkumar** [comment]
build

**Comment by NVnavkumar** [comment]
build

**Review by jlowe — DISMISSED** [review]
CI failure is unrelated, assume it will clear when rerun after fix is merged into branch-23.02.

File: sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala [hunk 3]
```diff
@@ -69,6 +69,13 @@ object SparkShimImpl extends Spark321PlusDBShims {
 
   override def reproduceEmptyStringBug: Boolean = false
 
+  override def isExecutorBroadcastShuffle(shuffle: ShuffleExchangeLike): Boolean = {
+    shuffle.shuffleOrigin match {
+      case EXECUTOR_BROADCAST => true
+      case _ => false
+    }
```
Comment (gerashegalov) [inline sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala:76]: maybe just 
```suggestion
    shuffle.shuffleOrigin == EXECUTOR_BROADCAST 
```

File: sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ShuffleOriginUtil.scala [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.nvidia.spark.rapids.shims
+
+import scala.collection.immutable.HashSet
```
Comment (gerashegalov) [inline sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ShuffleOriginUtil.scala:19]: Don't pick an implementation, let Scala figure it out by using `Set`

File: sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ShuffleOriginUtil.scala [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+
+import org.apache.spark.sql.execution.exchange.{ENSURE_REQUIREMENTS, REBALANCE_PARTITIONS_BY_COL, REBALANCE_PARTITIONS_BY_NONE, REPARTITION_BY_COL, REPARTITION_BY_NUM, ShuffleOrigin}
+
+object ShuffleOriginUtil {
+  private val knownOrigins: HashSet[ShuffleOrigin] = HashSet(ENSURE_REQUIREMENTS,
```
Comment (gerashegalov) [inline sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ShuffleOriginUtil.scala:24]:
```suggestion
  private val knownOrigins = Set(ENSURE_REQUIREMENTS,
```

Comment (NVnavkumar) [reply sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ShuffleOriginUtil.scala]: Cleaned this up, but Scala type interference wasn't completely working, so still need to specify type on `val`, so looks like `private val knownOrigins: Set[ShuffleOrigin]`

Comment (gerashegalov) [reply sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ShuffleOriginUtil.scala]: it's because of the the signature for `def isSupported(...)`, I should have suggested  `private val knownOrigins = Set[ShuffleOrigin](...)`

File: integration_tests/src/main/python/aqe_test.py [hunk 6]
```diff
@@ -128,6 +128,55 @@ def do_join(spark):
...
+            select 
+                a.name.firstname,
+                a.name.lastname,
+                b.full_url
+            from df2 a join (select id, concat(website,'/path') as full_url from df2) b
+                on a.id = b.id
+            """
+        )
+
+    conf = copy_and_update({ 'spark.rapids.sql.expression.Concat': 'false' }, _adaptive_conf)
```
Comment (gerashegalov) [inline integration_tests/src/main/python/aqe_test.py:172]: it does not make a semantic difference but `copy_and_update` is meant to create a clone of the conf object you want to preserve (first arg) with the update from the patch (second arg). So for consistency should be:
  ```suggestion
    conf = copy_and_update(_adaptive_conf, {'spark.rapids.sql.expression.Concat': 'false'})
```

**Review by gerashegalov — APPROVED** [review]
LGTM, just nits. the essence of the test is much more clear now

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Review by gerashegalov — APPROVED** [review]
