### PR TITLE
Fix ci problem caused by iceberg detect version.

### LINKED ISSUE #14512: [BUG] UnsupportedClassVersionError for IcebergSparkSessionExtensions in spark-3.5.0 rocky9 cuda13 integration tests
**Describe the bug**
Build: rapids_integration-pre_release-github/957

Multiple pytest test files fail in the 'spark-3.5.0 on rocky9 w/ cuda13' stage with `UnsupportedClassVersionError` when Spark tries to initialize `IcebergSparkSessionExtensions`. The Iceberg Spark extensions JAR was compiled with Java 11 (class file version 55.0), but the test JVM only supports up to Java 8 (class file version 52.0). This causes `SparkSession.conf` initialization to fail for all test workers, resulting in 505 errors across nearly all test modules.

Error logs:
```
ERROR ../../src/main/python/sort_test.py - py4j.protocol.Py4JJavaError: An error occurred while calling o91.conf.
: java.lang.UnsupportedClassVersionError: org/apache/iceberg/spark/ExtendedParser has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions.$anonfun$apply$1(IcebergSparkSessionExtensions.scala:35)
	at org.apache.spark.sql.SparkSessionExtensions.$anonfun$buildParser$1(SparkSessionExtensions.scala:308)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.sqlParser$lzycompute(BaseSessionStateBuilder.scala:138)
	at org.apache.spark.sql.SparkSession.conf$lzycompute(SparkSession.scala:185)
	at org.apache.spark.sql.SparkSession.conf(SparkSession.scala:185)
```

**Environment details**
- Spark version: 3.5.0 scala2.12 bin
- CUDA classifier: cuda13 (Driver 590.44.01)
- OS: Rocky Linux 9
- JVM: Java 8 (class file version 52.0)
- Iceberg extension JAR compiled with: Java 11 (class file version 55.0)
- Commit: 1ec241dc (PR #14494 backport to 26.04)

### PR DESCRIPTION
**Pull request by liurenjie1024**
Fixes #14512 .

### Description

The iceberg version detect was designed to be run in premerge ci, but we put it in default test mode by mistake. This pr fix it, e.g removing it out of default mode test, and only enable it in premerge ci.

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [ ] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

**Comment by pxLi** [comment]
suppose this should target to release/26.04

**Comment by pxLi** [comment]
~~Q: https://github.com/NVIDIA/spark-rapids/issues/14512 is not a premerge CI problem. Instead, it failed during non-iceberg test runs. This change seems not to be related to the reported issue?~~

As discussed offline, this change is intended to fix the nightly test that does not match the title. Feel free to move the test case to the pre-merge script later

**Comment by pxLi** [comment]
https://github.com/NVIDIA/spark-rapids/blob/release/26.04/jenkins/spark-tests.sh#L530
If no quick fix, please help remove the iceberg_detect cases from `DEFAULT` test_type to unblock other nightly cases thanks

File: jenkins/spark-tests.sh [hunk 1]
```diff
@@ -278,19 +278,13 @@ run_iceberg_tests() {
 
   local test_type=${1:-'default'}
 
-  # Version detection test: runs against ALL iceberg versions for the current Spark runtime
+  # Version detection test: runs against supported iceberg versions for the
+  # current Spark version.  Running unsupported versions (e.g. Iceberg 1.9+
+  # on Spark 3.5.0 with Java 8) causes UnsupportedClassVersionError that
+  # crashes every pytest worker during test collection.
```
Comment (gerashegalov) [inline jenkins/spark-tests.sh]: is this is long term fix or will you file an issue for activating different versions based on the JAVA_HOME version?

**Comment by liurenjie1024** [comment]
build
