### PR TITLE
Perform explicit UnsafeRow projection in ColumnarToRow transition

### LINKED ISSUE #5189: [BUG] Reading from iceberg table will fail.
Currently our plugin does not support iceberg so we want the iceberg reading can fallback to CPU gracefully instead of fail.

**Env:**
Spark 3.1.1 standalone cluster with Hive integration
22.04 snapshot jars

Below is a simple reading test and it will fail with our plugin:
```
spark-shell --packages org.apache.iceberg:iceberg-spark-runtime-3.1_2.12:0.13.1 \
    --conf spark.sql.session.timeZone=UTC \
    --conf "spark.driver.extraJavaOptions=-Duser.timezone=UTC" \
    --conf "spark.executor.extraJavaOptions=-Duser.timezone=UTC" \
    --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
    --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
    --conf spark.sql.catalog.spark_catalog.type=hive
```

After that, creating a demo table and run a query:
```
spark.sql("""CREATE TABLE spark_catalog.default.demo (id bigint, data string) USING iceberg;""")
spark.sql("""INSERT INTO spark_catalog.default.demo VALUES (1, 'a'), (2, 'b'), (3, 'c');""")
spark.sql("""select count(distinct id) from spark_catalog.default.demo""").show
```
Error:
```
java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.GenericInternalRow cannot be cast to org.apache.spark.sql.catalyst.expressions.UnsafeRow
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeRowToColumnarBatchIterator.fillBatch(Unknown Source)
	at com.nvidia.spark.rapids.UnsafeRowToColumnarBatchIterator.next(UnsafeRowToColumnarBatchIterator.java:122)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeRowToColumnarBatchIterator.next(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:283)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:238)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:235)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:181)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:283)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:238)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:235)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:181)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:283)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:238)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:235)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:181)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:283)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:238)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:235)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:181)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:242)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:188)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:239)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:216)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:256)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

CPU Spark:
```
scala> spark.conf.set("spark.rapids.sql.enabled", false)

scala>  spark.sql("""select count(distinct id) from spark_catalog.default.demo""").show
+------------------+
|count(DISTINCT id)|
+------------------+
|                 3|
+------------------+
```

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #5189.

The row to columnar transition was assuming that every row coming in was an `UnsafeRow` but that is not always the case.  This adds an explicit unsafe projection to the generated unsafe row iterator to handle those cases.

### CODE REVIEW

**Comment by jlowe** [comment]
Keeping this as a draft until this gets some at-scale performance tests

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
Premerge failed due to transitive Cloudera dependency, rekicking the build.

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala [hunk 1]
```diff
@@ -690,16 +690,29 @@ object GeneratedUnsafeRowToCudfRowIterator extends Logging {
...
+    ctx.currentVars = null
+    ctx.INPUT_ROW = internalRow
+
+    val generateUnsafeProj = GenerateUnsafeProjection.createCode(ctx,
+      schema.zipWithIndex.map { case (attr, i) => BoundReference(i, attr.dataType, attr.nullable) }
+    )
+
+    val iterRef = ctx.addReferenceObj("iter", input, classOf[Iterator[UnsafeRow]].getName)
+    val schemaRef = ctx.addReferenceObj("schema", schema,
+      classOf[Array[Attribute]].getCanonicalName)
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala:704]: this one became `getCanonicalName` instead of `getName` mostly curious on why.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala [hunk 2]
```diff
@@ -757,19 +770,22 @@ object GeneratedUnsafeRowToCudfRowIterator extends Logging {
...
-         |    super((scala.collection.Iterator<UnsafeRow>)references[0],
-         |      (org.apache.spark.sql.catalyst.expressions.Attribute[])references[1],
-         |      (com.nvidia.spark.rapids.CoalesceSizeGoal)references[2],
-         |      (com.nvidia.spark.rapids.GpuMetric)references[3],
-         |      (com.nvidia.spark.rapids.GpuMetric)references[4],
-         |      (com.nvidia.spark.rapids.GpuMetric)references[5],
-         |      (com.nvidia.spark.rapids.GpuMetric)references[6],
-         |      (com.nvidia.spark.rapids.GpuMetric)references[7],
-         |      (com.nvidia.spark.rapids.GpuMetric)references[8]);
+         |    super(
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala:778]: `references` are no longer used in the body of this function. Should we remove them from the arguments?

**Review by abellina — COMMENTED** [review]
Minor nits

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala (hunk 2 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala:778]: It is referenced.  Each of the *Ref values expands to a specific index in `references` with an explicit cast to the expected class.  It's producing the same string text to compile as it did before, but with the advantage that it doesn't need to manually keep the reference indices and `addReferenceObj` call order in sync.

**Review by abellina — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
The latest code changes do not appear to have a significant performance impact. Thanks to @mattahrens for running some performance tests.  This should now be ready for review.

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
@revans2 @tgravescs if one of you could take a look that would be great, as it needs a codeowner approval as well.

File: jenkins/spark-tests.sh [hunk 3]
```diff
@@ -159,6 +159,23 @@ export SCRIPT_PATH="$(pwd -P)"
...
+  # Iceberg does not support Spark 3.3+ yet
+  if [[ "$ICEBERG_SPARK_VER" < "3.3" ]]; then
+    SPARK_SUBMIT_FLAGS="$BASE_SPARK_SUBMIT_ARGS $SEQ_CONF \
+      --packages org.apache.iceberg:iceberg-spark-runtime-${ICEBERG_SPARK_VER}_2.12:${ICEBERG_VERSION} \
+      --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
+      --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
+      --conf spark.sql.catalog.spark_catalog.type=hadoop \
+      --conf spark.sql.catalog.spark_catalog.warehouse=/tmp/spark-warehouse-$$" \
+      ./run_pyspark_from_build.sh -m iceberg --iceberg
+  fi
```
Comment (abellina) [inline jenkins/spark-tests.sh:176]: nit, should this exit or print a message when it can't run iceberg but we've asked it to?

File: integration_tests/README.md [hunk 4]
```diff
@@ -387,6 +387,13 @@ The tests can be enabled by appending the option `--fuzz_test` to the command.
 
 To reproduce an error appearing in the fuzz tests, you also need to add the flag `--debug_tmp_path` to save the test data.
 
+### Enabling Iceberg tests
```
Comment (abellina) [inline integration_tests/README.md:390]: suggest we use "Apache Iceberg" the first time we refer to Iceberg.

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java [hunk 5]
```diff
@@ -43,7 +44,7 @@
  * be generated based off of the schema.
```
Comment (revans2) [inline sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java:44]: nit: Could we update the docs a bit? Explain what is happening with InternalRow?

**Review by revans2 — APPROVED** [review]
Just a minor nit on top of what @abellina found

File: sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java (hunk 5 above)
Comment (jlowe) [reply sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java:44]: I renamed the classes from UnsafeRow -> InternalRow to make this a bit clearer and added a small blurb about the rows being converted to UnsafeRow before going to ColumnarBatch.

**Comment by jlowe** [comment]
build

**Review by abellina — APPROVED** [review]

**Review by revans2 — APPROVED** [review]
