### PR TITLE
Fix compilation and scaladoc warnings

### LINKED ISSUE #1114: [BUG] Unreachable code warnings in GPU window code
**Describe the bug**
Building the plugin results in the following unreachable code warnings:
```
[WARNING] /home/jlowe/src/rapids-plugin-4-spark/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala:196: unreachable code
[WARNING]     case pythonFunc: GpuPythonUDF => pythonFunc
[WARNING]                                      ^
[WARNING] /home/jlowe/src/rapids-plugin-4-spark/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExec.scala:265: unreachable code
[WARNING]             case _: GpuPythonUDF => collect("AGGREGATE", frame, e)
```

**Expected behavior**
Code should compile without unreachable code warnings

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #1114, #1115, and #1149.

This cleans up compilation and scaladoc warnings in the build.

### CODE REVIEW

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala [hunk 1]
```diff
@@ -204,8 +204,6 @@ case class GpuWindowExpression(windowFunction: Expression, windowSpec: GpuWindow
       case other =>
         throw new IllegalStateException(s"${other.getClass} is not a supported window aggregation")
     }
-    // Add support for Pandas (Python) UDF
-    case pythonFunc: GpuPythonUDF => pythonFunc
```
Comment (jlowe) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala:208]: `GpuPythonUDF` derives from `GpuAggregateWindowFunction` which is why the compiler was complaining.  This has the same code as that for the `GpuAggregateWindowFunction` hence it can simply be deleted.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala [hunk 2]
```diff
@@ -262,7 +262,6 @@ trait GpuWindowInPandasExecBase extends UnaryExecNode with GpuExec {
           function match {
             case GpuAggregateExpression(_, _, _, _, _) => collect("AGGREGATE", frame, e)
             case _: GpuAggregateWindowFunction => collect("AGGREGATE", frame, e)
-            case _: GpuPythonUDF => collect("AGGREGATE", frame, e)
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala:265]: Similar situation here.  `GpuPythonUDF` derives from `GpuAggregateWindowFunction`, hence the unreachable code warning.  The implementation here is the same as the case that will be taken in practice, so this can simply be deleted.

**Comment by jlowe** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala (hunk 2 above)
Comment (revans2) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala:265]: Because this is in a file that is specific to the pandas operations it might be nice to put a comment by line 263 just to say that this includes `GpuPythonUDF`

**Review by revans2 — APPROVED** [review]
Just a nit about a comment

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]
