### PR TITLE
Fix oom of iceberg ci

### LINKED ISSUE #14407: [BUG] Iceberg integration tests fail with executor OOM (exit code 137) during GPU write operations
**Describe the bug**
Build: rapids_it-iceberg-dev/28

Two Iceberg integration tests failed due to Spark executor OOM kills (exit code 137) during GPU write operations.

Error logs:
```
FAILED iceberg_overwrite_dynamic_test.py::test_insert_overwrite_dynamic_bucket_partitioned_full_coverage[truncate(10, decimal128_col)] - py4j.protocol.Py4JJavaError: An error occurred while calling o91.sql.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2872.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2872.0 (TID 75756) executor 0: ExecutorLostFailure (executor 0 exited caused by one of the running tasks) Reason: Command exited with code 137
	at org.apache.spark.sql.execution.datasources.v2.GpuV2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:123)

FAILED iceberg_merge_test.py::test_iceberg_merge_full_coverage[truncate(5, string_col)-merge-on-read] - py4j.protocol.Py4JJavaError: An error occurred while calling o78018.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 330 in stage 2727.0 failed 1 times, most recent failure: Lost task 330.0 in stage 2727.0 (TID 100348) executor 0: ExecutorLostFailure (executor 0 exited caused by one of the running tasks) Reason: Command exited with code 137
```

**Environment details**
- Spark 3.5.5, Scala 2.12, RAPIDS plugin 26.04.0-SNAPSHOT
- Iceberg 1.6.1, 5 parallel test workers
- Executor memory: 6G, GPU: NVIDIA A30 (24576MiB)
- GPU alloc fraction: ~0.196 per worker (5 workers)

### PR DESCRIPTION
**Pull request by liurenjie1024**
Fixes #14407 .

### Description

After debugging, we found that most memory are consumed by iceberg's fanout write. In this pr, we disabled fanout writer by default, and add some standalone test case for it. And reduced the driver memory to 1G and worker memory to 2G.

### Checklists

- [x] This PR has added documentation for new or modified features or behaviors.
- [x] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

File: jenkins/spark-tests.sh [hunk 1]
```diff
@@ -293,13 +293,15 @@ run_iceberg_tests() {
     echo "Running Iceberg tests for Iceberg version $ICEBERG_VERSION"
     if [[ "$test_type" == "default" ]]; then
       echo "!!! Running iceberg tests"
-      PYSP_TEST_spark_driver_memory=6G \
-      PYSP_TEST_spark_executor_memory=6G \
-      PYSP_TEST_spark_jars_packages=org.apache.iceberg:iceberg-spark-runtime-${ICEBERG_SPARK_VER}_${SCALA_BINARY_VER}:${ICEBERG_VERSION} \
+      env \
+        PYSP_TEST_spark_driver_memory=1G \
```
[the remark this answers is not in the document]
Comment (liurenjie1024) [reply jenkins/spark-tests.sh:314]: Fixed.

**Comment by liurenjie1024** [comment]
Seems a break in spark-rapids-jni, will wait for another fix.

File: jenkins/spark-tests.sh [hunk 2]
```diff
@@ -293,13 +293,15 @@ run_iceberg_tests() {
...
+        PYSP_TEST_spark_executor_memory=2G \
+        PYSP_TEST_spark_jars_packages=org.apache.iceberg:iceberg-spark-runtime-${ICEBERG_SPARK_VER}_${SCALA_BINARY_VER}:${ICEBERG_VERSION} \
         PYSP_TEST_spark_sql_extensions="org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions" \
         PYSP_TEST_spark_sql_catalog_spark__catalog="org.apache.iceberg.spark.SparkSessionCatalog" \
         PYSP_TEST_spark_sql_catalog_spark__catalog_type="hadoop" \
         PYSP_TEST_spark_sql_catalog_spark__catalog_warehouse="/tmp/spark-warehouse-$RANDOM" \
+        "PYSP_TEST_spark_sql_catalog_spark__catalog_table-default_write_spark_fanout_enabled=false" \
```
Comment (jihoonson) [inline jenkins/spark-tests.sh:321]: Per https://iceberg.apache.org/docs/nightly/spark-configuration/#write-options, `write.spark.fanout.enabled` seems to be false by default. Why was it enabled before?

Comment (liurenjie1024) [reply jenkins/spark-tests.sh:321]: The logic is a little more complicated: https://github.com/apache/iceberg/blob/71cbe17cea5cac567920779de924eba62432934b/spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java#L198

**Comment by liurenjie1024** [comment]
build

**Comment by liurenjie1024** [comment]
build

**Comment by liurenjie1024** [comment]
build

**Comment by nvauto** [comment]
**NOTE: release/26.04 has been created from main. Please retarget your PR to release/26.04 if it should be included in the release.**

File: jenkins/spark-tests.sh (hunk 2 above)
Comment (jihoonson) [reply jenkins/spark-tests.sh:321]: Ah, so the fanout will be enabled by default if the ordering does not exist in the query. Makes sense to explicitly disable it then.

Comment (jihoonson) [reply jenkins/spark-tests.sh:321]: I think it would be nice to have some file to store these configs in the repo and read it for testing instead of hard-coding them in the script. Let's consider doing it if this config list grows.

Comment (jihoonson) [reply jenkins/spark-tests.sh:321]: BTW, let's document this in https://github.com/NVIDIA/spark-rapids/tree/main/integration_tests#enabling-apache-iceberg-tests.

Comment (liurenjie1024) [reply jenkins/spark-tests.sh:321]: Fixed.

**Comment by liurenjie1024** [comment]
build

**Comment by pxLi** [comment]
build

File: jenkins/spark-tests.sh [hunk 3]
```diff
@@ -309,14 +309,16 @@ run_iceberg_tests() {
     echo "Running Iceberg tests for Iceberg version $ICEBERG_VERSION"
     if [[ "$test_type" == "default" ]]; then
       echo "!!! Running iceberg tests"
-      EXPECTED_ICEBERG_VERSION=${ICEBERG_VERSION} \
-      PYSP_TEST_spark_driver_memory=6G \
-      PYSP_TEST_spark_executor_memory=6G \
-      PYSP_TEST_spark_jars_packages=org.apache.iceberg:iceberg-spark-runtime-${ICEBERG_SPARK_VER}_${SCALA_BINARY_VER}:${ICEBERG_VERSION} \
+      env \
+        EXPECTED_ICEBERG_VERSION=${ICEBERG_VERSION} \
+        PYSP_TEST_spark_driver_memory=1G \
```
Comment (gerashegalov) [inline jenkins/spark-tests.sh:314]: How was 1G validated?  Is this not too tight?

File: integration_tests/src/main/python/iceberg/iceberg_delete_test.py [hunk 4]
```diff
@@ -122,12 +122,13 @@ def test_iceberg_delete_unpartitioned_table(spark_tmp_table_factory, delete_mode
...
     )
 
-def _do_test_iceberg_delete_partitioned_table(spark_tmp_table_factory, partition_col_sql, delete_mode):
+def _do_test_iceberg_delete_partitioned_table(spark_tmp_table_factory, partition_col_sql, delete_mode, table_properties=None):
     """Helper function for partitioned table DELETE tests."""
     do_delete_test(
         spark_tmp_table_factory,
         lambda spark, table: spark.sql(f"DELETE FROM {table} WHERE _c2 % 3 = 0"),
         partition_col_sql=partition_col_sql,
+        table_properties=table_properties,
```
Comment (gerashegalov) [inline integration_tests/src/main/python/iceberg/iceberg_delete_test.py:131]: maybe in a futue RP, can we reconcile/standardize whether we name this table_props or table_properties for easier grepping.

File: integration_tests/src/main/python/iceberg/iceberg_overwrite_dynamic_test.py [hunk 5]
```diff
@@ -386,3 +387,14 @@ def overwrite_data(spark, table_name):
...
+
+@iceberg
+@datagen_overrides(seed=0, reason='https://github.com/NVIDIA/spark-rapids-jni/issues/4016')
+@ignore_order(local=True)
+@pytest.mark.skipif(is_iceberg_remote_catalog(), reason="Skip for remote catalog to reduce test time")
+def test_insert_overwrite_dynamic_partitioned_fanout_enabled(spark_tmp_table_factory):
+    _do_test_insert_overwrite_dynamic_partitioned(
+        spark_tmp_table_factory,
+        "year(_c9)",
+        table_prop={"format-version": "2", "write.spark.fanout.enabled": "true"})
```
Comment (gerashegalov) [inline integration_tests/src/main/python/iceberg/iceberg_overwrite_dynamic_test.py:400]: why is format-version passed here but not [here ](https://github.com/NVIDIA/spark-rapids/pull/14464/changes#diff-aa1851c0c87f549d0cfd26c36857d5b2f5e2ed9524238d6c02752388234f8869R600)
when setting "write.spark.fanout.enabled". Maybe add a comment

File: jenkins/spark-tests.sh (hunk 3 above)
Comment (liurenjie1024) [reply jenkins/spark-tests.sh:314]: We ran it in pipeline and locally.

File: integration_tests/src/main/python/iceberg/iceberg_overwrite_dynamic_test.py (hunk 5 above)
Comment (liurenjie1024) [reply integration_tests/src/main/python/iceberg/iceberg_overwrite_dynamic_test.py:400]: You mean in the test script env? Default format version changes with iceberg version, and it has no much impact.

File: integration_tests/src/main/python/iceberg/iceberg_delete_test.py (hunk 4 above)
Comment (liurenjie1024) [reply integration_tests/src/main/python/iceberg/iceberg_delete_test.py:131]: Will fix it in future pr.
