### PR TITLE
Work around incompatibility between Databricks Delta loads and GpuRegExpExtract

### LINKED ISSUE #5038: [BUG] When spark.rapids.sql.regexp.enabled is on in 22.04 snapshot jars, Reading a Delta table in Databricks may cause driver error
When spark.rapids.sql.regexp.enabled is on in 22.04 snapshot jars, Reading a Delta table in Databricks may cause driver error.

**Env:**
Databricks 10.4ML GPU
rapids-4-spark_2.12-22.04.0-20220322.104134-41.jar
cudf-22.04.0-20220322.035924-54.jar

**Reproduce Requirement**
spark.rapids.sql.regexp.enabled=true in cluster config when starting the cluster
Reading a specific delta table

**Reproduce query**
```
df=spark.read.format("delta").load("some_delta_table") 
```

**Error Message/Full Stacktrace**
```
Py4JJavaError: An error occurred while calling o424.load.
: java.lang.NullPointerException
	at org.apache.spark.sql.errors.QueryExecutionErrors$.expressionDecodingError(QueryExecutionErrors.scala:1184)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:199)
	at org.apache.spark.sql.execution.collect.DatasetSparkResult.toArray(DatasetSparkResult.scala:61)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3942)
	at org.apache.spark.sql.Dataset.$anonfun$collect$1(Dataset.scala:3099)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3930)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$6(SQLExecution.scala:195)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:342)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:153)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:852)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:115)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:292)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3928)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:3099)
	at com.databricks.sql.transaction.tahoe.SnapshotEdge.$anonfun$x$8$2(SnapshotEdge.scala:142)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at com.databricks.sql.transaction.tahoe.SnapshotEdge.$anonfun$x$8$1(SnapshotEdge.scala:108)
	at com.databricks.sql.acl.CheckPermissions$.trusted(CheckPermissions.scala:1582)
	at com.databricks.sql.transaction.tahoe.SnapshotEdge.x$8$lzycompute(SnapshotEdge.scala:108)
	at com.databricks.sql.transaction.tahoe.SnapshotEdge.x$8(SnapshotEdge.scala:107)
	at com.databricks.sql.transaction.tahoe.SnapshotEdge._metadata$lzycompute(SnapshotEdge.scala:107)
	at com.databricks.sql.transaction.tahoe.SnapshotEdge._metadata(SnapshotEdge.scala:107)
	at com.databricks.sql.transaction.tahoe.SnapshotEdge.metadata(SnapshotEdge.scala:185)
	at com.databricks.sql.transaction.tahoe.stats.DataSkippingReaderBase.$init$(DataSkippingReader.scala:182)
	at com.databricks.sql.transaction.tahoe.Snapshot.<init>(Snapshot.scala:75)
	at com.databricks.sql.transaction.tahoe.SnapshotEdge.<init>(SnapshotEdge.scala:68)
	at com.databricks.sql.transaction.tahoe.SnapshotManagementEdge.$anonfun$createSnapshot$2(SnapshotManagementEdge.scala:61)
	at com.databricks.sql.transaction.tahoe.SnapshotManagement.createSnapshotFromGivenOrEquivalentLogSegment(SnapshotManagement.scala:391)
	at com.databricks.sql.transaction.tahoe.SnapshotManagement.createSnapshotFromGivenOrEquivalentLogSegment$(SnapshotManagement.scala:379)
	at com.databricks.sql.transaction.tahoe.DeltaLog.createSnapshotFromGivenOrEquivalentLogSegment(DeltaLog.scala:74)
	at com.databricks.sql.transaction.tahoe.SnapshotManagementEdge.$anonfun$createSnapshot$1(SnapshotManagementEdge.scala:52)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at com.databricks.sql.transaction.tahoe.SnapshotManagementEdge.createSnapshot(SnapshotManagementEdge.scala:50)
	at com.databricks.sql.transaction.tahoe.SnapshotManagementEdge.createSnapshot$(SnapshotManagementEdge.scala:47)
	at com.databricks.sql.transaction.tahoe.DeltaLog.createSnapshot(DeltaLog.scala:74)
	at com.databricks.sql.transaction.tahoe.SnapshotManagement.$anonfun$getSnapshotAtInit$2(SnapshotManagement.scala:252)
	at scala.Option.map(Option.scala:230)
	at com.databricks.sql.transaction.tahoe.SnapshotManagement.$anonfun$getSnapshotAtInit$1(SnapshotManagement.scala:248)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:171)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:169)
	at com.databricks.sql.transaction.tahoe.DeltaLog.recordFrameProfile(DeltaLog.scala:74)
	at com.databricks.sql.transaction.tahoe.SnapshotManagement.getSnapshotAtInit(SnapshotManagement.scala:257)
	at com.databricks.sql.transaction.tahoe.SnapshotManagement.getSnapshotAtInit$(SnapshotManagement.scala:246)
	at com.databricks.sql.transaction.tahoe.DeltaLog.getSnapshotAtInit(DeltaLog.scala:74)
	at com.databricks.sql.transaction.tahoe.SnapshotManagement.$init$(SnapshotManagement.scala:54)
	at com.databricks.sql.transaction.tahoe.DeltaLog.<init>(DeltaLog.scala:79)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.$anonfun$apply$3(DeltaLog.scala:608)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:324)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.$anonfun$apply$2(DeltaLog.scala:608)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.withOperationTypeTag(DeltaLogging.scala:156)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.withOperationTypeTag$(DeltaLogging.scala:143)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.withOperationTypeTag(DeltaLog.scala:475)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.$anonfun$recordDeltaOperation$6(DeltaLogging.scala:121)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:171)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:169)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.recordFrameProfile(DeltaLog.scala:475)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.$anonfun$recordDeltaOperation$5(DeltaLogging.scala:120)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:366)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:460)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$4(UsageLogging.scala:480)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$2(UsageLogging.scala:232)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:212)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:20)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:276)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:261)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:20)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:455)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:375)
	at com.databricks.spark.util.PublicDBLogging.recordOperationWithResultTags(DatabricksSparkUsageLogger.scala:20)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:366)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:338)
	at com.databricks.spark.util.PublicDBLogging.recordOperation(DatabricksSparkUsageLogger.scala:20)
	at com.databricks.spark.util.PublicDBLogging.recordOperation0(DatabricksSparkUsageLogger.scala:57)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:137)
	at com.databricks.spark.util.UsageLogger.recordOperation(UsageLogger.scala:73)
	at com.databricks.spark.util.UsageLogger.recordOperation$(UsageLogger.scala:60)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:98)
	at com.databricks.spark.util.UsageLogging.recordOperation(UsageLogger.scala:431)
	at com.databricks.spark.util.UsageLogging.recordOperation$(UsageLogger.scala:410)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.recordOperation(DeltaLog.scala:475)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperation(DeltaLogging.scala:119)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperation$(DeltaLogging.scala:104)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.recordDeltaOperation(DeltaLog.scala:475)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.createDeltaLog$1(DeltaLog.scala:607)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.$anonfun$apply$4(DeltaLog.scala:627)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4724)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4721)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.getDeltaLogFromCache$1(DeltaLog.scala:627)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.apply(DeltaLog.scala:634)
	at com.databricks.sql.transaction.tahoe.DeltaLog$.forTable(DeltaLog.scala:525)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaTableV2.deltaLog$lzycompute(DeltaTableV2.scala:80)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaTableV2.deltaLog(DeltaTableV2.scala:80)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaTableV2.$anonfun$snapshot$3(DeltaTableV2.scala:108)
	at scala.Option.getOrElse(Option.scala:189)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaTableV2.snapshot$lzycompute(DeltaTableV2.scala:108)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaTableV2.snapshot(DeltaTableV2.scala:97)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaTableV2.toBaseRelation(DeltaTableV2.scala:177)
	at com.databricks.sql.transaction.tahoe.sources.DeltaDataSource.$anonfun$createRelation$4(DeltaDataSource.scala:218)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:171)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:169)
	at com.databricks.sql.transaction.tahoe.sources.DeltaDataSource.recordFrameProfile(DeltaDataSource.scala:53)
	at com.databricks.sql.transaction.tahoe.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:173)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:385)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:355)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:322)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:322)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

I suspect the issue is due to reading the detal log + regular expression in this query plan node:
```
(2) GpuProject
Input [2]: [metaData#19, protocol#20]
Arguments: [metaData#19, protocol#20, cast(regexp_extract(input_file_name(), /_delta_log/([0-9]{20})\., 1, /_delta_log/([0-9]{20})\.) as bigint) AS version#30L]
```

If we disable spark.rapids.sql.regexp.enabled, then it will work fine.
Then the good run's explain plan section regarding regular expression is below:
```
(2) GpuColumnarToRowTransition
Input [2]: [metaData#96, protocol#97]
Arguments: false

(3) Project [codegen id : 1]
Output [3]: [metaData#96, protocol#97, cast(regexp_extract(input_file_name(), /_delta_log/([0-9]{20})\., 1) as bigint) AS version#107L]
Input [2]: [metaData#96, protocol#97]

(4) GpuRowToColumnar
Input [3]: [metaData#96, protocol#97, version#107L]
Arguments: targetsize(536870912)
```

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #5038 

Databricks Delta is injecting a `regexp_extract(input_file_name(),...` during loads and the replacement of `RegExpExtract` with `GpuRegExpExtract` causes issues in the Databricks code.   This works around the issue by avoiding a replacement of `RegExpExtract` when on Databricks and the subject parameter is `InputFileName`, as this is likely the delta loading scenario that crashes when the `RegExpExtract` is replaced.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by abellina — APPROVED** [review]

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala [hunk 1]
```diff
@@ -969,6 +969,12 @@ class GpuRegExpExtractMeta(
   override def tagExprForGpu(): Unit = {
     GpuRegExpUtils.tagForRegExpEnabled(this)
 
+    ShimLoader.getShimVersion match {
```
Comment (revans2) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala:972]: Do we have/want a follow on issue to understand this? Did we test it on opensource deltalake to know if we have the same problem?

Comment (jlowe) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala:972]: I filed #5055 as a followup to investigate.  I did not test with open source Delta Lake, mostly because I was not able to reproduce the problem by simply writing a Delta Lake file and trying to read it.  @viadea tested this patch on a customer use-case, but I was not able to reproduce it myself.

I did check the [Delta Lake source](https://github.com/delta-io/delta) and did not see it generating `RegExpExtract`/`regexp_extract` usage.  It did have references to `RegExpExtract` but only in the context of a large list of expressions that can be part of a generated column, and this list is only used as a sanity-check on columns to support or it throws.

**Review by revans2 — APPROVED** [review]
