### PR TITLE
Include avro test by using '--packages' option [skip ci]

### LINKED ISSUE #5657: [BUG] Documented deployment of spark-avro is not tested
**Describe the bug**
The documented way of deploying [spark-avro](https://spark.apache.org/docs/latest/sql-data-sources-avro.html) which we are likely to encounter in the field is by having Spark load it at run time via `--packages` option from Maven.

However CI only tests with static classpath using `spark.*.extraClassPath` option. 

**Steps/Code to reproduce bug**
run intergration tests with `-k avro` with TEST_PARALLEL > 2

**Expected behavior**
Prioritize testing the advertised way of deploying `--packages` spark-avro if we need to pick one.

**Environment details (please complete the following information)**
 CI

**Additional context**
#5648

### PR DESCRIPTION
**Pull request by zhanga5**
Closes #5657

### CODE REVIEW

**Comment by zhanga5** [comment]
build

File: jenkins/spark-tests.sh [hunk 1]
```diff
@@ -284,6 +300,7 @@ export -f get_tests_by_tags
 # - DEFAULT: all tests except cudf_udf tests
 # - CUDF_UDF_ONLY: cudf_udf tests only, requires extra conda cudf-py lib
 # - ICEBERG_ONLY: iceberg tests only
+# - AVRO_ONLY: avro tests only (with --packages option instead of --jars)
```
Comment (tgravescs) [inline jenkins/spark-tests.sh:303]: we should add documentation to README about this option and mention using --packages since if you don't have internet access it won't work

Comment (tgravescs) [reply jenkins/spark-tests.sh:303]: https://github.com/NVIDIA/spark-rapids/tree/branch-22.10/integration_tests#enabling-apache-iceberg-tests

File: jenkins/spark-tests.sh [hunk 2]
```diff
@@ -211,6 +211,18 @@ run_iceberg_tests() {
   fi
 }
 
+ # Test spark-avro with documented way of deploying at run time via --packages option from Maven
+run_avro_tests() {
+  unset TEST_PARALLEL  # Enable auto spark local parallel in run_pyspark_from_build.sh
```
Comment (gerashegalov) [inline jenkins/spark-tests.sh:216]: `SPARK_SUBMIT_FLAGS` and TEST_PARALLEL > 0 are not compatible, see the thread on #6403

Comment (zhanga5) [reply jenkins/spark-tests.sh:216]: refined

Comment (pxLi) [reply jenkins/spark-tests.sh:216]: we do not require it must be parallel in this PR as we are testing `--package avro`. 

For this place to let run run_pyspark_from_build to set the parallelism may not always be a good idea as it try to set as many as parallelism as possible, the actually it would decrease the performance if over some specific value and could potentially caused host machine memory OOM on different GPU types. I guess we could hardcode it to 4 or 5 here

We can discuss about how to better parallelize tests like iceberg and avro in #6403. But for this PR lets keep it simple~

File: jenkins/spark-tests.sh (hunk 1 above)
Comment (zhanga5) [reply jenkins/spark-tests.sh:302]: looks like enabling avro test was quite different with iceberg or delta lake. Not sure whether should provide some consistency and then document it in same manner
- avro: https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/integration_tests/run_pyspark_from_build.sh#L81-L85
- iceberg or delta lake: https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/integration_tests/conftest.py#L45-L50

File: jenkins/spark-tests.sh (hunk 2 above)
Comment (gerashegalov) [reply jenkins/spark-tests.sh:216]: agreed. we need to drop `unset TEST_PARALLEL`  in this PR

File: jenkins/spark-tests.sh [hunk 3]
```diff
@@ -211,6 +211,17 @@ run_iceberg_tests() {
...
+  export PYSP_TEST_spark_jars_packages="org.apache.spark:spark-avro_2.12:${SPARK_VER}"
+
+  # Workaround to avoid appending avro jar file by '--jars'
+  rm -vf $LOCAL_JAR_PATH/spark-avro*.jar
```
Comment (gerashegalov) [inline jenkins/spark-tests.sh:220]: Maybe move out of the way (e.g. rename `spark-avro.jar` to `spark-avro.jar%`) before calling the avro tests and restore after to avoid side effects and creating dependence on the order of the tests?

File: jenkins/spark-tests.sh (hunk 2 above)
Comment (zhanga5) [reply jenkins/spark-tests.sh]: removed

File: jenkins/spark-tests.sh (hunk 3 above)
Comment (zhanga5) [reply jenkins/spark-tests.sh]: refined

**Review by pxLi — APPROVED** [review]
LGTM. I will upmerge this and update a few later in https://github.com/NVIDIA/spark-rapids/pull/6522

File: jenkins/spark-tests.sh (hunk 1 above)
Comment (pxLi) [reply jenkins/spark-tests.sh:304]: yeah, I think this should be a new issue to bring avro test consistent w/ other ones. filed an issue to track this https://github.com/NVIDIA/spark-rapids/issues/6532

**Comment by pxLi** [comment]
build

File: jenkins/spark-tests.sh [hunk 4]
```diff
@@ -211,6 +211,20 @@ run_iceberg_tests() {
   fi
 }
 
+ # Test spark-avro with documented way of deploying at run time via --packages option from Maven
+run_avro_tests() {
+  export PYSP_TEST_spark_jars_packages="org.apache.spark:spark-avro_2.12:${SPARK_VER}"
+
+  # Workaround to avoid appending avro jar file by '--jars'
+  AVRO_JAR_FILE=`cd $LOCAL_JAR_PATH && ls spark-avro*.jar`
+  mv $LOCAL_JAR_PATH/$AVRO_JAR_FILE $LOCAL_JAR_PATH/$AVRO_JAR_FILE%
```
Comment (pxLi) [inline jenkins/spark-tests.sh:220]: one thing that could cause issue is that mv could fail if no avro file in LOCAL_JAR_PATH. 
may simply `|| true` to avoid case that people mark ENV `INCLUDE_SPARK_AVRO_JAR=false`

Comment (zhanga5) [reply jenkins/spark-tests.sh]: reverted to previous simple workaround. It would be fine as avro test would be executed at the end of scripts and avro jar file will be auto downloaded each time

File: jenkins/spark-tests.sh (hunk 3 above)
Comment (pxLi) [reply jenkins/spark-tests.sh:219]: lets take care of all avro_test inconsistency in https://github.com/NVIDIA/spark-rapids/issues/6532

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
build
