### PR TITLE
Fix: orc_cast_test fails on CDH [databricks]

### LINKED ISSUE #6465: [BUG] orc_cast_test fails on CDH
orc_cast_test failed in the nightly CDH test run:
```
[2022-08-31T13:05:18.320Z] =================================== FAILURES ===================================
[2022-08-31T13:05:18.320Z] [31m[1m_____________________ test_casting_from_integer[timestamp] _____________________[0m
[2022-08-31T13:05:18.320Z] 
[2022-08-31T13:05:18.320Z] spark_tmp_path = '/tmp/pyspark_tests//rl-r7525-d32-u35.raplab.nvidia.com-main-38299-64100338/'
[2022-08-31T13:05:18.320Z] to_type = 'timestamp'
[2022-08-31T13:05:18.320Z] 
[2022-08-31T13:05:18.320Z]     @pytest.mark.parametrize('to_type', ['float', 'double', 'string', 'timestamp'])
[2022-08-31T13:05:18.320Z]     def test_casting_from_integer(spark_tmp_path, to_type):
[2022-08-31T13:05:18.320Z]         orc_path = spark_tmp_path + '/orc_cast_integer'
[2022-08-31T13:05:18.320Z]         # The Python 'datetime' module only supports a max-year of 10000, so we set the Long type max
[2022-08-31T13:05:18.320Z]         # to '1e11'. If the long-value is out of this range, pytest will throw an exception.
[2022-08-31T13:05:18.320Z]         data_gen = [('boolean_col', boolean_gen), ('tinyint_col', byte_gen),
[2022-08-31T13:05:18.320Z]                     ('smallint_col', ShortGen(min_val=BYTE_MAX + 1)),
[2022-08-31T13:05:18.320Z]                     ('int_col', IntegerGen(min_val=SHORT_MAX + 1)),
[2022-08-31T13:05:18.320Z]                     ('bigint_col', LongGen(min_val=INT_MAX + 1, max_val=int(1e11))),
[2022-08-31T13:05:18.320Z]                     ('negint_col', IntegerGen(max_val=-1))]
[2022-08-31T13:05:18.320Z]         create_orc(data_gen, orc_path)
[2022-08-31T13:05:18.320Z]     
[2022-08-31T13:05:18.320Z]         schema_str = "boolean_col {}, tinyint_col {}, smallint_col {}, int_col {}, bigint_col {}, negint_col {}"
[2022-08-31T13:05:18.320Z]         assert_gpu_and_cpu_are_equal_collect(
[2022-08-31T13:05:18.320Z] >           lambda spark: spark.read.schema(
[2022-08-31T13:05:18.320Z]                 schema_str.format(*([to_type] * len(data_gen)))).orc(orc_path)
[2022-08-31T13:05:18.320Z]         )
[2022-08-31T13:05:18.320Z] 
[2022-08-31T13:05:18.320Z] [1m[31m../../src/main/python/orc_cast_test.py[0m:65: 
[2022-08-31T13:05:18.320Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-08-31T13:05:18.320Z] [1m[31m../../src/main/python/asserts.py[0m:508: in assert_gpu_and_cpu_are_equal_collect
[2022-08-31T13:05:18.320Z]     _assert_gpu_and_cpu_are_equal(func, 'COLLECT', conf=conf, is_cpu_first=is_cpu_first)
[2022-08-31T13:05:18.320Z] [1m[31m../../src/main/python/asserts.py[0m:439: in _assert_gpu_and_cpu_are_equal
[2022-08-31T13:05:18.320Z]     assert_equal(from_cpu, from_gpu)
[2022-08-31T13:05:18.320Z] [1m[31m../../src/main/python/asserts.py[0m:106: in assert_equal
[2022-08-31T13:05:18.320Z]     _assert_equal(cpu, gpu, float_check=get_float_check(), path=[])
[2022-08-31T13:05:18.320Z] [1m[31m../../src/main/python/asserts.py[0m:42: in _assert_equal
[2022-08-31T13:05:18.320Z]     _assert_equal(cpu[index], gpu[index], float_check, path + [index])
[2022-08-31T13:05:18.320Z] [1m[31m../../src/main/python/asserts.py[0m:35: in _assert_equal
[2022-08-31T13:05:18.320Z]     _assert_equal(cpu[field], gpu[field], float_check, path + [field])
[2022-08-31T13:05:18.320Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-08-31T13:05:18.320Z] 
[2022-08-31T13:05:18.320Z] cpu = datetime.datetime(1970, 1, 1, 0, 0, 0, 1000)
[2022-08-31T13:05:18.320Z] gpu = datetime.datetime(1970, 1, 1, 0, 0, 1)
[2022-08-31T13:05:18.320Z] float_check = <function get_float_check.<locals>.<lambda> at 0x7f8fcfd8d950>
[2022-08-31T13:05:18.320Z] path = [0, 'boolean_col']
[2022-08-31T13:05:18.320Z] 
[2022-08-31T13:05:18.320Z]     def _assert_equal(cpu, gpu, float_check, path):
[2022-08-31T13:05:18.320Z]         t = type(cpu)
[2022-08-31T13:05:18.320Z]         if (t is Row):
[2022-08-31T13:05:18.320Z]             assert len(cpu) == len(gpu), "CPU and GPU row have different lengths at {} CPU: {} GPU: {}".format(path, len(cpu), len(gpu))
[2022-08-31T13:05:18.320Z]             if hasattr(cpu, "__fields__") and hasattr(gpu, "__fields__"):
[2022-08-31T13:05:18.320Z]                 assert cpu.__fields__ == gpu.__fields__, "CPU and GPU row have different fields at {} CPU: {} GPU: {}".format(path, cpu.__fields__, gpu.__fields__)
[2022-08-31T13:05:18.320Z]                 for field in cpu.__fields__:
[2022-08-31T13:05:18.320Z]                     _assert_equal(cpu[field], gpu[field], float_check, path + [field])
[2022-08-31T13:05:18.320Z]             else:
[2022-08-31T13:05:18.320Z]                 for index in range(len(cpu)):
[2022-08-31T13:05:18.320Z]                     _assert_equal(cpu[index], gpu[index], float_check, path + [index])
[2022-08-31T13:05:18.320Z]         elif (t is list):
[2022-08-31T13:05:18.320Z]             assert len(cpu) == len(gpu), "CPU and GPU list have different lengths at {} CPU: {} GPU: {}".format(path, len(cpu), len(gpu))
[2022-08-31T13:05:18.320Z]             for index in range(len(cpu)):
[2022-08-31T13:05:18.320Z]                 _assert_equal(cpu[index], gpu[index], float_check, path + [index])
[2022-08-31T13:05:18.320Z]         elif (t is tuple):
[2022-08-31T13:05:18.320Z]             assert len(cpu) == len(gpu), "CPU and GPU list have different lengths at {} CPU: {} GPU: {}".format(path, len(cpu), len(gpu))
[2022-08-31T13:05:18.320Z]             for index in range(len(cpu)):
[2022-08-31T13:05:18.320Z]                 _assert_equal(cpu[index], gpu[index], float_check, path + [index])
[2022-08-31T13:05:18.320Z]         elif (t is pytypes.GeneratorType):
[2022-08-31T13:05:18.320Z]             index = 0
[2022-08-31T13:05:18.320Z]             # generator has no zip :( so we have to do this the hard way
[2022-08-31T13:05:18.320Z]             done = False
[2022-08-31T13:05:18.320Z]             while not done:
[2022-08-31T13:05:18.320Z]                 sub_cpu = None
[2022-08-31T13:05:18.320Z]                 sub_gpu = None
[2022-08-31T13:05:18.320Z]                 try:
[2022-08-31T13:05:18.320Z]                     sub_cpu = next(cpu)
[2022-08-31T13:05:18.320Z]                 except StopIteration:
[2022-08-31T13:05:18.320Z]                     done = True
[2022-08-31T13:05:18.320Z]     
[2022-08-31T13:05:18.320Z]                 try:
[2022-08-31T13:05:18.320Z]                     sub_gpu = next(gpu)
[2022-08-31T13:05:18.320Z]                 except StopIteration:
[2022-08-31T13:05:18.320Z]                     done = True
[2022-08-31T13:05:18.320Z]     
[2022-08-31T13:05:18.320Z]                 if done:
[2022-08-31T13:05:18.320Z]                     assert sub_cpu == sub_gpu and sub_cpu == None, "CPU and GPU generators have different lengths at {}".format(path)
[2022-08-31T13:05:18.320Z]                 else:
[2022-08-31T13:05:18.320Z]                     _assert_equal(sub_cpu, sub_gpu, float_check, path + [index])
[2022-08-31T13:05:18.320Z]     
[2022-08-31T13:05:18.320Z]                 index = index + 1
[2022-08-31T13:05:18.320Z]         elif (t is dict):
[2022-08-31T13:05:18.320Z]             # The order of key/values is not guaranteed in python dicts, nor are they guaranteed by Spark
[2022-08-31T13:05:18.320Z]             # so sort the items to do our best with ignoring the order of dicts
[2022-08-31T13:05:18.320Z]             cpu_items = list(cpu.items()).sort(key=_RowCmp)
[2022-08-31T13:05:18.320Z]             gpu_items = list(gpu.items()).sort(key=_RowCmp)
[2022-08-31T13:05:18.320Z]             _assert_equal(cpu_items, gpu_items, float_check, path + ["map"])
[2022-08-31T13:05:18.320Z]         elif (t is int):
[2022-08-31T13:05:18.320Z]             assert cpu == gpu, "GPU and CPU int values are different at {}".format(path)
[2022-08-31T13:05:18.320Z]         elif (t is float):
[2022-08-31T13:05:18.320Z]             if (math.isnan(cpu)):
[2022-08-31T13:05:18.320Z]                 assert math.isnan(gpu), "GPU and CPU float values are different at {}".format(path)
[2022-08-31T13:05:18.320Z]             else:
[2022-08-31T13:05:18.320Z]                 assert float_check(cpu, gpu), "GPU and CPU float values are different {}".format(path)
[2022-08-31T13:05:18.320Z]         elif isinstance(cpu, str):
[2022-08-31T13:05:18.320Z]             assert cpu == gpu, "GPU and CPU string values are different at {}".format(path)
[2022-08-31T13:05:18.320Z]         elif isinstance(cpu, datetime):
[2022-08-31T13:05:18.320Z] >           assert cpu == gpu, "GPU and CPU timestamp values are different at {}".format(path)
[2022-08-31T13:05:18.320Z] [1m[31mE           AssertionError: GPU and CPU timestamp values are different at [0, 'boolean_col'][0m
[2022-08-31T13:05:18.320Z] 
[2022-08-31T13:05:18.320Z] [1m[31m../../src/main/python/asserts.py[0m:86: AssertionError
[2022-08-31T13:05:18.320Z] ----------------------------- Captured stdout call -----------------------------
[2022-08-31T13:05:18.320Z] ### CPU RUN ###
[2022-08-31T13:05:18.320Z] ### GPU RUN ###
[2022-08-31T13:05:18.320Z] ### COLLECT: GPU TOOK 0.16632556915283203 CPU TOOK 0.3948032855987549 ###
[2022-08-31T13:05:18.341Z] CPU OUTPUT: [Row(boolean_col=datetime.datetime(1970, 1, 1, 0, 0, 0, 1000), tinyint_col=datetime.datetime(1969, 12, 31, 23, 59, 59, 892000), smallint_col=datetime.datetime(1970, 1, 1, 0, 0, 16, 881000), int_col=datetime.datetime(1970, 1, 23, 19, 45, 25, 977000), bigint_col=datetime.datetime(1971, 8, 19, 8, 38, 12, 228000), negint_col=datetime.datetime(1969, 12, 18, 0, 5, 20, 729000)), 
[...]
[2022-08-31T13:05:18.381Z] GPU OUTPUT: [Row(boolean_col=datetime.datetime(1970, 1, 1, 0, 0, 1), tinyint_col=datetime.datetime(1969, 12, 31, 23, 58, 12), smallint_col=datetime.datetime(1970, 1, 1, 4, 41, 21), int_col=datetime.datetime(2032, 6, 27, 5, 12, 57), bigint_col=datetime.datetime(3600, 1, 15, 20, 43, 48), negint_col=datetime.datetime(1931, 9, 6, 17, 5, 29)), 
[...]
```

### PR DESCRIPTION
**Pull request by sinkinben**
Close #6465 

From the log, when input `integer = 1`, then
```text
[2022-08-31T13:05:18.320Z] cpu = datetime.datetime(1970, 1, 1, 0, 0, 0, 1000)
[2022-08-31T13:05:18.320Z] gpu = datetime.datetime(1970, 1, 1, 0, 0, 1)
```

The spark-321cdh assumes the integers in columnar vector as milliseconds, thus cpu output `microsecond = 1000` in the last field of `datetime`. It is different from the behavior of offical spark-321.

So I added a new shim for 321cdh to fix it.

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Comment by abellina** [comment]
build

**Review by abellina — APPROVED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 1]
```diff
@@ -280,6 +280,60 @@ object GpuOrcScan extends Arm {
...
+                              asSeconds: Boolean = true): ColumnVector = {
+    assert(colType == DType.BOOL8 || colType == DType.INT8 || colType == DType.INT16
+      || colType == DType.INT32 || colType == DType.INT64)
+
+    colType match {
+      case DType.BOOL8 | DType.INT8 | DType.INT16 | DType.INT32 =>
+        // Convert seconds to microseconds, we need to multiply 1e36
+        // Convert milliseconds to microseconds, we need to multiply 1e3
+        // integers * value => microseconds
+        val value = if (asSeconds) { 1000000 } else { 1000 }
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:303]: The name value is too generic. Maybe `microsecodndsFactor`? 

You can also avoid hardcoding if you switch to TimeUnit the tune of `TimeUnit.MICROSECONDS.convert(1L, TimeUnit.SECONDS)`

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 2]
```diff
@@ -280,6 +280,60 @@ object GpuOrcScan extends Arm {
...
+
+        // cuDF requires casting to Long first, then we can cast Long to Timestamp(in microseconds)
+        withResource(col.castTo(DType.INT64)) { longs =>
+          withResource(Scalar.fromLong(value)) { k =>
+            withResource(longs.mul(k)) { milliSeconds =>
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:308]: just curious can we - instead of manual multiplication  - conceptually do it using castTo only for the "seconds" case?

col.castTo(DType.INT64)  => castTo(DType.TIMESTAMP_SECONDS) =>  castTo(DType.TIMESTAMP_MICROSECONDS)

Comment (sinkinben) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala]: Nice tips, I have found an cuDF API `bitCastTo` to make the code more clear and readable.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 3]
```diff
@@ -280,6 +280,49 @@ object GpuOrcScan extends Arm {
...
+      || colType == DType.INT32 || colType == DType.INT64)
+    assert(timeUnit == DType.TIMESTAMP_SECONDS || timeUnit == DType.TIMESTAMP_MILLISECONDS)
+
+    colType match {
+      case DType.BOOL8 | DType.INT8 | DType.INT16 | DType.INT32 =>
+        // cuDF requires casting to Long first, then we can cast Long to Timestamp(in microseconds)
+        withResource(col.castTo(DType.INT64)) { longs =>
+          // bitCastTo will re-interpret the long values as 'timeUnit', and it will zero-copy cast
+          // between types with the same underlying length.
+          longs.bitCastTo(timeUnit).castTo(DType.TIMESTAMP_MICROSECONDS)
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:307]:
```suggestion
          withResource(longs.bitCastTo(timeUnit)) { timeView =>
            timeView.castTo(DType.TIMESTAMP_MICROSECONDS)
          }
```
The ColumnView from `longs.bitCastTo(timeUnit)` also needs to be closed.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 4]
```diff
@@ -280,6 +280,49 @@ object GpuOrcScan extends Arm {
...
+        }
+      case DType.INT64 =>
+        // In CPU code of ORC casting, if the integers are consider as seconds, then the conversion
+        // is 'integer -> milliseconds -> microseconds', and it checks the long-overflow when
+        // casting 'milliseconds -> microseconds', here we follow it.
+        val milliseconds = col.bitCastTo(timeUnit).castTo(DType.TIMESTAMP_MILLISECONDS)
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:313]: Same issue with the above.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 5]
```diff
@@ -280,6 +280,49 @@ object GpuOrcScan extends Arm {
...
+        withResource(milliseconds) { _ =>
+          // Check long-multiplication overflow
+          if (milliseconds.max() != null) {
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:316]: Can the scalar from `milliseconds.max() ` be null ?
Instead, we need to check its validity, and it should be closed too.
```suggestion
          withResource(milliseconds.max()) { maxS =>
            if (maxS.isValid) {
              testLongMultiplicationOverflow(maxS.getLong, 1000L)
            } else {
              // all nulls ？Need to take care of this case
            }
          }
          withResource(milliseconds.min()) { minS =>
            if (minS.isValid) {
              testLongMultiplicationOverflow(minS.getLong, 1000L)
            } else {
              // all nulls ？Need to take care of this case
            }
          }
          milliseconds.castTo(DType.TIMESTAMP_MICROSECONDS)
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 3 above)
Comment (sinkinben) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:307]: I did such thing in the previous code. But it will throw some exceptions like "Close Column Vector too many time....".

The description of `bitCastTo` is:

```
public ColumnView bitCastTo(DType type)
Zero-copy cast between types with the same underlying length. Similar to bit_cast in C++. This will take the underlying data and create new metadata so it is interpreted as a new type. Not all types are supported the width of the types must match.
```

it returns an ColumnView (not CoolumnVector), so I think there is no need to close it?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 5 above)
Comment (sinkinben) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:316]: Fixed.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 4 above)
Comment (sinkinben) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:313]: Fixed.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 3 above)
Comment (sinkinben) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:307]: Fixed.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 6]
```diff
@@ -280,6 +280,59 @@ object GpuOrcScan extends Arm {
...
+      case DType.INT64 =>
+        // In CPU code of ORC casting, if the integers are consider as seconds, then the conversion
+        // is 'integer -> milliseconds -> microseconds', and it checks the long-overflow when
+        // casting 'milliseconds -> microseconds', here we follow it.
+        val milliseconds = withResource(col.bitCastTo(timeUnit)) { timeView =>
+          timeView.castTo(DType.TIMESTAMP_MILLISECONDS)
+        }
+        withResource(milliseconds) { _ =>
+          // Check long-multiplication overflow
+          val maxValue = milliseconds.max()
```
Comment (firestarman) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala:320]: The `maxValue ` will be leaked if `milliseconds.min()` throw an exception.

Comment (sinkinben) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala]: Updated

**Review by firestarman — APPROVED** [review]

**Comment by firestarman** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala (hunk 1 above)
Comment (sinkinben) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala]: We can use `DateTimeConstants.MICROS_PER_MILLIS`

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala [hunk 7]
```diff
@@ -280,6 +280,60 @@ object GpuOrcScan extends Arm {
...
+  /**
+   * Convert the integer vector into timestamp(microseconds) vector.
+   * @param col The integer columnar vector.
+   * @param colType Specific integer type, it should be BOOL/INT8/INT16/INT32/INT64.
+   * @param asSeconds True if consider the integers as seconds, otherwise we consider them
+   *                  as milliseconds. This parameter is determined by the shims.
+   * @return A timestamp vector.
+   */
+  def castIntegersToTimestamp(col: ColumnView, colType: DType,
+                              asSeconds: Boolean = true): ColumnVector = {
```
[the remark this answers is not in the document]
Comment (sinkinben) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala]: Here I use `timeUnit: DType` to replace `asSeconds: boolean`, and assert timeUnit is `SECONDS` or `MILLISECONDS`
