### PR TITLE
Fix issue with parquet partitioned reads

### LINKED ISSUE #718: [BUG] GpuBroadcastHashJoinExec ArrayIndexOutOfBoundsException
**Describe the bug**

When performing a join of two tables created with a `PARTITIONED BY` clause using the following code, a GPU projection fails with `ArrayIndexOutOfBoundsException` due to receiving a broadcast batch with zero columns. The same code works fine on CPU, indicating that there is a bug in the plugin.

The query works if the `PARTITIONED BY` clause is removed from the `CREATE TABLE` statement for t1.

The failure happens with AQE on or off.

**Steps/Code to reproduce bug**

Run the following unit test.

```scala
test("Join partitioned tables") {

  withGpuSparkSession(spark => {
    import spark.implicits._

    val path = new File(TEST_FILES_ROOT, "test.parquet").getAbsolutePath
    (0 until 100)
        .map(i => (i,i*5))
        .toDF("a", "b")
        .write
        .mode(SaveMode.Overwrite)
        .parquet(path)
    spark.read.parquet(path).createOrReplaceTempView("testData")

    spark.sql("DROP TABLE IF EXISTS t1").collect()
    spark.sql("DROP TABLE IF EXISTS t2").collect()

    spark.sql("CREATE TABLE t1 (a INT, b INT) USING parquet PARTITIONED BY (a)").collect()
    spark.sql("CREATE TABLE t2 (a INT, b INT) USING parquet PARTITIONED BY (a)").collect()

    spark.sql("INSERT INTO TABLE t1 SELECT a, b FROM testData").collect()
    spark.sql("INSERT INTO TABLE t2 SELECT a, b FROM testData").collect()

    val df3 = spark.sql(
        "SELECT t1.a, t2.b " +
        "FROM t1 " +
        "JOIN t2 " +
        "ON t1.a = t2.a "
        )
    df3.collect()

  })
}

```

Stack trace:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.spark.sql.vectorized.ColumnarBatch.column(ColumnarBatch.java:102)
	at com.nvidia.spark.rapids.GpuBoundReference.columnarEval(GpuBoundAttribute.scala:95)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35)
	at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:50)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:160)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:157)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:157)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:192)
	at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:49)
	at com.nvidia.spark.rapids.shims.spark301.GpuBroadcastHashJoinExec.builtTable$lzycompute$1(GpuBroadcastHashJoinExec.scala:147)
	at com.nvidia.spark.rapids.shims.spark301.GpuBroadcastHashJoinExec.builtTable$1(GpuBroadcastHashJoinExec.scala:145)
	at com.nvidia.spark.rapids.shims.spark301.GpuBroadcastHashJoinExec.$anonfun$doExecuteColumnar$5(GpuBroadcastHashJoinExec.scala:162)
```

**Expected behavior**
The code should work when on GPU. Changing `withGpuSparkSession` to `withCpuSparkSession` makes the test pass.

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by revans2**
This fixes #718 

It also fixes a few other things I found while in the code.

It acquires the GPU Semaphore in cases where we are returning a batch, even if it is just row counts.

It updates the tests to use the new small file config.  I noticed it when I checked if my new test would fail without the fix in place, and it failed all 4 cases instead of just half of them that I thought it should.

### CODE REVIEW

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala [hunk 1]
```diff
@@ -924,13 +924,17 @@ class MultiFileParquetPartitionReader(
   private def addPartitionValues(
       batch: Option[ColumnarBatch],
       inPartitionValues: InternalRow): Option[ColumnarBatch] = {
-    batch.map { cb =>
-      val partitionValues = inPartitionValues.toSeq(partitionSchema)
-      val partitionScalars = ColumnarPartitionReaderWithPartitionValues
-        .createPartitionValues(partitionValues, partitionSchema)
-      withResource(partitionScalars) { scalars =>
-        ColumnarPartitionReaderWithPartitionValues.addPartitionValues(cb, scalars)
+    if (partitionSchema.nonEmpty) {
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:927]: Technically this change is not needed I originally started it to only grab the semaphore when there were partition values, but then I thought better and decided to grab it in all cases.  I left this because I thought it made the code more readable, even though it works without the change.

If others disagree I am happy to remove it.

**Review by tgravescs — APPROVED** [review]

**Comment by revans2** [comment]
python udf window tests are failing here too now.  Not sure how they passed for the original PR. Because this is a P1 I am going to merge this in as is, and then we can decide how to fix the test separately.
