### PR TITLE
Fix DPP/DFP cases when join keys are rewritten when there are multiple integral columns [databricks]

### LINKED ISSUE #7707: [BUG] IndexOutOfBoundsException when joining on 2 integer columns with DPP
**Describe the bug**
When joining on 2 integer columns that a table is partitioned by using DPP, get an `IndexOutOfBoundsException` in `GpuSubqueryBroadcastExec.projectSerializedBatchToRows`. This happens both when AQE is enabled or disabled.

**Steps/Code to reproduce bug**

In `dpp_test.py`, you can add the following query to `_statements`, and run `test_dpp_reuse_broadcast_exchange` to produce the exception:

```
    SELECT fact.key, fact.skey, sum(fact.value)
    FROM {0} fact
    JOIN {1} dim
    ON fact.key = dim.key AND fact.skey = dim.skey
    WHERE dim.filter = {2}
    GROUP BY fact.key, fact.skey
```

Relevant backtrace:

```
E                   Caused by: java.lang.IndexOutOfBoundsException: 1
E                   	at scala.collection.LinearSeqOptimized.apply(LinearSeqOptimized.scala:67)
E                   	at scala.collection.LinearSeqOptimized.apply$(LinearSeqOptimized.scala:65)
E                   	at scala.collection.immutable.List.apply(List.scala:91)
E                   	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$projectSerializedBatchToRows$1(GpuSubqueryBroadcastExec.scala:232)
E                   	at scala.Option.map(Option.scala:230)
E                   	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.projectSerializedBatchToRows(GpuSubqueryBroadcastExec.scala:231)
E                   	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$2(GpuSubqueryBroadcastExec.scala:212)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:145)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:143)
E                   	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$1(GpuSubqueryBroadcastExec.scala:209)
E                   	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
E                   	at scala.util.Success.$anonfun$map$1(Try.scala:255)
E                   	at scala.util.Success.map(Try.scala:213)
E                   	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
E                   	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
E                   	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
E                   	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Additional context**

Upon further inspection of the plan, you will notice that Spark does the following optimization in the `HashedRelationBroadcastMode`, where it will join the 2 int key expressions together into a single bigint key expression, so this means that `GpuSubqueryBroadcast` would need to handle splitting that up.

```
                          :     :- GpuSubqueryBroadcast dynamicpruning#291, 0, [key#265, skey#266]
                           :     :  +- GpuBroadcastExchange HashedRelationBroadcastMode(List((shiftleft(cast(input[0, int, true] as bigint), 32) | (cast(input[1, int, true] as bigint) & 4294967295))),false), [id=#434]
```

See https://github.com/apache/spark/blob/29eca8c87f4e8c19c0380f7c30668fd88edee573/sql/core/src/main/scala/org/apache/spark/sql/execution/joins/HashJoin.scala#L720 for join key rewrite

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #7707.

This PR handles the case when join keys are rewritten in Apache Spark when there are multiple integral columns that can fit inside a Long/BigInt column. It uses the same method `HashJoin.extractKeyExprAt()` that Spark uses in those cases but uses the logic of just checking that the build keys can be rewritten (since we don't have the `LongHashedRelation` that Apache Spark has). Spark will always rewrite the build keys if it can to use a hash join (this behavior is actually not controlled behind a configuration flag), so the need for this PR. This behavior is present in all versions of Spark from `3.1.1` (including Databricks), so no need for shim updates.

### CODE REVIEW

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala [hunk 1]
```diff
@@ -229,14 +229,28 @@ case class GpuSubqueryBroadcastExec(
     // are being extracted. The CPU already has the key projections applied in the broadcast
     // data and thus does not have similar logic here.
     val broadcastModeProject = modeKeys.map { keyExprs =>
-      val keyExpr = keyExprs(index)
+      val keyExpr = if (GpuHashJoin.canRewriteAsLongType(buildKeys)) {
+        // in this case, there is only 1 key expression since it's a packed version that encompasses
+        // multiple integral values into a single long using bit logic. In CPU Spark, the broadcast
+        // would create a LongHashedRelation instead of a standard HashedRelation.
+        keyExprs(0)
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala:236]: nit
```suggestion
        keyExprs.head
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala [hunk 2]
```diff
@@ -226,6 +226,15 @@ object GpuHashJoin extends Arm {
...
   }
+
+  /**
+    * Copied from Apache Spark, returns whether the keys can be rewritten as a packed long. If
+    * they can, we can assume that they are packed when we extract them out.
+    */
+  def canRewriteAsLongType(keys: Seq[Expression]): Boolean = {
+    keys.forall(_.dataType.isInstanceOf[IntegralType]) &&
+      keys.map(_.dataType.defaultSize).sum <= 8
+  }
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala:237]: Please add a permalink such as https://github.com/apache/spark/blob/29eca8c87f4e8c19c0380f7c30668fd88edee573/sql/core/src/main/scala/org/apache/spark/sql/execution/joins/HashJoin.scala#L709-L713 to the revision this snippet is taken from for easier tracking 

The implementation was changed in https://issues.apache.org/jira/browse/SPARK-38325 in 3.2.2+ for 3.2, and in 3.3+   It should be shimmed.

**Comment by gerashegalov** [comment]
Scalastyle check fails 
```
error file=/home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala message=Use Javadoc style indentation for multiline comments line=230 column=0
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala (hunk 2 above)
Comment (NVnavkumar) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala]: So it looks like this particular logic didn't fundamentally change in the underlying PR:

It went from this:
```
    if (keys.exists(!_.dataType.isInstanceOf[IntegralType])
      || keys.map(_.dataType.defaultSize).sum > 8) {
         return keys
    }
```

To this:

```
  private def canRewriteAsLongType(keys: Seq[Expression]): Boolean = {
    // TODO: support BooleanType, DateType and TimestampType
    keys.forall(_.dataType.isInstanceOf[IntegralType]) &&
      keys.map(_.dataType.defaultSize).sum <= 8
  }
...

  if (!canRewriteAsLongType(keys)) {
     return keys;
  }
```

So the first case is the explicit negation of the second logic which has been refactored into a private helper method and the negated output is checked here. 

In that PR, the material change being made is the underlying implementation of `HashJoin.rewriteKeyExprAt(...)`, which is a method I'm actually calling here, so whatever previous behavior should be preserved across Spark versions.

In our case we have to use this logic because we don't have access to the `LongHashedRelation` that would normally be created by the broadcast (since we're broadcasting columns).

I don't really know how to shim this, because there isn't any material difference in the logic (it was only refactored) that I'm using. The underlying method signature of `rewriteKeyExprAt` didn't change so I should be able to just call that Spark method and preserve behavior. I will add the permalink.

Comment (gerashegalov) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala]: yes, I ended up updating my comment that there was no change in logic, no need to shim

**Review by gerashegalov — APPROVED** [review]

**Comment by NVnavkumar** [comment]
build
