### PR TITLE
Fixes an issue were we were not properly checking log params and nullable output [databricks]

### LINKED ISSUE #13737: [AutoSparkUT] conv - Base conversion function fails on GPU
**Describe the bug**

The `conv` function (base conversion) fails on GPU during expression evaluation.
The test failed by below exception:
java.lang.RuntimeException: Logic error: Spark should fold the conv expr into scalar value.

It seems if we disable ConstantFolding to run with conv, it'll fail by the exception.

---

**Steps/Code to reproduce bug**

### Spark-shell Reproduction Code

**Environment Setup:**
```bash
export SPARK_HOME=/path/to/spark-3.3.0
export RAPIDS_JAR=rapids-4-spark_2.12-25.12.0-SNAPSHOT-cuda12.jar
```

**Reproduction Script:** `test-failures/reproduce-math-expressions-conv.scala`

```scala
// Test: conv function (base conversion)

val df = spark.range(1).selectExpr(
  "conv('3', 10, 2) as test1",
  "conv('-15', 10, -16) as test2",
  "conv('-15', 10, 16) as test3",
  "conv('big', 36, 16) as test4"
)

println("Expected results:")
println("  conv('3', 10, 2) = '11'")
println("  conv('-15', 10, -16) = '-F'")
println("  conv('-15', 10, 16) = 'FFFFFFFFFFFFFFF1'")
println("  conv('big', 36, 16) = '3A48'")
df.show(false)
```

**Run Command (with all 32 configuration parameters):**
```bash
$SPARK_HOME/bin/spark-shell \
  --master local[2] \
  --conf spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation,org.apache.spark.sql.catalyst.optimizer.ConstantFolding \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.sql.queryExecutionListeners=org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback \
  --conf spark.rapids.sql.explain=ALL \
  --conf spark.rapids.sql.test.isFoldableNonLitAllowed=true \
  --conf spark.rapids.sql.csv.read.decimal.enabled=true \
  --conf spark.rapids.sql.format.avro.enabled=true \
  --conf spark.rapids.sql.format.avro.read.enabled=true \
  --conf spark.rapids.sql.format.hive.text.write.enabled=true \
  --conf spark.rapids.sql.format.json.enabled=true \
  --conf spark.rapids.sql.format.json.read.enabled=true \
  --conf spark.rapids.sql.incompatibleDateFormats.enabled=true \
  --conf spark.rapids.sql.python.gpu.enabled=true \
  --conf spark.rapids.sql.rowBasedUDF.enabled=true \
  --conf spark.rapids.sql.window.collectList.enabled=true \
  --conf spark.rapids.sql.window.collectSet.enabled=true \
  --conf spark.rapids.sql.window.range.byte.enabled=true \
  --conf spark.rapids.sql.window.range.short.enabled=true \
  --conf spark.rapids.sql.expression.Ascii=true \
  --conf spark.rapids.sql.expression.Conv=true \
  --conf spark.rapids.sql.expression.GetJsonObject=true \
  --conf spark.rapids.sql.expression.JsonToStructs=true \
  --conf spark.rapids.sql.expression.StructsToJson=true \
  --conf spark.rapids.sql.exec.CollectLimitExec=true \
  --conf spark.rapids.sql.exec.FlatMapCoGroupsInPandasExec=true \
  --conf spark.rapids.sql.exec.WindowInPandasExec=true \
  --conf spark.rapids.sql.hasExtendedYearValues=false \
  --conf spark.unsafe.exceptionOnMemoryLeak=true \
  --conf spark.sql.session.timeZone=America/Los_Angeles \
  --jars $RAPIDS_JAR \
  < reproduce-math-expressions-conv.scala
```

---

**Expected behavior**

The `conv` function should convert numbers between different bases correctly. Example test cases:
- `conv("3", 10, 2)` should return `"11"`
- `conv("-15", 10, -16)` should return `"-F"`
- `conv("-15", 10, 16)` should return `"FFFFFFFFFFFFFFF1"`
- `conv("big", 36, 16)` should return `"3A48"`

**Actual behavior**

GPU version of conv function fails during test execution.
It threw:
java.lang.RuntimeException: Logic error: Spark should fold the conv expr into scalar value.

---

**Environment details**

- **Spark Version**: 3.3.0
- **RAPIDS Version**: 25.12.0-SNAPSHOT
- **CUDA Version**: 12.x
- **Test Suite**: MathExpressionsSuite
- **Test Name**: conv

---

**Additional context**

- **Original Spark Test Location**: `spark/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/MathExpressionsSuite.scala` (line 160)
- **Test Logic**: Validates base conversion function with various inputs including null handling and edge cases

### LINKED ISSUE #13738: [AutoSparkUT] log10 - Function has different output on GPU
**Describe the bug**

The `log10` function test fails on GPU during expression evaluation.

---

**Steps/Code to reproduce bug**

### Spark-shell Reproduction Code

**Environment Setup:**
```bash
export SPARK_HOME=/path/to/spark-3.3.0
export RAPIDS_JAR=rapids-4-spark_2.12-25.12.0-SNAPSHOT-cuda12.jar
```

**Reproduction Script:** `test-failures/reproduce-math-expressions-log10.scala`

```scala
// Test: log10 function with positive and negative values

// Positive values
val df1 = spark.range(1).selectExpr(
  "log10(0.1) as test1",
  "log10(1.0) as test2",
  "log10(10.0) as test3",
  "log10(100.0) as test4"
)
df1.show(false)

// Non-positive values (should return null)
val df2 = spark.range(1).selectExpr(
  "log10(0.0) as zero",
  "log10(-0.5) as negative",
  "log10(-1.0) as negative2"
)
df2.show(false)
```

**Run Command (with all 32 configuration parameters):**
```bash
cd test-failures
$SPARK_HOME/bin/spark-shell \
  --master local[2] \
  --conf spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation,org.apache.spark.sql.catalyst.optimizer.ConstantFolding \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.sql.queryExecutionListeners=org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback \
  --conf spark.rapids.sql.explain=ALL \
  --conf spark.rapids.sql.test.isFoldableNonLitAllowed=true \
  --conf spark.rapids.sql.csv.read.decimal.enabled=true \
  --conf spark.rapids.sql.format.avro.enabled=true \
  --conf spark.rapids.sql.format.avro.read.enabled=true \
  --conf spark.rapids.sql.format.hive.text.write.enabled=true \
  --conf spark.rapids.sql.format.json.enabled=true \
  --conf spark.rapids.sql.format.json.read.enabled=true \
  --conf spark.rapids.sql.incompatibleDateFormats.enabled=true \
  --conf spark.rapids.sql.python.gpu.enabled=true \
  --conf spark.rapids.sql.rowBasedUDF.enabled=true \
  --conf spark.rapids.sql.window.collectList.enabled=true \
  --conf spark.rapids.sql.window.collectSet.enabled=true \
  --conf spark.rapids.sql.window.range.byte.enabled=true \
  --conf spark.rapids.sql.window.range.short.enabled=true \
  --conf spark.rapids.sql.expression.Ascii=true \
  --conf spark.rapids.sql.expression.Conv=true \
  --conf spark.rapids.sql.expression.GetJsonObject=true \
  --conf spark.rapids.sql.expression.JsonToStructs=true \
  --conf spark.rapids.sql.expression.StructsToJson=true \
  --conf spark.rapids.sql.exec.CollectLimitExec=true \
  --conf spark.rapids.sql.exec.FlatMapCoGroupsInPandasExec=true \
  --conf spark.rapids.sql.exec.WindowInPandasExec=true \
  --conf spark.rapids.sql.hasExtendedYearValues=false \
  --conf spark.unsafe.exceptionOnMemoryLeak=true \
  --conf spark.sql.session.timeZone=America/Los_Angeles \
  --jars $RAPIDS_JAR \
  < reproduce-math-expressions-log10.scala
```

---

**Expected behavior**

The `log10` function should compute base-10 logarithm correctly for positive values and return null for non-positive values.

Test cases:
- `log10(x)` for x in `(1 to 20).map(_ * 0.1)` should work correctly
- `log10(x)` for x in `(-5 to 0).map(_ * 0.1)` should return null

**Actual behavior**

GPU output:
+-------------------+-----+-----+-----+                                         
|test1              |test2|test3|test4|
+-------------------+-----+-----+-----+
|-0.9999999999999998|0.0  |1.0  |2.0  |
+-------------------+-----+-----+-----+

+----+--------+---------+
|zero|negative|negative2|
+----+--------+---------+
|    |        |         |
+----+--------+---------+

CPU:
+-----+-----+-----+-----+
|test1|test2|test3|test4|
+-----+-----+-----+-----+
|-1.0 |0.0  |1.0  |2.0  |
+-----+-----+-----+-----+

+----+--------+---------+
|zero|negative|negative2|
+----+--------+---------+
|null|null    |null     |
+----+--------+---------+

---

**Environment details**

- **Spark Version**: 3.3.0
- **RAPIDS Version**: 25.12.0-SNAPSHOT
- **CUDA Version**: 12.x
- **Test Suite**: MathExpressionsSuite
- **Test Name**: log10

---

**Additional context**

- **Original Spark Test Location**: `spark/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/MathExpressionsSuite.scala` (line 435)
- **Test Logic**: Validates log10 function with positive and negative inputs

### LINKED ISSUE #13740: [AutoSparkUT] log2 - Function has different output on GPU
**Describe the bug**

The `log2` function test fails on GPU during expression evaluation.

---

**Steps/Code to reproduce bug**

### Spark-shell Reproduction Code

**Environment Setup:**
```bash
export SPARK_HOME=/path/to/spark-3.3.0
export RAPIDS_JAR=rapids-4-spark_2.12-25.12.0-SNAPSHOT-cuda12.jar
```

**Reproduction Script:** `test-failures/reproduce-math-expressions-log2.scala`

```scala
// Non-positive values (should return null)
val df2 = spark.range(1).selectExpr(
  "log2(0.0) as zero",
  "log2(-0.5) as negative",
  "log2(-1.0) as negative2"
)
df2.show(false)
```

**Run Command (with all 32 configuration parameters):**
```bash
cd test-failures
$SPARK_HOME/bin/spark-shell \
  --master local[2] \
  --conf spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation,org.apache.spark.sql.catalyst.optimizer.ConstantFolding \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.sql.queryExecutionListeners=org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback \
  --conf spark.rapids.sql.explain=ALL \
  --conf spark.rapids.sql.test.isFoldableNonLitAllowed=true \
  --conf spark.rapids.sql.csv.read.decimal.enabled=true \
  --conf spark.rapids.sql.format.avro.enabled=true \
  --conf spark.rapids.sql.format.avro.read.enabled=true \
  --conf spark.rapids.sql.format.hive.text.write.enabled=true \
  --conf spark.rapids.sql.format.json.enabled=true \
  --conf spark.rapids.sql.format.json.read.enabled=true \
  --conf spark.rapids.sql.incompatibleDateFormats.enabled=true \
  --conf spark.rapids.sql.python.gpu.enabled=true \
  --conf spark.rapids.sql.rowBasedUDF.enabled=true \
  --conf spark.rapids.sql.window.collectList.enabled=true \
  --conf spark.rapids.sql.window.collectSet.enabled=true \
  --conf spark.rapids.sql.window.range.byte.enabled=true \
  --conf spark.rapids.sql.window.range.short.enabled=true \
  --conf spark.rapids.sql.expression.Ascii=true \
  --conf spark.rapids.sql.expression.Conv=true \
  --conf spark.rapids.sql.expression.GetJsonObject=true \
  --conf spark.rapids.sql.expression.JsonToStructs=true \
  --conf spark.rapids.sql.expression.StructsToJson=true \
  --conf spark.rapids.sql.exec.CollectLimitExec=true \
  --conf spark.rapids.sql.exec.FlatMapCoGroupsInPandasExec=true \
  --conf spark.rapids.sql.exec.WindowInPandasExec=true \
  --conf spark.rapids.sql.hasExtendedYearValues=false \
  --conf spark.unsafe.exceptionOnMemoryLeak=true \
  --conf spark.sql.session.timeZone=America/Los_Angeles \
  --jars $RAPIDS_JAR \
  < reproduce-math-expressions-log2.scala
```

---

**Expected behavior**

The `log2` function should compute base-2 logarithm correctly for positive values and return null for non-positive values.

Test cases:
- `log2(x)` for x in `(-5 to 0).map(_ * 1.0)` should return null

**Actual behavior**

GPU output:
+----+--------+---------+
|zero |negative |negative2|
+----+--------+---------+
|         |               |                 |
+----+--------+---------+

CPU:
+----+--------+---------+
|zero |negative |negative2|
+----+--------+---------+
|null   |null         |null           |
+----+--------+---------+
---

**Environment details**

- **Spark Version**: 3.3.0
- **RAPIDS Version**: 25.12.0-SNAPSHOT
- **CUDA Version**: 12.x
- **Test Suite**: MathExpressionsSuite
- **Test Name**: log2

---

**Additional context**

- **Original Spark Test Location**: `spark/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/MathExpressionsSuite.scala` (line 469)
- **Test Logic**: Validates log2 function with positive and negative inputs

### LINKED ISSUE #13741: [AutoSparkUT] binary log - GPU returns NaN instead of null for negative base
**Describe the bug**

The `LOG` function with negative base on GPU returns `NaN` instead of `null` when given invalid input (negative base), while CPU correctly returns `null`.

---

**Steps/Code to reproduce bug**

### Spark-shell Reproduction Code

**Environment Setup:**
```bash
export SPARK_HOME=/path/to/spark-3.3.0
export RAPIDS_JAR=rapids-4-spark_2.12-25.12.0-SNAPSHOT-cuda12.jar
```

**Reproduction Script:** `test-failures/reproduce-math-expressions-binary-log.scala`

```scala
// Test: LOG(-1.0, 1.0) returns NaN instead of null

val df = spark.range(1).selectExpr(
  "log(-1.0, 1.0) as result"
)

println("Test: log(-1.0, 1.0)")
println("Expected: null")
println("Actual:")
df.show(false)
```

**Run Command (with all 32 configuration parameters):**
```bash
cd test-failures
$SPARK_HOME/bin/spark-shell \
  --master local[2] \
  --conf spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation,org.apache.spark.sql.catalyst.optimizer.ConstantFolding \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.sql.queryExecutionListeners=org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback \
  --conf spark.rapids.sql.explain=ALL \
  --conf spark.rapids.sql.test.isFoldableNonLitAllowed=true \
  --conf spark.rapids.sql.csv.read.decimal.enabled=true \
  --conf spark.rapids.sql.format.avro.enabled=true \
  --conf spark.rapids.sql.format.avro.read.enabled=true \
  --conf spark.rapids.sql.format.hive.text.write.enabled=true \
  --conf spark.rapids.sql.format.json.enabled=true \
  --conf spark.rapids.sql.format.json.read.enabled=true \
  --conf spark.rapids.sql.incompatibleDateFormats.enabled=true \
  --conf spark.rapids.sql.python.gpu.enabled=true \
  --conf spark.rapids.sql.rowBasedUDF.enabled=true \
  --conf spark.rapids.sql.window.collectList.enabled=true \
  --conf spark.rapids.sql.window.collectSet.enabled=true \
  --conf spark.rapids.sql.window.range.byte.enabled=true \
  --conf spark.rapids.sql.window.range.short.enabled=true \
  --conf spark.rapids.sql.expression.Ascii=true \
  --conf spark.rapids.sql.expression.Conv=true \
  --conf spark.rapids.sql.expression.GetJsonObject=true \
  --conf spark.rapids.sql.expression.JsonToStructs=true \
  --conf spark.rapids.sql.expression.StructsToJson=true \
  --conf spark.rapids.sql.exec.CollectLimitExec=true \
  --conf spark.rapids.sql.exec.FlatMapCoGroupsInPandasExec=true \
  --conf spark.rapids.sql.exec.WindowInPandasExec=true \
  --conf spark.rapids.sql.hasExtendedYearValues=false \
  --conf spark.unsafe.exceptionOnMemoryLeak=true \
  --conf spark.sql.session.timeZone=America/Los_Angeles \
  --jars $RAPIDS_JAR \
  < reproduce-math-expressions-binary-log.scala
```

---

**Expected behavior**

When calling `LOG(-1.0, 1.0)` (logarithm with negative base), the function should return `null` to indicate an invalid operation, consistent with Spark CPU behavior.

**Actual behavior**

GPU returns `NaN` instead of `null`.

---

**Environment details**

- **Spark Version**: 3.3.0
- **RAPIDS Version**: 25.12.0-SNAPSHOT
- **CUDA Version**: 12.x
- **Test Suite**: MathExpressionsSuite
- **Test Name**: binary log

---

**Additional context**

- **Original Spark Test Location**: `spark/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/MathExpressionsSuite.scala` (line 611)
- **Test Logic**: Validates that `Logarithm` expression correctly handles negative base input

### PR DESCRIPTION
**Pull request by revans2**
This fixes #13741 
This fixes #13740 
This fixes #13738 
This fixes #13737 

This partially fixes https://github.com/NVIDIA/spark-rapids/issues/89 (at least I think it does)

The comes down to a few issues that were fixed.

1) `log` and `conv` were not properly setting `nullable`. So if the output ended up with a NULL in it and we tried to bring it back to the CPU we might have gotten data corruption.
2) `log` had not implemented the all scalar version so it ended up not getting any validity checks
3) `conv` had implemented an all scalar version, but it threw an exception. It should almost never happen, so I made a version that does the right thing.
4) log has only done half of the input checks. This resulted in some NaN's being returned when Spark wanted them to be nulls.
5) The log check issues were then hidden by the test for them being marked as xfail. It was 5 years ago when I filed it so I don't know if things changed or what, but it all appears to pass now.

### Checklists

- [X] This PR has added documentation for new or modified features or behaviors.
- [X] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [ ] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

I didn't do any performance testing because correctness trumps performance. The change should be small because we are doing a few extra checks, but they are not that much.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala [hunk 1]
```diff
@@ -328,21 +328,22 @@ object GpuLogarithm {
    * Replace negative values with nulls. Note that the caller is responsible for closing the
    * returned GpuColumnVector.
    */
-  def fixUpLhs(input: GpuColumnVector): ColumnVector = {
-    withResource(Scalar.fromDouble(0)) { zero =>
+  def fixUpInput(input: GpuColumnVector, dt: DataType): GpuColumnVector = {
```
Comment (abellina) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala]: nit, I wish these were called `nullOutNegatives`

Comment (revans2) [reply sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala]: done, please have another look

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala [hunk 2]
```diff
@@ -328,21 +328,22 @@ object GpuLogarithm {
    * Replace negative values with nulls. Note that the caller is responsible for closing the
    * returned GpuColumnVector.
    */
-  def fixUpLhs(input: GpuColumnVector): ColumnVector = {
-    withResource(Scalar.fromDouble(0)) { zero =>
+  def nullOutNegatives(input: GpuColumnVector, dt: DataType): GpuColumnVector = {
```
Comment (mythrocks) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala:331]: 👏
