### PR TITLE
Fix shuffle fallback due to AQE on AWS EMR [databricks]

### LINKED ISSUE #9092: [BUG] NDS query 64 falls back to CPU only for a shuffle
When running NDS query 64 at the 3k scale factor on AWS EMR 6.12, there is an unnecessary fallback to the CPU for a shuffle.  The node sequence in the plan UI is:
```
GpuHashAggregate(partial) ->
  GpuColumnarToRow ->
    AdaptiveSparkPlan ->
      Exchange ->
        ReusedExchange ->
          AQEShuffleRead ->
            GpuRowToColumnar ->
              GpuHashAggregate(final)
```

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #9092.  AWS EMR can emit a plan fragment where the root of the plan is a shuffle followed by an adaptive plan.  Before, we would treat the adaptive plan as not columnar and thus not translate the shuffle because it's child was believed to be not columnar.  That would cause an injection of ColumnarToRow once we glued the eventually translated adaptive plan into the not-translated shuffle and a corresponding RowToColumnar on the other side of the shuffle.

This fixes the issue by examining the AQE plan to see if it looks like we're going to be able to translate the top node.  If so, we go ahead and treat the AQE node as columnar which allows the shuffle to be tagged to be translated.  Once we actually perform the translation, we check if the child is an AdaptiveSparkPlanExec and translate that to columnar along with the shuffle node being translated.

This also consolidates GpuShuffleMeta for Spark 3.4 with the Spark 3.1 shim since it was the same code.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Review by andygrove — APPROVED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala [hunk 1]
```diff
@@ -527,7 +527,8 @@ class GpuTransitionOverrides extends Rule[SparkPlan] {
    */
   private def insertColumnarToGpu(plan: SparkPlan): SparkPlan = {
     val nonQueryStagePlan = GpuTransitionOverrides.getNonQueryStagePlan(plan)
-    if (nonQueryStagePlan.supportsColumnar && !nonQueryStagePlan.isInstanceOf[GpuExec]) {
+    if (nonQueryStagePlan.supportsColumnar && !nonQueryStagePlan.isInstanceOf[GpuExec] &&
+      !nonQueryStagePlan.isInstanceOf[AdaptiveSparkPlanExec]) {
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala:531]: Never insert a `HostColumnarToGpu` for `AdaptiveSparkPlanExec`. Does that work on all of the versions of Spark that we support?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala [hunk 2]
```diff
@@ -650,8 +651,25 @@ abstract class SparkPlanMeta[INPUT <: SparkPlan](plan: INPUT,
...
         (plan.conf.adaptiveExecutionEnabled ||
         !parent.exists(_.supportsColumnar))) {
+      // Some platforms can present a plan where the root of the plan is a shuffle followed by
+      // an AdaptiveSparkPlanExec. If it looks like the AdaptiveSparkPlanExec will end up
+      // columnar than this shuffle should be columnar as well.
+      val shuffle = wrapped.asInstanceOf[ShuffleExchangeExec]
+      val isChildColumnar = shuffle.child match {
+        case adaptiveExec: AdaptiveSparkPlanExec if parent.isEmpty =>
+          val aqePlan = adaptiveExec.executedPlan
+          if (aqePlan.supportsColumnar) {
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala:661]: So what happens if all we have is a parquet read followed by an AdaptiveSparkPlanExec and then the shuffle? The `aqePlan` would support columnar, but it would not be on the GPU, at least not yet, and it is not guaranteed to be.

I guess this is a similar question around line 653. Is saying that the output data is columnar good enough, or do we want to know that the data is on the GPU?

**Review by revans2 — COMMENTED** [review]
I am primarily concerned about not inserting in the HostColumnarToGpu. It feels kind of fragile. Are we sure that we can always bypass the AdaptiveSparkPlanExec or at least mark it as columnar?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala (hunk 1 above)
Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala:531]: I didn't think AdaptiveSparkPlanExec would appear in front of a scan but instead in front of querystage or subquery node where AQE can examine the shuffle partitions and decide how many tasks to run in the subsequent stage.  Is that not the case?

Otherwise I'm not sure how we can know for sure whether an AdaptiveSparkPlanExec is really producing GPU output.  If the AdaptiveSparkPlan is not fully planned yet then I don't know if we can guarantee we know it will be.  I suppose one other approach is to use a plan tag approach where the shuffle exec marks the underlying AdaptiveSparkPlanExec node when it converts it to columnar to note that we should not inject a host columnar transition on that.

Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala:531]: There are two comments that I have here and I think you are responding to both here so I will try to do the same.

My first concern is that with this change we are essentially saying that all AdaptiveSparkPlanExec nodes that `supportsColumnar` output will produce GPU output. I think that is okay because I think we are the only ones that will set AdaptiveSparkPlanExec to be columnar. I just would like a comment or something explaining what is happening because it feel brittle.

My second concern is more of a performance issue compared to anything. We equate `supportsColumnar` with this is running on the GPU. I think that is a fairly good assumption most of the time, but a scan will output columnar data that is not on the GPU.  This code runs before columnar to row transitions are inserted into the plan. Which means if I do a join on a parquet file input, the first stage of the plan will look like a parquet read -> shuffle.  I don't know how AQE will plan things out for the child plan, but if it ever looks like read -> AdaptiveSparkPlanExec -> shuffle we could end up doing a shuffle on the GPU when the read might not be on the GPU.  But I think that is rare enough it is fine. Again it is more of having a comment here might be nice to explain what is happening any why.

Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala:531]: > I just would like a comment or something explaining what is happening because it feel brittle.

I'll add comments around this.  I agree it feels brittle, but I wasn't sure there was a better way to do this.  If Spark starts doing significant columnar processing in nodes we cannot replace (like AdaptiveSparkPlanExec), we've got a lot of work to do to keep things straight. :sweat_smile: 

> if it ever looks like read -> AdaptiveSparkPlanExec -> shuffle we could end up doing a shuffle on the GPU when the read might not be on the GPU.

Yeah this is related to the comment above.  We don't really have a good way to distinguish whether we're CPU or GPU for columnar execs that we cannot replace with GPU execs.

Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala:531]: I suppose for the AdaptiveSparkPlanExec is already columnar, we could do a similar technique to https://github.com/NVIDIA/spark-rapids/pull/9134/files#diff-389f8b5c364533aaab72c65af450b2a2a9c7c944112527455ba34af06a188c72R664-R665 where we try to see if the head node looks like it's going to be on the GPU in the adaptive sub-plan.  I think that would resolve the concern about non-GPU columnar read in that scenario.

Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala:531]: I am fine with just comments for now.

Comment (jlowe) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala]: I ended up tackling this with a new utility method in GpuOverrides that tries to predict whether an AdaptiveSparkPlanExec appears it will be translated to the GPU based on its current subplan.  Also refactored the code to use some more descriptive names which IMHO makes the code more readable without needing more comments.  If you feel more comments are still warranted, happy to add them.

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]
