### PR TITLE
Handle regexp_replace inconsistency with empty strings and zero-repetition patterns [databricks]

### LINKED ISSUE #5456: [BUG] Handle regexp_replace inconsistency from https://issues.apache.org/jira/browse/SPARK-39107
**Describe the bug**
When passing an empty string (`''`) and a regular expression containing only `?` or `*` repetitions, the output is not consistent between Spark and cuDF.  Note this is actually a pure inconsistency with Spark's `regexp_replace`, it actually does not apply to what Java does as a standard.  

**Steps/Code to reproduce bug**
PySpark Example Code:
```
from pyspark.sql import SparkSession

spark = SparkSession.builder \
      .master("local[*]") \
      .appName("regex_empty_match") \
      .config("spark.rapids.sql.regexp.enabled", "true") \
      .config("spark.rapids.sql.explain","ALL") \
      .config("spark.rapids.sql.castStringToTimestamp.enabled","true") \
      .config("spark.rapids.sql.exec.CollectLimitExec", "true") \
      .config("spark.rapids.sql.castFloatToString.enabled", "true") \
      .config("spark.rapids.sql.hasExtendedYearValues", "false") \
      .getOrCreate()  

df = spark.sparkContext.parallelize([[""],[""],["AAA"]]).toDF(["a"])
df.show()

df.selectExpr("regexp_replace(a,'A*','_REPLACED_')").show()
```

Spark (CPU) Output:
```
+------------------------------------+
|regexp_replace(a, A*, _REPLACED_, 1)|
+------------------------------------+
|                                                               |
|                                                               |
|                _REPLACED__REPLACED_  |
+------------------------------------+
```

Plugin (GPU) Output:
```
+-------------------------------------+
|regexp_replace(a, A*, _REPLACED_, 1)|
+-------------------------------------+
|                          _REPLACED_                |
|                          _REPLACED_                |
|                _REPLACED__REPLACED_   |
+------------------------------------+
```

**Expected behavior**

Empty string input should be short circuited in the plugin as this is what is expected in certain versions of Spark.

**Additional context**

This bug was originally reported to Spark in https://issues.apache.org/jira/browse/SPARK-39107, and the issue was fixed in apache/spark#36457 for newer patch versions of Spark in 3.1,3.2,3.3 and master, so shims will need to be created to handle the original faulty behavior.

### PR DESCRIPTION
**Pull request by anthony-chang**
Fixes #5456

When using `regexp_replace` on an empty string using a regex pattern containing only zero-repetitions (eg. `*`, `?`, `{0,}`, etc), the behaviour is different depending on which version of Spark. 

Given the input
```python
df = spark.sparkContext.parallelize([[""],[""],["AAA"]]).toDF(["a"])
df.selectExpr("regexp_replace(a,'A*','_REPLACED_')").show()
```
Spark versions 3.1.3, 3.1.4, 3.2.2, 3.3.0+ gives
```
+-------------------------------------+
|regexp_replace(a, A*, _REPLACED_, 1) |
+-------------------------------------+
|                          _REPLACED_ |
|                          _REPLACED_ |
|                _REPLACED__REPLACED_ |
+-------------------------------------+
```
but all other versions gives

```
+-------------------------------------+
|regexp_replace(a, A*, _REPLACED_, 1) |
+-------------------------------------+
|                                     |
|                                     |
|                _REPLACED__REPLACED_ |
+-------------------------------------+
```

This PR adds shims for the 2nd case to short circuit the plugin regex handling. 

Signed-off-by: Anthony Chang <antchang@nvidia.com>

### CODE REVIEW

File: sql-plugin/src/main/311-nondb/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala [hunk 1]
```diff
@@ -0,0 +1,22 @@
+/*
+ * Copyright (c) 2021-2022, NVIDIA CORPORATION.
```
Comment (andygrove) [inline sql-plugin/src/main/311-nondb/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala:2]: The copyrights on these filles should just have 2022 rather than 2021-2022

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala [hunk 2]
```diff
@@ -960,17 +961,52 @@ case class GpuRegExpReplace(
...
   }
 
   override def doColumnar(
       strExpr: GpuColumnVector,
       searchExpr: GpuScalar,
       replaceExpr: GpuScalar): ColumnVector = {
-    withResource(Scalar.fromString(cudfReplacementString)) { rep =>
-      strExpr.getBase.replaceRegex(cudfRegexPattern, rep)
+
+    val isEmptyRepetition: Boolean = {
```
Comment (andygrove) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala:976]: Should this be a recursive check using the recently added `contains` method? I'm thinking cases like `(((A*)))`

**Comment by andygrove** [comment]
@anthony-chang I know this is still WIP but could you update the PR description to explain what is changed in this PR

**Comment by anthony-chang** [comment]
build

**Comment by anthony-chang** [comment]
build

**Comment by anthony-chang** [comment]
build

**Comment by anthony-chang** [comment]
build

**Comment by anthony-chang** [comment]
build

**Comment by anthony-chang** [comment]
build

**Comment by anthony-chang** [comment]
build

**Comment by anthony-chang** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala [hunk 3]
```diff
@@ -960,17 +961,59 @@ case class GpuRegExpReplace(
...
+        case RegexSequence(parts) =>
+          parts.forall(isEmptyRepetition)
+        // cuDF does not support repetitions adjacent to a choice (eg. "a*|a"), but if
+        // we did, we would need to add a `case RegexChoice()` here
+        case _ => false
+      }
+    }
+
+    // For empty strings and a regex containing only a zero-match reptition, 
+    // the behaviour on Spark is different.
```
Comment (andygrove) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala:995]:
```suggestion
    // the behavior in some versions of Spark is different. 
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala [hunk 4]
```diff
@@ -960,17 +961,59 @@ case class GpuRegExpReplace(
...
+        // we did, we would need to add a `case RegexChoice()` here
+        case _ => false
+      }
+    }
+
+    // For empty strings and a regex containing only a zero-match reptition, 
+    // the behaviour on Spark is different. 
+    // see https://github.com/NVIDIA/spark-rapids/issues/5456
+    if (RegExpShim.reproduceEmptyStringBug() &&
+      isEmptyRepetition(new RegexParser(javaRegexpPattern).parse())) {
```
Comment (andygrove) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala:998]: nit: indent is off per the style guide we follow (see CONTRIBUTING.md for links to style guides)

```suggestion
        isEmptyRepetition(new RegexParser(javaRegexpPattern).parse())) {
```

**Comment by anthony-chang** [comment]
build

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala [hunk 5]
```diff
@@ -960,17 +961,59 @@ case class GpuRegExpReplace(
...
   }
 
   override def doColumnar(
       strExpr: GpuColumnVector,
       searchExpr: GpuScalar,
       replaceExpr: GpuScalar): ColumnVector = {
-    withResource(Scalar.fromString(cudfReplacementString)) { rep =>
-      strExpr.getBase.replaceRegex(cudfRegexPattern, rep)
+
+    def isEmptyRepetition(regex: RegexAST): Boolean = {
```
Comment (NVnavkumar) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala:976]: This method could actually live in the `RegExpUtils` object which is in the same file.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala (hunk 4 above)
Comment (NVnavkumar) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala]: Also, the parsing logic could all be encapsulated in that object, so as to not expose the RegexParser in the doColumnar method here.

**Comment by anthony-chang** [comment]
build

**Review by NVnavkumar — APPROVED** [review]

**Review by andygrove — APPROVED** [review]
