### PR TITLE
Fallback Delta scan if deletion vectors are being read in Databricks 13.3 [databricks]

### LINKED ISSUE #12539: [BUG] Unable to display rows from a Delta Table on Databricks 13.3 with Deletion Vectors enabled
**Describe the bug**
On Databricks 12.2 and 13.3 when querying a managed table, it incorrectly shows the rows as 0

**Steps/Code to reproduce bug**
* Create a notebook and attach it to Databricks 12.2/13.3 cluster in dedicated mode (single user) 
* run the following query 
```
from pyspark.sql import SparkSession
from pyspark.sql.functions import col

# Create a SparkSession
spark = SparkSession.builder \
    .appName("Read from Unity Catalog Metastore Table") \
    .enableHiveSupport() \
    .getOrCreate()

spark.sparkContext.setLogLevel("INFO")

spark.conf.set("spark.rapids.sql.enabled", "true")
spark.conf.set("spark.rapids.sql.explain", "ALL")

# Read data from the Hive Metastore table
df = spark.table("test_workspace_sraheja_2024_05_03.rjafri.department")

df.show()

```

**Expected behavior**
The above query should return 5 rows 

**Environment details (please complete the following information)**
* SHA1 - 9fcf74e724b3eaa8b8b3e5a43a0a1ce7d3ddd055) 
* Databricks 13.3

**Additional context**

### PR DESCRIPTION
**Pull request by razajafri**
This was a long-standing bug in the plugin where we falsely put the Delta scan on the GPU, causing nothing to be returned as a result in the project.

fixes #12539

### CODE REVIEW

**Comment by razajafri** [comment]
build

File: delta-lake/delta-spark332db/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala [hunk 1]
```diff
@@ -51,11 +50,11 @@ object GpuDeltaParquetFileFormat {
   def tagSupportForGpuFileSourceScan(meta: SparkPlanMeta[FileSourceScanExec]): Unit = {
     val format = meta.wrapped.relation.fileFormat.asInstanceOf[DeltaParquetFileFormat]
     val requiredSchema = meta.wrapped.requiredSchema
-    if (requiredSchema.exists(_.name == IS_ROW_DELETED_COLUMN_NAME)) {
+    if (requiredSchema.exists(_.name.startsWith("_databricks_internal"))) {
```
Comment (abellina) [inline delta-lake/delta-spark332db/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala:53]: Curious if the value of `IS_ROW_DELETED_COLUMN_NAME` is `_databricks_internal` and if so, could we use that constant in the startsWith search?

Comment (razajafri) [reply delta-lake/delta-spark332db/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala:53]: It's not. The open source uses a different prefix.

**Comment by razajafri** [comment]
@abellina @gerashegalov Do you have anymore questions on this PR?

File: integration_tests/src/main/python/delta_lake_test.py [hunk 2]
```diff
@@ -125,6 +125,25 @@ def create_delta(spark):
     assert_gpu_and_cpu_are_equal_collect(lambda spark: spark.read.format("delta").load(data_path),
                                          conf=confs)
 
+@allow_non_gpu('FileSourceScanExec')
+@delta_lake 
+def test_delta_read(spark_tmp_path):
```
Comment (gerashegalov) [inline integration_tests/src/main/python/delta_lake_test.py:130]: the name should be more specific. we are not testing just the read. It looks like the test case is 

``test_delta_log_query_with_deletion_vectors` because we disable the fallback for delta log and enable DV

**Review by gerashegalov — APPROVED** [review]
LGTM, nits
