### PR TITLE
Fix AST report can not create non-fixed-width column error [databricks]

### LINKED ISSUE #12505: [BUG] AST report ai.rapids.cudf.CudfException:  Invalid, non-fixed-width type
**Describe the bug**
From nvbug, when AST ColumnReference returns a string column, cuDF reports non-fixed-width error.

**Steps/Code to reproduce bug**
```python
import datetime

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
from pyspark.sql.window import Window



if __name__ == "__main__":

    spark = SparkSession.builder.appName(f"ast_error_rep").getOrCreate()
    spark.conf.set('spark.sql.adaptive.enabled','false')
    spark.conf.set('spark.rapids.sql.projectAstEnabled', 'true') 
    spark.conf.set("spark.rapids.sql.enabled","true")

    data = [
        (True, -121, -5755, 1334097539, 381282419020311609, -1.1721174086335895e+38, 2.0819242151822298e+304, 'A3iMw', datetime.datetime(7266, 5, 8, 8, 38, 33, 297395), 
datetime.date(9496, 3, 16)),
        (True, 27, 14757, -1576346870, 8658683339966252738, 7.71262355598091e+37, 
2.1026643576591284e-206, 'im86tIxX5puQJCBEeP', datetime.datetime(5660, 9, 29, 8, 7, 51, 885069), datetime.date(5764, 10, 27)),
        (None, None, None, None, None, None, None, None, None, None)
    ]
    schema =  StructType([
        StructField('col_bool', BooleanType(), True),
        StructField('col_byte', StringType(), True),
        StructField('col_short', ShortType(), True),
        StructField('col_int', IntegerType(), True),
        StructField('col_long', LongType(), True),
        StructField('col_float', FloatType(), True),
        StructField('col_double', DoubleType(), True),
        StructField('col_string', StringType(), True),
        StructField('col_timestamp', TimestampType(), True),
        StructField('col_date', DateType(), True)])
    df = spark.createDataFrame(data, schema)
    cols = df.columns

    df = df.withColumn("cidx", F.monotonically_increasing_id())
    window_spec = Window.orderBy("cidx")
    df = df.withColumn("rid", F.row_number().over(window_spec)).drop("cidx")

    df_bnlj_non_null_neg = df.alias("t1").join(df.alias("t2"),
                                               [(F.col("t1.col_int") > F.col("t2.col_int")), ~(F.col("t1.col_int").isNull())],
                                                how="leftsemi").selectExpr(*[f"isnotnull({c}) as {c}_isnotnull" for c in cols], "rid")
    df_bnlj_non_null_neg.show()
    df_bnlj_non_null_neg.explain()

    spark.stop()
```

Error:
```
25/04/10 05:40:09 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 4) (10.176.9.147 executor 0): ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-pre_release-431-cuda12/thirdparty/cudf/cpp/src/column/column_factories.cpp:159: Invalid, non-fixed-width type.
at ai.rapids.cudf.ast.CompiledExpression.computeColumn(Native Method)
at ai.rapids.cudf.ast.CompiledExpression.computeColumn(CompiledExpression.java:88)
at com.nvidia.spark.rapids.GpuProjectAstExec$$anon$1.$anonfun$next$15(basicPhysicalOperators.scala:765)
at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:166)
at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:163)
at scala.collection.immutable.List.foreach(List.scala:431)

```

### PR DESCRIPTION
**Pull request by res-life**
closes #12505

### Analysis
If an AST expr refer to a string column via AttributeReference, the cudf::compute_column will throw error: Invalid, non-fixed-width type
Refer to code [link](https://github.com/rapidsai/cudf/blob/v25.04.00/cpp/src/transform/compute_column.cu#L99):
```cpp
std::unique_ptr<column> compute_column(table_view const& table,
                                       ast::expression const& expr,
                                       rmm::cuda_stream_view stream,
                                       rmm::device_async_resource_ref mr)
{
// ......
  auto output_column = cudf::make_fixed_width_column(
    parser.output_type(), table.num_rows(), output_column_mask_state, stream, mr);
}
```

### changes

- Verify if any expr returns non-fixed-width column
- Print warning log when meets non-fixed-width column

#### Before:
```
GpuColumnarToRow false
+- GpuProjectAst [gpuisnotnull(col_int#53) AS col_int_isnotnull#79, gpuisnotnull(col_string#54) AS col_string_isnotnull#80, rid#62]
   +- GpuBroadcastNestedLoopJoin LeftSemi, GpuBuildRight, (col_int#53 > col_int#70), [col_int#70], 1073741824
      :- GpuProjectAst [col_int#53, col_string#54, rid#62]
      :  +- GpuCoalesceBatches targetsize(1073741824)
      :     +- GpuFilter gpuisnotnull(col_int#53)
      :        +- GpuRunningWindow [col_int#53, col_string#54, cidx#57L, gpurownumber$() gpuwindowspecdefinition(cidx#57L ASC NULLS FIRST, gpuspecifiedwindowframe(RowFrame, gpuspecialframeboundary(unboundedpreceding$()), gpuspecialframeboundary(currentrow$()))) AS rid#62], [cidx#57L ASC NULLS FIRST]
      :           +- GpuSort [cidx#57L ASC NULLS FIRST], false, com.nvidia.spark.rapids.OutOfCoreSort$@71688fc2
      :              +- GpuShuffleCoalesce 1073741824
      :                 +- GpuColumnarExchange gpusinglepartitioning$(), ENSURE_REQUIREMENTS, [plan_id=993]
      :                    +- GpuProject [col_int#53, col_string#54, monotonically_increasing_id() AS cidx#57L], true
      :                       +- GpuRowToColumnar targetsize(1073741824)
      :                          +- *(1) Scan ExistingRDD[col_int#53,col_string#54]
      +- GpuBroadcastExchange IdentityBroadcastMode, [plan_id=1005]
         +- GpuProjectAst [col_int#70]
            +- GpuCoalesceBatches targetsize(1073741824)
               +- GpuFilter gpuisnotnull(col_int#70)
                  +- GpuRowToColumnar targetsize(1073741824)
                     +- *(2) Scan ExistingRDD[col_int#70,col_string#71]
```

#### After
```
+- GpuProjectAst [gpuisnotnull(col_int#0) AS col_int_isnotnull#26, gpuisnotnull(col_string#1) AS col_string_isnotnull#27, rid#9]
   +- GpuBroadcastNestedLoopJoin LeftSemi, GpuBuildRight, (col_int#0 > col_int#17), [col_int#17], 1073741824
      :- GpuProject [col_int#0, col_string#1, rid#9], true
      :  +- GpuCoalesceBatches targetsize(1073741824)
      :     +- GpuFilter gpuisnotnull(col_int#0)
      :        +- GpuRunningWindow [col_int#0, col_string#1, cidx#4L, gpurownumber$() gpuwindowspecdefinition(cidx#4L ASC NULLS FIRST, gpuspecifiedwindowframe(RowFrame, gpuspecialframeboundary(unboundedpreceding$()), gpuspecialframeboundary(currentrow$()))) AS rid#9], [cidx#4L ASC NULLS FIRST]
      :           +- GpuSort [cidx#4L ASC NULLS FIRST], false, com.nvidia.spark.rapids.OutOfCoreSort$@cdfd7c2
      :              +- GpuShuffleCoalesce 1073741824
      :                 +- GpuColumnarExchange gpusinglepartitioning$(), ENSURE_REQUIREMENTS, [plan_id=162]
      :                    +- GpuProject [col_int#0, col_string#1, monotonically_increasing_id() AS cidx#4L], true
      :                       +- GpuRowToColumnar targetsize(1073741824)
      :                          +- *(1) Scan ExistingRDD[col_int#0,col_string#1]
      +- GpuBroadcastExchange IdentityBroadcastMode, [plan_id=174]
         +- GpuProjectAst [col_int#17]
            +- GpuCoalesceBatches targetsize(1073741824)
               +- GpuFilter gpuisnotnull(col_int#17)
                  +- GpuRowToColumnar targetsize(1073741824)
                     +- *(2) Scan ExistingRDD[col_int#17,col_string#18]
```
#### diff
The following AST project disappeared:
```
// This GpuProjectAst has a string column reference.
GpuProjectAst [col_int#53, col_string#54, rid#62]
====>>>>
GpuProject [col_int#0, col_string#1, rid#9], true
```

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala [hunk 1]
```diff
@@ -57,7 +57,9 @@ class GpuProjectExecMeta(
     val gpuExprs = childExprs.map(_.convertToGpu().asInstanceOf[NamedExpression]).toList
     val gpuChild = childPlans.head.convertIfNeeded()
     if (conf.isProjectAstEnabled) {
-      if (childExprs.forall(_.canThisBeAst)) {
+      if (childExprs.forall(_.canThisBeAst)
+        // cuDF requires return column is fix width
+        && gpuExprs.forall(expr => GpuBatchUtils.isFixedWidth(expr.dataType))) {
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala:62]: nit, we could cache the result of this so we don't have to re-run it for the warning later?

**Review by abellina — COMMENTED** [review]
This looks fine to me, I had a non-blocking nit. 

Note that this is really a test-only feature, and it is OFF by default. I do wonder if we need to put this in 25.04

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala (hunk 1 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala]: Done, now cache the reuslt.

**Comment by res-life** [comment]
> [nitpick] The test does not explicitly verify that the fallback execution path (GpuProjectExec) is used when encountering a non-fixed-width column. Consider capturing and asserting the execution plan to ensure the correct behavior.

The Copilot is right, did not capturing and asserting the execution plan, because there are both `GpuProjectAst` and `GpuProject`, it's hard to verify.

**Comment by res-life** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala [hunk 2]
```diff
@@ -57,16 +57,23 @@ class GpuProjectExecMeta(
     val gpuExprs = childExprs.map(_.convertToGpu().asInstanceOf[NamedExpression]).toList
     val gpuChild = childPlans.head.convertIfNeeded()
     if (conf.isProjectAstEnabled) {
-      if (childExprs.forall(_.canThisBeAst)) {
+      // cuDF requires result columns are fixed width
+      val resultTypes = gpuExprs.map(_.dataType)
+      val isFixedWidth = resultTypes.forall(GpuBatchUtils.isFixedWidth)
```
Comment (ttnghia) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala:62]: Nit: We are checking all columns to be fixed width so use `all*`.
```suggestion
      // cuDF requires result columns are fixed width
      val resultTypes = gpuExprs.map(_.dataType)
      val allFixedWidth = resultTypes.forall(GpuBatchUtils.isFixedWidth)
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala [hunk 3]
```diff
@@ -57,16 +57,23 @@ class GpuProjectExecMeta(
...
       }
       // explain AST because this is optional and it is sometimes hard to debug
       if (conf.shouldExplain) {
         val explain = childExprs.map(_.explainAst(conf.shouldExplainAll))
-            .filter(_.nonEmpty)
+          .filter(_.nonEmpty)
         if (explain.nonEmpty) {
           logWarning(s"AST PROJECT\n$explain")
         }
+        if (!isFixedWidth) {
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala:73]: We don't log in other cases where canThisBeAst fails, why are we logging here?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala [hunk 4]
```diff
@@ -57,16 +57,23 @@ class GpuProjectExecMeta(
     val gpuExprs = childExprs.map(_.convertToGpu().asInstanceOf[NamedExpression]).toList
     val gpuChild = childPlans.head.convertIfNeeded()
     if (conf.isProjectAstEnabled) {
-      if (childExprs.forall(_.canThisBeAst)) {
+      // cuDF requires result columns are fixed width
+      val resultTypes = gpuExprs.map(_.dataType)
+      val isFixedWidth = resultTypes.forall(GpuBatchUtils.isFixedWidth)
+      if (childExprs.forall(_.canThisBeAst) && isFixedWidth) {
```
Comment (revans2) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala:63]: I don't think we can support variable width types for intermediate values either. What is the expression that we say can be on AST, but outputs a non-fixed width type? That is where the check should be.

isnotnull only ever outputs a boolean column, so that is not the one causing the issues. Is it because we have pass through columns that are regular values? If so then we should be handling that in AstProject and not doing them through AST. There is no point in copying the column when we can just increment the reference count. AstProject is really set up for testing that AST expressions to the right thing so that we have more confidence in the joins. It has not been tested itself to be a regular project.

**Comment by res-life** [comment]
> intermediate values MUST not be non fixed width
I checked all the AST operators, like Add binary exprs, already have constrain that must be numeric types(fixed width)
Only AttributeReference does not check fixed width.
Refer to the latest version, add the check in `expr[AttributeReference]`
Current log is like:
```
Expression <AttributeReference> col_string#32 cannot be converted to GPU AST 
because AST Reference MUST refer to a fixed width column, found column with type: StringType
```

> we can just increment the reference count
Yes, could this be a follow-up?
When meet all the exprs in project lists are AttributeReference, no need to do AST transform.
e.g.: in this test case: 

GpuProjectAst [col_int#53, col_string#54, rid#62]
====>>>>
GpuProject [col_int#0, col_string#1, rid#9], true

Another follow-up:
investigate cuDF, how to  just increment the reference count in cuDF when doing column reference.

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
Wait, need to check IsNull/IsNotNull input type is non fixed width.

**Comment by res-life** [comment]
>  Wait, need to check IsNull/IsNotNull input type is non fixed width.

For the IsNull/IsNotNull, the input can be string type, refer to the test case:
```python

ast_descrs = [
    (string_gen, True)
]
def test_isnull(data_descr):
```

> intermediate values MUST not be non fixed width
This is not correct.
To be clear, the `cudf::compute_column` only check the output type, for the input it can be string type.

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
> We don't log in other cases where canThisBeAst fails, why are we logging here?
```scala
      // explain AST because this is optional and it is sometimes hard to debug
      if (conf.shouldExplain) {
        val explain = childExprs.map(_.explainAst(conf.shouldExplainAll))
            .filter(_.nonEmpty)
        if (explain.nonEmpty) {
          logWarning(s"AST PROJECT\n$explain")
        }
        if (!allReturnTypesFixedWidth) {
          logWarning(s"AST PROJECT\n  have non fixed return column, " +
            s"return types: ${gpuExprs.map(_.dataType)}")
        }
      }
```

**Comment by res-life** [comment]
`resultTypes.forall(GpuBatchUtils.isFixedWidth)` is lenient, but AST exprs already checked the output type is non fixed width. We can not only check attribute reference, e.g.: isNull(attribute_reference)  will not use AST if we only check attribute_reference

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala (hunk 2 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala]: Done

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala (hunk 3 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala]: > We don't log in other cases where canThisBeAst fails, why are we logging here?
No, we logged, if `canThisBeAst` fails and `conf.shouldExplain`  we log an warning.

The following code shows we log when conf.shouldExplain is true.
And also log non fixed width to keep consistent.

```scala
      // explain AST because this is optional and it is sometimes hard to debug
      if (conf.shouldExplain) {
        val explain = childExprs.map(_.explainAst(conf.shouldExplainAll))
            .filter(_.nonEmpty)
        if (explain.nonEmpty) {
          logWarning(s"AST PROJECT\n$explain")
        }
        if (!allReturnTypesFixedWidth) {
          logWarning(s"AST PROJECT\n  have non fixed return column, " +
            s"return types: ${gpuExprs.map(_.dataType)}")
        }
      }
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala (hunk 4 above)
Comment (res-life) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala]: > intermediate values MUST not be non fixed width

I checked all the AST operators, like Add binary exprs, already have constrain that must be numeric types(fixed width)
Only AttributeReference does not check fixed width.

>  we can just increment the reference count

Yes, could this be a follow-up?
When meet all the exprs in project lists are AttributeReference, no need to do AST transform.
e.g.: in this test case, we convert ProjectAST to Project because of string column.

GpuProjectAst [col_int#53, col_string#54, rid#62]
====>>>>
GpuProject [col_int#0, col_string#1, rid#9], true

Further more,  it's not needed if  all the exprs in project is just references, like Project [col_int_0#0, col_int_1#1, col_int_2#2] , should not do AST transform. 
This can be a follow-up. Or cuDF should properly handle this without memory copy.

Another follow-up:
investigate cuDF, how to just increment the reference count in cuDF when doing column reference.

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala [hunk 5]
```diff
@@ -57,7 +57,9 @@ class GpuProjectExecMeta(
     val gpuExprs = childExprs.map(_.convertToGpu().asInstanceOf[NamedExpression]).toList
     val gpuChild = childPlans.head.convertIfNeeded()
     if (conf.isProjectAstEnabled) {
-      if (childExprs.forall(_.canThisBeAst)) {
+      // cuDF requires return column is fixed width
+      val allReturnTypesFixedWidth = gpuExprs.forall(e => GpuBatchUtils.isFixedWidth(e.dataType))
+      if (childExprs.forall(_.canThisBeAst) && allReturnTypesFixedWidth) {
```
Comment (ttnghia) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala]: Micro optimization: use the already-computed boolean value first, so the `if` condition will short-circuit if it is false and avoid computing the second condition.
```suggestion
      if (allReturnTypesFixedWidth && childExprs.forall(_.canThisBeAst)) {
```

**Comment by ttnghia** [comment]
build

File: integration_tests/src/main/python/ast_test.py [hunk 6]
```diff
@@ -406,3 +408,28 @@ def test_multi_tier_ast():
         # repartition is here to avoid Spark simplifying the expression
         func=lambda spark: spark.range(10).withColumn("x", f.col("id")).repartition(1)\
             .selectExpr("x", "(id < x) == (id < (id + x))"))
+
+
+# Return column for AST MUST be fix width, e.g. byte, short, int, date, ...
+# Use GpuProjectExec instead of GpuProjectAstExec when meet an expr which return type is non fix width(e.g. string)
+# or cudf::compute_column will throw error: Invalid, non-fixed-width type
+@ignore_order(local=True)
+def test_not_use_ast_when_column_reference_to_string():
```
Comment (revans2) [inline integration_tests/src/main/python/ast_test.py]: I am kind of confused by this test. We are doing a complex window and join operation to verify that we used GpuProjectExec and not GpuAstProjectExec. Would it not have been simpler to just have a project over a single operation? I also assume that the test would have crashed without these changes?

**Comment by res-life** [comment]
Thanks, I'm trying to find the root cause.

**Comment by res-life** [comment]
> @res-life can you comment on this?
> 
> > isnotnull only ever outputs a boolean column, so that is not the one causing the issues.
> 
> As @revans2 suggests, `isnotnull` will return boolean columns, so that the return type has to be fixed width.
> 
> Which column is causing the variable width issue in the repro? It's not clear to me, and perhaps I am missing it.

Please refer to the latest test case:
```python
def test_refer_to_non_fixed_width_column():
    gens = [('col_int', int_gen), ('col_string', string_gen)]
    assert_gpu_and_cpu_are_equal_collect(
        lambda spark: gen_df(spark, gens).selectExpr("col_int * col_int", "col_string"),
        conf=_project_ast_enabled_conf)
``` 
In the above test case, the `col_string` is causing the variable width issue, `col_string` is from the scan table.
This issue is not related to `isnotnull`.

File: integration_tests/src/main/python/ast_test.py (hunk 6 above)
Comment (res-life) [reply integration_tests/src/main/python/ast_test.py]: > I am kind of confused by this test. We are doing a complex window and join operation to verify that we used GpuProjectExec and not GpuAstProjectExec. Would it not have been simpler to just have a project over a single operation? I also assume that the test would have crashed without these changes?

Please refer to the latest test case, a simple project will cause non-fixed-width error.
Without this PR, this test case crashes with error: Invalid, non-fixed-width type.

**Comment by res-life** [comment]
build

**Review by abellina — APPROVED** [review]
OK, so the ride-along column, on its own, would do this. That makes more sense to me. Thanks!

**Review by revans2 — APPROVED** [review]
