### PR TITLE
Implement the bug fix for SPARK-41448 and shim it for Spark 3.2.4 and Spark 3.3.{2,3} [databricks]

### LINKED ISSUE #8114: [BUG] [AUDIT] [SPARK-42478] Make a serializable jobTrackerId instead of a non-serializable JobID in FileWriterFactory
The changes in this PR make the jobId is consistent in task re-attempts in the file writers (e.g. `GpuFileFormatWriter`) https://github.com/apache/spark/commit/eb8fa5b713. It looks like this has gone from a date, to a date with seconds, to adding a random number to this jobId. On the retry, according to the comments, jobId should stay the same according to the Hadoop committer interface.

The issue was fixed in 3.4, but then also merged to 3.3 and 3.2. Looking at our code, I see our spark340 shim already calls `createJobTrackerID`, which is later passed to `createJobId` to recover the consistent `jobId`. I do not see these calls in our 3.3 and 3.2 lines of shims, and I am wondering if we need it.

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #8114.

This makes the map reduce job ID consistent across attempts in GpuFileFormatWriter. This fix was already fully incorporated into the Spark 3.4.0 shim code (and that shim has several other fixes), so this addresses all other Spark versions. It shims the 3.2.4/3.3.2/3.3.3 fix out so if there are further upstream fixes, the shim should accommodate those automatically.

### CODE REVIEW

**Comment by NVnavkumar** [comment]
build

**Comment by NVnavkumar** [comment]
build

File: sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala [hunk 1]
```diff
@@ -0,0 +1,41 @@
+/*
+ * Copyright (c) 2019-2023, NVIDIA CORPORATION.
```
Comment (jlowe) [inline sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala:2]:
```suggestion
 * Copyright (c) 2023, NVIDIA CORPORATION.
```

File: sql-plugin/src/main/spark324/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala [hunk 2]
```diff
@@ -0,0 +1,36 @@
+/*
+ * Copyright (c) 2019-2023, NVIDIA CORPORATION.
```
Comment (jlowe) [inline sql-plugin/src/main/spark324/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala:2]:
```suggestion
 * Copyright (c) 2023, NVIDIA CORPORATION.
```

File: sql-plugin/src/main/spark324/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+{"spark": "333"}
+spark-rapids-shim-json-lines ***/
+package org.apache.spark.sql.rapids.shims
+
+import org.apache.hadoop.mapred.JobID
+
+import org.apache.spark.internal.io.SparkHadoopWriterUtils
+
+/* This shim object uses the underlying fix from SparkHadoopWriterUtils in case this
+   logic is updated in the future for other versions of Spark 3.3 */
```
Comment (jlowe) [inline sql-plugin/src/main/spark324/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala:29]: Style nit: Multi-line comments either should use `//` at the start of each line or put a `*` at the start of each line, e.g.:
```suggestion
/**
 * This shim object uses the underlying fix from SparkHadoopWriterUtils in case this
 * logic is updated in the future for other versions of Spark 3.3
 */
```

**Review by revans2 — COMMENTED** [review]
Same comments as Jason

**Comment by NVnavkumar** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by abellina — APPROVED** [review]

File: sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+{"spark": "330cdh"}
+{"spark": "330db"}
+{"spark": "331"}
+spark-rapids-shim-json-lines ***/
+package org.apache.spark.sql.rapids.shims
+
+import org.apache.hadoop.mapred.JobID
+
+object RapidsHadoopWriterUtils {
+  // SPARK-41448 create a jobID directly from the jobTrackerID
```
Comment (gerashegalov) [inline sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala:37]: The before and after SPARK-41448 have an additional defensive [check](https://github.com/apache/spark/blob/47ddac13144b5cf62464c3a4c02d5110ea72862a/core/src/main/scala/org/apache/spark/internal/io/SparkHadoopWriterUtils.scala#L62-L64) for negative `id`. Probably robuster to just follow their logic?

Comment (NVnavkumar) [reply sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala:37]: Let me file a follow up PR to add this check.

Comment (NVnavkumar) [reply sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/RapidsHadoopWriterUtils.scala:37]: See https://github.com/NVIDIA/spark-rapids/pull/8458
