### PR TITLE
avoid using Thread.sleep in the flaky test case

### LINKED ISSUE #12883: [BUG] HostAllocSuite failed split should not happen immediately after fallback on memory contention failed
**Describe the bug**
first seen in rapids_nightly-pre_release-github run:836

NOTE: this failed with **branch-25.06** and only failed UT of one shim, could be a rare case and hard to repro

TEST THREAD APPEARS TO BE STUCK: `The code passed to failAfter did not complete within 10 seconds. (HostAllocSuite.scala:731)`
```
[2025-06-06T07:43:23.777Z] 		TEST THREAD APPEARS TO BE STUCK
[2025-06-06T07:43:23.777Z] thread2
[2025-06-06T07:43:23.777Z] 	java.lang.Thread.yield(Native Method)
[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.HostAllocSuite$TaskThread.$anonfun$run$1(HostAllocSuite.scala:195)
[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.HostAllocSuite$TaskThread$$Lambda$1115/1593574170.apply$mcV$sp(Unknown Source)
[2025-06-06T07:43:23.777Z] 	scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

[2025-06-06T07:43:23.777Z] 	org.apache.spark.sql.internal.SQLConf$.withExistingConf(SQLConf.scala:158)

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.HostAllocSuite$TaskThread.run(HostAllocSuite.scala:186)

[2025-06-06T07:43:23.777Z] Reference Handler

[2025-06-06T07:43:23.777Z] 	java.lang.Object.wait(Native Method)

[2025-06-06T07:43:23.777Z] 	java.lang.Object.wait(Object.java:502)

[2025-06-06T07:43:23.777Z] 	java.lang.ref.Reference.tryHandlePending(Reference.java:191)

[2025-06-06T07:43:23.777Z] 	java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

[2025-06-06T07:43:23.777Z] thread1

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.jni.SparkResourceAdaptor.blockThreadUntilReady(Native Method)

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.jni.SparkResourceAdaptor.blockThreadUntilReady(SparkResourceAdaptor.java:267)

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.jni.RmmSpark.blockThreadUntilReady(RmmSpark.java:432)

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:638)

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:578)

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.RmmRapidsRetryIterator$.drainSingleWithVerification(RmmRapidsRetryIterator.scala:295)

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRetryNoSplit(RmmRapidsRetryIterator.scala:189)

[2025-06-06T07:43:23.777Z] 	com.nvidia.spark.rapids.HostAllocSuite$AllocOnAnotherThreadWithWarmup$1.doAlloc(HostAllocSuite.scala:699)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$AllocOnAnotherThread$$anon$2.doIt(HostAllocSuite.scala:217)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$AllocOnAnotherThread$$anon$2.doIt(HostAllocSuite.scala:215)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$TaskThread$TaskThreadTrackingOp.doIt(HostAllocSuite.scala:86)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$TaskThread.$anonfun$run$1(HostAllocSuite.scala:193)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$TaskThread$$Lambda$1115/1593574170.apply$mcV$sp(Unknown Source)

[2025-06-06T07:43:23.778Z] 	scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

[2025-06-06T07:43:23.778Z] 	org.apache.spark.sql.internal.SQLConf$.withExistingConf(SQLConf.scala:158)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$TaskThread.run(HostAllocSuite.scala:186)

[2025-06-06T07:43:23.778Z] TEST THREAD ScalaTest-main-running-HostAllocSuite

[2025-06-06T07:43:23.778Z] 	java.lang.Object.wait(Native Method)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$TaskThread$TaskThreadTrackingOp.get(HostAllocSuite.scala:115)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$AllocOnAnotherThread.waitForAlloc(HostAllocSuite.scala:228)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$51(HostAllocSuite.scala:748)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$51$adapted(HostAllocSuite.scala:742)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$$Lambda$1179/90328954.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$50(HostAllocSuite.scala:742)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$50$adapted(HostAllocSuite.scala:739)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$$Lambda$1178/1933312427.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$49(HostAllocSuite.scala:739)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$$Lambda$1176/1967481106.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	org.scalatest.enablers.Timed$$anon$1.timeoutAfter(Timed.scala:127)

[2025-06-06T07:43:23.778Z] 	org.scalatest.concurrent.TimeLimits$.failAfterImpl(TimeLimits.scala:282)

[2025-06-06T07:43:23.778Z] 	org.scalatest.concurrent.TimeLimits.failAfter(TimeLimits.scala:231)

[2025-06-06T07:43:23.778Z] 	org.scalatest.concurrent.TimeLimits.failAfter$(TimeLimits.scala:230)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.failAfter(HostAllocSuite.scala:37)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$48(HostAllocSuite.scala:731)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$$Lambda$142/1951350823.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)

[2025-06-06T07:43:23.778Z] 	org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)

[2025-06-06T07:43:23.778Z] 	org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Transformer.apply(Transformer.scala:22)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Transformer.apply(Transformer.scala:20)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)

[2025-06-06T07:43:23.778Z] 	org.scalatest.TestSuite.withFixture(TestSuite.scala:196)

[2025-06-06T07:43:23.778Z] 	org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1564)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:224)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:236)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike$$Lambda$922/163187202.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:236)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:218)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.org$scalatest$BeforeAndAfterEach$$super$runTest(HostAllocSuite.scala:37)

[2025-06-06T07:43:23.778Z] 	org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:234)

[2025-06-06T07:43:23.778Z] 	org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.runTest(HostAllocSuite.scala:37)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:269)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike$$Lambda$918/530410675.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)

[2025-06-06T07:43:23.778Z] 	org.scalatest.SuperEngine$$Lambda$919/85776251.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	scala.collection.immutable.List.foreach(List.scala:431)

[2025-06-06T07:43:23.778Z] 	org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[2025-06-06T07:43:23.778Z] 	org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)

[2025-06-06T07:43:23.778Z] 	org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:269)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:268)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1564)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite.run(Suite.scala:1114)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite.run$(Suite.scala:1096)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1564)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:273)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike$$Lambda$912/1699576084.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	org.scalatest.SuperEngine.runImpl(Engine.scala:535)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:273)

[2025-06-06T07:43:23.778Z] 	org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:272)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.org$scalatest$BeforeAndAfterAll$$super$run(HostAllocSuite.scala:37)

[2025-06-06T07:43:23.778Z] 	org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)

[2025-06-06T07:43:23.778Z] 	org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)

[2025-06-06T07:43:23.778Z] 	org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite.run(HostAllocSuite.scala:37)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1178)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1225)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite$$Lambda$910/89617226.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)

[2025-06-06T07:43:23.778Z] 	scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)

[2025-06-06T07:43:23.778Z] 	scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite.runNestedSuites(Suite.scala:1223)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite.runNestedSuites$(Suite.scala:1156)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite.run(Suite.scala:1111)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Suite.run$(Suite.scala:1096)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:47)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1321)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1315)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$$$Lambda$908/220689838.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	scala.collection.immutable.List.foreach(List.scala:431)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1315)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:992)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:970)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$$$Lambda$60/1634132079.apply(Unknown Source)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1481)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:970)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner$.main(Runner.scala:775)

[2025-06-06T07:43:23.778Z] 	org.scalatest.tools.Runner.main(Runner.scala)

[2025-06-06T07:43:23.778Z] Cleaner Thread

[2025-06-06T07:43:23.778Z] 	java.lang.Object.wait(Native Method)

[2025-06-06T07:43:23.778Z] 	java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)

[2025-06-06T07:43:23.778Z] 	ai.rapids.cudf.MemoryCleaner.lambda$static$0(MemoryCleaner.java:189)

[2025-06-06T07:43:23.778Z] 	ai.rapids.cudf.MemoryCleaner$$Lambda$129/806005387.run(Unknown Source)

[2025-06-06T07:43:23.778Z] 	java.lang.Thread.run(Thread.java:750)

[2025-06-06T07:43:23.778Z] Finalizer

[2025-06-06T07:43:23.778Z] 	java.lang.Object.wait(Native Method)

[2025-06-06T07:43:23.778Z] 	java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)

[2025-06-06T07:43:23.778Z] 	java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)

[2025-06-06T07:43:23.778Z] 	java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:188)

[2025-06-06T07:43:23.778Z] ScalaTest-dispatcher

[2025-06-06T07:43:23.778Z] 	sun.misc.Unsafe.park(Native Method)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)

[2025-06-06T07:43:23.778Z] 	org.scalatest.LinkedBlockingQueue.take(JavaClassesWrappers.scala:45)

[2025-06-06T07:43:23.778Z] 	org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:166)

[2025-06-06T07:43:23.778Z] 	java.lang.Thread.run(Thread.java:750)

[2025-06-06T07:43:23.778Z] process reaper

[2025-06-06T07:43:23.778Z] 	sun.misc.Unsafe.park(Native Method)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)

[2025-06-06T07:43:23.778Z] 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[2025-06-06T07:43:23.778Z] 	java.lang.Thread.run(Thread.java:750)

[2025-06-06T07:43:23.778Z] Timer-9

[2025-06-06T07:43:23.778Z] 	java.lang.Thread.dumpThreads(Native Method)

[2025-06-06T07:43:23.778Z] 	java.lang.Thread.getAllStackTraces(Thread.java:1615)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.HostAllocSuite$MyThreadSignaler$.apply(HostAllocSuite.scala:310)

[2025-06-06T07:43:23.778Z] 	org.scalatest.concurrent.SignalerTimeoutTask.run(SignalerTimeoutTask.scala:28)

[2025-06-06T07:43:23.778Z] 	org.scalatest.Timer$$anon$1.run(JavaClassesWrappers.scala:91)

[2025-06-06T07:43:23.778Z] 	java.util.TimerThread.mainLoop(Timer.java:555)

[2025-06-06T07:43:23.778Z] 	java.util.TimerThread.run(Timer.java:505)

[2025-06-06T07:43:23.778Z] SparkResourceAdaptor WatchDog

[2025-06-06T07:43:23.778Z] 	java.lang.Thread.sleep(Native Method)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.jni.SparkResourceAdaptor.lambda$new$0(SparkResourceAdaptor.java:84)

[2025-06-06T07:43:23.778Z] 	com.nvidia.spark.rapids.jni.SparkResourceAdaptor$$Lambda$1070/773348080.run(Unknown Source)

[2025-06-06T07:43:23.778Z] 	java.lang.Thread.run(Thread.java:750)

[2025-06-06T07:43:23.778Z] Signal Dispatcher

[2025-06-06T07:43:23.778Z] 	

[2025-06-06T07:43:23.778Z] [ 99969][07:43:23:533315][error ] [A][Stream 0x1][Upstream 1024B][FAILURE maximum pool size exceeded: Not enough room to grow, current/max/try size = 0.000000 B, 0.000000 B, 1024.000000 B]

[2025-06-06T07:43:23.778Z] - split should not happen immediately after fallback on memory contention *** FAILED ***

[2025-06-06T07:43:23.778Z]   The code passed to failAfter did not complete within 10 seconds. (HostAllocSuite.scala:731)
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by binmahone**
closes #12883 

From https://github.com/NVIDIA/spark-rapids/issues/12883#issuecomment-3044292682, we can see:

```
[2025-07-04T06:55:12.180Z] 06:55:12.085339,DETAIL,140107466143296,140107466143296,1,THREAD_BLOCKED,,thread (id: 140107466143296) is_retry_alloc_before_bufn set to true
```

thread 1 is entering is_retry_alloc_before_bufn without thread 2 going through THREAD_BUFN_THROW and then become THREAD_BUFN, this is abnormal! 

In my theory, at the time of this line of log, thread 2 maybe in sleeping state ( even though in the test code thread 2 start to sleep 1000ms before thread 1 start to sleep 1000ms, this should be possible in JVM, but rarely happends, that's why the test case only fails very rarely). When thread 1 sees thread 2 sleeping, thread 1 will reach an `all bufn state`, even if thread 2 has not THREAD_BUFN_THROW yet. If no THREAD_BUFN_THROW ever happends, the test case will stuck by design.

The workaround is that we use some busy code to replace Thread.sleep for the test case, just like what we did in the PR. But this issue exposes the limitation of the `is_thread_bufn_or_above` concept, which is to sensitive to TIMED_WAITING, worth rethinking on it @revans2  @abellina

### CODE REVIEW

**Comment by binmahone** [comment]
build

File: sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala [hunk 1]
```diff
@@ -695,14 +695,31 @@ class HostAllocSuite extends AnyFunSuite with BeforeAndAfterEach with
     class AllocOnAnotherThreadWithWarmup(override val thread: TaskThread,
         override val size: Long) extends AllocOnAnotherThread(thread, size) {
 
+      def wasteSomeTime(): Unit = {
```
Comment (gerashegalov) [inline sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala]: This is usually called busyWait  or spinWait  that you could use as the base for the name of the method for it to sound more professional.

File: sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala [hunk 2]
```diff
@@ -695,14 +695,31 @@ class HostAllocSuite extends AnyFunSuite with BeforeAndAfterEach with
...
+        val startTime = System.currentTimeMillis
+        val duration = 100 // 100ms
+
+        val endTime = startTime + duration
+        var result = 0.0
+
+        while (System.currentTimeMillis < endTime) {
+          result += Math.sqrt(Math.random)
```
Comment (gerashegalov) [inline sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala]: On JDK9+ we would call `Thread.onSpinWait` here. Maybe use `Thread.yield` here until we are upgraded in terms of JDK

Comment (binmahone) [reply sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala]: good idea, I have changed to using yield. thx @gerashegalov !

**Comment by binmahone** [comment]
buld

**Review by abellina — APPROVED** [review]

**Comment by abellina** [comment]
would be great to get some :eyes: from @revans2 on the state machine part of it.

**Review by gerashegalov — APPROVED** [review]
LGTM

**Comment by binmahone** [comment]
build
