### PR TITLE
Fix issue when out of core sorting nested data types

### LINKED ISSUE #2225: [BUG] GpuSort fails on tables containing arrays.
On `spark-rapids` `0.6` + `cudf-0.20`, when `GpuSort` is called on a table containing arrays, one sees the following failure:
```
21/04/21 19:31:14 WARN TaskSetManager: Lost task 5.0 in stage 3.0 (TID 43, 10.0.0.21, executor driver): ai.rapids.cudf.Cu
dfException: cuDF failure at: ../src/merge/merge.cu:246: Unsupported type for merge.
        at ai.rapids.cudf.Table.merge(Native Method)
        at ai.rapids.cudf.Table.merge(Table.java:1524)
        at com.nvidia.spark.rapids.GpuSorter.$anonfun$mergeSort$2(SortUtils.scala:204)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:55)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:53)
        at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:65)
        at com.nvidia.spark.rapids.GpuSorter.$anonfun$mergeSort$1(SortUtils.scala:200)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:65)
        at com.nvidia.spark.rapids.GpuSorter.mergeSort(SortUtils.scala:196)
        at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.$anonfun$mergeSortEnoughToOutput$2(GpuSortExec.scala:407)
...
```

I haven't boiled it down yet, but I _suspect_ that it's possible to reproduce this with a simpler case: On a large table containing an array column, run:
```sql
SELECT * FROM mytable ORDER BY non_array_column;
```

The following is a query where I see this occur:
```scala
val mybench = spark.read.parquet("/path/to/large.parquet")
mybench.createOrReplaceTempView("mytable")

val query = """
    SELECT uid, 
           SUM(dollars) 
               OVER ( PARTITION BY uid 
                       ORDER BY cast(dateLong/1000 AS TIMESTAMP) 
                       RANGE BETWEEN INTERVAL 14 DAYS PRECEDING AND CURRENT ROW) sum_dollars_14_days,
           COLLECT_LIST(dollars) 
               OVER ( PARTITION BY uid 
                       ORDER BY CAST(dateLong/1000 AS TIMESTAMP) 
                       RANGE BETWEEN INTERVAL 14 DAYS PRECEDING AND CURRENT ROW) collect_dollars_14_days
    FROM mytable
"""

val top_earners_query = s"""
  SELECT uid, collect_dollars_14_days, sum_dollars_14_days FROM ($query) ORDER BY sum_dollars_14_days DESC
""

sql(top_earners_query).show
```
Data schema:
```+--------+---------+-------+
|col_name|data_type|comment|
+--------+---------+-------+
|     uid|   bigint|   null|
|   uname|   string|   null|
|dateLong|   bigint|   null|
|      dt|     date|   null|
| dateStr|   string|   null|
| dollars|      int|   null|
+--------+---------+-------+
```

### PR DESCRIPTION
**Pull request by revans2**
This fixes #2225

### CODE REVIEW

**Comment by revans2** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala [hunk 1]
```diff
@@ -201,7 +201,23 @@ class GpuSorter(
...
+          val hasNested = {
+            val tab = tabs.head
+            (0 until tab.getNumberOfColumns).exists { i =>
+              tab.getColumn(i).getType.isNestedType
+            }
+          }
+          if (hasNested) {
+            // so as a work around we concat all of the data together and then sort it.
+            // It is slower, but it works
+            withResource(Table.concatenate(tabs: _*)) { concated =>
```
Comment (razajafri) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala:215]: nit: spelling concatenate

Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala:215]: I don't know what you mean.  Do you want me to fully spell out "concatenate" instead of "concat" or "concatenated" instead of my shortened "concated"?

File: integration_tests/src/main/python/data_gen.py [hunk 2]
```diff
@@ -252,6 +252,29 @@ def __init__(self, nullable=True, min_val =LONG_MIN, max_val = LONG_MAX,
     def start(self, rand):
         self._start(rand, lambda : rand.randint(self._min_val, self._max_val))
 
+class LongRangeGen(DataGen):
+    """Generate Longs in incramenting order."""
```
Comment (jlowe) [inline integration_tests/src/main/python/data_gen.py:256]:
```suggestion
    """Generate Longs in incrementing order."""
```

File: integration_tests/src/main/python/sort_test.py [hunk 3]
```diff
@@ -171,3 +171,20 @@ def test_large_orderby():
...
+@pytest.mark.parametrize('data_gen', [byte_gen,
+    string_gen,
+    float_gen,
+    date_gen,
+    timestamp_gen,
+    decimal_gen_default,
+    StructGen([('child1', byte_gen)]),
+    ArrayGen(byte_gen, max_length=5)], ids=idfn)
+def test_large_orderby_nested_ridealong(data_gen):
+    # we use a LongRangeGen to avoid
```
Comment (jlowe) [inline integration_tests/src/main/python/sort_test.py:186]: this sentence seems cutoff -- to avoid...what?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala (hunk 1 above)
Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala:215]: Should we file a follow-on in the plugin for us to revisit this when the cudf issue is done?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala [hunk 4]
```diff
@@ -201,7 +201,23 @@ class GpuSorter(
           batches.foreach { cb =>
             tabs += GpuColumnVector.from(cb)
           }
-          Table.merge(tabs.toArray, cudfOrdering: _*)
+          // In the current version of cudf merge does not work for structs or lists (nested types)
+          // This should be fixed by https://github.com/rapidsai/cudf/issues/8050
```
Comment (razajafri) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala:205]: Should we file a follow-on in the plugin for us to revisit this when the cudf issue is done?

**Review by jlowe — APPROVED** [review]
Just minor, non-blocking nits from me.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala (hunk 4 above)
Comment (revans2) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala:205]: #2252

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@jlowe @razajafri I have addressed your review comments.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala (hunk 1 above)
Comment (razajafri) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala]: if you meant for this to be then I see no problem

**Review by razajafri — APPROVED** [review]
