### PR TITLE
Split up stream side for exploding joins

### LINKED ISSUE #1629: [BUG] TPC-DS-like query 72 at scale=3TB fails with "Maximum join output size exceeded"
This is with 8 executors (each with an A100 with 40GB) and 4 concurrent tasks (4 cores/exec)

```
ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/cudf-release-11.0/cpp/src/join/hash_join.cuh:149: Maximum join output size exceeded
        at ai.rapids.cudf.Table.innerJoin(Native Method)
        at ai.rapids.cudf.Table.access$3500(Table.java:44)
        at ai.rapids.cudf.Table$TableOperation.innerJoin(Table.java:2233)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin.doJoinLeftRight(GpuHashJoin.scala:307)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin.com$nvidia$spark$rapids$shims$spark300$GpuHashJoin$$doJoin(GpuHashJoin.scala:274)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:223)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:189)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:223)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
        at com.nvidia.spark.rapids.RowToColumnarIterator.hasNext(GpuRowToColumnarExec.scala:542)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:211)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:228)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManager.scala:95)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by revans2**
This is an alternative to #2411 and is more of a first step towards #2408.  The performance at scale factor 200 on query 72 is similar between both patches. We are going to run tests tonight to see about larger scale factors.

If things look similar for this patch compared to #2411 I would rather go with this patch as it is less code and has no external dependencies.

This is similar to #2411 in that there are no new tests added for the same reasons.

This fixes #1629 but more work will be needed for it to have good performance

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
I have been running a bunch of benchmarks recently. I have some numbers for 52c6d8d, and d4c8a4d of this patch and for #2411.

We ran both #2411 and 52c6d8d at scale factor 3k on a large cluster. Both patches successfully ran the query, which prior to these patches would just crash with out of memory errors at this scale.  Without special tuning for this patch #2411 took 31.8 mins to complete, but 52c6d8d was able to complete the same query in 10.8 mins.  This was enough for me to close #2411 as it would have required a lot of special tuning to match the same numbers that we got with this patch.


While profiling 52c6d8d at scale factor 200 I saw that a lot of time was being spent in the initial exploding join before it realized it was too large and split up the stream side batches.

image

That is the 22.8 second section in the profile above.  At scale factor 200 there ended up being 12 of this for a total time of about 4.56 mins. With that in mind I decided to refactor things and wrote d4c8a4d so that it would do the quick size estimate up front for all joins and split them if it looked like it was needed.

I then reran all of NDS on the original patch 52c6d8d and the new patch d4c8a4d. Interestingly instead of being 5 mins faster query 72 was actually 16.5 mins faster. Looking at metrics while the query was running it looks like a lot of this was because the initial join gather map that fails first causes all of the data on the GPU to spill, and then all joins afterwards had to pull back in a lot of data over and over again.

But the cost of doing the metrics ahead of the join is not free. If I add up the times of all of the other queries in NDS they are 1.12 mins slower than before this patch.  As such in the short term I think d4c8a4d is worth the added cost. Once cudf can do the size calculation without spilling we might want to rethink it because the cost savings are not as dramatic and they do not fit in well with AST filters in joins, that also should be coming.

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala [hunk 1]
```diff
@@ -328,8 +347,74 @@ class HashJoinIterator(
...
+    case _ => 1
+  }
+
+  private def splitAndSave(cb: ColumnarBatch,
+      numBatches: Int,
+      oom: Option[OutOfMemoryError] = None): Unit = {
+    val batchSize = cb.numRows() / numBatches
+    if (oom.isDefined && batchSize < 100) {
+      // We just need some kind of cutoff to not get stuck in a loop if the batches get to be too
+      // small but we want to at least give it a change to work (mostly for tests where the
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala:398]:
```suggestion
      // small but we want to at least give it a chance to work (mostly for tests where the
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala [hunk 2]
```diff
@@ -342,14 +427,49 @@ class HashJoinIterator(
...
         nextCb = nextCbFromGatherer()
-      } else if (stream.hasNext) {
+      } else if (pendingSplits.nonEmpty || stream.hasNext) {
         // Need to refill the gatherer
         gathererStore.foreach(_.close())
         gathererStore = None
-        withResource(stream.next()) { cb =>
+        val cb = if (pendingSplits.isEmpty) {
+          val cb = stream.next()
+          // This is arbitrary, just do avoid doing duplicate work
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala:436]:
```suggestion
          // This is arbitrary, just to avoid doing duplicate work
```

File: sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala [hunk 3]
```diff
@@ -342,14 +427,49 @@ class HashJoinIterator(
...
+        withResource(cb) { cb =>
           streamTime += (System.nanoTime() - startTime)
-          withResource(GpuProjectExec.project(built.getBatch, boundBuiltKeys)) { builtKeys =>
-            gathererStore = joinGatherer(builtKeys, built, cb)
+          try {
+            withResource(GpuProjectExec.project(built.getBatch, boundBuiltKeys)) { builtKeys =>
+              gathererStore = joinGatherer(builtKeys, built, cb)
+            }
+          } catch {
+            // For now we are only going to look at Inner joins. THis should work for all join
```
Comment (jlowe) [inline sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala:460]:
```suggestion
            // For now we are only going to look at Inner joins. This should work for all join
```

**Review by jlowe — DISMISSED** [review]
Just minor cleanup nits on the comments, lgtm.

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]
