### PR TITLE
BloomFilter v2 support [databricks]

### LINKED ISSUE #14148: [FEA] Support BloomFilter V2 format introduced in Spark 4.1.x (SPARK-47547)
## Description

Spark 4.1.1 introduced a new BloomFilter V2 format via [SPARK-47547](https://issues.apache.org/jira/browse/SPARK-47547) ([commit a08d8b093c0](https://github.com/apache/spark/commit/a08d8b093c0ec09cc6ce2c3642502f4842aebd86)).

### Changes in Spark 4.1.1

1. **New `BloomFilterImplV2` class** added alongside the original `BloomFilterImpl`

2. **New Version 2 format** with different header structure:
   - **V1 Header (12 bytes):** Version(4) + NumHashes(4) + NumLongs(4)
   - **V2 Header (16 bytes):** Version(4) + NumHashes(4) + **Seed(4)** + NumLongs(4)

3. **Default changed to V2:** The `BloomFilter.create()` method now creates V2 bloom filters by default

4. **V2 fixes int32 truncation issue** - The current bit index calculation in V1 does not use any part of the indexable space above the first 31 bits, causing performance degradation when item count approaches Integer.MAX_VALUE

### Current Status

The spark-rapids-jni library only supports V1:
```cpp
// bloom_filter.cu:162
CUDF_EXPECTS(header.version == 1, "Unexpected bloom filter version");
```

This causes runtime errors:
```
ai.rapids.cudf.CudfException: CUDF failure at: .../bloom_filter.cu:162: Unexpected bloom filter version
```

### Required Changes

1. Update `spark-rapids-jni` to support V2 header format (16 bytes with seed field)
2. Update bloom filter bit indexing logic to match V2's improved algorithm

### Workaround

BloomFilter support is currently disabled for Spark 4.1.1 in spark-rapids until JNI support is added.

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #14148.
Depends on https://github.com/NVIDIA/spark-rapids-jni/pull/4360.

### Description
This commit adds support for the new BloomFilter v2 format that was added in Apache Spark 4.1.1 (via https://github.com/apache/spark/commit/a08d8b093c0ec09cc6ce2c3642502f4842aebd86).

### Background
The v1 format used INT32s for bit index calculation.  When the number of items in the bloom-filter approaches INT_MAX, one sees a higher rate of collisions. The v2 format uses INT64 values for bit index calculations, allowing the full bit space to be addressed.  Apparently, this reduces the false positive rates for large filters.

Before the fix in this current PR was applied to spark-rapids, only certain bloom filter join tests would fail against Apache Spark 4.1.1;  specifically:
1. `test_bloom_filter_join_cpu_build`, where the bloom filter is built on CPU and then probed on GPU. This failed because the CPU would produce a v2 filter that couldn't be treated as a v1 format on GPU.
2. `test_bloom_filter_join_split_cpu_build`, where the bloom filter is partially aggregated on CPU, then merged on GPU.  Again, the GPU-side merging expected v1 format, while the CPU produced v2.

Note that `test_bloom_filter_join_cpu_probe` and `test_bloom_filter_join` did not actually fail on 4.1.1. That is because:
1. `test_bloom_filter_join_cpu_probe` tests CPU probing, which supports v1 and v2 flexibly.
2. `test_bloom_filter_join` tests both the build and probe jointly being either on CPU, or GPU. The CPU ran v2 format, the GPU ran v1.  Both produce the same query results, albeit with different formats.

### Effect 
The fix in this commit allows for v1 and v2 formats to be jointly supported on GPU, depending on the Spark version.

#### Documentation
The change is not strictly user-facing.  The bloom filter involved is an implementation detail, constructed in the background, and not exposed to the user.  The user should see performance improvement for joins in the INT_MAX cases, but nothing else.  No documentation need be updated.

#### Tests
The existing bloom filter test cases should really cover this.  `test_bloom_filter_join_cpu_build` and `test_bloom_filter_join_split_cpu_build` have been re-enabled for Spark version >= 4.1.1.

#### Performance Tests
This has been tested by performing joins on two synthetically generated tables, as follows:
  1. A fact table `fact` was generated with ~2 billion rows (11GB), consisting two fields:
    - `id`:BIGINT: 10 distinct values, uniformly distributed (195M rows each), except one value (`10`) that only has one row.
    - `str`:STRING:  Immaterial baggage.
  2. A dimension table `dim` was generated with ~2 billion rows (8GB), with exactly one field:
    - `id`:BIGINT: Each row is distinct, approaching `Int.MAX_INT`.

The following query was run:
```sql
SELECT COUNT(1) FROM fact f JOIN dim d ON f.id=d.id AND d.id < 2147483647
```
Predicate pushdown for Parquet was also disabled (via `set spark.sql.parquet.filterPushdown=false`), to avoid obfuscation.

The join predicate was chosen so that the bloom-filter created would be quite large.  The expected result is that there would be just 1 result row from the join

The test was run against the `26.02` release version and the `26.04` release candidate, on Spark 4.1.1 and Spark 3.5.x.

It was observed that the `26.04` version performed about identically with `26.02`.  The query took about 33 seconds (with the `26.04` "fixed" version, on average, being a few 100ms faster than `26.02`.)

As an aside, tests were also run with the predicate chosen to select `id=10`:
```sql
SELECT COUNT(1) FROM fact f JOIN dim d ON f.id=d.id AND d.id = 10
```

Again, it was observed that the fixed version performed about the same as the `26.02`, i.e. about 350ms.

### Checklists

- [ ] This PR has added documentation for new or modified features or behaviors.
- [X] This PR has added new tests or modified existing tests to cover new code paths.
      (Please explain in the PR description how the new code paths are tested, such as names of the new/existing tests that cover them.)
- [X] Performance testing has been performed and its results are added in the PR description. Or, an issue has been filed with a link in the PR description.

### CODE REVIEW

File: sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+{"spark": "358"}
+{"spark": "400"}
+{"spark": "401"}
+{"spark": "402"}
+spark-rapids-shim-json-lines ***/
+package com.nvidia.spark.rapids.shims
+
+object BloomFilterConstantsShims {
+  val BLOOM_FILTER_FORMAT_VERSION: Int = 1
+}
```
[the remark this answers is not in the document]
Comment (mythrocks) [reply sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala]: Agreed.  This is now fixed.

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala [hunk 2]
```diff
@@ -59,7 +59,9 @@ import org.apache.spark.sql.types.{BinaryType, DataType}
 case class GpuBloomFilterAggregate(
     child: Expression,
     estimatedNumItemsRequested: Long,
-    numBitsRequested: Long) extends GpuAggregateFunction {
+    numBitsRequested: Long,
+    version: Int = BloomFilter.VERSION_2,
+    seed: Int = BloomFilter.DEFAULT_SEED) extends GpuAggregateFunction {
```
[the remark this answers is not in the document]
Comment (mythrocks) [reply sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala]: @greptile-apps:  This should now have been resolved in the latest commits on this pull request.

**Comment by mythrocks** [comment]
@greptile-apps:  Have all the concerns from the review been addressed in the latest version?

**Comment by mythrocks** [comment]
The dependency PR (https://github.com/NVIDIA/spark-rapids-jni/pull/4360) has been merged.  The CI will fail until 4360 finds its way into a published snapshot.  That shouldn't prevent us from reviewing this change.

**Comment by jihoonson** [comment]
> I believe V1-to-V2 change is a correctness bug fix for extreme-scale bloom filters, not a performance improvement on typical workloads like NDS/TPCDS. We would see difference if the bloom filters are large (hundreds of MB) and billions of items to to see any difference.

My understanding is this is a performance issue not a correctness bug fix. The v1 will have a higher false-positive rate with large data sets, but should produce correct results. Am I missing something?

**Comment by mythrocks** [comment]
Build

**Comment by pxLi** [comment]
New 26.04 nightly JNI is just available, re-kick the build to include DB runtime validations https://github.com/NVIDIA/spark-rapids/issues/14462

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
early termination of CI


spark400db173,
```
[2026-03-25T06:33:08.646Z] [INFO] --- scala-maven-plugin:4.9.2:compile (scala-compile-first) @ rapids-4-spark-sql_2.13 ---

[2026-03-25T06:33:08.902Z] [INFO] Compiler bridge file: /home/ubuntu/spark-rapids/scala2.13/target/spark400db173/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.13-1.10.0-bin_2.13.18__61.0-1.10.0_20240505T232140.jar

[2026-03-25T06:33:23.713Z] [INFO] compiling 571 Scala sources and 37 Java sources to /home/ubuntu/spark-rapids/scala2.13/sql-plugin/target/spark400db173/classes ...

[2026-03-25T06:33:23.969Z] [ERROR] [Error] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterShims.scala:86: not found: value BloomFilterConstantsShims

[2026-03-25T06:33:23.970Z] [ERROR] [Error] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala:53: object BloomFilterConstantsShims is not a member of package com.nvidia.spark.rapids.shims

[2026-03-25T06:33:24.529Z] [ERROR] [Error] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala:65: not found: value BloomFilterConstantsShims

[2026-03-25T06:33:24.529Z] [ERROR] three errors found

[2026-03-25T06:33:24.784Z] [INFO] ------------------------------------------------------------------------

[2026-03-25T06:33:24.784Z] [INFO] Reactor Summary for RAPIDS Accelerator for Apache Spark Root Project 26.04.0-SNAPSHOT:
```

**Comment by abellina** [comment]
@mythrocks @jihoonson why are we merging something without any performance tests? When are the performance tests going to be completed? Also spark-rapids build is broken due to the deprecation of the BloomFilter.create method in jni.

**Comment by amahussein** [comment]
> My understanding is this is a performance issue not a correctness bug fix. The v1 will have a higher false-positive rate with large data sets, but should produce correct results. Am I missing something?

@jihoonson I don't remember Spark's PR provided any information about performance difference with that fix.
The performance is impacted in 2 dimensions:

1. The bloomFilter functionality:
    - if Spark OSS's decision to injectRuntimeFilter is based on the rate of false positive, then this fix impacts the Plans because bloomFilters injection will change post that fix. Last time I checked that was not the case. It has no dynamic FPP to decide whether this bloomFilter should be removed or not.
    - I don't think a benchmark like NDS-Sf3k can give insights on performance. OSS BloomFilter heuristics are conservative anyway and the scale of data won't hit that scenario
2. Implementation in RAPIDS/-JNI

We need separate benchmark for bloomFilters.
Now, we have a blocker because RAPIDS-JNI is merged and it cause RAPIDS build to fail.

CC: @abellina

**Comment by mythrocks** [comment]
> Now, we have a blocker because RAPIDS-JNI is merged and it cause RAPIDS build to fail.

That is addressed in #14468.

**Comment by mythrocks** [comment]
> @mythrocks @jihoonson why are we merging something without any performance tests? When are the performance tests going to be completed? 

It is not my intention to break the build, or to merge changes that weren't perf tested.

The JNI benchmark tests were updated in https://github.com/NVIDIA/spark-rapids-jni/pull/4360 to include the v2 format.

I intended to document this here after I was done testing:  I have been running tests on the plugin change for a while now.  The tests are custom and local; I didn't think NDS addresses this change.

The test involves an inner join a fact table against a dimension table, where:
1. Dimension table: 2 Billion rows, each with a unique key
2. Fact table:  2 Billion rows split uniformly over 10 key values.  Only 1 key matches against the dimension table.

The tests force the bloom-join optimization on.

My findings have been:
1. No difference in performance between 26.02 and my candidate changes in 26.04.  This is no surprise, given that there isn't an appreciable change for the V1 format.
2. I haven't yet been able to produce an appreciable difference between the V1 and V2 format.  This testing is still ongoing, but I don't think that qualifies to hold this change.  The first point would be a more relevant gating criterion.

The above should address @jihoonson and @amahussein's question:  The change from V1 to V2 was a performance issue for Apache Spark.  It is a functionality issue for `spark-rapids`, since we're trying to match binary compatibility for v2.

> Also spark-rapids build is broken due to the deprecation of the BloomFilter.create method in jni.

#14468. I hadn't expected turbulence on #14406 in Databricks.

File: sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+{"spark": "350db143"}
+{"spark": "351"}
+{"spark": "352"}
+{"spark": "353"}
+{"spark": "354"}
+{"spark": "355"}
+{"spark": "356"}
+{"spark": "357"}
+{"spark": "358"}
+{"spark": "400"}
```
Comment (nartal1) [inline sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala:41]: We need to include "400db173" shim here as we have recently added support to DB-17.3

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala
Comment (nartal1) [inline sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala:41]: Same as above comment - Add 400db173 shim in all the relevant files.

File: sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala (hunk 3 above)
Comment (mythrocks) [reply sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala:41]: Yep, that explains the borkage here.

Comment (mythrocks) [reply sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala:41]: This is sorted now.

File: sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala
Comment (mythrocks) [reply sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala:41]: This is sorted now.

**Comment by mythrocks** [comment]
Build

**Comment by jihoonson** [comment]
> @mythrocks @jihoonson why are we merging something without any performance tests? When are the performance tests going to be completed? 

@abellina It is important to track the performance change of each PR, but I don't think the performance testing must be done in the same PR. There are often such cases when you want to get the code merged in first and then do some performance testing, such as 1) the feature is too big to fit in a single PR, 2) you don't have enough time to run performance tests for some reason, such as code freeze. In any case, we should track the issue to measure performance of the feature. Our PR template suggests to file a follow-up github issue in this case. In the case of this PR, the performance test must be completed before the release. We will be able to decide whether to keep the feature or not based on the result. This only becomes the case when the author decides to do the performance test later. I'm fine either way as long as the performance testing is done before the release.

File: sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala (hunk 3 above)
Comment (mythrocks) [reply sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala:41]: This should really be sorted now. 

@nartal1: Any chance you might confirm?  I've been prone to unforced errors today.

Comment (nartal1) [reply sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterConstantsShims.scala:41]: I could build successfully on DB-17.3 with the latest commit. LGTM. Thanks @mythrocks !

**Comment by nartal1** [comment]
build

**Comment by mythrocks** [comment]
```
[2026-03-25T23:23:31.799Z] - might_contain with V2 literal bloom filter buffer *** FAILED ***
[2026-03-25T23:23:31.799Z]   java.io.IOException: Unexpected Bloom filter version number (2)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.util.sketch.BloomFilterImpl.readFrom0(BloomFilterImpl.java:256)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.util.sketch.BloomFilterImpl.readFrom(BloomFilterImpl.java:265)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.util.sketch.BloomFilter.readFrom(BloomFilter.java:178)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.sql.catalyst.expressions.BloomFilterMightContain.deserialize(BloomFilterMightContain.scala:124)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.sql.catalyst.expressions.BloomFilterMightContain.bloomFilter$lzycompute(BloomFilterMightContain.scala:94)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.sql.catalyst.expressions.BloomFilterMightContain.bloomFilter(BloomFilterMightContain.scala:92)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.sql.catalyst.expressions.BloomFilterMightContain.eval(BloomFilterMightContain.scala:98)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.sql.catalyst.optimizer.ConstantFolding$.org$apache$spark$sql$catalyst$optimizer$ConstantFolding$$constantFolding(expressions.scala:80)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.sql.catalyst.optimizer.ConstantFolding$.$anonfun$constantFolding$4(expressions.scala:90)
[2026-03-25T23:23:31.799Z]   at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1249)
[2026-03-25T23:23:31.799Z]   ...
```
I'll sort the test out.

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
The failing test doesn't seem to have to do with bloom filters. 
```python
112086:2026-03-26T07:45:35.5084196Z [2026-03-26T07:28:48.027Z] FAILED ../../../../integration_tests/src/main/python/hash_aggregate_test.py::test_hash_grpby_sum[KUDO-{'spark.rapids.sql.variableFloatAgg.enabled': 'true', 'spark.rapids.sql.castStringToFloat.enabled': 'true'}-[('a', Long), ('b', Integer), ('c', Long)]][DATAGEN_SEED=1774509770, TZ=UTC, INJECT_OOM, IGNORE_ORDER, INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(HashAggregateExec,AggregateExpression,UnscaledValue,MakeDecimal,AttributeReference,Alias,Sum,Count,Max,Min,Average,Cast,StddevPop,StddevSamp,VariancePop,VarianceSamp,NormalizeNaNAndZero,GreaterThan,Literal,If,EqualTo,First,SortAggregateExec,Coalesce,IsNull,EqualNullSafe,PivotFirst,GetArrayItem,ShuffleExchangeExec,HashPartitioning)] - py4j.protocol.Py4JJavaError: An error occurred while calling o692.collectToPython.
➜  ~/workspace/dev/spark-rapids/bloomfilters-v2/deleteme
```
I might give this another crank.

**Comment by mythrocks** [comment]
Build

**Comment by nvauto** [comment]
**NOTE: release/26.04 has been created from main. Please retarget your PR to release/26.04 if it should be included in the release.**

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
@jihoonson, @amahussein, et al:  I have updated the performance-testing section of the description with my tests.  I have also rebased this to `origin/release/26.04`.

Please let me know if this doesn't look agreeable.

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build
