### PR TITLE
Print nvidia-smi output when a task fails due to a cuda fatal exception.

### LINKED ISSUE #5028: [FEA] CUDA error debug
I wish when executors failed with unknown CUDA error or some other CUDA errors, the executor log can print more debug information such as nvidia-smi output to show the reason why.

For example, 
```
ai.rapids.cudf.CudaException: unknown error
	at ai.rapids.cudf.Cuda.freeZero(Native Method)
	at com.nvidia.spark.rapids.GpuDeviceManager$.setGpuDeviceAndAcquire(GpuDeviceManager.scala:99)
	at com.nvidia.spark.rapids.GpuDeviceManager$.$anonfun$initializeGpu$1(GpuDeviceManager.scala:125)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:23)
	at scala.Option.map(Option.scala:230)
	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpu(GpuDeviceManager.scala:125)
	at 
```

### PR DESCRIPTION
**Pull request by jbrennan333**
Signed-off-by: Jim Brennan <jimb@nvidia.com>

Closes #5028.

When the plugin onTaskFailure callback is called and the failure reason is a CudaFatalException, log the output of nvidia-smi.

Putting this up as a draft to invite comments.  Is there a better way to do this?

### CODE REVIEW

**Comment by jbrennan333** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 1]
```diff
@@ -338,10 +348,12 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
           case Some(_: CudaFatalException) =>
             logError("Stopping the Executor based on exception being a fatal CUDA error: " +
               s"${ef.toErrorString}")
+            logGpuDebugInfo()
             System.exit(20)
           case Some(_: CudaException) =>
-            logDebug(s"Executor onTaskFailed because of a non-fatal CUDA error: " +
+            logWarning(s"Executor onTaskFailed because of a non-fatal CUDA error: " +
               s"${ef.toErrorString}")
+            logGpuDebugInfo()
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:356]: since we could have many tasks failing at the same time (or queued up waiting to fail due to this..) maybe we should set a static variable that says this info was printed once? I am actually pretty confused why this isn't a fatal error. Or maybe this gets printed once a minute or something (if tasks keep failing sporadically every so many minutes?)

**Comment by abellina** [comment]
Have we tried looking at NVML? (https://developer.nvidia.com/nvidia-management-library-nvml) instead of calling nvidia-smi.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 2]
```diff
@@ -324,6 +325,15 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
     }
   }
 
+  // Try to output nvidia-smi output when task fails due to a cuda exception.
+  private def logGpuDebugInfo() = {
+    try {
+      val nvidiaSmiOutput = "nvidia-smi".!!
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:331]: I think it does not capture stderr.

When there is an error I also assume there is a non-negligible chance that nvidia-smi blocks for a long time or indefinitely. Do we need a time out?

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 3]
```diff
@@ -324,6 +325,15 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
...
+      logWarning("nvidia-smi output:\n" + nvidiaSmiOutput)
+    } catch {
+      case _: Throwable => // ignore
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:334]: we should at least log WARN this .

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala (hunk 1 above)
Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:356]: Good point.  This also goes to a [question I asked in the issue](https://github.com/NVIDIA/spark-rapids/issues/5028#issuecomment-1255597384).  Do we want to do this only for cudaFatalExceptions, in which case we are exiting and need to just print it.   If we want this output for non-fatal cuda exceptions as well, then I agree we need to put in some kind of limiting.  Maybe just once would be ok in that case?  Or once every x task failures.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala (hunk 2 above)
Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:331]: That's a good idea.  We don't want to hang in the call back.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala (hunk 3 above)
Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:334]: Agreed.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala (hunk 1 above)
Comment (abellina) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:356]: I assume/hope "ai.rapids.cudf.CudaException: unknown error" is a fatal exception (from the original issue). If it is then yeah I would focus on this for fatal exception only.

For other CUDA exceptions, I am not sure the nvidia-smi output helps. It seems you really want to know what is going on in the host if we can't attach to it like in the "unknown error" case.

Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:356]: Another question - I changed the logDebug here to a logWarning - seems like we'd want to see these.  Was there a reason it was logDebug for the non-fatal failures?  Log output reduction?

**Comment by jbrennan333** [comment]
> Have we tried looking at NVML?
I did look at it a little.  My impression was that we wanted something quickly that we can include in 22.10, so I thought I'd start with this fairly simple scala/nvidia-smi approach.

**Comment by jbrennan333** [comment]
build

**Comment by jbrennan333** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 4]
```diff
@@ -324,6 +327,32 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
...
   }
 
+  // Try to run nvidia-smi when task fails due to a cuda exception.
+  private def logGpuDebugInfo() = {
+    try {
+      val nvidiaSmiStdout = new StringBuilder
+      val nvidiaSmiStderr = new StringBuilder
+      val cmd = "nvidia-smi".run(
+        ProcessLogger(s => nvidiaSmiStdout.append(s + "\n"), s => nvidiaSmiStderr.append(s + "\n")))
+      val cmdFuture = concurrent.Future(concurrent.blocking(cmd.exitValue()))
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:337]: It seems weird that this needs to use a thread pool. Should it not invoke the command once per process while blocking the task thread?  

Also, I believe we should `synchronize` this function wholesale, and `System.exit(20)` inside of the synchronized block. That way, any other task thread won't try to print `nvidia-smi`, instead they will all arrive here, block, then print nvidia-smi once and then exit the process. Thoughts?

Comment (abellina) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:337]: If we do move the `System.exit` into this function, we could change it into `logGpuDebugInfoAndExit`

Comment (abellina) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:337]: @jbrennan333 pointed out the use of the thread pool here is to address the timeout concern (https://github.com/NVIDIA/spark-rapids/pull/6606#discussion_r978892815) from @gerashegalov. That seems fine to me, I would probably add a comment to make it clear this is done for that reason.

**Comment by jbrennan333** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala (hunk 4 above)
Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala]: I updated this to just do the wait in a while loop (using Process.isAlive).

**Comment by jbrennan333** [comment]
I am wondering if I should also do this for RapidsExecutorPlugin.init(), when it fails with a CudaFatalException?

**Comment by jbrennan333** [comment]
I pushed a change to do this in `RapidsExecutorPlugin.init` as well.

**Comment by jbrennan333** [comment]
build

**Comment by jbrennan333** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 5]
```diff
@@ -338,7 +377,7 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
           case Some(_: CudaFatalException) =>
             logError("Stopping the Executor based on exception being a fatal CUDA error: " +
               s"${ef.toErrorString}")
-            System.exit(20)
+            logGpuDebugInfoAndExit(20)
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:380]: nit, 
```suggestion
            logGpuDebugInfoAndExit(systemExitCode=20)
```

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 6]
```diff
@@ -324,6 +328,41 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
...
+        case Some(exitStatus) =>
+          if (exitStatus == 0) {
+            logWarning("nvidia-smi:\n" + nvidiaSmiStdout)
+          } else {
+            logWarning("nvidia-smi failed with: " + nvidiaSmiStdout + nvidiaSmiStderr)
+          }
+        case None => logWarning("nvidia-smi command timed out")
+      }
+    } catch {
+      case e: Throwable => logWarning("nvidia-smi process failed with: "
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:360]: perhaps move `logWarning` to the next line? minor nit on indentation, so we can probably just interpolate `${e.getMessage()}`

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 7]
```diff
@@ -324,6 +328,41 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
...
+  }
+
+  // Try to run nvidia-smi when task fails due to a cuda exception.
+  private def logGpuDebugInfoAndExit(systemExitCode: Int) = synchronized {
+    try {
+      val nvidiaSmiStdout = new StringBuilder
+      val nvidiaSmiStderr = new StringBuilder
+      val cmd = "nvidia-smi".run(
+        ProcessLogger(s => nvidiaSmiStdout.append(s + "\n"), s => nvidiaSmiStderr.append(s + "\n")))
+      waitForProcess(cmd, 2000) match {
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:350]: should this be something like 10 seconds? Especially during process launches, nvidia-smi can take a long time to start up.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 8]
```diff
@@ -269,6 +270,9 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
       logInfo(s"The number of concurrent GPU tasks allowed is $concurrentGpuTasks")
       GpuSemaphore.initialize(concurrentGpuTasks)
     } catch {
+      case e: CudaFatalException =>
+        logError("Exception in the executor plugin, shutting down!", e)
+        logGpuDebugInfoAndExit(1)
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:275]: this exit code is 1, whilst the driver-side one is 20. Mostly curious on why the difference.

**Review by abellina — CHANGES_REQUESTED** [review]

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala (hunk 8 above)
Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:275]: I didn't want to change the exit codes that were there previously.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala (hunk 7 above)
Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:350]: I can definitely make it longer.  Since we are exiting, I think it is safe to do so.

**Comment by jbrennan333** [comment]
build

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 9]
```diff
@@ -269,10 +270,13 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
       logInfo(s"The number of concurrent GPU tasks allowed is $concurrentGpuTasks")
       GpuSemaphore.initialize(concurrentGpuTasks)
     } catch {
+      // Exceptions in executor plugin can cause a single thread to die but the executor process
+      // sticks around without any useful info until it hearbeat times out. Print what happened
+      // and exit immediately.
+      case e: CudaFatalException =>
+      logError("Fatal Exception in the executor plugin, shutting down!", e)
```
Comment (abellina) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:277]: 2 space indent here

**Review by abellina — COMMENTED** [review]
minor indentation nit.

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala (hunk 9 above)
Comment (jbrennan333) [reply sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:277]: Thanks for spotting that.

**Comment by jbrennan333** [comment]
build

**Comment by jbrennan333** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by abellina** [comment]
So the original error documented in (https://github.com/NVIDIA/spark-rapids/issues/5028) was a `CudaException`. Is this now a `CudaFatalException`?

**Comment by abellina** [comment]
> Good point. The original error also appears to be during init. The "when executors fail" is what lead me to handle CudaFatalException vs CudaException - I originally was handling both in the task callback, but we backed off that. I'm thinking perhaps I should handle CudaException in RapidsExecutorPlugin.init in addition to CudaFatalException. Are there CudaExceptions that cause the executor to fail in init where we wouldn't want the nvidia-smi output?

I would catch CudaException during init and do this nvidia-smi output, to address the original request.

**Comment by jbrennan333** [comment]
I changed the init code to do the nvidia-smi output on all `CudaException`s.  `CudaFatalException` extends  `CudaException`.

**Review by abellina — APPROVED** [review]
LGTM

File: sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala [hunk 10]
```diff
@@ -324,6 +328,41 @@ class RapidsExecutorPlugin extends ExecutorPlugin with Logging {
     }
   }
 
+  // Wait for command spawned via Process
+  private def waitForProcess(cmd: Process, durationMs: Long): Option[Int] = {
+    val endTime = System.currentTimeMillis() + durationMs
+    do {
+      Thread.sleep(10)
```
Comment (gerashegalov) [inline sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala:335]: good old Java allows to waitFor with timeout https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor-long-java.util.concurrent.TimeUnit-
